### Restart and Run All Cells

In [1]:
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
year = 2022
quarter = 3
today = date.today()
today_str = today.strftime("%Y-%m-%d")
today_str

'2023-01-11'

In [3]:
cols = 'name year quarter q_amt_c q_amt_p inc_profit percent'.split()

format_dict = {
                'q_amt':'{:,}','q_amt_c':'{:,}','q_amt_p':'{:,}','inc_profit':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',   
                'latest_amt':'{:,}','previous_amt':'{:,}','inc_amt':'{:,}',
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'percent':'{:.2f}%','inc_pct':'{:.2f}%'
              }

In [4]:
sql = """
SELECT name,year,quarter,q_amt 
FROM epss 
WHERE (year = %s AND quarter <= %s) 
OR (year = %s-1 AND quarter >= %s+1)
ORDER BY year DESC, quarter DESC
"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT name,year,quarter,q_amt
FROM epss
WHERE (year = 2022 AND quarter <= 3)
OR (year = 2022-1 AND quarter >= 3+1)
ORDER BY year DESC, quarter DESC

In [6]:
dfc = pd.read_sql(sql, conlt)
dfc["Counter"] = 1
dfc_grp = dfc.groupby(["name"], as_index=False).sum()
dfc_grp = dfc_grp[dfc_grp["Counter"] == 4]
dfc_grp.sample(5)

      name  year  quarter     q_amt  Counter
50     CPN  8087       10   9769856        4
111     LH  8087       10   8334140        4
142    PRM  8087       10   1698355        4
121  MAKRO  8087       10  14319482        4
185   STEC  8087       10    919069        4

In [7]:
sql = """
SELECT name,year,quarter,q_amt 
FROM epss 
WHERE (year = %s AND quarter <= %s-1) 
OR (year = %s-1 AND quarter >= %s) 
ORDER BY year DESC, quarter DESC"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT name,year,quarter,q_amt
FROM epss
WHERE (year = 2022 AND quarter <= 3-1)
OR (year = 2022-1 AND quarter >= 3)
ORDER BY year DESC, quarter DESC

In [8]:
dfp = pd.read_sql(sql, conlt)
dfp["Counter"] = 1
dfp_grp = dfp.groupby(["name"], as_index=False).sum()
dfp_grp = dfp_grp[dfp_grp["Counter"] == 4]
dfp_grp.sample(5).style.format(format_dict)

In [9]:
dfp.name.unique().shape

(233,)

In [10]:
sql = """
SELECT *
FROM stocks
"""
stocks = pd.read_sql(sql, conlt)
stocks.shape

(233, 15)

In [11]:
sql = """
SELECT *
FROM tickers
"""
tickers = pd.read_sql(sql, conlt)
tickers.shape

(401, 9)

In [12]:
dfm = pd.merge(dfc_grp, dfp_grp, on="name", suffixes=(["_c", "_p"]), how="inner")
dfm["inc_profit"] = dfm["q_amt_c"] - dfm["q_amt_p"]
dfm["percent"] = round(dfm["inc_profit"] / abs(dfm["q_amt_p"]) * 100, 2)
dfm["year"] = year
dfm["quarter"] = "Q" + str(quarter)
df_percent = dfm[cols]
df_percent.sample(5).style.format(format_dict)

In [13]:
sql = """
DELETE FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)

rp = conlt.execute(sql)
rp.rowcount

DELETE FROM qt_profits
WHERE year = 2022 AND quarter = 'Q3'

215

In [15]:
sql = "SELECT name, id FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.sample(5)

      name   id
98      EA  148
210   NNCL  327
318  SUPER  487
382  UPOIC  603
135  HUMAN  655

In [16]:
df_ins = pd.merge(df_percent, tickers, on="name", how="inner")
df_ins.sample(5).style.format(format_dict)

In [17]:
rcds = df_ins.values.tolist()
len(rcds)

216

In [18]:
sql = """
INSERT INTO qt_profits (name, year, quarter, latest_amt, previous_amt, \
inc_amt, inc_pct, ticker_id) \
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""
print(sql)

INSERT INTO qt_profits (name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct, ticker_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)

In [19]:
for rcd in rcds:
    conlt.execute(sql, rcd)

### End of loop

In [21]:
criteria_1 = df_ins.q_amt_c > 440_000
df_ins.loc[criteria_1, cols].sample(5).style.format(format_dict)

In [22]:
criteria_2 = df_ins.q_amt_p > 400_000
df_ins.loc[criteria_2, cols].sample(5).style.format(format_dict)

In [23]:
criteria_3 = df_ins.percent > 10.00
df_ins.loc[criteria_3, cols].sample(5).style.format(format_dict)

In [24]:
df_ins_criteria = criteria_1 & criteria_2 & criteria_3
df_ins.loc[df_ins_criteria, cols].sample(5).style.format(format_dict)

In [25]:
df_ins[df_ins_criteria].sort_values(by=["percent"], ascending=[False]).sample(5).style.format(format_dict)

In [26]:
df_ins[df_ins_criteria].sort_values(by=["name"], ascending=[True]).sample(5).style.format(format_dict)

In [27]:
df_ins[df_ins_criteria].sort_values(by=["name"], ascending=[True]).sample(5).style.format(format_dict)

In [28]:
sql = """
SELECT name, COUNT(*) AS 'Nbr. of Group of 4 Quarters'
FROM qt_profits
GROUP BY name
HAVING COUNT(*) = 1
ORDER BY COUNT(*) DESC, name
"""
print(sql)

tmp = pd.read_sql(sql, conlt)
tmp

SELECT name, COUNT(*) AS 'Nbr. of Group of 4 Quarters'
FROM qt_profits
GROUP BY name
HAVING COUNT(*) = 1
ORDER BY COUNT(*) DESC, name

   name  Nbr. of Group of 4 Quarters
0   BE8                            1
1  ONEE                            1