In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2022
quarter = 4
today = date.today()
today_str = today.strftime("%Y-%m-%d")
today_str

'2023-01-21'

In [2]:
today = date(2023, 1, 20)
today_str = today.strftime("%Y-%m-%d")
today_str

'2023-01-20'

In [3]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [ ]:
names = """
IP
""".split()
names

In [ ]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [ ]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND name IN (%s)
"""
sql = sql % (year, quarter, in_p)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

### End of Process for specified stocks

In [4]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, today_str)
print(sql)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2022 AND quarter = 4
AND publish_date >= '2023-01-20'

### End of Normal Process

In [5]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
qt_pf = pd.read_sql(sql, conlt)
qt_pf.head().style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2022 AND quarter = 'Q4'

In [6]:
df_merge = pd.merge(epss, qt_pf, on=["name"], suffixes=(["_e", "_q"]), how="inner")
df_merge.head().style.format(format_dict)

### Delete duplicated year and quarter

In [7]:
columns = ["year_q", "quarter_q"]
epssqt_pf = df_merge.drop(columns, axis=1)
epssqt_pf.head().style.format(format_dict)

In [8]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
yr_pf = pd.read_sql(sql, conlt)
yr_pf.head().style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2022 AND quarter = 'Q4'

In [9]:
df_merge2 = pd.merge(
    epssqt_pf, yr_pf, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.head().style.format(format_dict)

### Delete duplicated year and quarter

In [10]:
columns = ["year_e", "quarter_e"]
profits = df_merge2.drop(columns, axis=1)
profits.head().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent

In [11]:
profits[profits["name"] == "KTB"].style.format(format_dict)

In [12]:
criteria_1 = profits.latest_amt_y > 440_000
profits.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [13]:
criteria_2 = profits.previous_amt_y >= 400_000
profits.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [14]:
criteria_3 = profits.inc_pct_y >= 10.00
profits.loc[criteria_3, cols].style.format(format_dict)

In [15]:
criteria_4 = (profits.q_amt > profits.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
profits.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [16]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#profits_criteria = criteria_1 & criteria_2 
filter = profits.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [17]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [18]:
final = pre_final.loc[:,:]
final.style.format(format_dict)

In [ ]:
#final = filter.drop(colt, axis=1)
#final.style.format(format_dict)

In [19]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [20]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s AND B.quarter = (%s-1)"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2022 AND A.quarter = 4
AND B.year = 2022 AND B.quarter = (4-1)

In [21]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [22]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [23]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
2,TTB,14195190,13147199,1047991,7.97,14195190,10474045,3721145,35.53,2022,4,3847324,2799333,3714636

In [24]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [25]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [26]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [27]:
final2.kind.value_counts()

1    1
Name: kind, dtype: int64

In [28]:
final2["inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2["inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2["inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2["inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [29]:
final2["inc_pct_py"].replace("inf", np.nan, inplace=True)

In [30]:
final2["mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [31]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

  name  mean_pct
2  TTB   21.1273

In [32]:
final2["std_pct"] = final2[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [33]:
final2[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

  name    std_pct
2  TTB  17.839577

In [34]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [35]:
df_merge4 = pd.merge(final2, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final3 = df_merge4[colv].copy()
final3.style.format(format_dict)

In [36]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2022 AND quarter = 4
ORDER BY name

In [37]:
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

In [38]:
df_merge = pd.merge(
    final3, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.head().style.format(format_dict)

In [39]:
final4 = df_merge[df_merge["_merge"] == "left_only"]
final4

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
0,TTB,2022,4,1.0,14195190.0,10474045.0,3721145.0,35.53,14195190.0,13147199.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [40]:
final5 = final4[colw]
final5.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
0,TTB,2022,4,1.0,14195190.0,10474045.0,3721145.0,35.53,14195190.0,13147199.0,...,3847324.0,2799333.0,1047991.0,37.437168,3714636.0,132688.0,3.572032,541.0,21.1273,17.839577

In [41]:
rcds = final5.values.tolist()
len(rcds)

1

In [42]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2022 AND quarter = 4
ORDER BY name

In [43]:
for rcd in rcds:
    print(rcd)

['TTB', 2022, 4, 1.0, 14195190.0, 10474045.0, 3721145.0, 35.53, 14195190.0, 13147199.0, 1047991.0, 7.97, 3847324.0, 2799333.0, 1047991.0, 37.43716806825054, 3714636.0, 132688.0, 3.57203236064045, 541.0, 21.127300107222748, 17.839577058451464]

In [44]:
sql = """
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""
print(sql)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

In [45]:
for rcd in rcds:
    conlt.execute(sql, rcd)

### End of Create Data

In [46]:
sql = """
SELECT name, market
FROM tickers"""
tickers = pd.read_sql(sql, conlt)
tickers.shape

(401, 2)

In [47]:
df_merge = pd.merge(final5, tickers, on='name', how='inner')
df_merge[['name','market']].sort_values('name').style.format(format_dict)

### Insert Profits from PortLt to PortMy

In [48]:
names = final5.name
names

0    TTB
Name: name, dtype: object

In [49]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'TTB'"

In [50]:
#quarter = 4
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('TTB') AND year = 2022 AND quarter = 4

In [51]:
profits_inp = pd.read_sql(sql, conlt)
profits_inp.style.format(format_dict)

In [52]:
profits_inp.sort_values(by=["kind", "name"], ascending=[True, True]).style.format(format_dict)

In [53]:
rcds = profits_inp.values.tolist()
len(rcds)

1

In [54]:
for rcd in rcds:
    print(rcd)

[2559, 'TTB', 2022, 4, 1, 14195190, 10474045, 3721145, 35.53, 14195190, 13147199, 1047991, 7.97, 3847324, 2799333, 1047991, 37.43716806825054, 3714636, 132688, 3.57203236064045, 541, 21.127300107222748, 17.839577058451464]

In [55]:
sql = """
INSERT INTO profits (id, name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""
print(sql)

INSERT INTO profits (id, name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

In [56]:
for rcd in rcds:
    conmy.execute(sql, rcd)

In [57]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp.set_index("name", inplace=True)
df_tmp.index

Index(['AH', 'AIT', 'BANPU', 'BDMS', 'BEM', 'BH', 'CK', 'CKP', 'COM7', 'CPALL',
       'CPF', 'CPN', 'EA', 'GFPT', 'HMPRO', 'ICHI', 'III', 'JMART', 'JMT',
       'KCE', 'LH', 'MEGA', 'NER', 'PTL', 'PTTEP', 'QH', 'SAPPE', 'SC', 'SIRI',
       'SPALI', 'SVI', 'SYNEX', 'TTB'],
      dtype='object', name='name')

### After call 450-Export-to-PortPg

In [58]:
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('TTB') AND year = 2022 AND quarter = 4

In [59]:
profits_inp = pd.read_sql(sql, conpg)
profits_inp[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

  name  ticker_id
0  TTB        549

In [60]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('TTB')
ORDER BY name

In [61]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].sort_values(by=[ "name"], ascending=[True])

  name   id                   market
0  TTB  549  SET50 / SETHD / SETTHSI

### Additional process to find stocks in SET50 & SET100

In [62]:
names = epss['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'KKP', 'KTB', 'KTC', 'SCB', 'TTB'"

In [63]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('KKP', 'KTB', 'KTC', 'SCB', 'TTB')
ORDER BY name

In [64]:
df = pd.read_sql(sql, conlt)
df

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,255,KKP,KIATNAKIN PHATRA BANK PUBLIC COMPANY LIMITED,Financials,Banking,SET100 / SETCLMV / SETHD / SETTHSI,https://bank.kkpfg.com/,2017-07-23 06:31:20.501543,2021-01-26 15:41:59.628375
1,258,KTB,KRUNG THAI BANK PUBLIC COMPANY LIMITED,Financials,Banking,SET50 / SETHD / SETTHSI,https://krungthai.com,2017-07-23 06:31:20.817937,2021-01-26 15:41:59.639321
2,259,KTC,KRUNGTHAI CARD PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50 / SETTHSI,www.ktc.co.th,2017-07-23 06:31:20.917985,2021-01-26 15:41:59.644329
3,426,SCB,THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED,Financials,Banking,SET50 / SETCLMV / SETTHSI,www.scb.co.th,2017-07-23 06:31:44.091944,2022-01-15 03:54:13.062428
4,541,TTB,TMBTHANACHART BANK PUBLIC COMPANY LIMITED,Financials,Banking,SET50 / SETHD / SETTHSI,https://www.ttbbank.com,2017-07-23 06:32:01.386912,2022-01-15 03:54:13.227847