In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2022
quarter = 4
today = date.today()
today_str = today.strftime("%Y-%m-%d")
today_str

'2023-02-18'

In [2]:
today = date(2023, 2, 17)
today_str = today.strftime("%Y-%m-%d")
today_str

'2023-02-17'

In [3]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [ ]:
names = """
IP
""".split()
names

In [ ]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [ ]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND name IN (%s)
"""
sql = sql % (year, quarter, in_p)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

### End of Process for specified stocks

In [4]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, today_str)
print(sql)
epss = pd.read_sql(sql, conlt)
epss.style.format(format_dict)

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2022 AND quarter = 4
AND publish_date >= '2023-02-17'

### End of Normal Process

In [5]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
qt_pf = pd.read_sql(sql, conlt)
qt_pf.sample(5).style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2022 AND quarter = 'Q4'

In [6]:
df_merge = pd.merge(epss, qt_pf, on=["name"], suffixes=(["_e", "_q"]), how="inner")
df_merge.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [7]:
columns = ["year_q", "quarter_q"]
epssqt_pf = df_merge.drop(columns, axis=1)
epssqt_pf.head(5).style.format(format_dict)

In [8]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
yr_pf = pd.read_sql(sql, conlt)
yr_pf.sample(5).style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2022 AND quarter = 'Q4'

In [9]:
df_merge2 = pd.merge(
    epssqt_pf, yr_pf, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.head(5).style.format(format_dict)

### Delete duplicated year and quarter

In [10]:
columns = ["year_e", "quarter_e"]
profits = df_merge2.drop(columns, axis=1)
profits.head().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent
4. YoY Profit Higher

In [11]:
profits[profits["name"] == "PSH"].style.format(format_dict)

In [12]:
criteria_1 = profits.latest_amt_y > 440_000
profits.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [13]:
criteria_2 = profits.previous_amt_y >= 400_000
profits.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).style.format(format_dict)

In [14]:
criteria_3 = profits.inc_pct_y >= 10.00
profits.loc[criteria_3, cols].style.format(format_dict)

In [15]:
criteria_4 = (profits.q_amt > profits.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
profits.loc[criteria_4,colt].sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [16]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
#profits_criteria = criteria_1 & criteria_2 
filter = profits.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [17]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [18]:
final = pre_final.loc[:,:]
final.style.format(format_dict)

In [19]:
#final = filter.drop(colt, axis=1)
#final.style.format(format_dict)

In [20]:
final.sort_values(by=["name"], ascending=True).style.format(format_dict)

In [21]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s AND B.quarter = (%s-1)"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2022 AND A.quarter = 4
AND B.year = 2022 AND B.quarter = (4-1)

In [22]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().style.format(format_dict)

In [23]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [24]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
0,PSH,2772326,2589196,183130,7.07,2772326,2352637,419689,17.84,2022,4,1171599,988469,619169
1,SNC,727235,726466,769,0.11,727235,636352,90883,14.28,2022,4,190094,189325,65206

In [25]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [26]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [27]:
final2["kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [28]:
final2.kind.value_counts()

1    2
Name: kind, dtype: int64

In [29]:
final2["inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2["inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2["inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2["inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [30]:
final2["inc_pct_py"].replace("inf", np.nan, inplace=True)

In [31]:
final2["mean_pct"] = final2[
    ["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]
].mean(axis=1, skipna=True)

In [32]:
final2[["name", "mean_pct"]].sort_values(by=["mean_pct"], ascending=False)

  name   mean_pct
1  SNC  51.581142
0  PSH  33.164457

In [33]:
final2["std_pct"] = final2[["inc_pct_y", "inc_pct_q", "inc_pct_py", "inc_pct_pq"]].std(
    axis=1
)

In [34]:
final2[["name", "std_pct"]].sort_values(by=["std_pct"], ascending=True)

  name    std_pct
0  PSH  37.737620
1  SNC  93.532101

In [35]:
sql = "SELECT name, id, market FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.head().style.format(format_dict)

In [36]:
df_merge4 = pd.merge(final2, tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final3 = df_merge4[colv].copy()
final3.style.format(format_dict)

In [37]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2022 AND quarter = 4
ORDER BY name

In [38]:
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

In [39]:
df_merge = pd.merge(
    final3, profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.head().style.format(format_dict)

In [40]:
final4 = df_merge[df_merge["_merge"] == "left_only"]
final4

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
0,PSH,2022,4,1.0,2772326.0,2352637.0,419689.0,17.84,2772326.0,2589196.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,SNC,2022,4,1.0,727235.0,636352.0,90883.0,14.28,727235.0,726466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [41]:
final5 = final4[colw]
final5.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
0,PSH,2022,4,1.0,2772326.0,2352637.0,419689.0,17.84,2772326.0,2589196.0,...,1171599.0,988469.0,183130.0,18.526631,619169.0,552430.0,89.221198,377.0,33.164457,37.737620
1,SNC,2022,4,1.0,727235.0,636352.0,90883.0,14.28,727235.0,726466.0,...,190094.0,189325.0,769.0,0.406180,65206.0,124888.0,191.528387,457.0,51.581142,93.532101

In [42]:
rcds = final5.values.tolist()
len(rcds)

2

In [43]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
profits = pd.read_sql(sql, conlt)
profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2022 AND quarter = 4
ORDER BY name

In [44]:
for rcd in rcds:
    print(rcd)

['PSH', 2022, 4, 1.0, 2772326.0, 2352637.0, 419689.0, 17.84, 2772326.0, 2589196.0, 183130.0, 7.07, 1171599.0, 988469.0, 183130.0, 18.526630577185525, 619169.0, 552430.0, 89.22119808969764, 377.0, 33.164457166720794, 37.737619835082064]
['SNC', 2022, 4, 1.0, 727235.0, 636352.0, 90883.0, 14.28, 727235.0, 726466.0, 769.0, 0.11, 190094.0, 189325.0, 769.0, 0.4061798494652053, 65206.0, 124888.0, 191.52838695825537, 457.0, 51.58114170193014, 93.53210104166186]

In [45]:
sql = """
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""
print(sql)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

In [46]:
for rcd in rcds:
    conlt.execute(sql, rcd)

### End of Create Data

In [47]:
sql = """
SELECT name, market
FROM tickers"""
tickers = pd.read_sql(sql, conlt)
tickers.shape

(401, 2)

In [48]:
df_merge = pd.merge(final5, tickers, on='name', how='inner')
df_merge[['name','market']].sort_values('name').style.format(format_dict)

### Insert Profits from PortLt to PortMy

In [49]:
names = final5.name
names

0    PSH
1    SNC
Name: name, dtype: object

In [50]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'PSH', 'SNC'"

In [51]:
#quarter = 4
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('PSH', 'SNC') AND year = 2022 AND quarter = 4

In [52]:
profits_inp = pd.read_sql(sql, conlt)
profits_inp.style.format(format_dict)

In [53]:
profits_inp.sort_values(by=["kind", "name"], ascending=[True, True]).style.format(format_dict)

In [54]:
rcds = profits_inp.values.tolist()
len(rcds)

2

In [55]:
for rcd in rcds:
    print(rcd)

[2565, 'PSH', 2022, 4, 1, 2772326, 2352637, 419689, 17.84, 2772326, 2589196, 183130, 7.07, 1171599, 988469, 183130, 18.526630577185525, 619169, 552430, 89.22119808969764, 377, 33.164457166720794, 37.737619835082064]
[2566, 'SNC', 2022, 4, 1, 727235, 636352, 90883, 14.28, 727235, 726466, 769, 0.11, 190094, 189325, 769, 0.4061798494652053, 65206, 124888, 191.52838695825537, 457, 51.58114170193014, 93.53210104166186]

In [56]:
sql = """
INSERT INTO profits (id, name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""
print(sql)

INSERT INTO profits (id, name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq, ticker_id, mean_pct, std_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

In [57]:
for rcd in rcds:
    conmy.execute(sql, rcd)

In [58]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
df_tmp = pd.read_sql(sql, conmy)
df_tmp.set_index("name", inplace=True)
df_tmp.index

Index(['AH', 'ASK', 'BANPU', 'BDMS', 'BEM', 'BH', 'CK', 'CKP', 'COM7', 'CPALL',
       'CPF', 'CPN', 'EA', 'GFPT', 'GULF', 'HMPRO', 'ICHI', 'III', 'JMT', 'LH',
       'MEGA', 'PSH', 'PTL', 'QH', 'SAPPE', 'SC', 'SIRI', 'SNC', 'SPALI',
       'SYNEX', 'TTB'],
      dtype='object', name='name')

### After call 450-Export-to-PortPg

In [66]:
sql = """
SELECT * 
FROM profits 
WHERE name IN (%s) AND year = %s AND quarter = %s"""
sql = sql % (in_p, year, quarter)
print(sql)

SELECT *
FROM profits
WHERE name IN ('AIE', 'CBG', 'CPNREIT', 'STA', 'NER', 'MST', 'PSH', 'SNC', 'STGT', 'TASCO', 'TIDLOR') AND year = 2022 AND quarter = 4

In [67]:
profits_inp = pd.read_sql(sql, conpg)
profits_inp[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

  name  ticker_id
1  PSH        383
0  SNC        465

In [68]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('AIE', 'CBG', 'CPNREIT', 'STA', 'NER', 'MST', 'PSH', 'SNC', 'STGT', 'TASCO', 'TIDLOR')
ORDER BY name

In [69]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].sort_values(by=[ "name"], ascending=[True])

       name   id                              market
0       AIE  691                                sSET
1       CBG   90             SET50 / SETCLMV / SETWB
2   CPNREIT  127                                 SET
3       MST  298                                 SET
4       NER  649                                sSET
5       PSH  383                             SETTHSI
6       SNC  465                      sSET / SETTHSI
7       STA  489            SET100 / SETTHSI / SETWB
8      STGT  685                    SET100 / SETTHSI
9     TASCO  511  SET100 / SETCLMV / SETHD / SETTHSI
10   TIDLOR  696                               SET50

### Additional process to find stocks in SET50 & SET100

In [70]:
names = epss['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'AIE', 'CBG', 'CPNREIT', 'STA', 'NER', 'MST', 'PSH', 'SNC', 'STGT', 'TASCO', 'TIDLOR'"

In [71]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('AIE', 'CBG', 'CPNREIT', 'STA', 'NER', 'MST', 'PSH', 'SNC', 'STGT', 'TASCO', 'TIDLOR')
ORDER BY name

In [72]:
df = pd.read_sql(sql, conlt)
df

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,720,AIE,AI ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,sSET,www.aienergy.co.th,2021-02-21 16:12:17.821078,2022-01-15 03:54:12.607554
1,87,CBG,CARABAO GROUP PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETWB,www.carabaogroup.com,2017-07-23 06:30:54.027998,2019-11-19 07:11:19.512684
2,647,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2017-12-21 13:43:29.709328,2017-12-21 13:43:29.709328
3,290,MST,MAYBANK SECURITIES (THAILAND) PUBLIC COMPANY L...,Financials,Finance & Securities,SET,www.maybank-ke.co.th,2017-07-23 06:31:24.727336,2022-01-15 03:54:12.929487
4,680,NER,NORTH EAST RUBBER PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,sSET,www.nerubber.com,2019-03-03 03:43:42.465733,2019-11-19 07:11:24.050281
5,377,PSH,PRUKSA HOLDING PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SETTHSI,www.psh.co.th,2017-07-23 06:31:36.425256,2021-01-26 15:41:59.827209
6,457,SNC,SNC FORMER PUBLIC COMPANY LIMITED,Industrials,Industrial Materials & Machinery,sSET / SETTHSI,www.sncformer.com,2017-07-23 06:31:48.790403,2022-01-15 03:54:13.099177
7,481,STA,SRI TRANG AGRO-INDUSTRY PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,www.sritranggroup.com,2017-07-23 06:31:51.957277,2022-01-15 03:54:13.122661
8,714,STGT,SRI TRANG GLOVES (THAILAND) PUBLIC COMPANY LIM...,Consumer Products,Personal Products & Pharmaceuticals,SET100 / SETTHSI,www.sritranggloves.com,2021-01-26 15:42:00.052117,2022-01-15 03:54:13.136033
9,502,TASCO,TIPCO ASPHALT PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SET100 / SETCLMV / SETHD / SETTHSI,www.tipcoasphalt.com,2017-07-23 06:31:54.989965,2021-01-26 15:42:00.086060
10,723,TIDLOR,NGERN TID LOR PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50,www.ngerntidlor.com/th/home.html,2021-05-10 23:19:52.787664,2022-01-15 03:54:13.168709