### portmy database: profits, stocks tables
### portpg database: consensus, tickers tables
### csv files: consensus-ORD.csv

In [1]:
import pandas as pd
import numpy as np
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/stock')
const = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

pd.set_option('display.max_row', None)
pd.set_option('display.max_column', None)

today = date.today()
today

datetime.date(2023, 1, 7)

### Process after last business day, yesterday must be last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-07
yesterday: 2023-01-06 00:00:00

In [3]:
# find the beginning of the week for the given yesterday
week_start = yesterday.to_period('W').start_time
week_end = yesterday.to_period('W').end_time
week_start = week_start.date()
week_end = week_end.date()
print(f'week start: {week_start}')
print(f'week end: {week_end}')

week start: 2023-01-02
week end: 2023-01-08

In [4]:
yesterday = yesterday.date()
week_start, yesterday

(datetime.date(2023, 1, 2), datetime.date(2023, 1, 6))

In [5]:
s50_pct = 25
s100_pct = 30
s999_pct = 35

### Restart and Run All Cells

In [6]:
cols = 'quarter price target_price upside buy hold sell yield max_price min_price pe pbv dly_vol beta'.split()
colt = 'name price target_price upside buy hold sell market sector subsector dly_vol beta yield'.split()
colu = 'price target_price upside buy hold sell mrkt yield'.split()

format_dict = {
    'latest_amt_y':'{:,}','previous_amt_y':'{:,}','inc_amt_y':'{:,}',   
    'latest_amt_q':'{:,}','previous_amt_q':'{:,}','inc_amt_q':'{:,}',    
    'q_amt_c':'{:,}','y_amt': '{:,}','inc_amt_py':'{:,}', 
    'q_amt_p': '{:,}','inc_amt_pq':'{:,}', 
    'inc_pct_y': '{:.2f}%','inc_pct_q': '{:.2f}%',
    'inc_pct_py': '{:.2f}%','inc_pct_pq': '{:.2f}%',
    'mean_pct': '{:.2f}%','std_pct': '{:.2f}%','upside': '{:.2f}%', 
    
    'price':'{:.2f}','target_price':'{:.2f}','diff':'{:.2f}',
    'eps_a':'{:.2f}','eps_b':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'yield':'{:.2f}%',
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}',    
}

In [7]:
sql = """
SELECT * FROM profits 
ORDER BY id DESC 
LIMIT 1
"""
tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

In [8]:
names = tmp['name'].values.tolist()
names

['SIRI']

In [9]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'SIRI'"

In [10]:
sql = '''
SELECT * 
FROM consensus 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT *
FROM consensus
WHERE name IN ('SIRI')

In [11]:
sql = '''
SELECT * FROM stocks 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT * FROM stocks
WHERE name IN ('SIRI')

In [12]:
sql = '''
SELECT * FROM tickers 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT * FROM tickers
WHERE name IN ('SIRI')

In [13]:
sql = '''
SELECT name, kind, year, quarter
FROM profits
ORDER BY name'''
my_profits = pd.read_sql(sql, conmy)
my_profits

     name  kind  year  quarter
0      AH     1  2022        3
1     AIT     1  2022        3
2   BANPU     1  2022        3
3     BBL     1  2022        3
4    BDMS     1  2022        3
5     BEM     1  2022        3
6      BH     1  2022        3
7      CK     1  2022        3
8     CKP     1  2022        3
9    COM7     1  2022        3
10  CPALL     1  2022        3
11    CPF     1  2022        3
12    CPN     1  2022        3
13     EA     1  2022        3
14   GFPT     1  2022        3
15  HMPRO     1  2022        3
16   ICHI     1  2022        3
17    III     1  2022        3
18  JMART     1  2022        3
19    JMT     1  2022        3
20    KCE     1  2022        3
21    KKP     1  2022        3
22    KTB     1  2022        3
23     LH     1  2022        3
24   MEGA     1  2022        3
25    NER     1  2022        3
26    PTL     1  2022        1
27  PTTEP     1  2022        3
28     QH     1  2022        3
29  SAPPE     1  2022        3
30     SC     1  2022        3
31    SCB     1  2022        3
32   SIRI     1  2022        3
33  SPALI     1  2022        3
34    SVI     1  2022        3
35  SYNEX     1  2022        3
36    TFG     1  2022        3
37    TTB     1  2022        3

In [14]:
sql = """
SELECT name, price, target_price, 
buy, hold, sell, yield, 
date(updated_at), ('%s'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0
"""
sql = sql % (today)
print(sql)
#sql = sql % (today, today)
#AND ('%s'::date - date(updated_at)::date) < 15
consensus = pd.read_sql(sql, conpg)
consensus.set_index('name', inplace=True)
consensus['diff'] = consensus['target_price'] - consensus['price']
consensus['upside'] = round(consensus['diff']/consensus['price']*100,2)
consensus.shape

SELECT name, price, target_price,
buy, hold, sell, yield,
date(updated_at), ('2023-01-07'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0

(208, 10)

In [15]:
#consensus.loc['TSTH',['target','upside']] = [1.52,1]

In [16]:
prf_css = pd.merge(my_profits, consensus, on='name', how='inner')
prf_css.sample(10).style.format(format_dict)

In [17]:
prf_css.days.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [18]:
names = prf_css.loc[prf_css.days == 2]['name']
names

2     BANPU
15    HMPRO
37      TTB
Name: name, dtype: object

In [19]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'BANPU', 'HMPRO', 'TTB'"

In [20]:
sqlDel = '''
DELETE FROM consensus 
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM consensus
WHERE name IN ('BANPU', 'HMPRO', 'TTB')

In [21]:
#rp = conpg.execute(sqlDel)
#rp.rowcount

### If there are deleted records, must rerun from select consensus

### Profits w/o consensus

In [22]:
df_tmp = pd.merge(my_profits, consensus, on='name', how='outer',indicator=True)
prf_wo_css = df_tmp['_merge'] == 'left_only'
df_tmp[prf_wo_css]

Empty DataFrame
Columns: [name, kind, year, quarter, price, target_price, buy, hold, sell, yield, date, days, diff, upside, _merge]
Index: []

In [23]:
names = df_tmp[prf_wo_css]['name']
names

Series([], Name: name, dtype: object)

In [24]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

''

In [25]:
sqlDel = '''
DELETE FROM profits
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM profits
WHERE name IN ()

In [26]:
rp = conmy.execute(sqlDel)
rp.rowcount

0

### If there are deleted records, must rerun from select profits

### Start of Gain Percentage Calculation

In [27]:
sql = '''
SELECT name, max_price, min_price, pe, pbv, daily_volume AS dly_vol, beta, market
FROM stocks
'''
my_stocks = pd.read_sql(sql, conmy)
my_stocks.sample(10)

,name,max_price,min_price,pe,pbv,dly_vol,beta,market
213,THG,99.50,36.25,28.94,5.81,121.89,0.51,SET100 / SETWB
88,KKP,76.25,59.50,7.80,1.19,516.91,0.77,SET100 / SETCLMV / SETHD / SETTHSI
98,LIT,3.64,1.63,999.99,0.71,0.35,1.01,mai
76,ICHI,12.30,7.20,26.16,2.54,74.19,1.71,sSET / SETCLMV / SETTHSI
221,TQM,51.00,33.25,30.05,10.81,57.87,1.37,SET100 / SETTHSI
53,EASTW,9.55,4.90,11.05,0.80,10.65,0.71,sSET / SETTHSI
115,ORI,12.70,9.20,8.02,1.75,165.23,1.56,SET100 / SETHD / SETTHSI
242,IMH,23.30,10.80,7.68,3.15,4.35,0.47,mai
130,RATCH,44.50,35.75,11.61,0.88,360.41,0.63,SET50 / SETCLMV / SETHD / SETTHSI
5,AMATA,23.00,17.10,10.32,1.24,249.21,1.52,SET100 / SETCLMV / SETTHSI

In [28]:
filters = [
   (my_stocks.market.str.contains('SET50')),
   (my_stocks.market.str.contains('SET100')),
   (my_stocks.market.str.contains('mai'))]
values = ['SET50','SET100','mai']
my_stocks["mrkt"] = np.select(filters, values, default='SET999')

In [29]:
my_stocks["mrkt"].value_counts()

SET999    148
SET50      50
SET100     46
mai         9
Name: mrkt, dtype: int64

In [30]:
prf_css_stk = pd.merge(prf_css, my_stocks, on='name', how='inner')
prf_css_stk.set_index('name', inplace=True)
prf_css_stk.shape

(38, 21)

In [31]:
set50 = prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside >= s50_pct)
flt_set50 = prf_css_stk[set50]
flt_set50[cols].style.format(format_dict)

In [32]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside < s50_pct)]\
    [cols].style.format(format_dict)

In [33]:
set100 = prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside >= s100_pct)
flt_set100 = prf_css_stk[set100]
flt_set100[cols].style.format(format_dict)

In [34]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside < s100_pct)]\
    [cols].style.format(format_dict)

In [35]:
set999 = prf_css_stk.mrkt.str.contains('SET999') & (prf_css_stk.upside >= s999_pct) 
flt_set999 = prf_css_stk[set999]
flt_set999[cols].style.format(format_dict)

In [36]:
prf_css_stk.loc\
    [(prf_css_stk.mrkt.str.contains('SET999')) & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [37]:
mai = prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside >= s999_pct)
flt_mai = prf_css_stk[mai]
flt_mai[cols].style.format(format_dict)

In [38]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [39]:
flt_all = pd.concat([flt_set50,flt_set100,flt_set999,flt_mai])
flt_all.sort_values(['upside'],ascending=[False]).style.format(format_dict)

In [40]:
flt_all[colu].sort_values(by='name',ascending=True).style.format(format_dict)

In [41]:
'candidates to buy = ' + str(flt_all.shape[0]) + ' stocks'

'candidates to buy = 9 stocks'

In [42]:
sql = '''
SELECT name, sector, subsector
FROM tickers'''
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape[0]

403

In [43]:
final = pd.merge(flt_all, pg_tickers, on='name', how='inner')
final.reset_index()
final[colt].sort_values(['name'],ascending=[True]).to_json("C:/ClearStep/dist/consensus.json", orient="table")

### Final result to update to port_lite stocks

In [44]:
final[colt].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [45]:
final.shape

(9, 24)

### Matching check with Buy table in MySql database to filter only records not yet in stocks

In [46]:
sql = """
SELECT name
FROM buy
WHERE active = 1"""
buy_df = pd.read_sql(sql, const)
buy_df.shape

(27, 1)

In [47]:
final_buy = pd.merge(final, buy_df, on='name', how='outer', indicator=True)
final_buy.shape

(33, 25)

In [48]:
not_in_port = final_buy.loc[
    final_buy['_merge'] == 'left_only']
not_in_port[colt].shape

(6, 13)

In [49]:
not_in_port2 = not_in_port[colt].copy()
not_in_port2

,name,price,target_price,upside,buy,hold,sell,market,sector,subsector,dly_vol,beta,yield
1,CPF,24.20,31.35,29.55,2.0,0.0,0.0,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,Agro & Food Industry,Food & Beverage,503.17,0.76,3.2
3,SCB,110.50,143.40,29.77,5.0,0.0,0.0,SET50 / SETCLMV / SETTHSI,Financials,Banking,1590.69,1.31,4.4
4,CKP,4.60,6.40,39.13,3.0,0.0,0.0,SET100 / SETCLMV / SETTHSI,Resources,Energy & Utilities,42.95,1.04,2.4
5,AH,28.75,40.13,39.58,5.0,1.0,0.0,sSET / SETTHSI,Industrials,Automotive,78.12,1.47,5.3
6,GFPT,12.70,17.58,38.43,5.0,0.0,0.0,SETTHSI,Agro & Food Industry,Agribusiness,49.45,0.58,2.7
8,TFG,5.15,8.00,55.34,3.0,0.0,0.0,SET,Agro & Food Industry,Food & Beverage,31.64,1.03,5.4

In [50]:
file_name = 'consensus-ORD.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(output_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(data_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(box_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(one_file, index=False)

In [51]:
sql = """
SELECT *
FROM stocks"""
stocks = pd.read_sql(sql, conlite)
stocks.shape

(67, 18)

In [52]:
df_merge4 = pd.merge(not_in_port2, stocks, on='name', how='outer', indicator=True)
df_merge4.shape

(67, 31)

In [53]:
df_merge4[df_merge4['_merge'] == 'left_only'].sort_values('name',ascending=True)

Empty DataFrame
Columns: [name, price, target_price, upside, buy, hold, sell, market_x, sector, subsector, dly_vol, beta_x, yield, id, max_price, min_price, status, buy_target, sell_target, volume, beta_y, cost, qty, buy_spread, sell_spread, available_qty, bl, sh, reason, market_y, _merge]
Index: []