### portmy database: profits, stocks tables
### portpg database: consensus, tickers tables
### csv files: consensus-ORD.csv

In [1]:
import pandas as pd
import numpy as np
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/stock')
const = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

pd.set_option('display.max_row', None)
pd.set_option('display.max_column', None)

today = date.today()
today

datetime.date(2023, 1, 21)

### Process after last business day, yesterday must be last business day

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-21
yesterday: 2023-01-20 00:00:00

In [3]:
# find the beginning of the week for the given yesterday
week_start = yesterday.to_period('W').start_time
week_end = yesterday.to_period('W').end_time
week_start = week_start.date()
week_end = week_end.date()
print(f'week start: {week_start}')
print(f'week end: {week_end}')

week start: 2023-01-16
week end: 2023-01-22

In [4]:
yesterday = yesterday.date()
week_start, yesterday

(datetime.date(2023, 1, 16), datetime.date(2023, 1, 20))

In [5]:
s50_pct = 20
s100_pct = 25
s999_pct = 30

### Restart and Run All Cells

In [6]:
cols = 'quarter price target_price upside buy hold sell yield max_price min_price pe pbv dly_vol beta'.split()
colt = 'name price target_price upside buy hold sell market sector subsector dly_vol beta yield'.split()
colu = 'price target_price upside buy hold sell mrkt yield'.split()

format_dict = {
    'latest_amt_y':'{:,}','previous_amt_y':'{:,}','inc_amt_y':'{:,}',   
    'latest_amt_q':'{:,}','previous_amt_q':'{:,}','inc_amt_q':'{:,}',    
    'q_amt_c':'{:,}','y_amt': '{:,}','inc_amt_py':'{:,}', 
    'q_amt_p': '{:,}','inc_amt_pq':'{:,}', 
    'inc_pct_y': '{:.2f}%','inc_pct_q': '{:.2f}%',
    'inc_pct_py': '{:.2f}%','inc_pct_pq': '{:.2f}%',
    'mean_pct': '{:.2f}%','std_pct': '{:.2f}%','upside': '{:.2f}%', 
    
    'price':'{:.2f}','target_price':'{:.2f}','diff':'{:.2f}',
    'eps_a':'{:.2f}','eps_b':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'yield':'{:.2f}%',
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}',    
}

In [7]:
sql = """
SELECT * FROM profits 
ORDER BY id DESC 
LIMIT 1
"""
tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

In [8]:
names = tmp['name'].values.tolist()
names

['TTB']

In [9]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'TTB'"

In [10]:
sql = '''
SELECT * 
FROM consensus 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT *
FROM consensus
WHERE name IN ('TTB')

In [11]:
sql = '''
SELECT * FROM stocks 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conlite)
tmp.style.format(format_dict)

SELECT * FROM stocks
WHERE name IN ('TTB')

In [12]:
sql = '''
SELECT * FROM tickers 
WHERE name IN (%s)
'''
sql = sql % in_p
print(sql)

tmp = pd.read_sql(sql, conmy)
tmp.style.format(format_dict)

SELECT * FROM tickers
WHERE name IN ('TTB')

In [13]:
sql = '''
SELECT name, kind, year, quarter
FROM profits
ORDER BY name'''
my_profits = pd.read_sql(sql, conmy)
my_profits

     name  kind  year  quarter
0      AH     1  2022        3
1     AIT     1  2022        3
2   BANPU     1  2022        3
3    BDMS     1  2022        3
4     BEM     1  2022        3
5      BH     1  2022        3
6      CK     1  2022        3
7     CKP     1  2022        3
8    COM7     1  2022        3
9   CPALL     1  2022        3
10    CPF     1  2022        3
11    CPN     1  2022        3
12     EA     1  2022        3
13   GFPT     1  2022        3
14  HMPRO     1  2022        3
15   ICHI     1  2022        3
16    III     1  2022        3
17  JMART     1  2022        3
18    JMT     1  2022        3
19    KCE     1  2022        3
20     LH     1  2022        3
21   MEGA     1  2022        3
22    NER     1  2022        3
23    PTL     1  2022        1
24  PTTEP     1  2022        3
25     QH     1  2022        3
26  SAPPE     1  2022        3
27     SC     1  2022        3
28   SIRI     1  2022        3
29  SPALI     1  2022        3
30    SVI     1  2022        3
31  SYNEX     1  2022        3
32    TTB     1  2022        4

In [14]:
sql = """
SELECT name, price, target_price, 
buy, hold, sell, yield, 
date(updated_at), ('%s'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0
"""
sql = sql % (today)
print(sql)
#sql = sql % (today, today)
#AND ('%s'::date - date(updated_at)::date) < 15
consensus = pd.read_sql(sql, conpg)
consensus.set_index('name', inplace=True)
consensus['diff'] = consensus['target_price'] - consensus['price']
consensus['upside'] = round(consensus['diff']/consensus['price']*100,2)
consensus.shape

SELECT name, price, target_price,
buy, hold, sell, yield,
date(updated_at), ('2023-01-21'::date - date(updated_at)::date) AS days
FROM consensus
WHERE price > 0 AND target_price > 0

(209, 10)

In [15]:
#consensus.loc['TSTH',['target','upside']] = [1.52,1]

In [16]:
prf_css = pd.merge(my_profits, consensus, on='name', how='inner')
prf_css.sample(10).style.format(format_dict)

In [17]:
prf_css.days.value_counts(normalize=True).to_frame().style.format('{:.2%}')

In [22]:
names = prf_css.loc[prf_css.days == 21]['name']
names

23    PTL
Name: name, dtype: object

In [23]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'PTL'"

In [24]:
sqlDel = '''
DELETE FROM consensus 
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM consensus
WHERE name IN ('PTL')

In [21]:
#rp = conpg.execute(sqlDel)
#rp.rowcount

### If there are deleted records, must rerun from select consensus

### Profits w/o consensus

In [25]:
df_tmp = pd.merge(my_profits, consensus, on='name', how='outer',indicator=True)
prf_wo_css = df_tmp['_merge'] == 'left_only'
df_tmp[prf_wo_css]

Empty DataFrame
Columns: [name, kind, year, quarter, price, target_price, buy, hold, sell, yield, date, days, diff, upside, _merge]
Index: []

In [26]:
names = df_tmp[prf_wo_css]['name']
names

Series([], Name: name, dtype: object)

In [27]:
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

''

In [28]:
sqlDel = '''
DELETE FROM profits
WHERE name IN (%s)
'''
sqlDel = sqlDel % in_p
print(sqlDel)

DELETE FROM profits
WHERE name IN ()

In [29]:
rp = conmy.execute(sqlDel)
rp.rowcount

0

### If there are deleted records, must rerun from select profits

### Start of Gain Percentage Calculation

In [30]:
sql = '''
SELECT name, max_price, min_price, pe, pbv, daily_volume AS dly_vol, beta, market
FROM stocks
'''
my_stocks = pd.read_sql(sql, conmy)
my_stocks.sample(10)

,name,max_price,min_price,pe,pbv,dly_vol,beta,market
191,TVI,24.70,11.30,16.56,2.11,2.54,0.73,sSET
155,SPPT,6.00,3.20,999.99,1.95,5.42,0.74,SET
30,BPP,17.20,13.90,8.19,1.00,25.25,0.81,SETCLMV / SETTHSI
190,TU,21.50,15.20,9.75,1.25,387.93,0.70,SET50 / SETCLMV / SETHD / SETWB
142,SCCC,175.50,144.50,12.39,1.31,20.94,0.43,SETCLMV / SETTHSI
124,PTG,16.40,12.90,28.62,2.84,160.50,1.24,SET100 / SETTHSI
178,TTB,1.47,1.09,10.38,0.64,429.83,1.05,SET50 / SETHD / SETTHSI
47,DCON,0.60,0.36,17.95,0.96,2.03,1.23,SET
56,EGCO,190.00,159.50,23.88,0.71,177.61,0.52,SET50 / SETCLMV / SETHD / SETTHSI
67,GLOBAL,23.70,16.80,26.69,4.63,480.68,1.03,SET50 / SETCLMV / SETTHSI / SETWB

In [31]:
filters = [
   (my_stocks.market.str.contains('SET50')),
   (my_stocks.market.str.contains('SET100')),
   (my_stocks.market.str.contains('mai'))]
values = ['SET50','SET100','mai']
my_stocks["mrkt"] = np.select(filters, values, default='SET999')

In [32]:
my_stocks["mrkt"].value_counts()

SET999    148
SET50      50
SET100     46
mai         9
Name: mrkt, dtype: int64

In [33]:
prf_css_stk = pd.merge(prf_css, my_stocks, on='name', how='inner')
prf_css_stk.set_index('name', inplace=True)
prf_css_stk.shape

(33, 21)

In [34]:
set50 = prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside >= s50_pct)
flt_set50 = prf_css_stk[set50]
flt_set50[cols].style.format(format_dict)

In [35]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET50') & (prf_css_stk.upside < s50_pct)]\
    [cols].style.format(format_dict)

In [36]:
set100 = prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside >= s100_pct)
flt_set100 = prf_css_stk[set100]
flt_set100[cols].style.format(format_dict)

In [37]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('SET100') & (prf_css_stk.upside < s100_pct)]\
    [cols].style.format(format_dict)

In [38]:
set999 = prf_css_stk.mrkt.str.contains('SET999') & (prf_css_stk.upside >= s999_pct) 
flt_set999 = prf_css_stk[set999]
flt_set999[cols].style.format(format_dict)

In [39]:
prf_css_stk.loc\
    [(prf_css_stk.mrkt.str.contains('SET999')) & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [40]:
mai = prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside >= s999_pct)
flt_mai = prf_css_stk[mai]
flt_mai[cols].style.format(format_dict)

In [41]:
prf_css_stk.loc\
    [prf_css_stk.mrkt.str.contains('mai') & (prf_css_stk.upside < s999_pct)]\
    [cols].style.format(format_dict)

In [42]:
flt_all = pd.concat([flt_set50,flt_set100,flt_set999,flt_mai])
flt_all.sort_values(['upside'],ascending=[False]).style.format(format_dict)

In [43]:
flt_all[colu].sort_values(by='name',ascending=True).style.format(format_dict)

In [44]:
'candidates to buy = ' + str(flt_all.shape[0]) + ' stocks'

'candidates to buy = 7 stocks'

In [45]:
sql = '''
SELECT name, sector, subsector
FROM tickers'''
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape[0]

403

In [46]:
final = pd.merge(flt_all, pg_tickers, on='name', how='inner')
final.reset_index()
final[colt].sort_values(['name'],ascending=[True]).to_json("C:/ClearStep/dist/consensus.json", orient="table")

### Final result to update to port_lite stocks

In [47]:
final[colt].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [48]:
final.shape

(7, 24)

### Matching check with Buy table in MySql database to filter only records not yet in stocks

In [49]:
sql = """
SELECT name
FROM buy
WHERE active = 1"""
buy_df = pd.read_sql(sql, const)
buy_df.shape

(27, 1)

In [50]:
final_buy = pd.merge(final, buy_df, on='name', how='outer', indicator=True)
final_buy.shape

(32, 25)

In [51]:
not_in_port = final_buy.loc[
    final_buy['_merge'] == 'left_only']
not_in_port[colt].shape

(5, 13)

In [52]:
not_in_port2 = not_in_port[colt].copy()
not_in_port2

,name,price,target_price,upside,buy,hold,sell,market,sector,subsector,dly_vol,beta,yield
1,CPF,24.10,31.35,30.08,2.0,0.0,0.0,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,Agro & Food Industry,Food & Beverage,421.03,0.77,3.2
3,CK,23.70,30.11,27.05,3.0,0.0,0.0,SET100 / SETCLMV,Property & Construction,Construction Services,167.92,0.82,1.7
4,CKP,4.64,6.60,42.24,2.0,0.0,0.0,SET100 / SETCLMV / SETTHSI,Resources,Energy & Utilities,60.77,1.04,2.6
5,MEGA,49.75,62.70,26.03,5.0,0.0,0.0,SET100 / SETCLMV / SETTHSI / SETWB,Services,Commerce,178.57,1.14,3.0
6,GFPT,13.20,17.40,31.82,4.0,0.0,0.0,SETTHSI,Agro & Food Industry,Agribusiness,76.82,0.69,2.7

In [53]:
file_name = 'consensus-ORD.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(output_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(data_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(box_file, index=False)
not_in_port[colt].sort_values(['name'],ascending=[True]).to_csv(one_file, index=False)

In [54]:
sql = """
SELECT *
FROM stocks"""
stocks = pd.read_sql(sql, conlite)
stocks.shape

(66, 18)

In [55]:
df_merge4 = pd.merge(not_in_port2, stocks, on='name', how='outer', indicator=True)
df_merge4.shape

(66, 31)

In [56]:
df_merge4[df_merge4['_merge'] == 'left_only'].sort_values('name',ascending=True)

Empty DataFrame
Columns: [name, price, target_price, upside, buy, hold, sell, market_x, sector, subsector, dly_vol, beta_x, yield, id, max_price, min_price, status, buy_target, sell_target, volume, beta_y, cost, qty, buy_spread, sell_spread, available_qty, bl, sh, reason, market_y, _merge]
Index: []