In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 7), datetime.date(2023, 1, 6))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-07
yesterday: 2023-01-06 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 1, 6), datetime.date(2022, 1, 6))

### Restart and Run All Cells

### Weekly process or when stataus changes.

In [4]:
pd.read_sql_query('SELECT * FROM sales ORDER BY name', conlite)

           id   name     fm_date     to_date  days  fm_price  to_price   diff  \
0     1200124     AP  2021-12-30  2022-01-06     5      9.55      9.45  -0.10
1     1200125     AP  2022-01-06  2022-01-10     2      9.45      9.70   0.25
2     1200126     AP  2022-01-10  2022-01-11     1      9.70      9.40  -0.30
3     1200127     AP  2022-01-11  2022-01-14     3      9.40      9.55   0.15
4     1200128     AP  2022-01-13  2022-01-24     7      9.55      9.25  -0.30
5     1200129     AP  2022-01-24  2022-01-27     3      9.25     10.10   0.85
6     1200130     AP  2022-01-27  2022-01-28     1     10.10     10.00  -0.10
7     1200131     AP  2022-01-28  2022-02-02     3     10.00     10.30   0.30
8     1200132     AP  2022-02-02  2022-02-03     1     10.30     10.10  -0.20
9     1200133     AP  2022-02-03  2022-02-07     2     10.10     10.60   0.50
10    1200134     AP  2022-02-07  2022-02-08     1     10.60     10.50  -0.10
11    1200135     AP  2022-02-08  2022-02-09     1     10.50     10.90   0.40
12    1200136     AP  2022-02-09  2022-02-14     3     10.90     10.70  -0.20
13    1200137     AP  2022-02-14  2022-02-15     1     10.70     10.90   0.20
14    1200138     AP  2022-02-15  2022-02-17     2     10.90     10.80  -0.10
15    1200139     AP  2022-02-17  2022-02-18     1     10.80     11.00   0.20
16    1200140     AP  2022-02-18  2022-02-21     1     11.00     10.80  -0.20
17    1200141     AP  2022-02-21  2022-02-23     2     10.80     11.30   0.50
18    1200142     AP  2022-02-23  2022-03-02     5     11.30     10.50  -0.80
19    1200143     AP  2022-03-01  2022-03-04     3     10.50     10.80   0.30
20    1200144     AP  2022-03-04  2022-03-08     2     10.80     10.20  -0.60
21    1200145     AP  2022-03-08  2022-03-09     1     10.20     10.40   0.20
22    1200146     AP  2022-03-09  2022-03-10     1     10.40     10.30  -0.10
23    1200147     AP  2022-03-10  2022-03-11     1     10.30     10.40   0.10
24    1200148     AP  2022-03-11  2022-03-14     1     10.40     10.20  -0.20
25    1200149     AP  2022-03-14  2022-03-17     3     10.20     10.50   0.30
26    1200150     AP  2022-03-17  2022-03-22     3     10.50     10.40  -0.10
27    1200151     AP  2022-03-18  2022-03-24     4     10.40     10.70   0.30
28    1200152     AP  2022-03-23  2022-03-25     2     10.70     10.60  -0.10
29    1200153     AP  2022-03-25  2022-04-04     6     10.60     11.00   0.40
30    1200154     AP  2022-03-30  2022-04-07     6     11.00     10.70  -0.30
31    1200155     AP  2022-04-07  2022-04-11     2     10.70     11.00   0.30
32    1200156     AP  2022-04-11  2022-04-12     1     11.00     10.90  -0.10
33    1200157     AP  2022-04-12  2022-04-21     7     10.90     11.50   0.60
34    1200158     AP  2022-04-20  2022-04-22     2     11.50     11.40  -0.10
35    1200159     AP  2022-04-22  2022-04-28     4     11.40     11.90   0.50
36    1200160     AP  2022-04-28  2022-05-11     9     11.90     10.50  -1.40
37    1200161     AP  2022-05-11  2022-05-18     5     10.50     11.00   0.50
38    1200162     AP  2022-05-18  2022-05-24     4     11.00     10.70  -0.30
39    1200163     AP  2022-05-23  2022-06-02     8     10.70     11.20   0.50
40    1200164     AP  2022-05-30  2022-06-06     5     11.20     11.10  -0.10
41    1200165     AP  2022-06-06  2022-06-07     1     11.10     11.20   0.10
42    1200166     AP  2022-06-07  2022-06-14     5     11.20      9.95  -1.25
43    1200167     AP  2022-06-14  2022-06-15     1      9.95     10.10   0.15
44    1200168     AP  2022-06-15  2022-06-20     3     10.10      9.90  -0.20
45    1200169     AP  2022-06-17  2022-06-23     4      9.90     10.00   0.10
46    1200170     AP  2022-06-23  2022-06-24     1     10.00      9.80  -0.20
47    1200171     AP  2022-06-24  2022-07-01     5      9.80     10.00   0.20
48    1200172     AP  2022-06-29  2022-07-06     5     10.00      9.80  -0.20
49    1200173     AP  2022-07-05  2022-07-07     2      9.80      9.95   0.15
50    1200174     AP  2022-07-07  2022-07-19     8      9.95      9.15  -0.80
51    1200175     AP  2022-07-19  2022-07-25     4      9.15      9.80   0.65
52    1200176     AP  2022-07-25  2022-07-26     1      9.80      9.70  -0.10
53    1200177     AP  2022-07-26  2022-08-05     8      9.70     10.40   0.70
54    1200178     AP  2022-08-05  2022-08-09     2     10.40     10.30  -0.10
55    1200179     AP  2022-08-08  2022-08-11     3     10.30     10.50   0.20
56    1200180     AP  2022-08-10  2022-08-19     7     10.50     10.30  -0.20
57    1200181     AP  2022-08-15  2022-08-22     5     10.30     10.40   0.10
58    1200182     AP  2022-08-22  2022-08-24     2     10.40     10.20  -0.20
59    1200183     AP  2022-08-23  2022-08-29     4     10.20     10.30   0.10
60    1200184     AP  2022-08-25  2022-09-05     7     10.30      9.90  -0.40
61    1200185     AP  2022-09-01  2022-09-06     3      9.90     10.00   0.10
62    1200186     AP  2022-09-06  2022-09-07     1     10.00      9.85  -0.15
63    1200187     AP  2022-09-07  2022-09-12     3      9.85     10.40   0.55
64    1200188     AP  2022-09-12  2022-09-16     4     10.40     10.00  -0.40
65    1200189     AP  2022-09-16  2022-09-20     2     10.00     10.10   0.10
66    1200190     AP  2022-09-19  2022-09-21     2     10.10      9.85  -0.25
67    1200191     AP  2022-09-21  2022-09-22     1      9.85      9.95   0.10
68    1200192     AP  2022-09-22  2022-09-26     2      9.95      9.65  -0.30
69    1200193     AP  2022-09-26  2022-09-27     1      9.65      9.75   0.10
70    1200194     AP  2022-09-27  2022-10-04     5      9.75      9.35  -0.40
71    1200195     AP  2022-10-03  2022-10-07     4      9.35      9.65   0.30
72    1200196     AP  2022-10-06  2022-10-12     4      9.65      9.45  -0.20
73    1200197     AP  2022-10-12  2022-10-20     6      9.45      9.90   0.45
74    1200198     AP  2022-10-20  2022-10-25     3      9.90      9.60  -0.30
75    1200199     AP  2022-10-21  2022-10-27     4      9.60     10.20   0.60
76    1200200     AP  2022-10-26  2022-10-31     3     10.20      9.80  -0.40
77    1200201     AP  2022-10-31  2022-11-07     5      9.80     10.30   0.50
78    1200202     AP  2022-11-07  2022-11-08     1     10.30     10.20  -0.10
79    1200203     AP  2022-11-08  2022-11-10     2     10.20     10.40   0.20
80    1200204     AP  2022-11-10  2022-11-23     9     10.40     10.10  -0.30
81    1200205     AP  2022-11-23  2022-11-24     1     10.10     10.20   0.10
82    1200206     AP  2022-11-24  2022-11-28     2     10.20     10.10  -0.10
83    1200207     AP  2022-11-25  2022-11-29     2     10.10     10.20   0.10
84    1200208     AP  2022-11-29  2022-11-30     1     10.20     10.10  -0.10
85    1200209     AP  2022-11-30  2022-12-08     6     10.10     10.90   0.80
86    1200210     AP  2022-12-08  2022-12-09     1     10.90     10.80  -0.10
87    1200211     AP  2022-12-09  2022-12-15     4     10.80     11.20   0.40
88    1200212     AP  2022-12-14  2022-12-16     2     11.20     11.10  -0.10
89    1200213     AP  2022-12-16  2022-12-19     1     11.10     11.30   0.20
90    1200214     AP  2022-12-19  2022-12-21     2     11.30     11.10  -0.20
91    1200215     AP  2022-12-21  2022-12-29     6     11.10     11.70   0.60
92    1200216     AP  2022-12-29  2022-12-30     1     11.70     11.60  -0.10
93    1202000     AP  2022-12-30  2023-01-03     2     11.60     11.70   0.10
94    1202009     AP  2023-01-03  2023-01-04     1     11.70     11.60  -0.10
95    1202017     AP  2023-01-04  2023-01-06     2     11.60     11.50  -0.10
96    1200217  BANPU  2021-12-30  2022-01-17    12     10.60     11.20   0.60
97    1200218  BANPU  2022-01-07  2022-01-25    12     11.20     10.60  -0.60
98    1200219  BANPU  2022-01-25  2022-01-31     4     10.60     11.10   0.50
99    1200220  BANPU  2022-01-31  2022-02-03     3     11.10     10.80  -0.30
100   1200221  BANPU  2022-02-03  2022-02-09     4     10.80     11.40   0.60
101   1200222  BANPU  2022-02-09  2022-02-11     2     11.40     11.30  -0.10
102   1200223  BANPU  2022-02-10  2022-02-14     2     11.30     11.50   0.20
103   1200224  BANPU  2022-02-14  2022-02-21     5     11.50     10.80  -0.70
104   1200225  BANPU  2022-02-21  2022-02-23     2     10.80     11.10   0.30
105   1200226  BANPU  2022-02-23  2022-02-24     1     11.10     10.80  -0.30
106   1200227  BANPU  2022-02-24  2022-03-03     5     10.80     12.50   1.70
107   1200228  BANPU  2022-03-03  2022-03-04     1     12.50     11.70  -0.80
108   1200229  BANPU  2022-03-04  2022-03-07     1     11.70     12.10   0.40
109   1200230  BANPU  2022-03-07  2022-03-10     3     12.10     11.30  -0.80
110   1200231  BANPU  2022-03-10  2022-03-11     1     11.30     11.50   0.20
111   1200232  BANPU  2022-03-11  2022-03-15     2     11.50     10.80  -0.70
112   1200233  BANPU  2022-03-15  2022-03-18     3     10.80     11.10   0.30
113   1200234  BANPU  2022-03-18  2022-03-21     1     11.10     11.00  -0.10
114   1200235  BANPU  2022-03-21  2022-03-29     6     11.00     11.50   0.50
115   1200236  BANPU  2022-03-29  2022-03-31     2     11.50     11.00  -0.50
116   1200237  BANPU  2022-03-31  2022-04-07     5     11.00     11.30   0.30
117   1200238  BANPU  2022-04-07  2022-04-12     3     11.30     10.80  -0.50
118   1200239  BANPU  2022-04-12  2022-04-22     8     10.80     11.90   1.10
119   1200240  BANPU  2022-04-22  2022-04-27     3     11.90     11.60  -0.30
120   1200241  BANPU  2022-04-25  2022-04-29     4     11.60     12.30   0.70
121   1200242  BANPU  2022-04-29  2022-05-03     2     12.30     12.20  -0.10
122   1200243  BANPU  2022-05-03  2022-05-09     4     12.20     12.50   0.30
123   1200244  BANPU  2022-05-06  2022-05-12     4     12.50     11.50  -1.00
124   1200245  BANPU  2022-05-12  2022-05-18     4     11.50     11.90   0.40
125   1200246  BANPU  2022-05-17  2022-05-19     2     11.90     11.70  -0.20
126   1200247  BANPU  2022-05-19  2022-05-23     2     11.70     12.20   0.50
127   1200248  BANPU  2022-05-20  2022-05-25     3     12.20     11.80  -0.40
128   1200249  BANPU  2022-05-25  2022-05-26     1     11.80     12.20   0.40
129   1200250  BANPU  2022-05-26  2022-05-30     2     12.20     12.10  -0.10
130   1200251  BANPU  2022-05-27  2022-06-07     7     12.10     13.30   1.20
131   1200252  BANPU  2022-06-07  2022-06-08     1     13.30     13.00  -0.30
132   1200253  BANPU  2022-06-08  2022-06-09     1     13.00     13.10   0.10
133   1200254  BANPU  2022-06-09  2022-06-13     2     13.10     13.00  -0.10
134   1200255  BANPU  2022-06-10  2022-06-14     2     13.00     13.40   0.40
135   1200256  BANPU  2022-06-14  2022-06-20     4     13.40     12.50  -0.90
136   1200257  BANPU  2022-06-20  2022-06-21     1     12.50     12.80   0.30
137   1200258  BANPU  2022-06-21  2022-06-24     3     12.80     12.20  -0.60
138   1200259  BANPU  2022-06-24  2022-06-30     4     12.20     12.60   0.40
139   1200260  BANPU  2022-06-29  2022-07-04     3     12.60     12.20  -0.40
140   1200261  BANPU  2022-07-04  2022-07-05     1     12.20     12.50   0.30
141   1200262  BANPU  2022-07-05  2022-07-06     1     12.50     12.20  -0.30
142   1200263  BANPU  2022-07-06  2022-07-11     3     12.20     12.90   0.70
143   1200264  BANPU  2022-07-11  2022-07-15     4     12.90     12.50  -0.40
144   1200265  BANPU  2022-07-15  2022-07-19     2     12.50     12.90   0.40
145   1200266  BANPU  2022-07-19  2022-07-21     2     12.90     12.80  -0.10
146   1200267  BANPU  2022-07-20  2022-07-27     5     12.80     13.40   0.60
147   1200268  BANPU  2022-07-27  2022-08-02     4     13.40     13.10  -0.30
148   1200269  BANPU  2022-08-02  2022-08-03     1     13.10     13.30   0.20
149   1200270  BANPU  2022-08-03  2022-08-08     3     13.30     12.60  -0.70
150   1200271  BANPU  2022-08-08  2022-08-17     7     12.60     14.00   1.40
151   1200272  BANPU  2022-08-17  2022-08-22     3     14.00     13.90  -0.10
152   1200273  BANPU  2022-08-18  2022-08-30     8     13.90     14.90   1.00
153   1200274  BANPU  2022-08-30  2022-09-02     3     14.90     13.90  -1.00
154   1200275  BANPU  2022-09-02  2022-09-06     2     13.90     14.50   0.60
155   1200276  BANPU  2022-09-06  2022-09-08     2     14.50     14.00  -0.50
156   1200277  BANPU  2022-09-08  2022-09-12     2     14.00     14.40   0.40
157   1200278  BANPU  2022-09-12  2022-09-19     5     14.40     13.30  -1.10
158   1200279  BANPU  2022-09-19  2022-09-21     2     13.30     13.70   0.40
159   1200280  BANPU  2022-09-21  2022-10-03     8     13.70     12.10  -1.60
160   1200281  BANPU  2022-10-03  2022-10-06     3     12.10     12.70   0.60
161   1200282  BANPU  2022-10-06  2022-10-07     1     12.70     12.30  -0.40
162   1200283  BANPU  2022-10-07  2022-10-17     6     12.30     12.80   0.50
163   1200284  BANPU  2022-10-17  2022-10-19     2     12.80     12.40  -0.40
164   1200285  BANPU  2022-10-19  2022-10-20     1     12.40     12.70   0.30
165   1200286  BANPU  2022-10-20  2022-10-25     3     12.70     12.40  -0.30
166   1200287  BANPU  2022-10-25  2022-10-27     2     12.40     12.50   0.10
167   1200288  BANPU  2022-10-26  2022-10-28     2     12.50     12.30  -0.20
168   1200289  BANPU  2022-10-28  2022-11-01     2     12.30     12.60   0.30
169   1200290  BANPU  2022-11-01  2022-11-02     1     12.60     12.50  -0.10
170   1200291  BANPU  2022-11-02  2022-11-07     3     12.50     13.00   0.50
171   1200292  BANPU  2022-11-07  2022-11-09     2     13.00     12.60  -0.40
172   1200293  BANPU  2022-11-09  2022-11-11     2     12.60     12.80   0.20
173   1200294  BANPU  2022-11-11  2022-11-18     5     12.80     12.40  -0.40
174   1200295  BANPU  2022-11-18  2022-11-24     4     12.40     13.10   0.70
175   1200296  BANPU  2022-11-23  2022-11-28     3     13.10     12.70  -0.40
176   1200297  BANPU  2022-11-28  2022-12-06     6     12.70     13.50   0.80
177   1200298  BANPU  2022-12-06  2022-12-08     2     13.50     13.30  -0.20
178   1200299  BANPU  2022-12-08  2022-12-14     4     13.30     13.70   0.40
179   1200300  BANPU  2022-12-14  2022-12-19     3     13.70     13.50  -0.20
180   1200301  BANPU  2022-12-19  2022-12-20     1     13.50     13.60   0.10
181   1200302  BANPU  2022-12-20  2022-12-21     1     13.60     13.50  -0.10
182   1200303  BANPU  2022-12-21  2022-12-22     1     13.50     13.60   0.10
183   1200304  BANPU  2022-12-22  2022-12-23     1     13.60     13.40  -0.20
184   1200305  BANPU  2022-12-23  2022-12-26     1     13.40     13.50   0.10
185   1200306  BANPU  2022-12-26  2022-12-27     1     13.50     13.40  -0.10
186   1200307  BANPU  2022-12-27  2022-12-30     3     13.40     13.70   0.30
187   1202002  BANPU  2022-12-30  2023-01-06     5     13.70     12.30  -1.40
188   1200308    BCP  2021-12-30  2022-01-05     4     25.25     26.25   1.00
189   1200309    BCP  2022-01-05  2022-01-06     1     26.25     25.50  -0.75
190   1200310    BCP  2022-01-06  2022-01-12     4     25.50     27.50   2.00
191   1200311    BCP  2022-01-12  2022-01-14     2     27.50     26.75  -0.75
192   1200312    BCP  2022-01-13  2022-01-17     2     26.75     27.50   0.75
193   1200313    BCP  2022-01-17  2022-01-18     1     27.50     27.00  -0.50
194   1200314    BCP  2022-01-18  2022-01-19     1     27.00     27.50   0.50
195   1200315    BCP  2022-01-19  2022-01-24     3     27.50     26.75  -0.75
196   1200316    BCP  2022-01-24  2022-01-26     2     26.75     27.50   0.75
197   1200317    BCP  2022-01-26  2022-01-27     1     27.50     27.00  -0.50
198   1200318    BCP  2022-01-27  2022-02-07     7     27.00     30.75   3.75
199   1200319    BCP  2022-02-07  2022-02-11     4     30.75     29.00  -1.75
200   1200320    BCP  2022-02-11  2022-02-14     1     29.00     29.75   0.75
201   1200321    BCP  2022-02-14  2022-02-15     1     29.75     29.25  -0.50
202   1200322    BCP  2022-02-15  2022-02-18     3     29.25     30.75   1.50
203   1200323    BCP  2022-02-18  2022-02-21     1     30.75     29.75  -1.00
204   1200324    BCP  2022-02-21  2022-02-25     4     29.75     31.25   1.50
205   1200325    BCP  2022-02-24  2022-02-28     2     31.25     31.00  -0.25
206   1200326    BCP  2022-02-28  2022-03-01     1     31.00     31.75   0.75
207   1200327    BCP  2022-03-01  2022-03-02     1     31.75     31.25  -0.50
208   1200328    BCP  2022-03-02  2022-03-03     1     31.25     32.25   1.00
209   1200329    BCP  2022-03-03  2022-03-07     2     32.25     30.75  -1.50
210   1200330    BCP  2022-03-07  2022-03-08     1     30.75     31.00   0.25
211   1200331    BCP  2022-03-08  2022-03-09     1     31.00     29.50  -1.50
212   1200332    BCP  2022-03-09  2022-03-11     2     29.50     31.00   1.50
213   1200333    BCP  2022-03-11  2022-03-15     2     31.00     29.00  -2.00
214   1200334    BCP  2022-03-15  2022-03-17     2     29.00     29.50   0.50
215   1200335    BCP  2022-03-17  2022-03-18     1     29.50     29.00  -0.50
216   1200336    BCP  2022-03-18  2022-03-28     6     29.00     30.50   1.50
217   1200337    BCP  2022-03-24  2022-03-30     4     30.50     29.50  -1.00
218   1200338    BCP  2022-03-30  2022-03-31     1     29.50     29.75   0.25
219   1200339    BCP  2022-03-31  2022-04-04     2     29.75     29.50  -0.25
220   1200340    BCP  2022-04-01  2022-04-07     4     29.50     31.00   1.50
221   1200341    BCP  2022-04-07  2022-04-12     3     31.00     30.50  -0.50
222   1200342    BCP  2022-04-08  2022-04-22    10     30.50     32.00   1.50
223   1200343    BCP  2022-04-21  2022-04-26     3     32.00     31.75  -0.25
224   1200344    BCP  2022-04-25  2022-05-05     8     31.75     34.75   3.00
225   1200345    BCP  2022-05-05  2022-05-09     2     34.75     34.00  -0.75
226   1200346    BCP  2022-05-09  2022-05-10     1     34.00     34.75   0.75
227   1200347    BCP  2022-05-10  2022-05-12     2     34.75     33.75  -1.00
228   1200348    BCP  2022-05-12  2022-05-18     4     33.75     35.25   1.50
229   1200349    BCP  2022-05-18  2022-05-30     8     35.25     32.00  -3.25
230   1200350    BCP  2022-05-30  2022-05-31     1     32.00     33.00   1.00
231   1200351    BCP  2022-05-31  2022-06-01     1     33.00     32.75  -0.25
232   1200352    BCP  2022-06-01  2022-06-09     6     32.75     35.00   2.25
233   1200353    BCP  2022-06-08  2022-06-13     3     35.00     31.75  -3.25
234   1200354    BCP  2022-06-13  2022-06-15     2     31.75     32.75   1.00
235   1200355    BCP  2022-06-15  2022-06-17     2     32.75     29.25  -3.50
236   1200356    BCP  2022-06-17  2022-06-23     4     29.25     31.50   2.25
237   1200357    BCP  2022-06-23  2022-06-27     2     31.50     30.50  -1.00
238   1200358    BCP  2022-06-27  2022-06-29     2     30.50     32.00   1.50
239   1200359    BCP  2022-06-29  2022-07-06     5     32.00     30.75  -1.25
240   1200360    BCP  2022-07-06  2022-07-07     1     30.75     31.25   0.50
241   1200361    BCP  2022-07-07  2022-07-11     2     31.25     30.75  -0.50
242   1200362    BCP  2022-07-08  2022-07-12     2     30.75     31.00   0.25
243   1200363    BCP  2022-07-12  2022-07-15     3     31.00     29.00  -2.00
244   1200364    BCP  2022-07-15  2022-07-19     2     29.00     30.00   1.00
245   1200365    BCP  2022-07-19  2022-07-25     4     30.00     29.00  -1.00
246   1200366    BCP  2022-07-22  2022-08-03     8     29.00     30.25   1.25
247   1200367    BCP  2022-08-03  2022-08-08     3     30.25     29.00  -1.25
248   1200368    BCP  2022-08-05  2022-08-10     3     29.00     30.25   1.25
249   1200369    BCP  2022-08-10  2022-08-11     1     30.25     30.00  -0.25
250   1200370    BCP  2022-08-11  2022-08-30    13     30.00     36.75   6.75
251   1200371    BCP  2022-08-30  2022-09-01     2     36.75     34.50  -2.25
252   1200372    BCP  2022-09-01  2022-09-02     1     34.50     35.00   0.50
253   1200373    BCP  2022-09-02  2022-09-08     4     35.00     32.75  -2.25
254   1200374    BCP  2022-09-08  2022-09-12     2     32.75     33.25   0.50

In [5]:
sqlDel = """DELETE FROM sales"""
rp = conlite.execute(sqlDel)
rp.rowcount

2197

In [6]:
sql = """
SELECT name
FROM orders 
ORDER BY name
"""
df = pd.read_sql(sql, conlite)

names = df['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CKP', 'CPF', 'CPNREIT', 'GFPT', 'GVREIT', 'IVL', 'JMART', 'LPF', 'MAKRO', 'PTT', 'SCC', 'SINGER', 'SYNEX', 'TFFIF', 'TFG', 'TMT', 'WHAIR'"

In [7]:
len(in_p.split(','))

20

### Get past one year data

In [8]:
sql = """
SELECT * 
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (a_year_ago, in_p)
print(sql)

SELECT *
FROM price
WHERE date >= '2022-01-06' AND name IN ('ASP', 'BANPU', 'BCH', 'CKP', 'CPF', 'CPNREIT', 'GFPT', 'GVREIT', 'IVL', 'JMART', 'LPF', 'MAKRO', 'PTT', 'SCC', 'SINGER', 'SYNEX', 'TFFIF', 'TFG', 'TMT', 'WHAIR')
ORDER BY name, date

In [9]:
df = pd.read_sql(sql, const)
df.shape

(4860, 7)

In [10]:
data_path = "../data/"
file_name = "Yearly-Price-by-Name.csv"
output_file = data_path + file_name

df.set_index("name", inplace=True)
df.to_csv(output_file, header=None)

In [11]:
sql = """
SELECT name,trade 
FROM orders 
WHERE name IN (%s)
ORDER BY name
"""
sql = sql % in_p
orders = pd.read_sql(sql, conlite)
orders.set_index(['name'],inplace=True)
orders.shape

(20, 1)

### Create monitors from stocks

In [12]:
sql = """
SELECT name, trade 
FROM orders 
ORDER BY name
"""
monitors = pd.read_sql(sql, conlite)
monitors.set_index(["name"], inplace=True)
monitors

        trade
name
ASP         S
BANPU       S
BCH         S
CKP         B
CPF         B
CPNREIT     B
GFPT        B
GVREIT      B
IVL         B
JMART       S
LPF         B
MAKRO       S
PTT         B
SCC         S
SINGER      B
SYNEX       S
TFFIF       B
TFG         B
TMT         S
WHAIR       B

In [13]:
monitors.shape[0]

20

In [14]:
file_name = "monitors.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name

orders.to_csv(data_file, header=None)
orders.to_csv(output_file)
orders.to_csv(box_file)

In [15]:
sql = """
SELECT trade, COUNT(*) AS items 
FROM orders
GROUP BY trade
ORDER BY trade
"""
grp = pd.read_sql(sql, conlite)
grp

  trade  items
0     B     12
1     S      8

In [16]:
file_name = 'price-uploads.csv'
url = data_path + file_name
url

'../data/price-uploads.csv'

In [17]:
uploads = pd.read_csv(url)
uploads.sort_values(['name'],ascending=[True]).shape

(145, 1)

In [18]:
df_merge = pd.merge(orders, uploads, on='name', how='outer', indicator=True)
df_merge.sort_values(['name'],ascending=[True]).shape

(149, 3)

In [19]:
new_prices = df_merge['_merge'] == 'left_only'
df_merge[new_prices]

       name trade     _merge
4       CPF     B  left_only
5   CPNREIT     B  left_only
16    TFFIF     B  left_only
17      TFG     B  left_only

In [20]:
new_prices = df_merge['_merge'] == 'right_only'
df_merge[new_prices].shape

(129, 3)

In [21]:
sql = """
SELECT name, status, market
FROM stocks 
ORDER BY status, name
"""
stocks = pd.read_sql(sql, conlite)
stocks.set_index(["name"], inplace=True)
stocks.shape

(67, 2)

In [22]:
file_name = "stocks-all.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

stocks.to_csv(data_file, header=None)
stocks.to_csv(output_file)
stocks.to_csv(box_file)
stocks.to_csv(one_file)

In [23]:
sql = """
SELECT name, status 
FROM stocks 
WHERE status IN ("B","O")
ORDER BY name
"""

buy_candidates = pd.read_sql(sql, conlite)
buy_candidates.set_index(["name"], inplace=True)
buy_candidates

        status
name
CKP          O
CPF          O
CPNREIT      B
GFPT         O
GVREIT       B
IVL          B
LPF          O
PTT          O
SINGER       B
TFFIF        B
TFG          O
WHAIR        B

In [24]:
buy_candidates.shape[0]

12

In [25]:
sql = """
SELECT name, status 
FROM stocks 
WHERE status IN ("I","S")
ORDER BY name
"""

sell_candidates = pd.read_sql(sql, conlite)
sell_candidates.set_index(["name"], inplace=True)
sell_candidates

      status
name
ASP        S
BANPU      I
BCH        I
JMART      I
MAKRO      I
SCC        I
SYNEX      I
TMT        S

In [26]:
sell_candidates.shape[0]

8