In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 27), datetime.date(2023, 2, 26))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-02-27
yesterday: 2023-02-24 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 2, 24), datetime.date(2022, 2, 24))

### Restart and Run All Cells

### Weekly process or when stataus changes.

In [4]:
pd.read_sql_query('SELECT COUNT(*) AS records FROM sales', conlite)

   records
0     2117

In [5]:
sqlDel = """DELETE FROM sales"""
rp = conlite.execute(sqlDel)
rp.rowcount

2424

In [6]:
sql = """
SELECT name
FROM orders 
ORDER BY name
"""
df = pd.read_sql(sql, conlite)

names = df['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASK', 'ASW', 'BANPU', 'BH', 'BJC', 'COM7', 'DIF', 'GULF', 'IVL', 'JMART', 'JMT', 'KCE', 'ORI', 'PSH', 'QH', 'RCL', 'SAT', 'SC', 'SINGER', 'SNC', 'TCAP', 'TMT', 'TTB', 'WHA', 'WHART', 'WICE'"

In [7]:
len(in_p.split(','))

26

### Get past one year data

In [8]:
sql = """
SELECT name, date, price, qty, maxp, minp 
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (a_year_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-02-24' AND name IN ('ASK', 'ASW', 'BANPU', 'BH', 'BJC', 'COM7', 'DIF', 'GULF', 'IVL', 'JMART', 'JMT', 'KCE', 'ORI', 'PSH', 'QH', 'RCL', 'SAT', 'SC', 'SINGER', 'SNC', 'TCAP', 'TMT', 'TTB', 'WHA', 'WHART', 'WICE')
ORDER BY name, date

In [9]:
df = pd.read_sql(sql, const)
df.head()

  name        date  price      qty   maxp   minp
0  ASK  2022-02-24  45.75  1077191  47.00  44.75
1  ASK  2022-02-25  47.00  1537875  47.25  45.25
2  ASK  2022-02-28  49.00  2453561  49.00  46.25
3  ASK  2022-03-01  48.75   694064  49.50  48.25
4  ASK  2022-03-02  47.75   506579  49.00  47.75

In [10]:
data_path = "../data/"
file_name = "Yearly-Price-by-Name.csv"
output_file = data_path + file_name

df.set_index("name", inplace=True)
df.to_csv(output_file, header=None)

### Create monitors from orders

In [11]:
sql = """
SELECT name,trade 
FROM orders 
WHERE name IN (%s)
ORDER BY name
"""
sql = sql % in_p
orders = pd.read_sql(sql, conlite)
orders.set_index(['name'],inplace=True)
orders

       trade
name
ASK        B
ASW        B
BANPU      B
BH         B
BJC        B
COM7       B
DIF        S
GULF       B
IVL        S
JMART      B
JMT        B
KCE        B
ORI        S
PSH        B
QH         B
RCL        B
SAT        B
SC         B
SINGER     B
SNC        B
TCAP       B
TMT        S
TTB        B
WHA        B
WHART      B
WICE       B

In [12]:
file_name = "monitors.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name

orders.to_csv(data_file, header=None)
orders.to_csv(output_file)
orders.to_csv(box_file)

In [13]:
sql = """
SELECT trade, COUNT(*) AS items 
FROM orders
GROUP BY trade
ORDER BY trade
"""
grp = pd.read_sql(sql, conlite)
grp

  trade  items
0     B     22
1     S      4

### For new orders that never have XXX.html & XXX.CSV

In [14]:
file_name = 'price-uploads.csv'
url = data_path + file_name
url

'../data/price-uploads.csv'

In [15]:
uploads = pd.read_csv(url)
uploads.sort_values(['name'],ascending=[True]).shape

(151, 1)

In [16]:
df_merge = pd.merge(orders, uploads, on='name', how='outer', indicator=True)
df_merge.sort_values(['name'],ascending=[True]).shape

(158, 3)

In [17]:
new_prices = df_merge['_merge'] == 'left_only'
df_merge[new_prices]

    name trade     _merge
1    ASW     B  left_only
4    BJC     B  left_only
5   COM7     B  left_only
13   PSH     B  left_only
14    QH     B  left_only
23   WHA     B  left_only
25  WICE     B  left_only

In [18]:
new_prices = df_merge['_merge'] == 'right_only'
df_merge[new_prices].shape

(132, 3)

In [19]:
sql = """
SELECT name, status, market
FROM stocks 
ORDER BY status, name
"""
stocks = pd.read_sql(sql, conlite)
stocks.set_index(["name"], inplace=True)
stocks.shape

(66, 2)

In [20]:
file_name = "stocks-all.csv"
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name

stocks.to_csv(data_file, header=None)
stocks.to_csv(output_file)
stocks.to_csv(box_file)
stocks.to_csv(one_file)

In [21]:
sql = """
SELECT name, status 
FROM stocks 
WHERE status IN ("B","O")
ORDER BY name
"""
buy_candidates = pd.read_sql(sql, conlite)
buy_candidates.set_index(["name"], inplace=True)
buy_candidates

       status
name
ASK         B
ASW         O
BANPU       B
BH          O
BJC         O
COM7        O
GULF        O
JMART       B
JMT         B
KCE         B
PSH         O
QH          O
RCL         B
SAT         O
SC          O
SINGER      B
SNC         O
TCAP        O
TTB         O
WHA         O
WHART       B
WICE        O

In [22]:
buy_candidates.shape[0]

22

In [23]:
sql = """
SELECT name, status 
FROM stocks 
WHERE status IN ("I","S")
ORDER BY name
"""

sell_candidates = pd.read_sql(sql, conlite)
sell_candidates.set_index(["name"], inplace=True)
sell_candidates

     status
name
DIF       I
IVL       I
ORI       I
TMT       S

In [24]:
sell_candidates.shape[0]

4