In [1]:
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine('mysql+pymysql://root:@localhost:3306/portfolio_development')
conpf = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 1, 30)

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-30
yesterday: 2023-01-27

### Tables in the process

In [3]:
format_dict = {
    'shares':'{:,}',    
    'price':'{:.2f}',
    'dividend':'{:.4f}', 
    'date':'{:%Y-%m-%d}', 
    
    'qty':'{:,}','shares':'{:,}',
    'price':'{:.2f}','buy_price':'{:.2f}',
    'dividend':'{:.4f}',    
    'fee':'{:,.2f}','vat':'{:,.2f}','net':'{:,.2f}',
  
    'days':'{:,}',
    'price':'{:.2f}',
    'fee':'{:,.2f}','vat':'{:,.2f}','net':'{:,.2f}','profit':'{:,.2f}',
    'percent':'{:,.2f}%','yearly':'{:,.2f}%',   
    
    'shares':'{:,}',    
    'q4':'{:.4f}','q3':'{:.4f}','q2':'{:.4f}','q1':'{:.4f}','dividend':'{:.4f}',
    'xdate':'{:%Y-%m-%d}','paiddate':'{:%Y-%m-%d}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    
    'qty':'{:,}','available_qty':'{:,}',
    'cost':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}','buy_target':'{:.2f}','sell_target':'{:.2f}',
    'volume':'{:,.2f}','beta':'{:,.2f}',
    }

In [41]:
# Sells table in MySQL portfolio database
sql = """
SELECT name, stock_id, B.date AS buy_date, qty, B.price AS buy_price, S.* 
FROM sells S
JOIN buys B ON S.buy_id = B.id
JOIN stocks T ON B.stock_id = T.id
ORDER BY S.id DESC
LIMIT 1"""
sells = pd.read_sql(sql, conpf)
sells.style.format(format_dict)

### In case of sale, retreive buy id from sells record (buy_id)

In [42]:
# Buys table in MySQL portfolio database
transaction = 'S'

names = sells['name']
name = names.to_string(index=False)
name

'WHAIR'

In [43]:
sr_qty = sells['qty']
qty = sr_qty.to_string(index=False)
qty = int(qty) * -1

sr_price = sells['buy_price']
buy_price = sr_price.to_string(index=False)
buy_price = float(buy_price)

sr_price = sells['price']
sell_price = sr_price.to_string(index=False)
sell_price = float(sell_price)

buy_ids = sells['buy_id']
buy_id = buy_ids.to_string(index=False)

sql = """
SELECT name, B.* 
FROM buys B
JOIN stocks T 
ON B.stock_id = T.id
WHERE B.id = %s
"""
sql = sql % buy_id
print(sql)

buys = pd.read_sql(sql, conpf)
buys.style.format(format_dict)

SELECT name, B.*
FROM buys B
JOIN stocks T
ON B.stock_id = T.id
WHERE B.id = 1233

In [44]:
transaction, name, qty, sell_price, buy_price

('S', 'WHAIR', -10000, 7.8, 7.7)

### In case of buy, retreive buy id from latest buy record (id)

In [21]:
sql = """
SELECT name, B.* 
FROM buys B
JOIN stocks T 
ON B.stock_id = T.id
ORDER BY id DESC
LIMIT 1
"""
print(sql)
buys = pd.read_sql(sql, conpf)
buys.style.format(format_dict)

SELECT name, B.*
FROM buys B
JOIN stocks T
ON B.stock_id = T.id
ORDER BY id DESC
LIMIT 1

In [22]:
transaction = 'B'

names = buys['name']
name = names.to_string(index=False)

sr_qty = buys['qty']
qty = sr_qty.to_string(index=False)
qty = int(qty)

sr_price = buys['price']
buy_price = sr_price.to_string(index=False)
buy_price = float(buy_price)

transaction, name, qty, buy_price

('B', 'JMT', 900, 53.0)

## Begin of Sale transaction

### Begin of Update buy table in MySQL stock database from sale transaction

In [45]:
sql = """
SELECT * 
FROM buy 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

buy = pd.read_sql(sql, const)
buy.drop(['volsell', 'volbal','dividend'], axis=1, inplace=True)
buy.rename(columns={'volbuy':'shares'},inplace=True)
buy['shares'] = buy['shares'].astype('int64')
buy.style.format(format_dict)

SELECT *
FROM buy
WHERE name = 'WHAIR'

In [46]:
new_cost = 8.7
sqlUpd = """
UPDATE buy
SET volbuy = volbuy + %s, price = %s
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, new_cost, name)
print(sqlUpd)

UPDATE buy
SET volbuy = volbuy + -10000, price = 8.7
WHERE name = 'WHAIR'

In [47]:
rp = const.execute(sqlUpd)
rp.rowcount

1

In [48]:
sql = """
SELECT * 
FROM buy 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

buy = pd.read_sql(sql, const)
buy.drop(['volsell', 'volbal','dividend'], axis=1, inplace=True)
buy.rename(columns={'volbuy':'shares'},inplace=True)
buy['shares'] = buy['shares'].astype('int64')
buy.style.format(format_dict)

SELECT *
FROM buy
WHERE name = 'WHAIR'

### If shares become zero, must delete from buy table

In [ ]:
sqlDel = """
DELETE FROM buy
WHERE name = '%s' AND volbuy = 0"""
sqlDel = sqlDel % name
print(sqlDel)

In [ ]:
rp = const.execute(sqlDel)
rp.rowcount

### End of Update buy table in MySQL stock database from sale transaction

### Begin of Update dividend table in MySQL stock database from sale transaction

In [49]:
sql = """
SELECT * 
FROM dividend 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

dividend = pd.read_sql(sql, const)
dividend.drop(['PRICE', 'PERCENT'], axis=1, inplace=True)
dividend.columns = dividend.columns.str.lower()
dividend['shares'] = dividend['shares'].astype('int64')
dividend['xdate'] = pd.to_datetime(dividend['xdate'])
dividend['paiddate'] = pd.to_datetime(dividend['paiddate'])
dividend.style.format(format_dict)

SELECT *
FROM dividend
WHERE name = 'WHAIR'

In [50]:
sqlUpd = """
UPDATE dividend
SET shares = shares + %s
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, name)
print(sqlUpd)

UPDATE dividend
SET shares = shares + -10000
WHERE name = 'WHAIR'

In [51]:
rp = const.execute(sqlUpd)
rp.rowcount

1

In [52]:
sql = """
SELECT * 
FROM dividend 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

dividend = pd.read_sql(sql, const)
dividend.drop(['PRICE', 'PERCENT'], axis=1, inplace=True)
dividend.columns = dividend.columns.str.lower()
dividend['shares'] = dividend['shares'].astype('int64')
dividend['xdate'] = pd.to_datetime(dividend['xdate'])
dividend['paiddate'] = pd.to_datetime(dividend['paiddate'])
dividend.style.format(format_dict)

SELECT *
FROM dividend
WHERE name = 'WHAIR'

### If shares become zero and want to delete from DIVIDEND table

In [ ]:
sqlDel = """
DELETE FROM dividend
WHERE name = '%s'
"""
sqlDel = sqlDel % (name)
print(sqlDel)

In [ ]:
rp = const.execute(sqlDel)
rp.rowcount

### End of Update dividend table in MySQL stock database from sale transaction

### Begin of Update stocks table in SQLite port_lite database from sale transaction

In [58]:
sql = """
SELECT * 
FROM stocks 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

stocks = pd.read_sql(sql, conlite)
stocks.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'WHAIR'

In [54]:
buy_target  = 7.5 # must calculate manually beforehand
sell_target = 8.9
status = 'I'
reason = "HD"
sell_qty = 10000

sqlUpd = """
UPDATE stocks
SET available_qty = available_qty + %s,
qty = %s, buy_target = %s, sell_target = %s, reason = '%s', status = '%s'
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, sell_qty, buy_target, sell_target, reason, status, name)
print(sqlUpd)

UPDATE stocks
SET available_qty = available_qty + -10000,
qty = 10000, buy_target = 7.5, sell_target = 8.9, reason = 'HD', status = 'I'
WHERE name = 'WHAIR'

In [55]:
rp = conlite.execute(sqlUpd)
rp.rowcount

1

In [56]:
sql = """
SELECT * 
FROM stocks 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

stocks = pd.read_sql(sql, conlite)
stocks.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'WHAIR'

### End of Update stocks table in SQLite port_lite database from sale transaction

### If shares become zero and no longer wants to keep STOCK record

In [ ]:
sqlDel = """
DELETE FROM stocks
WHERE name = '%s' AND available_qty <= 0
"""
sqlDel = sqlDel % name
print(sqlDel)

In [ ]:
rp = conlite.execute(sqlDel)
rp.rowcount

## End of Sale process

## Begin of  Buy process

### Begin of Update buy table in MySQL database from buy transaction

In [57]:
sql = """
SELECT * 
FROM buy 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

buy = pd.read_sql(sql, const)
buy['date'] = pd.to_datetime(buy['date'])
buy.drop(['volsell', 'volbal'], axis=1, inplace = True)
buy.rename(columns={'volbuy':'shares'}, inplace = True)
buy['shares'] = buy['shares'].astype('int64')
buy

SELECT *
FROM buy
WHERE name = 'WHAIR'

    name       date  shares  price  active  dividend period grade
0  WHAIR 2021-10-11   50000    8.7       1    0.6744      2    B4

### In case there is the same stock name in port

In [24]:
new_cost = 57 # new average cost must be calculated manually beforehand
sqlUpd = """
UPDATE buy
SET volbuy = volbuy + %s, price = %s
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, new_cost, name)
print(sqlUpd)

UPDATE buy
SET volbuy = volbuy + 900, price = 57
WHERE name = 'JMT'

In [25]:
rp = const.execute(sqlUpd)
rp.rowcount

1

In [26]:
sql = """
SELECT * 
FROM buy 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

buy = pd.read_sql(sql, const)
buy.drop(['volsell', 'volbal'], axis=1, inplace=True)
buy.rename(columns={'volbuy':'shares'},inplace=True)
buy['shares'] = buy['shares'].astype('int64')
buy.style.format(format_dict)

SELECT *
FROM buy
WHERE name = 'JMT'

### In case of totally new stock

In [ ]:
rcd = ['JMT', '2023-01-26', 2400, 58.50, 0, 0, 1, 0, 4,'A4']
rcd

In [ ]:
sqlIns = """
INSERT INTO buy (name, date, volbuy, price, volsell, volbal, active, dividend, period, grade)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
print(sqlIns)

In [ ]:
rp = const.execute(sqlIns, rcd)
rp.rowcount

In [ ]:
sql = """
SELECT * 
FROM buy 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

buy = pd.read_sql(sql, const)
buy.drop(['volsell', 'volbal'], axis=1, inplace=True)
buy.rename(columns={'volbuy':'shares'},inplace=True)
buy['shares'] = buy['shares'].astype('int64')
buy.style.format(format_dict)

### End of Update buy table in MySQL database from buy transaction

### Begin of Update dividend table in MySQL stock database from buy transaction

In [27]:
sql = """
SELECT * 
FROM dividend 
WHERE name = '%s' 
"""
sql = sql % name
print(sql)

dividend = pd.read_sql(sql, const)
dividend.drop(['PRICE', 'PERCENT'], axis=1, inplace=True)
dividend.columns = dividend.columns.str.lower()
dividend['shares'] = dividend['shares'].astype('int64')
dividend['xdate'] = pd.to_datetime(dividend['xdate'])
dividend['paiddate'] = pd.to_datetime(dividend['paiddate'])
dividend.style.format(format_dict)

SELECT *
FROM dividend
WHERE name = 'JMT'

In [28]:
sqlUpd = """
UPDATE dividend
SET shares = shares + %s
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, name)
print(sqlUpd)

UPDATE dividend
SET shares = shares + 900
WHERE name = 'JMT'

In [29]:
rp = const.execute(sqlUpd)
rp.rowcount

1

In [30]:
sql = """
SELECT * 
FROM dividend 
WHERE name = '%s' 
"""
sql = sql % name
print(sql)

dividend = pd.read_sql(sql, const)
dividend.drop(['PRICE', 'PERCENT'], axis=1, inplace=True)
dividend.columns = dividend.columns.str.lower()
dividend['shares'] = dividend['shares'].astype('int64')
dividend['xdate'] = pd.to_datetime(dividend['xdate'])
dividend['paiddate'] = pd.to_datetime(dividend['paiddate'])
dividend.style.format(format_dict)

SELECT *
FROM dividend
WHERE name = 'JMT'

### In case of totally new stock

In [ ]:
rcd = ['GFPT', 0.10, 0, 0, 0, 0.10, 7500, '2023-03-07', '2023-04-28', '', 0]
rcd

In [ ]:
sqlIns = """
INSERT INTO dividend (name, q4, q3, q2, q1, dividend, shares, xdate, paiddate, kind, actual)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
print(sqlIns)

In [ ]:
rp = const.execute(sqlIns, rcd)
rp.rowcount

### End of Create dividend table in MySQL stock database from buy transaction

### Begin of Update stocks table in SQLite port_lite database from buy transaction

In [31]:
sql = """
SELECT * 
FROM stocks 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

stocks = pd.read_sql(sql, conlite)
stocks

SELECT *
FROM stocks
WHERE name = 'JMT'

,id,name,max_price,min_price,status,buy_target,sell_target,volume,beta,cost,qty,buy_spread,sell_spread,available_qty,bl,sh,reason,market
0,9728,JMT,88.25,39.81,I,51,61.5,900.97,1.33,58.5,2400,-42,45,2400,0,0,DTD,SET50

In [34]:
new_cost = 57
buy_target = 53
sell_target = 60
status = 'I'
reason = 'DTD'
new_buy_qty = 1500
new_sell_qty = 1500
new_cost, buy_target, sell_target, status, reason, new_buy_qty, new_sell_qty

(57, 53, 60, 'I', 'DTD', 1500, 1500)

In [35]:
sqlUpd = """
UPDATE stocks
SET available_qty = available_qty + %s, 
cost = %s, buy_target = %s, sell_target = %s, status = '%s', 
reason = '%s', qty = %s
WHERE name = '%s'
"""
sqlUpd = sqlUpd % (qty, new_cost, buy_target, sell_target, status, reason, new_sell_qty, name)
print(sqlUpd)

UPDATE stocks
SET available_qty = available_qty + 900,
cost = 57, buy_target = 53, sell_target = 60, status = 'I',
reason = 'DTD', qty = 1500
WHERE name = 'JMT'

In [36]:
rp = conlite.execute(sqlUpd)
rp.rowcount

1

In [37]:
sql = """
SELECT * 
FROM stocks 
WHERE name = '%s'
"""
sql = sql % name
print(sql)

stocks = pd.read_sql(sql, conlite)
stocks.style.format(format_dict)

SELECT *
FROM stocks
WHERE name = 'JMT'

### End of Update stocks table in SQLite port_lite database from buy transaction

## End of  Buy process

In [59]:
sql = "SELECT period, buy.grade AS grade, buy.name AS name, buy.date AS date, \
FORMAT(volbuy,0) AS volbuy, FORMAT(buy.price,2) AS buy_price, price.price AS mkt_price,\
FORMAT((volbuy * buy.price),2) AS amtbuy, FORMAT((volbuy * price.price),2) AS amtmkt, \
FORMAT(((price.price - buy.price) * volbuy),2) AS amtpol, \
FORMAT((((price.price - buy.price)*volbuy)/(volbuy*buy.price)*100),2) AS pctpol \
FROM buy INNER JOIN price ON buy.name = price.name WHERE price.date = '%s' \
ORDER BY period, buy.name"
sql = sql % (yesterday)
print(sql)

SELECT period, buy.grade AS grade, buy.name AS name, buy.date AS date, FORMAT(volbuy,0) AS volbuy, FORMAT(buy.price,2) AS buy_price, price.price AS mkt_price,FORMAT((volbuy * buy.price),2) AS amtbuy, FORMAT((volbuy * price.price),2) AS amtmkt, FORMAT(((price.price - buy.price) * volbuy),2) AS amtpol, FORMAT((((price.price - buy.price)*volbuy)/(volbuy*buy.price)*100),2) AS pctpol FROM buy INNER JOIN price ON buy.name = price.name WHERE price.date = '2023-01-27' ORDER BY period, buy.name

In [60]:
output = pd.read_sql(sql, const)
output

,period,grade,name,date,volbuy,buy_price,mkt_price,amtbuy,amtmkt,amtpol,pctpol
0,1,C4,ASP,2022-03-07,"30,000",3.80,3.10,"114,000.00","93,000.00","-21,000.00",-18.42
1,1,C4,MCS,2016-09-20,"75,000",15.40,10.10,"1,155,000.00","757,500.00","-397,500.00",-34.42
2,1,C3,PTTGC,2021-03-17,"6,000",64.75,50.50,"388,500.00","303,000.00","-85,500.00",-22.01
3,1,C4,STA,2021-06-15,"7,500",39.25,22.90,"294,375.00","171,750.00","-122,625.00",-41.66
4,1,C2,TMT,2021-08-16,"36,000",10.20,8.35,"367,200.00","300,600.00","-66,600.00",-18.14
5,2,A4,BCH,2021-09-07,"15,000",21.46,20.90,"321,900.00","313,500.00","-8,400.00",-2.61
6,2,A4,CPNREIT,2022-08-16,"30,000",19.10,19.50,"573,000.00","585,000.00","12,000.00",2.09
7,2,B1,DCC,2022-05-05,"60,000",2.96,2.82,"177,600.00","169,200.00","-8,400.00",-4.73
8,2,B4,DIF,2020-08-01,"40,000",14.70,13.70,"588,000.00","548,000.00","-40,000.00",-6.80
9,2,B1,GVREIT,2022-08-24,"40,000",8.90,9.45,"356,000.00","378,000.00","22,000.00",6.18
10,2,C4,JASIF,2018-05-17,"130,000",10.00,8.15,"1,300,000.00","1,059,500.00","-240,500.00",-18.50
11,2,A1,RCL,2021-11-08,"24,000",39.80,31.75,"955,200.00","762,000.00","-193,200.00",-20.23
12,2,B2,SCCC,2022-02-23,"1,200",171.00,158.50,"205,200.00","190,200.00","-15,000.00",-7.31
13,2,A4,SENA,2022-03-29,"105,000",4.48,3.92,"470,400.00","411,600.00","-58,800.00",-12.50
14,2,A3,TFFIF,2022-11-30,"10,000",7.50,8.15,"75,000.00","81,500.00","6,500.00",8.67
15,2,B4,WHAIR,2021-10-11,"50,000",8.70,7.80,"435,000.00","390,000.00","-45,000.00",-10.34
16,2,B1,WHART,2022-01-05,"30,000",11.70,11.80,"351,000.00","354,000.00","3,000.00",0.85
17,3,A2,IVL,2022-08-29,"4,800",42.00,41.25,"201,600.00","198,000.00","-3,600.00",-1.79
18,3,A4,KCE,2021-10-07,"14,000",72.75,50.25,"1,018,500.00","703,500.00","-315,000.00",-30.93
19,3,A4,NER,2021-09-01,"27,000",7.45,6.60,"201,150.00","178,200.00","-22,950.00",-11.41
20,3,A2,ORI,2022-04-07,"45,000",11.00,11.90,"495,000.00","535,500.00","40,500.00",8.18
21,3,A4,SYNEX,2022-01-07,"15,000",28.70,16.10,"430,500.00","241,500.00","-189,000.00",-43.90
22,4,A3,BANPU,2023-01-06,"12,000",12.30,12.30,"147,600.00","147,600.00",0.00,0.00
23,4,A4,JMART,2023-01-20,"3,600",39.50,37.25,"142,200.00","134,100.00","-8,100.00",-5.70
24,4,A4,JMT,2023-01-26,"3,300",57.00,55.50,"188,100.00","183,150.00","-4,950.00",-2.63
25,4,C2,SCC,2021-09-20,600,405.00,340.00,"243,000.00","204,000.00","-39,000.00",-16.05
26,4,A2,SINGER,2023-01-19,"3,600",28.00,27.50,"100,800.00","99,000.00","-1,800.00",-1.79

In [61]:
file_name = 'portfolio.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

output.to_csv(output_file, header=True, index=False)
output.to_csv(data_file, header=True, index=False)
output.to_csv(box_file, header=True, index=False)
output.to_csv(one_file, header=True, index=False)
output.to_csv(osd_file, header=True, index=False)