### Restart & Run All Cells

In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 3, 3), datetime.date(2023, 3, 2))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-03-03
yesterday: 2023-03-02

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

Moved StockQuotation (1).xlsx to Datasets
Moved StockQuotation (2).xlsx to Datasets
Moved StockQuotation (3).xlsx to Datasets
Moved StockQuotation (4).xlsx to Datasets
Moved StockQuotation (5).xlsx to Datasets
Moved StockQuotation (6).xlsx to Datasets
Moved StockQuotation (7).xlsx to Datasets
Moved StockQuotation (8).xlsx to Datasets
Moved StockQuotation (9).xlsx to Datasets
Moved StockQuotation.xlsx to Datasets

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
60     NEX 13.90   0.50    3.73 13.50 13.90 13.40     11978690       164239.33
3    AMATA 20.90   0.70    3.47 20.30    21 20.20     21958214       455201.50
47     JAS  2.14   0.06    2.88  2.10  2.16  2.08     29011239        61588.94
37   FORTH 38.25      1    2.68    37 38.50    37      1293591        48950.06
20     BYD 10.20   0.20       2    10 10.40  9.90     10933506       110856.24
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
30     CRC    44  -1.25   -2.76    45    45 43.75     11847780       523095.92
73     RBF 12.10  -0.40   -3.20 12.60 12.60 12.10      3488748        42801.90
80  SINGER 22.20  -0.90   -3.90 22.80    23 22.10     23774295       534485.17
42    HANA 54.50  -2.50   -4.39 57.25 57.25 51.75     37617606      2033190.88
11     BCP    32  -1.50   -4.48 32.25 32.50    32      6335855       203885.95

[98 rows x 9 columns]

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
102,SKY,31.75,1.50,4.96,30.25,32.25,30.00,7360344,231797.38
31,EKH,8.40,0.30,3.70,8.15,8.45,8.00,10875629,90257.06
71,NUSA,1.05,0.03,2.94,1.02,1.07,1.02,18982515,19918.12
7,AMANAH,4.08,0.10,2.51,4.00,4.12,3.98,6552420,26484.98
12,AS,13.00,0.30,2.36,12.80,13.00,12.80,260921,3369.30
...,...,...,...,...,...,...,...,...,...
60,MCS,9.45,-0.30,-3.08,9.65,9.70,9.45,1464157,13962.55
29,DRT,7.85,-0.25,-3.09,7.80,7.90,7.80,971403,7597.58
106,SO,8.80,-0.30,-3.30,9.10,9.10,8.75,684034,6066.79
43,ITD,1.59,-0.06,-3.64,1.67,1.67,1.57,44114152,70262.62
38,HUMAN,11.30,-0.60,-5.04,11.90,11.90,11.20,6717343,76968.62

In [8]:
df_sSET.query('Symbol == "MCS"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
60,MCS,-,9.45,-0.30,-3.08,9.65,9.70,9.45,0,0.00,1464157,13962.55,215100,9.45,9.50,55600

In [9]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
50,SUPER,0.56,0.02,3.70,0.55,0.56,0.54,24314437,13421.25
1,AMATA,20.90,0.70,3.47,20.30,21.00,20.20,21958214,455201.50
51,TASCO,18.80,0.50,2.73,18.30,18.80,18.30,9770029,182394.84
41,SAMART,5.25,0.10,1.94,5.25,5.25,5.15,2760500,14371.00
27,KBANK,139.50,2.50,1.82,137.50,139.50,137.00,14833964,2060777.38
...,...,...,...,...,...,...,...,...,...
14,CK,20.30,-0.50,-2.40,20.50,20.70,20.10,7903589,160839.91
17,CRC,44.00,-1.25,-2.76,45.00,45.00,43.75,11847780,523095.92
18,DRT,7.85,-0.25,-3.09,7.80,7.90,7.80,971403,7597.58
39,RBF,12.10,-0.40,-3.20,12.60,12.60,12.10,3488748,42801.90
5,BCP,32.00,-1.50,-4.48,32.25,32.50,32.00,6335855,203885.95

In [10]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
12,KKP,66.75,1.00,1.52,66.50,67.25,66.25,8932508,596236.44
27,TTB,1.39,0.02,1.46,1.37,1.39,1.36,260463858,359526.57
13,KTB,17.30,0.20,1.17,17.20,17.40,17.00,21265026,366975.28
9,GUNKUL,3.96,0.04,1.02,3.94,3.98,3.90,54456167,214729.41
24,TCAP,43.00,0.25,0.58,42.75,43.00,42.75,1800710,77308.97
...,...,...,...,...,...,...,...,...,...
28,TU,15.60,-0.30,-1.89,15.50,15.70,15.40,14936317,232400.48
5,BTS,7.65,-0.15,-1.92,7.85,7.85,7.55,75031664,575671.00
4,BCPG,9.25,-0.20,-2.12,9.30,9.35,9.20,4007424,37170.23
14,LH,9.55,-0.25,-2.55,9.80,9.80,9.55,38781516,374355.41
10,HANA,54.50,-2.50,-4.39,57.25,57.25,51.75,37617606,2033190.88

In [11]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
5,AMATA,20.90,0.70,3.47,20.30,21.00,20.20,21958214,455201.50
11,BAFS,32.00,0.75,2.40,31.25,32.00,31.25,534315,16971.98
53,ITEL,3.62,0.08,2.26,3.56,3.64,3.54,2366013,8476.45
72,PR9,19.50,0.40,2.09,19.10,20.00,19.10,4449021,87582.80
55,KBANK,139.50,2.50,1.82,137.50,139.50,137.00,14833964,2060777.38
...,...,...,...,...,...,...,...,...,...
32,CPN,66.25,-1.75,-2.57,67.50,67.50,65.25,19233883,1276786.65
33,CRC,44.00,-1.25,-2.76,45.00,45.00,43.75,11847780,523095.92
36,DRT,7.85,-0.25,-3.09,7.80,7.90,7.80,971403,7597.58
47,HANA,54.50,-2.50,-4.39,57.25,57.25,51.75,37617606,2033190.88
15,BCP,32.00,-1.50,-4.48,32.25,32.50,32.00,6335855,203885.95

In [12]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
1,BDMS,28.00,0.50,1.82,27.75,28.25,27.50,30761521,858976.57
2,BEM,9.25,0.10,1.09,9.20,9.25,9.00,85854340,784433.57
17,MEGA,46.25,0.50,1.09,45.75,46.50,45.75,2239421,103337.39
21,RCL,31.75,0.25,0.79,31.75,32.00,31.25,3255503,103192.71
14,HMPRO,13.90,0.10,0.72,14.00,14.30,13.80,29238272,412311.12
...,...,...,...,...,...,...,...,...,...
27,TU,15.60,-0.30,-1.89,15.50,15.70,15.40,14936317,232400.48
5,BTS,7.65,-0.15,-1.92,7.85,7.85,7.55,75031664,575671.00
11,CRC,44.00,-1.25,-2.76,45.00,45.00,43.75,11847780,523095.92
20,RBF,12.10,-0.40,-3.20,12.60,12.60,12.10,3488748,42801.90
23,SINGER,22.20,-0.90,-3.90,22.80,23.00,22.10,23774295,534485.17

In [13]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_FIN = pd.read_excel(input_file, header=9)
df_FIN = df_FIN[df_FIN['%Change'] != '-']
df_FIN[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change Open  High  Low Total Volume Total Value (k)
39   UOBKH  5.60   0.30    5.66 5.45  5.70 5.45       344503         1932.37
12     FSS  3.78   0.10    2.72 4.20  4.32 3.76     40788707       165360.62
1   AMANAH  4.08   0.10    2.51    4  4.12 3.98      6552420        26484.98
7      CGH  0.89   0.02    2.30 0.88  0.91 0.88     43657763        39031.88
19     KGI  5.10   0.10       2 5.05  5.15 5.05      8778135        44759.51
..     ...   ...    ...     ...  ...   ...  ...          ...             ...
8    CHASE  2.88  -0.06   -2.04 2.94  2.96 2.86     13237479        38339.15
15    HENG  2.84  -0.06   -2.07 2.92  2.94 2.82     13612086        38854.19
24     MST 11.10  -0.70   -5.93   11 11.10   11       553867         6113.40
2     ASAP  2.72  -0.18   -6.21 2.88  2.88 2.68      2106060         5753.98
32     SGC  3.16  -0.32   -9.20 3.50  3.52 3.16     70357263       231956.99

[40 rows x 9 columns]

In [14]:
df_FIN.query('Symbol == "ASK"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,ASK,-,28.25,0,0,28.50,28.75,28.25,0,0,2399502,68123.04,289800,28,28.25,4000

In [15]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
42,QHHR,6.70,0.15,2.29,6.60,6.70,6.60,344101,2295.60
18,GVREIT,9.45,0.15,1.61,9.30,9.45,9.30,94400,886.15
38,MNRF,2.80,0.04,1.45,2.80,2.80,2.80,300,0.84
20,HYDROGEN,10.30,0.10,0.98,10.30,10.30,10.20,66800,681.44
6,BKKCP,10.60,0.10,0.95,10.50,10.60,10.50,234,2.47
...,...,...,...,...,...,...,...,...,...
27,LHSC,12,-0.20,-1.64,12.10,12.10,11.50,29600,347.80
52,TLHPF,7.75,-0.15,-1.90,7.85,7.85,7.65,18300,141.60
9,CPNREIT,14.60,-0.40,-2.67,15.20,15.30,14.20,10189854,150597.87
34,MIT,1.50,-0.06,-3.85,1.55,1.57,1.49,231800,348.63
46,SIRIP,7.40,-0.55,-6.92,7.40,7.40,7.40,100,0.74

In [16]:
df_PFREIT.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,14.60,-0.40,-2.67,15.20,15.30,14.20,0,0,10189854,150597.87,82100,14.50,14.60,62600

In [17]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
6   BIOTEC  0.83   0.03    3.75  0.81  0.84  0.80      6927048         5691.26
5      BEM  9.25   0.10    1.09  9.20  9.25     9     85854340       784433.57
17    PORT  1.87   0.02    1.08  1.85  1.87  1.82        78558          145.64
26    WICE 10.70   0.10    0.94 10.60    11 10.50      3961789        42688.10
20     RCL 31.75   0.25    0.79 31.75    32 31.25      3255503       103192.71
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
19     PSL 15.30  -0.30   -1.92 15.50 15.60 15.20      5855266        89682.99
18     PRM  7.40  -0.15   -1.99  7.60  7.60  7.35      6167710        45973.32
12    KIAT  0.48  -0.01   -2.04  0.50  0.50  0.48      3336360         1629.24
10     III    13  -0.30   -2.26 13.30 13.30    13      1472410        19326.00
3        B  0.37  -0.01   -2.63  0.38  0.38  0.37     13485591         5066.77

[25 rows x 9 columns]

In [18]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
25     SKY 31.75   1.50    4.96 30.25 32.25    30      7360344       231797.38
14     JAS  2.14   0.06    2.88  2.10  2.16  2.08     29011239        61588.94
7    FORTH 38.25      1    2.68    37 38.50    37      1293591        48950.06
13    ITEL  3.62   0.08    2.26  3.56  3.64  3.54      2366013         8476.45
21  SAMART  5.25   0.10    1.94  5.25  5.25  5.15      2760500        14371.00
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
28   SYNEX 15.60  -0.40   -2.50    16    16 15.50      1664125        26135.62
6   DTCENT  1.85  -0.06   -3.14  1.92  1.92  1.84      4765749         8871.93
8    HUMAN 11.30  -0.60   -5.04 11.90 11.90 11.20      6717343        76968.62
23     SDC  0.14  -0.02  -12.50  0.15  0.16  0.13    165959099        23668.34
32     TWZ  0.06  -0.01  -14.29  0.06  0.07  0.06      8384235          510.23

[31 rows x 9 columns]

In [19]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_FIN, df_PFREIT, df_TRANS, df_ICT])
df.shape

(630, 16)

In [20]:
df.Symbol.nunique()

363

In [21]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(363, 16)

In [22]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [23]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.74,0.00,0.00,0.74,0.75,0.73,7722896,5704.85
0,AAV,2.82,0.02,0.71,2.82,2.82,2.78,26285681,73702.02
1,ACE,2.42,0,0,2.44,2.46,2.42,13779344,33494.64
2,ADVANC,203,1,0.50,203,203,200,4208290,849189.93
0,AEONTS,199,2,1.02,197,199.50,197,302386,60048.61
...,...,...,...,...,...,...,...,...,...
139,WHAUP,3.80,-0.02,-0.52,3.82,3.86,3.80,3066357,11719.20
140,WICE,10.70,0.10,0.94,10.60,11.00,10.50,3961789,42688.10
141,WORK,17.70,0.00,0.00,17.70,17.80,17.70,22571,400.76
142,XPG,1.19,-0.01,-0.83,1.20,1.22,1.18,13438240,16025.13
143,ZEN,16.30,-0.30,-1.81,16.30,16.50,16.30,346303,5656.79

In [24]:
df.insert(1, 'Date', today)

In [25]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-03-03,2.82,0.02,0.71,2.82,2.82,2.78,26285681,73702.02
1,ACE,2023-03-03,2.42,0,0,2.44,2.46,2.42,13779344,33494.64
2,ADVANC,2023-03-03,203,1,0.50,203,203,200,4208290,849189.93
3,AMATA,2023-03-03,20.90,0.70,3.47,20.30,21,20.20,21958214,455201.50
4,AOT,2023-03-03,70.50,-1.25,-1.74,71.50,71.50,70.25,25367513,1791835.85
...,...,...,...,...,...,...,...,...,...,...
22,SAMTEL,2023-03-03,6.10,0.05,0.83,6,6.10,6,61200,370.86
23,SDC,2023-03-03,0.14,-0.02,-12.50,0.15,0.16,0.13,165959099,23668.34
26,SVOA,2023-03-03,2.36,0,0,2.38,2.40,2.34,707606,1674.05
27,SYMC,2023-03-03,5.30,0.05,0.95,5.25,5.30,5.05,117201,616.44
32,TWZ,2023-03-03,0.06,-0.01,-14.29,0.06,0.07,0.06,8384235,510.23

In [26]:
file_name = "name-ttl.csv"
input_file = data_path + file_name

df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [27]:
df_out = df[colt]
df_out.shape

(363, 10)

In [28]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(191, 10)

In [29]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [30]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [31]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [32]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes