In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 9), datetime.date(2023, 2, 8))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-09
yesterday: 2023-02-08

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

### SET100, sSET, SETCLMV, SETHD, SETTHSI, SETWB, CONMAT, PFREIT, TRANS, ICT

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

Moved StockQuotation (1).xlsx to Datasets
Moved StockQuotation (2).xlsx to Datasets
Moved StockQuotation (3).xlsx to Datasets
Moved StockQuotation (4).xlsx to Datasets
Moved StockQuotation (5).xlsx to Datasets
Moved StockQuotation (6).xlsx to Datasets
Moved StockQuotation (7).xlsx to Datasets
Moved StockQuotation (8).xlsx to Datasets
Moved StockQuotation (9).xlsx to Datasets
Moved StockQuotation.xlsx to Datasets

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
38,FORTH,42.75,2.75,6.88,40.00,43.25,39.25,6150681,253695.80
50,JMT,52.25,1.50,2.96,50.75,53.00,50.25,13112496,671275.27
90,TIDLOR,29.75,0.75,2.59,29.00,29.75,29.00,13653477,400507.78
58,MEGA,52.00,1.25,2.46,50.75,52.25,50.75,1901213,98168.02
2,ADVANC,200.00,4.50,2.30,195.00,201.00,194.00,9499359,1875536.81
...,...,...,...,...,...,...,...,...,...
85,STARK,2.82,-0.06,-2.08,2.86,2.86,2.76,83747238,235261.70
53,KEX,17.70,-0.40,-2.21,18.10,18.10,17.50,3901134,69134.70
43,HANA,59.50,-1.50,-2.46,61.00,61.00,59.00,12070758,722328.30
86,STGT,11.40,-0.30,-2.56,11.70,11.70,11.30,15828907,181660.03
52,KCE,48.50,-2.00,-3.96,50.00,50.25,47.75,59036397,2875172.21

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
18,BEYOND,16.90,1.20,7.64,16.20,17.00,16.00,9120996,150672.53
91,SAK,7.30,0.25,3.55,7.05,7.35,6.85,7765038,55447.72
69,NSL,25.25,0.65,2.64,24.70,25.50,24.70,1400244,35247.31
100,SITHAI,1.68,0.04,2.44,1.65,1.70,1.65,7430506,12457.92
85,ROJNA,6.40,0.15,2.40,6.25,6.40,6.15,1884843,11869.45
...,...,...,...,...,...,...,...,...,...
76,PLUS,8.60,-0.20,-2.27,8.80,8.85,8.35,5401861,46244.06
92,SAMART,4.98,-0.12,-2.35,5.10,5.10,4.90,16266709,81333.70
65,NCAP,4.82,-0.12,-2.43,4.90,4.94,4.72,26678246,127973.15
143,ZEN,17.80,-0.50,-2.73,18.10,18.10,17.60,174009,3095.42
128,TSTH,1.12,-0.04,-3.45,1.15,1.15,1.09,12128718,13472.95

In [8]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
32,MEGA,52.00,1.25,2.46,50.75,52.25,50.75,1901213,98168.02
17,CRC,45.25,1.00,2.26,44.50,45.50,44.00,10816904,483171.49
29,KKP,68.50,1.50,2.24,67.00,68.50,67.00,7858397,532917.80
26,IRPC,3.16,0.06,1.94,3.14,3.16,3.06,167987017,524388.58
24,ICHI,12.30,0.20,1.65,12.10,12.40,12.00,2256909,27419.47
...,...,...,...,...,...,...,...,...,...
55,TU,15.80,-0.30,-1.86,16.10,16.20,15.70,36058161,571286.08
56,VNG,5.25,-0.10,-1.87,5.30,5.35,5.10,1693830,8802.06
42,SAMART,4.98,-0.12,-2.35,5.10,5.10,4.90,16266709,81333.70
49,STGT,11.40,-0.30,-2.56,11.70,11.70,11.30,15829207,181663.45
54,TSTH,1.12,-0.04,-3.45,1.15,1.15,1.09,12128718,13472.95

In [9]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,ADVANC,200.00,4.50,2.30,195.00,201.00,194.00,9536959,1883076.81
12,KKP,68.50,1.50,2.24,67.00,68.50,67.00,7863397,533260.30
11,INTUCH,73.00,1.00,1.39,72.00,73.00,71.75,2322724,168322.18
13,KTB,17.30,0.20,1.17,17.10,17.30,17.10,18601869,319444.58
29,WHA,3.94,0.04,1.03,3.92,3.94,3.84,95314495,370601.17
...,...,...,...,...,...,...,...,...,...
8,EGCO,170.50,-1.00,-0.58,171.00,171.50,169.50,692572,117874.42
18,PTTEP,164.00,-1.00,-0.61,165.00,165.00,163.50,8998503,1477900.67
23,SPALI,24.10,-0.40,-1.63,24.70,24.70,24.10,8715848,211919.76
28,TU,15.80,-0.30,-1.86,16.10,16.20,15.70,36058161,571286.08
10,HANA,59.50,-1.50,-2.46,61.00,61.00,59.00,12088758,723400.75

In [10]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,ADVANC,200.00,4.50,2.30,195.00,201.00,194.00,9536959,1883076.81
12,KKP,68.50,1.50,2.24,67.00,68.50,67.00,7863597,533274.00
11,INTUCH,73.00,1.00,1.39,72.00,73.00,71.75,2322824,168329.48
13,KTB,17.30,0.20,1.17,17.10,17.30,17.10,18601869,319444.58
29,WHA,3.94,0.04,1.03,3.92,3.94,3.84,95314495,370601.17
...,...,...,...,...,...,...,...,...,...
8,EGCO,170.50,-1.00,-0.58,171.00,171.50,169.50,692572,117874.42
18,PTTEP,163.50,-1.50,-0.91,165.00,165.00,163.50,9000103,1478163.02
23,SPALI,24.20,-0.30,-1.22,24.70,24.70,24.10,9071048,220515.60
28,TU,15.80,-0.30,-1.86,16.10,16.20,15.70,36058161,571286.08
10,HANA,59.50,-1.50,-2.46,61.00,61.00,59.00,12088758,723400.75

In [11]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
11,CRC,45.50,1.25,2.82,44.50,45.50,44.00,10824904,483535.34
18,MEGA,52.00,1.25,2.46,50.75,52.25,50.75,1901213,98168.02
17,M,56.75,1.00,1.79,55.75,57.00,55.00,2175932,122049.63
21,RBF,12.80,0.20,1.59,12.60,12.80,12.30,2186220,27341.47
14,HMPRO,14.80,0.20,1.37,14.50,14.80,14.40,21820429,318854.72
...,...,...,...,...,...,...,...,...,...
29,VIBHA,2.74,-0.04,-1.44,2.76,2.76,2.72,1952526,5347.49
15,JWD,20.10,-0.30,-1.47,20.40,20.40,19.70,4040740,80771.75
25,STA,24.10,-0.40,-1.63,24.50,24.50,23.90,9160022,221204.82
16,KEX,17.70,-0.40,-2.21,18.10,18.10,17.50,3901634,69143.55
1,BDMS,28.75,-0.75,-2.54,29.50,29.50,28.50,35050427,1013429.48

In [34]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_CONMAT = pd.read_excel(input_file, header=9)
df_CONMAT = df_CONMAT[df_CONMAT['%Change'] != '-']
df_CONMAT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,CCP,0.48,0.03,6.67,0.45,0.49,0.45,27287213,12840.97
8,Q-CON,11.00,0.50,4.76,10.60,12.40,10.30,4535367,51398.04
3,DCON,0.44,0.01,2.33,0.44,0.44,0.42,7051612,3029.16
19,WIIK,1.89,0.02,1.07,1.87,1.89,1.86,521800,978.73
15,TOA,34.50,0.25,0.73,34.50,34.50,33.50,1040160,35205.74
...,...,...,...,...,...,...,...,...,...
12,SKN,5.25,-0.05,-0.94,5.35,5.40,5.20,251300,1321.74
13,STECH,2.08,-0.02,-0.95,2.08,2.10,2.06,613700,1270.84
11,SCP,5.10,-0.05,-0.97,5.10,5.10,5.05,148100,753.54
1,COTTO,2.02,-0.02,-0.98,2.06,2.06,2.02,1433611,2913.87
18,VNG,5.25,-0.10,-1.87,5.30,5.35,5.10,1694830,8807.31

In [13]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
25,LHHOTEL,13.70,0.20,1.48,13.50,13.80,13.40,105809,1435.17
10,CPTGF,7.80,0.10,1.30,7.70,7.80,7.70,253799,1967.67
23,KPNPF,5.10,0.05,0.99,5.05,5.10,5.05,610,3.09
40,PPF,11.50,0.10,0.88,11.40,11.50,11.40,35900,412.37
27,LHSC,12,0.10,0.84,11.90,12,11.90,6906,82.43
...,...,...,...,...,...,...,...,...,...
59,WHAIR,7.90,-0.10,-1.25,7.95,7.95,7.90,256846,2033.16
53,TNPF,1.81,-0.03,-1.63,1.81,1.81,1.81,500,0.91
60,WHART,11.50,-0.20,-1.71,11.70,11.70,11.50,880226,10210.12
7,BOFFICE,8.25,-0.15,-1.79,8.35,8.35,8.25,37800,312.74
31,M-PAT,4.52,-0.36,-7.38,4.88,4.94,4.52,700,3.30

In [14]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
6   BIOTEC  0.97   0.05    5.43  0.92     1  0.92     37753401        36486.84
20     PSL 16.40   0.30    1.86 16.10 16.40 16.10      5953083        96960.38
18    PORT  2.06   0.02    0.98  2.04  2.10  2.04       162802          335.92
26    WICE 11.50   0.10    0.88 11.40 11.50 11.10      4111433        46317.40
21     RCL 30.75   0.25    0.82 30.50 30.75 30.25      1824185        55644.15
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
17     NYT  3.50  -0.04   -1.13  3.52  3.56  3.46      1803605         6299.53
11     JWD 20.10  -0.30   -1.47 20.40 20.40 19.70      4040740        80771.75
19     PRM  7.85  -0.15   -1.88  7.95  7.95  7.75      4408460        34583.54
24    TSTE  7.25  -0.15   -2.03  7.25  7.25  7.25          101            0.73
12     KEX 17.70  -0.40   -2.21 18.10 18.10 17.50      3901634        69143.55

[25 rows x 9 columns]

In [15]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
33     TWZ  0.08   0.01   14.29  0.07  0.08  0.07     26336825         1845.05
8    FORTH    43      3    7.50    40 43.25 39.25      6289881       259649.22
0   ADVANC   200   4.50    2.30   195   201   194      9565161      1888717.42
31     TKC 22.90   0.50    2.23 22.30 23.10 22.30      3282911        74827.69
11    INET  5.60   0.10    1.82  5.60  5.85  5.45      2636106        14973.60
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
2      ALT  2.24  -0.02   -0.88  2.26  2.26  2.24       687400         1539.84
26     SKY 26.25  -0.25   -0.94    26    27 25.50      5739096       148862.27
12   INSET  3.70  -0.04   -1.07  3.68  3.72  3.58      8083307        29552.48
22  SAMART     5  -0.10   -1.96  5.10  5.10  4.90     16275509        81377.70
18     JTS 40.25  -1.25   -3.01 41.25 41.50    39      1298734        51968.25

[33 rows x 9 columns]

In [16]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_CONMAT, df_PFREIT, df_TRANS, df_ICT])
df.shape

(505, 16)

In [17]:
df.Symbol.nunique()

335

In [18]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(335, 16)

In [19]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [20]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.85,0.01,1.19,0.83,0.86,0.83,15800409,13288.51
0,AAV,3.04,0.00,0.00,3.06,3.06,3.00,32488987,98403.67
1,ACE,2.52,-0.02,-0.79,2.54,2.56,2.50,21359616,53832.43
2,ADVANC,200.00,4.50,2.30,195.00,201.00,194.00,9499359,1875536.81
1,AGE,3.68,-0.02,-0.54,3.72,3.72,3.66,787311,2898.03
...,...,...,...,...,...,...,...,...,...
139,WHAUP,4.10,0.02,0.49,4.08,4.10,4.06,566061,2306.40
140,WICE,11.50,0.10,0.88,11.40,11.50,11.10,4108733,46286.35
141,WORK,18.40,0.00,0.00,18.50,18.50,18.30,132105,2422.31
142,XPG,1.41,0.01,0.71,1.41,1.43,1.40,10610090,14972.40
143,ZEN,17.80,-0.50,-2.73,18.10,18.10,17.60,174009,3095.42

In [21]:
df.insert(1, 'Date', today)

In [22]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-09,3.04,0.00,0.00,3.06,3.06,3.00,32488987,98403.67
1,ACE,2023-02-09,2.52,-0.02,-0.79,2.54,2.56,2.50,21359616,53832.43
2,ADVANC,2023-02-09,200.00,4.50,2.30,195.00,201.00,194.00,9499359,1875536.81
3,AMATA,2023-02-09,20.00,-0.20,-0.99,20.20,20.20,19.80,7409107,147660.43
4,AOT,2023-02-09,73.75,-0.25,-0.34,73.75,73.75,73.25,10645727,782516.46
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-09,6.35,-0.05,-0.78,6.40,6.40,6.25,535600,3383.63
24,SDC,2023-02-09,0.19,0,0,0.18,0.19,0.18,53503207,9682.76
27,SVOA,2023-02-09,2.64,-0.02,-0.75,2.64,2.66,2.60,1862801,4889.24
28,SYMC,2023-02-09,6,0,0,5.95,6,5.95,3705,22.17
33,TWZ,2023-02-09,0.08,0.01,14.29,0.07,0.08,0.07,26336825,1845.05

In [23]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [24]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [25]:
df_out = df[colt]
df_out.shape

(335, 10)

In [26]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(183, 10)

In [27]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [28]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'daily_volume'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')

In [29]:
colp = 'name date price high low volume open'.split()
colp

['name', 'date', 'price', 'high', 'low', 'volume', 'open']

In [30]:
file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [31]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes

In [32]:
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')

In [33]:
df_merge.rename(columns={
                         
                         'change':'chg_amt','%change':'chg_pct'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'chg_amt', 'chg_pct', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')