In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 10), datetime.date(2023, 2, 9))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-10
yesterday: 2023-02-09

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

### SET100, sSET, SETCLMV, SETHD, SETTHSI, SETWB, CONMAT, PFREIT, TRANS, ICT

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
5,AP,12.30,0.50,4.24,11.90,12.30,11.80,60884658,737655.62
2,ADVANC,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
38,FORTH,44.00,1.25,2.92,42.50,44.75,42.50,7836387,342634.26
6,AWC,5.85,0.15,2.63,5.70,5.85,5.65,55484175,320122.64
45,INTUCH,74.50,1.75,2.41,73.25,74.50,73.25,4266477,315846.58
...,...,...,...,...,...,...,...,...,...
81,SINGER,26.75,-0.75,-2.73,27.25,27.50,26.75,2084092,56358.92
49,JMART,34.50,-1.00,-2.82,35.25,35.50,34.50,7973040,277227.82
31,DELTA,896.00,-26.00,-2.82,920.00,934.00,890.00,2497109,2259776.13
50,JMT,50.50,-1.50,-2.88,51.75,52.00,50.25,11528715,586354.25
78,SCB,100.50,-3.00,-2.90,103.50,103.50,99.75,29652000,3001876.35

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
122,TKC,24.80,2.10,9.25,23.40,24.80,23.10,14002145,336373.80
102,SKY,27.75,1.75,6.73,25.75,28.00,25.50,8395943,228419.33
92,SAMART,5.35,0.25,4.90,5.10,5.35,5.10,5446600,28495.19
20,BRI,11.80,0.50,4.42,11.30,11.90,11.30,8583678,99884.08
59,MC,12.20,0.50,4.27,11.70,12.70,11.60,6793450,82535.88
...,...,...,...,...,...,...,...,...,...
76,PLUS,8.40,-0.25,-2.89,8.60,8.65,8.35,3106324,26301.17
0,7UP,0.82,-0.03,-3.53,0.85,0.85,0.82,17610162,14589.43
2,AH,30.75,-1.25,-3.91,32.00,32.00,30.50,5272428,164452.58
17,BEAUTY,1.47,-0.06,-3.92,1.53,1.54,1.46,62135928,92975.79
34,GJS,0.35,-0.02,-5.41,0.37,0.37,0.35,3980000,1429.11

In [8]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
42,SAMART,5.35,0.25,4.90,5.10,5.35,5.10,5446600,28495.19
25,INTUCH,74.50,1.75,2.41,73.25,74.50,73.25,4266477,315846.58
3,BBL,164.00,3.00,1.86,161.00,166.00,160.00,17608585,2879077.77
50,SUPER,0.63,0.01,1.61,0.63,0.63,0.62,11720223,7311.51
27,JWD,20.40,0.30,1.49,20.00,20.40,20.00,1709326,34711.73
...,...,...,...,...,...,...,...,...,...
31,MAJOR,18.10,-0.30,-1.63,18.40,18.40,18.00,3286282,59485.99
14,CK,22.10,-0.40,-1.78,22.50,22.60,22.10,3006254,66679.33
0,AJ,12.50,-0.30,-2.34,12.60,12.80,12.40,356994,4479.03
26,IRPC,3.08,-0.08,-2.53,3.14,3.16,3.08,98692533,306122.51
43,SCB,100.50,-3.00,-2.90,103.50,103.50,99.75,29652000,3001876.35

In [9]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
1,AP,12.30,0.50,4.24,11.90,12.30,11.80,60884658,737655.62
0,ADVANC,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
11,INTUCH,74.50,1.75,2.41,73.25,74.50,73.25,4266477,315846.58
2,BBL,164.00,3.00,1.86,161.00,166.00,160.00,17608585,2879077.77
15,ORI,11.90,0.20,1.71,11.70,11.90,11.60,4834840,57045.85
...,...,...,...,...,...,...,...,...,...
3,BCH,20.80,-0.10,-0.48,20.90,21.00,20.70,5768406,120067.29
4,BCPG,9.85,-0.05,-0.51,9.90,9.95,9.85,1036974,10245.61
12,KKP,67.75,-0.50,-0.73,68.25,68.25,67.50,6827777,463266.92
5,BTS,8.15,-0.10,-1.21,8.20,8.25,8.10,50331413,411103.89
7,CPF,22.90,-0.30,-1.29,23.10,23.20,22.90,28297908,650249.02

In [10]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
7,AP,12.30,0.50,4.24,11.90,12.30,11.80,60884658,737655.62
2,ADVANC,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
10,AWC,5.85,0.15,2.63,5.70,5.85,5.65,55484175,320122.64
68,NRF,5.90,0.15,2.61,5.85,5.95,5.75,3344908,19566.26
52,INTUCH,74.50,1.75,2.41,73.25,74.50,73.25,4266477,315846.58
...,...,...,...,...,...,...,...,...,...
53,IRPC,3.08,-0.08,-2.53,3.14,3.16,3.08,98692533,306122.51
34,DELTA,896.00,-26.00,-2.82,920.00,934.00,890.00,2497109,2259776.13
90,SCB,100.50,-3.00,-2.90,103.50,103.50,99.75,29652000,3001876.35
106,TOA,33.50,-1.25,-3.60,34.50,34.50,33.50,957088,32425.11
3,AH,30.75,-1.25,-3.91,32.00,32.00,30.50,5272428,164452.58

In [11]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
15,JWD,20.40,0.30,1.49,20.00,20.40,20.00,1709326,34711.73
14,HMPRO,14.90,0.20,1.36,14.60,14.90,14.50,16787572,247863.35
28,TVO,29.00,0.25,0.87,29.00,29.00,28.75,1021546,29446.04
22,RCL,30.75,0.25,0.82,30.50,30.75,30.25,1341212,41016.40
21,RBF,12.80,0.10,0.79,12.70,12.80,12.70,1027213,13060.38
...,...,...,...,...,...,...,...,...,...
18,MEGA,51.50,-0.50,-0.96,51.75,52.00,51.25,1598024,82480.69
5,BTS,8.15,-0.10,-1.21,8.20,8.25,8.10,50331413,411103.89
10,CPF,22.90,-0.30,-1.29,23.10,23.20,22.90,28297908,650249.02
8,COM7,30.50,-0.50,-1.61,30.75,31.00,30.50,6267187,192226.57
24,SINGER,26.75,-0.75,-2.73,27.25,27.50,26.75,2084092,56358.92

In [12]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_CONMAT = pd.read_excel(input_file, header=9)
df_CONMAT = df_CONMAT[df_CONMAT['%Change'] != '-']
df_CONMAT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
8,Q-CON,12.20,1.30,11.93,11.00,12.40,11.00,4969648,59102.86
3,DCON,0.44,0.01,2.33,0.43,0.44,0.43,2818800,1237.05
14,TASCO,18.30,0.20,1.10,18.10,18.30,17.90,4524966,82212.90
1,COTTO,2.04,0.02,0.99,2.06,2.06,2.02,1065235,2170.41
13,STECH,2.08,0.02,0.97,2.06,2.08,2.06,159400,328.37
...,...,...,...,...,...,...,...,...,...
11,SCP,5.05,-0.05,-0.98,5.10,5.15,5.05,42500,215.83
5,EPG,8.55,-0.10,-1.16,8.70,8.70,8.55,1342815,11514.59
0,CCP,0.47,-0.01,-2.08,0.48,0.48,0.46,9790483,4610.34
6,GEL,0.31,-0.01,-3.12,0.32,0.32,0.31,2753802,873.04
15,TOA,33.50,-1.25,-3.60,34.50,34.50,33.50,957088,32425.11

In [13]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
45  SHREIT  3.42   0.10    3.01  3.42  3.42  3.42       451500         1544.13
21  IMPACT 13.80   0.20    1.47    14 14.10 13.70       470474         6557.99
58   WHABT  8.95   0.10    1.13  8.85  8.95  8.85        25810          229.32
23   KPNPF  5.15   0.05    0.98  5.15  5.15  5.15          100            0.52
50   SSTRT  5.70   0.05    0.88  5.70  5.70  5.70         3816           21.75
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
14  FTREIT 11.40  -0.20   -1.72 11.40 11.40 11.30       322513         3674.16
13   ERWPF  4.20  -0.12   -2.78  4.14  4.20  4.12       164500          682.87
39    POPF 11.30  -0.40   -3.42 11.30 11.40 11.30       621112         7068.01
43    QHOP  2.70  -0.12   -4.26  2.72  2.74  2.70        81700          221.84
57  URBNPF  1.90  -0.10      -5  1.91     2  1.90        10800           20.76

[60 rows x 9 columns]

In [14]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
9      DMT 12.90   0.20    1.57 12.80    13 12.70       985802        12731.22
11     JWD 20.40   0.30    1.49    20 20.40    20      1709326        34711.73
21     RCL 30.75   0.25    0.82 30.50 30.75 30.25      1341212        41016.40
5      BEM  9.55      0       0  9.55  9.55  9.50     18500068       176390.04
6   BIOTEC  0.96      0       0  0.96  0.98  0.96     17444494        16908.31
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
26    WICE 11.30  -0.10   -0.88 11.40 11.60 11.30      1406725        16009.85
7      BTS  8.15  -0.10   -1.21  8.20  8.25  8.10     50331413       411103.89
0      AAV  3.02  -0.04   -1.31  3.04  3.06  3.02     13069430        39631.33
10     III 14.30  -0.30   -2.05 14.60 14.60 14.10      7509039       107297.73
3        B  0.43  -0.01   -2.27  0.44  0.44  0.42     10039086         4319.86

[23 rows x 9 columns]

In [15]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
31     TKC 24.80   2.10    9.25 23.40 24.80 23.10     14002145       336373.80
26     SKY 27.75   1.75    6.73 25.75    28 25.50      8395943       228419.33
22  SAMART  5.35   0.25    4.90  5.10  5.35  5.10      5446600        28495.19
0   ADVANC   206   6.50    3.26   202   206   201     17037520      3473210.18
8    FORTH    44   1.25    2.92 42.50 44.75 42.50      7836387       342634.26
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
3      AMR  3.90  -0.06   -1.52  3.94  3.94  3.90       347629         1358.50
23  SAMTEL  6.20  -0.10   -1.59  6.25  6.30  6.15       800453         4969.87
11    INET  5.45  -0.10   -1.80  5.55  5.55  5.40       798506         4377.95
17   JMART 34.50     -1   -2.82 35.25 35.50 34.50      7973040       277227.82
24     SDC  0.18  -0.01   -5.26  0.18  0.19  0.17    100555996        18166.32

[33 rows x 9 columns]

In [16]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_CONMAT, df_PFREIT, df_TRANS, df_ICT])
df.shape

(616, 16)

In [17]:
df.Symbol.nunique()

357

In [18]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(357, 16)

In [19]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [20]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.82,-0.03,-3.53,0.85,0.85,0.82,17610162,14589.43
0,AAV,3.02,-0.04,-1.31,3.04,3.06,3.02,13069430,39631.33
1,ACE,2.48,-0.04,-1.59,2.52,2.52,2.48,12908381,32137.28
2,ADVANC,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
1,AGE,3.70,0.04,1.09,3.68,3.72,3.68,1226076,4529.89
...,...,...,...,...,...,...,...,...,...
140,WICE,11.30,-0.10,-0.88,11.40,11.60,11.30,1406725,16009.85
19,WIIK,1.89,0.00,0.00,1.88,1.89,1.87,309901,583.80
141,WORK,18.40,0.10,0.55,18.40,18.40,18.30,141505,2595.00
142,XPG,1.41,0.00,0.00,1.41,1.42,1.40,6767065,9551.85
143,ZEN,17.50,-0.30,-1.69,17.60,18.00,17.50,483400,8553.34

In [21]:
df.insert(1, 'Date', today)

In [22]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-10,3.02,-0.04,-1.31,3.04,3.06,3.02,13069430,39631.33
1,ACE,2023-02-10,2.48,-0.04,-1.59,2.52,2.52,2.48,12908381,32137.28
2,ADVANC,2023-02-10,206.00,6.50,3.26,202.00,206.00,201.00,17037520,3473210.18
3,AMATA,2023-02-10,19.90,-0.30,-1.49,20.00,20.10,19.80,6819745,136037.32
4,AOT,2023-02-10,73.00,-0.50,-0.68,73.25,73.50,73.00,14762919,1080412.49
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-10,6.20,-0.10,-1.59,6.25,6.30,6.15,800453,4969.87
24,SDC,2023-02-10,0.18,-0.01,-5.26,0.18,0.19,0.17,100555996,18166.32
27,SVOA,2023-02-10,2.60,-0.04,-1.52,2.62,2.64,2.60,960203,2506.87
28,SYMC,2023-02-10,5.95,-0.05,-0.83,5.95,5.95,5.90,4200,24.87
33,TWZ,2023-02-10,0.07,0,0,0.08,0.08,0.07,3858952,276.34

In [23]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [24]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [25]:
df_out = df[colt]
df_out.shape

(357, 10)

In [26]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(194, 10)

In [27]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [28]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [29]:
colp = 'name date price high low volume open'.split()
colp

['name', 'date', 'price', 'high', 'low', 'volume', 'open']

In [30]:
file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [31]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes