### Restart & Run All Cells

In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 16), datetime.date(2023, 2, 15))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-16
yesterday: 2023-02-15

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
31,DELTA,976.00,72.00,7.96,934.00,988.00,930.00,7159104,6906023.88
50,JMT,45.50,2.75,6.43,43.75,46.50,42.00,42547825,1898232.61
21,CBG,105.50,6.25,6.30,105.00,106.00,104.00,14269416,1496605.89
65,OSP,30.50,1.75,6.09,31.75,33.00,30.50,76360084,2366185.74
38,FORTH,43.00,2.25,5.52,41.50,43.00,40.50,3320048,140339.86
...,...,...,...,...,...,...,...,...,...
81,SINGER,18.30,-0.50,-2.66,19.20,19.30,18.00,62838179,1170493.86
11,BCP,34.25,-1.00,-2.84,35.50,35.50,34.25,8709101,301951.92
74,RBF,12.20,-0.40,-3.17,12.60,12.70,12.10,3878479,48185.03
34,EA,83.25,-3.25,-3.76,86.25,86.25,83.00,18960219,1588755.28
67,PSL,13.60,-0.70,-4.90,14.20,14.20,13.50,24717301,339386.32

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
91,SAK,7.50,0.75,11.11,7.05,7.50,6.90,15219330,111336.29
22,BWG,1.06,0.06,6.00,1.00,1.07,1.00,92325149,96663.18
65,NCAP,4.62,0.26,5.96,4.40,4.62,4.38,12733389,57565.81
115,TC,12.00,0.60,5.26,11.40,12.10,11.40,1315700,15546.74
126,TOG,9.55,0.45,4.95,9.50,9.90,9.45,1664359,15987.05
...,...,...,...,...,...,...,...,...,...
80,PRM,7.70,-0.20,-2.53,7.95,7.95,7.70,9096472,70826.52
92,SAMART,5.30,-0.15,-2.75,5.45,5.50,5.30,3513200,18799.26
140,WICE,10.10,-0.30,-2.88,10.50,10.50,10.00,6910285,70372.51
103,SMPC,11.90,-0.50,-4.03,12.40,12.40,11.80,2647122,31708.55
55,LPN,4.30,-0.20,-4.44,4.48,4.52,4.26,17715931,76831.96

In [8]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
13,CBG,105.50,6.25,6.30,105.00,106.00,104.00,14269416,1496605.89
35,OSP,30.50,1.75,6.09,31.75,33.00,30.50,76360084,2366185.74
23,GUNKUL,4.30,0.16,3.86,4.24,4.34,4.20,181716027,776435.33
24,ICHI,12.40,0.40,3.33,12.00,12.40,12.00,4985062,61238.33
10,BH,215.00,6.00,2.87,214.00,217.00,212.00,5183045,1111484.99
...,...,...,...,...,...,...,...,...,...
28,KBANK,139.50,-2.00,-1.41,141.00,141.50,138.50,18629689,2601639.34
9,BGRIM,40.75,-1.00,-2.40,41.75,42.00,40.50,13861323,566624.34
42,SAMART,5.30,-0.15,-2.75,5.45,5.50,5.30,3513200,18799.26
5,BCP,34.25,-1.00,-2.84,35.50,35.50,34.25,8709101,301951.92
40,RBF,12.20,-0.40,-3.17,12.60,12.70,12.10,3878479,48185.03

In [9]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
16,OSP,30.50,1.75,6.09,31.75,33.00,30.50,76360084,2366185.74
9,GUNKUL,4.30,0.16,3.86,4.24,4.34,4.20,181716027,776435.33
21,SAWAD,54.50,1.75,3.32,53.25,54.50,52.75,8166059,438705.37
25,THANI,4.00,0.12,3.09,4.06,4.06,3.98,19822472,79726.96
6,CHG,3.92,0.08,2.08,3.84,3.94,3.84,43557516,169734.25
...,...,...,...,...,...,...,...,...,...
2,BBL,162.50,-1.50,-0.91,164.50,164.50,161.50,9146168,1485744.93
29,WHA,3.84,-0.04,-1.03,3.90,3.92,3.84,43889180,169673.37
13,KTB,16.90,-0.20,-1.17,17.10,17.10,16.80,29608337,501680.18
23,SPALI,23.90,-0.30,-1.24,24.20,24.30,23.90,8709109,209221.44
10,HANA,58.25,-1.00,-1.69,60.50,61.25,57.50,14222681,840875.15

In [10]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
85,SAK,7.50,0.75,11.11,7.05,7.50,6.90,15219330,111336.29
34,DELTA,976.00,72.00,7.96,934.00,988.00,930.00,7159104,6906023.88
26,CBG,105.50,6.25,6.30,105.00,106.00,104.00,14269416,1496605.89
71,OSP,30.50,1.75,6.09,31.75,33.00,30.50,76360084,2366185.74
58,KEX,15.60,0.60,4.00,15.00,16.20,14.90,15089912,236371.69
...,...,...,...,...,...,...,...,...,...
20,BGRIM,40.75,-1.00,-2.40,41.75,42.00,40.50,13861323,566624.34
116,VGI,4.42,-0.12,-2.64,4.54,4.54,4.36,41710689,184154.93
15,BCP,34.25,-1.00,-2.84,35.50,35.50,34.25,8709101,301951.92
38,EA,83.25,-3.25,-3.76,86.25,86.25,83.00,18960219,1588755.28
76,PSL,13.60,-0.70,-4.90,14.20,14.20,13.50,24717301,339386.32

In [11]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
6,CBG,105.50,6.25,6.30,105.00,106.00,104.00,14269416,1496605.89
19,OSP,30.50,1.75,6.09,31.75,33.00,30.50,76360084,2366185.74
16,KEX,15.60,0.60,4.00,15.00,16.20,14.90,15089912,236371.69
3,BH,215.00,6.00,2.87,214.00,217.00,212.00,5183045,1111484.99
8,COM7,29.75,0.75,2.59,29.25,30.00,28.75,13657938,404118.04
...,...,...,...,...,...,...,...,...,...
25,STA,23.60,-0.20,-0.84,23.80,23.90,22.90,9420596,220457.88
15,JWD,19.70,-0.20,-1.01,19.90,20.10,19.70,2963844,58846.25
24,SINGER,18.30,-0.50,-2.66,19.20,19.30,18.00,62838179,1170493.86
17,M,54.00,-1.50,-2.70,55.50,55.50,53.50,2701160,146411.19
21,RBF,12.20,-0.40,-3.17,12.60,12.70,12.10,3878479,48185.03

In [12]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_FIN = pd.read_excel(input_file, header=9)
df_FIN = df_FIN[df_FIN['%Change'] != '-']
df_FIN[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
28,SAK,7.50,0.75,11.11,7.05,7.50,6.90,15219330,111336.29
16,JMT,45.50,2.75,6.43,43.75,46.50,42,42547825,1898232.61
25,NCAP,4.62,0.26,5.96,4.40,4.62,4.38,12733389,57565.81
32,SM,1.98,0.08,4.21,1.92,1.99,1.92,4093601,8052.49
31,SGC,3.74,0.14,3.89,3.70,3.82,3.60,122546455,458085.72
...,...,...,...,...,...,...,...,...,...
5,BAM,15.50,-0.10,-0.64,15.60,15.60,15.30,29041562,449424.82
23,MST,11.50,-0.10,-0.86,11.60,11.60,11.50,35917,415.07
0,AEONTS,197.50,-2.50,-1.25,199,199.50,197.50,145423,28856.45
6,BYD,11.60,-0.20,-1.69,11.80,12,11.50,7583520,88308.43
7,CGH,0.91,-0.02,-2.15,0.92,0.94,0.91,11510549,10661.00

In [13]:
df_FIN.query('Symbol == "ASK"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,ASK,-,31,0.25,0.81,31.25,31.75,30.75,0,0,3653445,113592.21,320700,30.75,31,153300

In [14]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
36,MNIT,1.77,0.11,6.63,1.78,1.78,1.75,6100,10.78
43,QHOP,2.68,0.08,3.08,2.56,2.68,2.56,200,0.52
22,INETREIT,11.80,0.30,2.61,11.50,11.80,11.50,637004,7439.27
50,SSTRT,5.70,0.10,1.79,5.65,5.70,5.65,13300,75.66
60,WHART,11.50,0.20,1.77,11.40,11.50,11.20,995609,11294.06
...,...,...,...,...,...,...,...,...,...
14,FTREIT,11.20,-0.10,-0.88,11.10,11.30,11.10,488603,5471.83
41,PROSPECT,9.75,-0.10,-1.02,9.80,9.80,9.70,200615,1953.83
48,SRIPANWA,7,-0.10,-1.41,7.10,7.10,7,309902,2170.08
45,SHREIT,3.34,-0.06,-1.76,3.40,3.42,3.34,12100,41.32
46,SIRIP,7.75,-0.30,-3.73,7.65,7.75,7.60,5700,43.83

In [15]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
12    KEX 15.60   0.60       4    15 16.20 14.90     15089912       236371.69
18   PORT  2.04   0.05    2.51  1.99  2.04  1.99       103001          206.17
3       B  0.41   0.01    2.50  0.41  0.41  0.40      7700617         3146.95
21    RCL 29.50   0.50    1.72 29.25    30 29.25      1739426        51496.29
9     DMT    12   0.20    1.69 11.90 12.20 11.80      1548325        18574.06
..    ...   ...    ...     ...   ...   ...   ...          ...             ...
11    JWD 19.70  -0.20   -1.01 19.90 20.10 19.70      2963844        58846.25
15   MENA  1.89  -0.03   -1.56  1.92  1.92  1.88      1095400         2077.21
19    PRM  7.70  -0.20   -2.53  7.95  7.95  7.70      9096472        70826.52
26   WICE 10.10  -0.30   -2.88 10.50 10.50    10      6910285        70372.51
20    PSL 13.60  -0.70   -4.90 14.20 14.20 13.50     24717301       339386.32

[23 rows x 9 columns]

In [16]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol Last Change %Change  Open  High   Low Total Volume Total Value (k)
24     SDC 0.19   0.02   11.76  0.17  0.19  0.17     38733231         7028.48
8    FORTH   43   2.25    5.52 41.50    43 40.50      3320048       140339.86
18     JTS   39      2    5.41    40 40.25 38.75       863261        34102.84
21      PT 7.15   0.35    5.15  6.80  7.65  6.75     13035813        95498.66
26     SKY   26   1.20    4.84 24.90 26.25 23.10      9381255       231367.01
..     ...  ...    ...     ...   ...   ...   ...          ...             ...
3      AMR 3.66      0       0  3.66  3.68  3.64       234500          857.52
33     TWZ 0.07      0       0  0.07  0.08  0.06      7419407          519.14
13  INTUCH   75  -0.25   -0.33 75.25 75.50 74.75      2381946       178822.71
20     MSC 9.35  -0.05   -0.53  9.40  9.40  9.30       100219          941.15
22  SAMART 5.30  -0.15   -2.75  5.45  5.50  5.30      3513200        18799.26

[33 rows x 9 columns]

In [17]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_FIN, df_PFREIT, df_TRANS, df_ICT])
df.shape

(631, 16)

In [18]:
df.Symbol.nunique()

362

In [19]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(362, 16)

In [20]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [21]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.80,0.01,1.27,0.79,0.81,0.79,10041053,8034.61
0,AAV,2.98,0.04,1.36,2.94,2.98,2.92,24165688,71424.66
1,ACE,2.50,0.06,2.46,2.44,2.50,2.44,16119904,39870.47
2,ADVANC,211.00,2.00,0.96,209.00,212.00,208.00,6838734,1438637.82
0,AEONTS,197.50,-2.50,-1.25,199,199.50,197.50,145423,28856.45
...,...,...,...,...,...,...,...,...,...
139,WHAUP,4.02,-0.02,-0.50,4.02,4.06,4.02,1309775,5288.39
140,WICE,10.10,-0.30,-2.88,10.50,10.50,10.00,6910285,70372.51
141,WORK,17.90,0.30,1.70,17.60,17.90,17.60,264602,4707.94
142,XPG,1.34,0.03,2.29,1.33,1.35,1.32,9793600,13114.80
143,ZEN,17.00,0.20,1.19,16.80,17.20,16.70,225238,3825.62

In [22]:
df.insert(1, 'Date', today)

In [23]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-16,2.98,0.04,1.36,2.94,2.98,2.92,24165688,71424.66
1,ACE,2023-02-16,2.50,0.06,2.46,2.44,2.50,2.44,16119904,39870.47
2,ADVANC,2023-02-16,211.00,2.00,0.96,209.00,212.00,208.00,6838734,1438637.82
3,AMATA,2023-02-16,19.90,0.20,1.02,19.80,20.10,19.70,5515642,110041.09
4,AOT,2023-02-16,72.75,-0.25,-0.34,73.00,73.25,72.75,8972560,653859.62
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-16,6.35,0.05,0.79,6.30,6.35,6.25,169201,1061.64
24,SDC,2023-02-16,0.19,0.02,11.76,0.17,0.19,0.17,38733231,7028.48
27,SVOA,2023-02-16,2.36,0.04,1.72,2.32,2.40,2.32,727208,1719.05
28,SYMC,2023-02-16,5.90,0.05,0.85,5.90,5.95,5.70,3100,17.94
33,TWZ,2023-02-16,0.07,0,0,0.07,0.08,0.06,7419407,519.14

In [24]:
file_name = "name-ttl.csv"
input_file = data_path + file_name

df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [25]:
df_out = df[colt]
df_out.shape

(362, 10)

In [26]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(195, 10)

In [27]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [28]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [29]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [30]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes