In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 16), datetime.date(2023, 2, 15))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-16
yesterday: 2023-02-15

### Restart & Run All Cells

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

Moved HistoricalTrading.xlsx to Datasets
Moved StockQuotation (1).xlsx to Datasets
Moved StockQuotation (2).xlsx to Datasets
Moved StockQuotation (3).xlsx to Datasets
Moved StockQuotation (4).xlsx to Datasets
Moved StockQuotation (5).xlsx to Datasets
Moved StockQuotation (6).xlsx to Datasets
Moved StockQuotation (7).xlsx to Datasets
Moved StockQuotation (8).xlsx to Datasets
Moved StockQuotation (9).xlsx to Datasets
Moved StockQuotation.xlsx to Datasets

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
65,OSP,31.00,2.25,7.83,31.75,33.00,30.50,60478214,1880046.49
31,DELTA,972.00,68.00,7.52,934.00,988.00,930.00,6539090,6302412.88
50,JMT,45.25,2.50,5.85,43.75,46.50,42.00,40034240,1784057.60
21,CBG,105.00,5.75,5.79,105.00,106.00,104.00,10639322,1113400.90
53,KEX,15.80,0.80,5.33,15.00,16.20,14.90,14270198,223581.71
...,...,...,...,...,...,...,...,...,...
74,RBF,12.30,-0.30,-2.38,12.60,12.70,12.30,2283644,28703.41
16,BGRIM,40.50,-1.25,-2.99,41.75,42.00,40.50,11869545,485664.59
34,EA,83.75,-2.75,-3.18,86.25,86.25,83.00,13789717,1157681.66
98,VGI,4.38,-0.16,-3.52,4.54,4.54,4.36,32668781,144388.34
67,PSL,13.70,-0.60,-4.20,14.20,14.20,13.50,20836167,286589.32

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
91,SAK,7.50,0.75,11.11,7.05,7.50,6.90,13005725,94817.08
102,SKY,26.25,1.45,5.85,24.90,26.25,23.10,8799045,216285.17
65,NCAP,4.60,0.24,5.50,4.40,4.60,4.38,10652681,47989.62
96,SCM,5.85,0.30,5.41,5.60,5.90,5.50,1011500,5852.14
115,TC,12.00,0.60,5.26,11.40,12.10,11.40,987400,11607.80
...,...,...,...,...,...,...,...,...,...
134,UTP,15.00,-0.30,-1.96,15.30,15.30,15.00,616659,9330.58
18,BEYOND,15.20,-0.40,-2.56,15.80,15.80,14.90,579000,8880.89
32,EP,3.94,-0.12,-2.96,4.06,4.06,3.92,1259587,5017.63
103,SMPC,11.90,-0.50,-4.03,12.40,12.40,11.80,2333812,27980.37
55,LPN,4.30,-0.20,-4.44,4.48,4.52,4.26,15951131,69254.17

In [8]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
35,OSP,31.00,2.25,7.83,31.75,33.00,30.50,60478214,1880046.49
13,CBG,105.00,5.75,5.79,105.00,106.00,104.00,10639322,1113400.90
23,GUNKUL,4.32,0.18,4.35,4.24,4.34,4.20,135825120,579807.88
10,BH,216.00,7.00,3.35,214.00,217.00,212.00,3832240,820886.31
24,ICHI,12.40,0.40,3.33,12.00,12.40,12.00,4261261,52280.42
...,...,...,...,...,...,...,...,...,...
31,MAJOR,17.80,-0.20,-1.11,17.90,18.00,17.70,1279977,22846.68
28,KBANK,139.00,-2.50,-1.77,141.00,141.50,138.50,14814731,2069599.19
5,BCP,34.50,-0.75,-2.13,35.50,35.50,34.50,5919859,206045.19
40,RBF,12.30,-0.30,-2.38,12.60,12.70,12.30,2283644,28703.41
9,BGRIM,40.75,-1.00,-2.40,41.75,42.00,40.50,11869745,485672.72

In [9]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
16,OSP,31.00,2.25,7.83,31.75,33.00,30.50,60482414,1880176.69
9,GUNKUL,4.32,0.18,4.35,4.24,4.34,4.20,136525120,582831.88
25,THANI,4.02,0.14,3.61,4.06,4.06,3.98,17367827,69908.18
6,CHG,3.92,0.08,2.08,3.84,3.94,3.84,38164659,148627.96
21,SAWAD,53.50,0.75,1.42,53.25,54.25,52.75,5202378,278082.39
...,...,...,...,...,...,...,...,...,...
1,AP,11.90,-0.10,-0.83,12.00,12.10,11.80,24029829,287000.13
2,BBL,162.50,-1.50,-0.91,164.50,164.50,161.50,8232212,1337245.46
14,LH,9.70,-0.10,-1.02,9.75,9.80,9.65,14308995,138983.70
13,KTB,16.90,-0.20,-1.17,17.10,17.10,16.80,23788092,403308.78
10,HANA,58.25,-1.00,-1.69,60.50,61.25,57.50,13355085,790330.60

In [10]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
85,SAK,7.50,0.75,11.11,7.05,7.50,6.90,13005830,94817.86
71,OSP,31.00,2.25,7.83,31.75,33.00,30.50,60491214,1880449.49
34,DELTA,974.00,70.00,7.74,934.00,988.00,930.00,6539490,6302802.18
26,CBG,105.00,5.75,5.79,105.00,106.00,104.00,10639322,1113400.90
58,KEX,15.70,0.70,4.67,15.00,16.20,14.90,14280198,223738.71
...,...,...,...,...,...,...,...,...,...
15,BCP,34.50,-0.75,-2.13,35.50,35.50,34.50,5919859,206045.19
20,BGRIM,40.75,-1.00,-2.40,41.75,42.00,40.50,11869745,485672.72
116,VGI,4.40,-0.14,-3.08,4.54,4.54,4.36,32672981,144406.82
38,EA,83.75,-2.75,-3.18,86.25,86.25,83.00,13789717,1157681.66
76,PSL,13.70,-0.60,-4.20,14.20,14.20,13.50,20836167,286589.32

In [11]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
19,OSP,31.00,2.25,7.83,31.75,33.00,30.50,60613214,1884231.49
6,CBG,105.00,5.75,5.79,105.00,106.00,104.00,10639522,1113421.90
16,KEX,15.70,0.70,4.67,15.00,16.20,14.90,14280198,223738.71
3,BH,215.00,6.00,2.87,214.00,217.00,212.00,3833240,821101.31
22,RCL,29.75,0.75,2.59,29.25,30.00,29.25,1112998,33007.23
...,...,...,...,...,...,...,...,...,...
14,HMPRO,14.70,-0.10,-0.68,14.70,14.80,14.60,13262693,194760.36
25,STA,23.50,-0.30,-1.26,23.80,23.90,22.90,8544274,199787.89
24,SINGER,18.50,-0.30,-1.60,19.20,19.30,18.00,56060640,1046347.22
21,RBF,12.30,-0.30,-2.38,12.60,12.70,12.30,2283644,28703.41
17,M,54.00,-1.50,-2.70,55.50,55.50,53.50,2295855,124580.37

In [12]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_FIN = pd.read_excel(input_file, header=9)
df_FIN = df_FIN[df_FIN['%Change'] != '-']
df_FIN[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
28,SAK,7.50,0.75,11.11,7.05,7.50,6.90,13005830,94817.86
16,JMT,45.25,2.50,5.85,43.75,46.50,42,40035240,1784102.85
25,NCAP,4.58,0.22,5.05,4.40,4.60,4.38,10660681,48026.26
32,SM,1.98,0.08,4.21,1.92,1.99,1.92,3304300,6489.68
33,TH,2.16,0.08,3.85,2.10,2.18,2.06,12859524,27391.86
...,...,...,...,...,...,...,...,...,...
0,AEONTS,198,-2,-1,199,199.50,197.50,119823,23790.45
7,CGH,0.92,-0.01,-1.08,0.92,0.94,0.91,9744749,9051.90
36,TK,8.10,-0.10,-1.22,8.15,8.20,8.05,606500,4925.19
5,BAM,15.40,-0.20,-1.28,15.60,15.60,15.30,26986292,417588.34
6,BYD,11.60,-0.20,-1.69,11.80,12,11.50,6569820,76484.05

In [13]:
df_FIN.query('Symbol == "ASK"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,ASK,-,31,0.25,0.81,31.25,31.75,30.75,0,0,3273026,101804.64,414800,30.75,31,58800

In [14]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
36,MNIT,1.78,0.12,7.23,1.78,1.78,1.75,3100,5.47
22,INETREIT,11.80,0.30,2.61,11.50,11.80,11.50,531704,6203.54
50,SSTRT,5.70,0.10,1.79,5.65,5.70,5.65,11600,65.97
8,CPNCG,11.60,0.20,1.75,11.50,11.60,11.50,90000,1037.95
32,M-STOR,6.20,0.10,1.64,6.20,6.20,6,3100,18.99
...,...,...,...,...,...,...,...,...,...
29,LUXF,7.50,-0.10,-1.32,7.45,7.50,7.45,5200,38.99
43,QHOP,2.56,-0.04,-1.54,2.56,2.56,2.56,100,0.26
34,MIT,1.68,-0.03,-1.75,1.73,1.73,1.68,18400,31.42
46,SIRIP,7.75,-0.30,-3.73,7.65,7.75,7.60,5700,43.83
57,URBNPF,1.91,-0.08,-4.02,1.92,1.92,1.91,5200,9.97

In [15]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
12    KEX 15.70   0.70    4.67    15 16.20 14.90     14315798       224297.69
21    RCL 29.75   0.75    2.59 29.25    30 29.25      1113098        33010.21
9     DMT    12   0.20    1.69 11.90 12.20 11.80      1220224        14621.57
18   PORT  2.02   0.03    1.51  1.99  2.02  1.99       101801          203.72
10    III 14.10   0.10    0.71    14 14.20 13.90      2515076        35238.21
..    ...   ...    ...     ...   ...   ...   ...          ...             ...
4      BA    14  -0.10   -0.71    14 14.20 13.90       707763         9945.95
15   MENA  1.90  -0.02   -1.04  1.92  1.92  1.88       726900            1379
19    PRM  7.80  -0.10   -1.27  7.95  7.95  7.75      4984544        38901.73
26   WICE 10.20  -0.20   -1.92 10.50 10.50    10      6126080        62449.90
20    PSL 13.60  -0.70   -4.90 14.20 14.20 13.50     20847667       286745.87

[23 rows x 9 columns]

In [16]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
24     SDC  0.19   0.02   11.76  0.17  0.19  0.17     34394831         6205.67
18     JTS 39.25   2.25    6.08    40 40.25 38.75       754917        29863.63
26     SKY    26   1.20    4.84 24.90 26.25 23.10      8805245       216446.37
8    FORTH 42.50   1.75    4.29 41.50    43 40.50      2515026       105770.70
21      PT  7.05   0.25    3.68  6.80  7.65  6.75     12110712        88903.68
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
13  INTUCH 75.25      0       0 75.25 75.50 74.75      1805632       135559.46
30   THCOM 15.80      0       0 15.80 16.10 15.60      5815101        91890.53
3      AMR  3.66      0       0  3.66  3.68  3.64       141600          518.03
33     TWZ  0.07      0       0  0.07  0.08  0.06      5176374          362.12
22  SAMART  5.40  -0.05   -0.92  5.45  5.50  5.30      2607100        13986.26

[33 rows x 9 columns]

In [17]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_FIN, df_PFREIT, df_TRANS, df_ICT])
df.shape

(630, 16)

In [18]:
df.Symbol.nunique()

361

In [19]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(361, 16)

In [20]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [21]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.80,0.01,1.27,0.79,0.81,0.79,5677034,4541.76
0,AAV,2.96,0.02,0.68,2.94,2.96,2.92,13445954,39684.43
1,ACE,2.48,0.04,1.64,2.44,2.50,2.44,13912954,34353.56
2,ADVANC,211.00,2.00,0.96,209.00,212.00,208.00,5335119,1121404.24
0,AEONTS,198,-2,-1,199,199.50,197.50,119823,23790.45
...,...,...,...,...,...,...,...,...,...
139,WHAUP,4.02,-0.02,-0.50,4.02,4.06,4.02,1117675,4515.50
140,WICE,10.20,-0.20,-1.92,10.50,10.50,10.00,6125780,62446.84
141,WORK,17.80,0.20,1.14,17.60,17.90,17.60,218926,3892.85
142,XPG,1.34,0.03,2.29,1.33,1.35,1.32,9256541,12395.11
143,ZEN,17.20,0.40,2.38,16.80,17.20,16.70,143338,2422.33

In [22]:
df.insert(1, 'Date', today)

In [23]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-16,2.96,0.02,0.68,2.94,2.96,2.92,13445954,39684.43
1,ACE,2023-02-16,2.48,0.04,1.64,2.44,2.50,2.44,13912954,34353.56
2,ADVANC,2023-02-16,211.00,2.00,0.96,209.00,212.00,208.00,5335119,1121404.24
3,AMATA,2023-02-16,19.80,0.10,0.51,19.80,20.10,19.70,4001918,79870.12
4,AOT,2023-02-16,72.75,-0.25,-0.34,73.00,73.25,72.75,6267316,456950.21
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-16,6.30,0,0,6.30,6.35,6.25,147601,925.51
24,SDC,2023-02-16,0.19,0.02,11.76,0.17,0.19,0.17,34394831,6205.67
27,SVOA,2023-02-16,2.38,0.06,2.59,2.32,2.40,2.32,450108,1064.15
28,SYMC,2023-02-16,5.90,0.05,0.85,5.90,5.90,5.90,100,0.59
33,TWZ,2023-02-16,0.07,0,0,0.07,0.08,0.06,5176374,362.12

In [24]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [25]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [26]:
df_out = df[colt]
df_out.shape

(361, 10)

In [27]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(195, 10)

In [28]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [29]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [30]:
colp = 'name date price high low volume open'.split()
colp

['name', 'date', 'price', 'high', 'low', 'volume', 'open']

In [31]:
file_name = "Price.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [32]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes