In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

data_path = "../data/"
dts_path = "/Users/User/Downloads/Datasets/"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 7), datetime.date(2023, 2, 6))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-07
yesterday: 2023-02-06

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

### Delete files in folder Datasets, if there is no file, error causes program to stop

In [ ]:
#for filename in glob.glob(os.path.join(dts_path, '*.xlsx')):
    print(f'Delete {filename}')
    os.remove(filename)

### SET100, sSET, SETCLMV, SETHD, SETTHSI, SETWB, CONMAT, PFREIT, TRANS, ICT

In [ ]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

In [4]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [5]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
84,STA,23.40,0.80,3.54,22.60,23.60,22.60,17792391,410653.26
86,STGT,11.40,0.30,2.70,11.10,11.60,11.00,26522526,302055.12
83,SPRC,11.40,0.30,2.70,11.30,11.50,11.20,30955605,353231.89
16,BGRIM,40.75,1.00,2.52,40.00,40.75,39.75,9101197,365517.13
31,DELTA,970.00,20.00,2.11,966.00,996.00,962.00,4132116,4034300.21
...,...,...,...,...,...,...,...,...,...
85,STARK,2.94,-0.06,-2.00,3.00,3.02,2.92,57344552,169727.82
96,TTB,1.42,-0.03,-2.07,1.44,1.45,1.42,194236716,276844.84
76,SABUY,13.00,-0.40,-2.99,13.50,13.50,13.00,41170399,542325.59
60,MTC,37.00,-1.75,-4.52,38.75,39.00,36.75,35140049,1317204.38
89,THG,68.00,-3.25,-4.56,71.00,71.75,67.00,11758723,805737.68

In [6]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
17,BEAUTY,1.59,0.13,8.90,1.46,1.61,1.44,261554760,406670.13
26,DDD,18.40,1.20,6.98,17.20,18.40,17.20,2574408,46135.95
57,MACO,0.62,0.04,6.90,0.59,0.62,0.59,59064093,35968.69
93,SAPPE,52.50,3.00,6.06,50.00,52.50,50.00,2552941,131784.88
18,BEYOND,14.80,0.70,4.96,14.20,14.80,13.90,2109111,30301.75
...,...,...,...,...,...,...,...,...,...
137,VIH,8.55,-0.25,-2.84,8.85,8.85,8.45,2876859,24813.46
65,NCAP,4.84,-0.16,-3.20,5.00,5.05,4.78,36472971,178669.22
47,KAMART,8.35,-0.30,-3.47,8.70,8.70,8.25,10133431,85210.26
35,HENG,3.14,-0.12,-3.68,3.26,3.26,3.14,15835661,50270.77
111,STPI,5.10,-0.35,-6.42,5.50,5.50,5.05,13855772,72347.82

In [7]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
49,STGT,11.40,0.30,2.70,11.10,11.60,11.00,26522526,302055.12
47,SPRC,11.40,0.30,2.70,11.30,11.50,11.20,30955605,353231.89
9,BGRIM,40.75,1.00,2.52,40.00,40.75,39.75,9101197,365517.13
15,CKP,4.68,0.08,1.74,4.64,4.72,4.60,24336619,113698.60
11,BJC,38.50,0.50,1.32,38.25,38.75,37.50,4774943,182526.65
...,...,...,...,...,...,...,...,...,...
31,MAJOR,18.60,-0.20,-1.06,18.70,18.80,18.40,1235687,23003.45
14,CK,22.40,-0.30,-1.32,22.60,22.80,22.40,5067398,114296.94
5,BCP,35.50,-0.50,-1.39,36.00,36.00,35.25,5801589,206626.30
29,KKP,67.50,-1.00,-1.46,68.50,68.50,67.25,9986259,675593.28
42,SAMART,5.60,-0.10,-1.75,5.85,5.85,5.60,9903903,56251.20

In [8]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
23,SPALI,24.50,0.30,1.24,24.40,24.70,24.10,17117094,418845.77
10,HANA,64.00,0.75,1.19,63.00,65.00,63.00,14815331,949666.44
16,OSP,28.50,0.25,0.88,28.25,28.50,28.00,5471542,154774.20
1,AP,11.90,0.10,0.85,11.90,11.90,11.70,16341272,193278.33
18,PTTEP,165.00,1.00,0.61,164.00,165.50,164.00,15544249,2560725.53
...,...,...,...,...,...,...,...,...,...
13,KTB,17.20,-0.20,-1.15,17.30,17.40,17.20,37917040,654660.83
25,THANI,4.06,-0.06,-1.46,4.10,4.12,4.06,18301546,74524.31
12,KKP,67.50,-1.00,-1.46,68.50,68.50,67.25,9986259,675593.28
21,SAWAD,55.50,-1.00,-1.77,56.00,56.50,55.00,10005330,555531.03
27,TTB,1.42,-0.03,-2.07,1.44,1.45,1.42,194236716,276844.84

In [9]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
86,SAPPE,52.50,3.00,6.06,50.00,52.50,50.00,2552941,131784.88
42,ETC,4.60,0.16,3.60,4.46,4.62,4.46,27268940,123563.56
98,STA,23.40,0.80,3.54,22.60,23.60,22.60,17792391,410653.26
95,SIRI,1.92,0.06,3.23,1.88,1.92,1.87,249162219,473339.77
99,STGT,11.40,0.30,2.70,11.10,11.60,11.00,26522526,302055.12
...,...,...,...,...,...,...,...,...,...
88,SAWAD,55.50,-1.00,-1.77,56.00,56.50,55.00,10005330,555531.03
113,TTB,1.42,-0.03,-2.07,1.44,1.45,1.42,194236716,276844.84
85,SAK,7.05,-0.20,-2.76,7.30,7.30,7.00,2719032,19312.06
65,MTC,37.00,-1.75,-4.52,38.75,39.00,36.75,35140049,1317204.38
43,GFPT,12.60,-0.60,-4.55,13.20,13.30,12.60,13964192,178375.59

In [10]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
25,STA,23.40,0.80,3.54,22.60,23.60,22.60,17792391,410653.26
29,VIBHA,2.78,0.04,1.46,2.74,2.80,2.72,9523459,26306.11
4,BJC,38.50,0.50,1.32,38.25,38.75,37.50,4774943,182526.65
19,OSP,28.50,0.25,0.88,28.25,28.50,28.00,5471542,154774.20
21,RBF,12.90,0.10,0.78,12.80,13.00,12.80,3377331,43600.96
...,...,...,...,...,...,...,...,...,...
2,BEM,9.60,-0.15,-1.54,9.70,9.75,9.55,58793587,565334.31
8,COM7,31.75,-0.50,-1.55,32.00,32.25,31.25,15549744,495102.88
16,KEX,18.30,-0.30,-1.61,18.60,18.70,18.20,2231293,40973.52
23,SABUY,13.00,-0.40,-2.99,13.50,13.50,13.00,41170399,542325.59
26,THG,68.00,-3.25,-4.56,71.00,71.75,67.00,11758723,805737.68

In [11]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_CONMAT = pd.read_excel(input_file, header=9)
df_CONMAT = df_CONMAT[df_CONMAT['%Change'] != '-']
df_CONMAT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,CCP,0.45,0.03,7.14,0.42,0.46,0.42,33085588,14771.12
6,GEL,0.32,0.01,3.23,0.31,0.33,0.31,30021266,9602.16
3,DCON,0.44,0.01,2.33,0.44,0.45,0.43,10327040,4537.19
11,SCP,5.20,0.05,0.97,5.15,5.20,5.10,77205,397.09
8,Q-CON,10.60,0.10,0.95,10.50,10.80,10.30,318799,3357.40
...,...,...,...,...,...,...,...,...,...
17,UMI,1.54,-0.01,-0.65,1.56,1.57,1.53,624689,966.04
18,VNG,5.55,-0.05,-0.89,5.60,5.60,5.45,746211,4115.08
7,PPP,2.14,-0.02,-0.93,2.14,2.14,2.10,130010,276.30
16,TPIPL,1.82,-0.02,-1.09,1.84,1.84,1.82,8860867,16172.16
15,TOA,34.25,-0.50,-1.44,34.75,34.75,34.25,308244,10609.07

In [12]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
10,CPTGF,7.70,0.20,2.67,7.55,7.80,7.55,693623,5312.94
53,TNPF,1.84,0.04,2.22,1.86,1.86,1.84,1300,2.39
28,LPF,14.20,0.20,1.43,14,14.30,14,366099,5189.57
24,KTBSTMR,8.85,0.10,1.14,8.75,8.85,8.75,69300,606.66
11,CTARAF,5.35,0.05,0.94,5.35,5.35,5.35,100,0.54
...,...,...,...,...,...,...,...,...,...
51,TIF1,9.10,-0.10,-1.09,9.10,9.10,9.10,1000,9.10
14,FTREIT,11.70,-0.20,-1.68,11.90,11.90,11.70,196402,2314.85
46,SIRIP,8,-0.15,-1.84,8,8,8,300,2.40
31,M-PAT,4.76,-0.10,-2.06,4.46,4.80,4.46,6200,29.22
56,TU-PF,0.91,-0.04,-4.21,0.93,0.94,0.90,24500,22.34

In [13]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
3        B  0.44   0.03    7.32  0.42  0.46  0.41    158162818        69981.95
24    TSTE  7.80   0.40    5.41  7.90  7.90  7.80         2595           20.44
4       BA 14.80   0.30    2.07 14.60 14.90 14.20      9344082       136141.32
13    KIAT  0.50   0.01    2.04  0.50  0.50  0.49      2311200         1153.78
2   ASIMAR  1.85   0.03    1.65  1.82  1.85  1.82       173315          319.28
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
15    MENA  1.93  -0.03   -1.53  1.94  1.98  1.90     12027803        23381.79
5      BEM  9.60  -0.15   -1.54  9.70  9.75  9.55     58793587       565334.31
12     KEX 18.30  -0.30   -1.61 18.60 18.70 18.20      2231293        40973.52
18    PORT  2.10  -0.04   -1.87  2.14  2.16     2       631423         1310.82
26    WICE 11.70  -0.30   -2.50    12 12.10 11.60      6565095        77325.62

[25 rows x 9 columns]

In [14]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
12   INSET  3.78   0.18       5  3.74  3.92  3.64     61098668       231570.55
11    INET  5.65   0.15    2.73  5.50  6.05  5.45      6313330        36021.73
31     TKC 22.70   0.50    2.25 22.20 22.90    22      2985565        67133.51
26     SKY 25.75   0.50    1.98 25.25    26 24.30      7651251       192262.76
15     JAS  2.36   0.04    1.72  2.34  2.36  2.32     13297303        31148.87
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
17   JMART 36.75  -0.50   -1.34 37.25 37.50 36.50      8468235       313643.98
1      AIT  6.60  -0.10   -1.49  6.70  6.70  6.60      1178324         7806.07
22  SAMART  5.60  -0.10   -1.75  5.85  5.85  5.60      9903903        56251.20
18     JTS 42.75     -1   -2.29    43 43.50 41.75      1394282        59402.07
24     SDC  0.20  -0.02   -9.09  0.21  0.22  0.19    276501167        56365.45

[33 rows x 9 columns]

In [15]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_CONMAT, df_PFREIT, df_TRANS, df_ICT])
df.shape

(613, 16)

In [16]:
df.Symbol.nunique()

354

In [17]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(354, 16)

In [18]:
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [19]:
df.columns

Index(['Symbol', 'Trading Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR Volume', 'TR Value (k)', 'Total Volume', 'Total Value (k)',
       'Bid Size', 'Bid', 'Offer', 'Offer Size'],
      dtype='object')

In [20]:
df.head()

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,AAV,-,3.08,-0.02,-0.65,3.10,3.12,3.06,0,0.00,47860704,148095.62,10938600,3.06,3.08,307300
1,ACE,-,2.56,0.00,0.00,2.56,2.58,2.54,0,0.00,23915176,61242.86,4541200,2.54,2.56,456300
2,ADVANC,-,196.50,-0.50,-0.25,197.00,198.00,196.00,0,0.00,3223977,633905.67,581100,196.00,196.50,51200
3,AMATA,-,20.20,0.00,0.00,20.20,20.30,19.90,0,0.00,6175226,124102.27,171800,20.10,20.20,143600
4,AOT,-,73.50,-0.25,-0.34,73.50,74.00,73.25,0,0.00,19882884,1462189.50,5942900,73.50,73.75,439300

In [21]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [22]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.88,0.00,0.00,0.90,0.92,0.86,300735083,269440.61
0,AAV,3.08,-0.02,-0.65,3.10,3.12,3.06,47860704,148095.62
1,ACE,2.56,0.00,0.00,2.56,2.58,2.54,23915176,61242.86
2,ADVANC,196.50,-0.50,-0.25,197.00,198.00,196.00,3223977,633905.67
1,AGE,3.70,-0.02,-0.54,3.72,3.72,3.70,1095242,4058.48
...,...,...,...,...,...,...,...,...,...
140,WICE,11.70,-0.30,-2.50,12.00,12.10,11.60,6565095,77325.62
19,WIIK,1.86,0.00,0.00,1.86,1.90,1.86,1267811,2382.20
141,WORK,18.60,0.00,0.00,18.60,18.80,18.50,584418,10880.59
142,XPG,1.43,0.00,0.00,1.42,1.44,1.42,16048321,22934.86
143,ZEN,18.30,0.70,3.98,17.50,18.40,17.50,1457528,26301.22

In [23]:
df.insert(1, 'Date', today)

In [24]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-07,3.08,-0.02,-0.65,3.10,3.12,3.06,47860704,148095.62
1,ACE,2023-02-07,2.56,0.00,0.00,2.56,2.58,2.54,23915176,61242.86
2,ADVANC,2023-02-07,196.50,-0.50,-0.25,197.00,198.00,196.00,3223977,633905.67
3,AMATA,2023-02-07,20.20,0.00,0.00,20.20,20.30,19.90,6175226,124102.27
4,AOT,2023-02-07,73.50,-0.25,-0.34,73.50,74.00,73.25,19882884,1462189.50
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-07,6.80,-0.05,-0.73,6.95,6.95,6.80,210301,1437.27
24,SDC,2023-02-07,0.20,-0.02,-9.09,0.21,0.22,0.19,276501167,56365.45
27,SVOA,2023-02-07,2.60,0,0,2.60,2.62,2.56,593935,1539.71
28,SYMC,2023-02-07,6,0,0,6,6,5.95,2500,14.95
33,TWZ,2023-02-07,0.07,0,0,0.07,0.08,0.07,4843505,354.47

In [25]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [26]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [27]:
df_out = df[colt]
df_out.shape

(354, 10)

In [28]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(194, 10)

In [29]:
df_merge.columns

Index(['Symbol', 'Date', 'Last', 'Change', '%Change', 'Open', 'High', 'Low',
       'Total-Volume', 'Total-Value-(k)'],
      dtype='object')

In [30]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [31]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'daily_volume',
                         'change':'chg_amt','%change':'chg_pct'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'chg_amt', 'chg_pct', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')

In [32]:
file_name = "Price-Today.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.set_index("name", inplace=True)
df_merge.to_csv(output_file, header=True)
df_merge.to_csv(osd_file, header=True)

In [33]:
df_merge.reset_index(inplace=True)
df_merge

,name,date,price,chg_amt,chg_pct,open,high,low,volume,daily_volume
0,ACE,2023-02-07,2.56,0.00,0.00,2.56,2.58,2.54,23915176,61242.86
1,ADVANC,2023-02-07,196.50,-0.50,-0.25,197.00,198.00,196.00,3223977,633905.67
2,AH,2023-02-07,32.75,-0.25,-0.76,33.00,33.25,32.50,1688685,55467.11
3,AIE,2023-02-07,3.00,0.14,4.90,2.90,3.00,2.88,5198687,15360.20
4,AIMIRT,2023-02-07,12.30,-0.10,-0.81,12.40,12.40,12.30,122600,1508.11
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-07,8,0,0,8.05,8.05,8,846450,6771.95
190,WHART,2023-02-07,11.60,0,0,11.60,11.70,11.60,484312,5621.90
191,WHAUP,2023-02-07,4.12,0.00,0.00,4.12,4.14,4.08,1427266,5862.84
192,WICE,2023-02-07,11.70,-0.30,-2.50,12.00,12.10,11.60,6565095,77325.62
193,WORK,2023-02-07,18.60,0.00,0.00,18.60,18.80,18.50,584418,10880.59

### Must recall whenever there is change in orders

In [ ]:
file_name = "orders.csv"
input_file = data_path + file_name

orders = pd.read_csv(input_file)
orders

In [ ]:
df_merge2 = pd.merge(orders, df_merge, left_on = 'name', right_on = 'symbol', how='inner')
df_merge2

In [ ]:
df_merge2.columns

In [ ]:
df_merge2['spd'] = 0
df_merge2['active'] = 0

In [ ]:
colm = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'current', 'change', 'percent',
        'active', 'xdate']
df_merge2[colm]

In [ ]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge2[colm].to_csv(output_file, header=None, index=False)
df_merge2[colm].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb