In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

data_path = "../data/"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

pd.options.display.max_rows = 11
today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 6), datetime.date(2023, 2, 5))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-06
yesterday: 2023-02-03

In [10]:
file_name = "Price.csv"
input_file = data_path + file_name
input_file

'../data/Price.csv'

In [11]:
colt = 'Symbol Date Last High Low Total-Volume Open'.split()
prices = pd.read_csv(input_file, header=None)
prices.columns = colt
prices

     Symbol        Date    Last    High     Low  Total-Volume    Open
0       ACE  2023-02-03    2.54    2.58    2.54      16419256    2.56
1    ADVANC  2023-02-03  198.50  198.50  197.00       2401870  197.50
2        AH  2023-02-03   32.25   32.75   32.00       1850308   32.75
3       AIE  2023-02-03    2.80    2.86    2.80       1129796    2.84
4    AIMIRT  2023-02-03   12.50   12.50   12.40          7300   12.40
..      ...         ...     ...     ...     ...           ...     ...
188   WHAIR  2023-02-03    8.05    8.05    8.00        449631    8.00
189   WHART  2023-02-03   11.80   11.80   11.60        932206   11.80
190   WHAUP  2023-02-03    4.12    4.20    4.06      11632453    4.10
191    WICE  2023-02-03   11.90   12.00   11.70       4764194   11.70
192    WORK  2023-02-03   18.30   18.40   18.30        355565   18.40

[193 rows x 7 columns]

In [12]:
prices.columns = prices.columns.str.lower()
prices.columns

Index(['symbol', 'date', 'last', 'high', 'low', 'total-volume', 'open'], dtype='object')

In [13]:
file_name = "orders.csv"
input_file = data_path + file_name
input_file

'../data/orders.csv'

In [14]:
orders = pd.read_csv(input_file)
orders

   trade    name    qty  price  active reason  market       xdate
0      B   BANPU   6000  10.80       0    DTD   SET50  2023-04-08
1      B      CK   4500  22.50       0   5pct  SET100  2022-12-22
2      B     CKP  20000   4.50       0     3L  SET100  2022-12-22
3      B    COM7   3000  30.00       0    XXX   SET50  2022-12-22
4      B     CPF   4000  23.00       0    XXX   SET50  2022-12-22
..   ...     ...    ...    ...     ...    ...     ...         ...
16     S     ORI  15000  12.50       0   CP1S  SET100  2023-05-09
17     S  SINGER   1200  29.25       0    DTD  SET100  2023-04-29
18     S     STA   2500  23.00       0    CUT  SET100  2023-04-19
19     S     TMT  12000   8.70       0   C9.0     SET  2023-04-18
20     S   WHAIR  10000   8.90       0     HD     SET  2023-03-04

[21 rows x 8 columns]

In [ ]:
df = pd.merge(orders, prices, left_on='name', right_on='symbol', how='inner')
df.columns

In [ ]:
df