In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

data_path = "../data/"
dts_path = "/Users/User/Downloads/Datasets/"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 6), datetime.date(2023, 2, 5))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-06
yesterday: 2023-02-03

In [3]:
# Function to classify a file
def classify_file(filename):
    # Find the file extension
    extension = filename.split('.')[-1]

    # Iterate over the categories
    for category, extensions in categories.items():
        # If the extension matches one of the extensions in the category, move the file
        if extension in extensions:
            # Construct the file paths
            source_path = os.path.join(directory, filename)
            dest_path = os.path.join(directory, category, filename)

            # Move the file
            os.rename(source_path, dest_path)
            print(f'Moved {filename} to {category}')
            break

### Delete files in folder Datasets, if there is no file, error causes program to stop

In [ ]:
#for filename in glob.glob(os.path.join(dts_path, '*.xlsx')):
    print(f'Delete {filename}')
    os.remove(filename)

### SET100, sSET, SETCLMV, SETHD, SETTHSI, SETWB, CONMAT, PFREIT, TRANS, ICT

In [4]:
# Classify all existing files in the directory
for filename in os.listdir(directory):
    classify_file(filename)

In [5]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [6]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
18,BLA,30.25,1.25,4.31,29.00,30.50,29.00,7770895,233390.57
76,SABUY,13.40,0.50,3.88,13.00,13.60,12.90,37566486,501764.91
91,TIPH,51.75,1.50,2.99,50.25,52.00,50.25,2947676,150942.53
22,CENTEL,54.00,1.25,2.37,52.75,54.25,52.75,3567775,192049.53
94,TQM,43.25,1.00,2.37,42.00,43.75,42.00,2846944,123005.43
...,...,...,...,...,...,...,...,...,...
43,HANA,63.25,-1.50,-2.32,63.75,64.50,62.75,9503122,601935.88
29,CPN,73.00,-1.75,-2.34,74.00,74.50,73.00,8059800,591859.11
64,ORI,11.70,-0.30,-2.50,11.90,12.00,11.70,5653682,66735.87
52,KCE,56.50,-1.50,-2.59,57.75,57.75,56.25,25252398,1437812.52
38,FORTH,42.50,-1.50,-3.41,43.50,44.50,42.50,4526416,196245.98

In [7]:
file_name = "StockQuotation (1).xlsx"
input_file = dts_path + file_name
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['%Change'] != '-']
df_sSET[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,7UP,0.88,0.10,12.82,0.79,0.88,0.79,235938856,200949.93
44,ITEL,4.14,0.38,10.11,3.78,4.14,3.78,42053601,168901.06
102,SKY,25.25,2.25,9.78,23.80,25.50,23.70,18592433,458837.39
65,NCAP,5.00,0.28,5.93,4.72,5.05,4.70,47235939,232019.01
49,KISS,9.70,0.50,5.43,9.45,9.75,9.40,14409361,138444.31
...,...,...,...,...,...,...,...,...,...
38,HUMAN,12.40,-0.30,-2.36,12.60,12.60,12.30,3292081,40844.34
128,TSTH,1.16,-0.03,-2.52,1.19,1.20,1.16,6238233,7332.28
20,BRI,11.00,-0.30,-2.65,11.30,11.30,11.00,3178009,35131.79
85,ROJNA,6.35,-0.20,-3.05,6.50,6.55,6.30,1597604,10226.06
82,RABBIT,1.15,-0.05,-4.17,1.20,1.20,1.15,44674327,52065.48

In [8]:
file_name = "StockQuotation (2).xlsx"
input_file = dts_path + file_name
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['%Change'] != '-']
df_CLMV[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
12,BPP,17.00,0.30,1.80,16.70,17.00,16.70,1047519,17672.73
51,TASCO,18.30,0.20,1.10,18.10,18.60,18.10,16869357,310078.55
32,MEGA,51.75,0.50,0.98,51.50,52.00,51.50,1434420,74271.16
56,VNG,5.60,0.05,0.90,5.55,5.60,5.50,308500,1711.32
15,CKP,4.60,0.04,0.88,4.56,4.64,4.56,11507495,53010.60
...,...,...,...,...,...,...,...,...,...
50,SUPER,0.63,-0.01,-1.56,0.64,0.65,0.62,204432056,129669.67
2,BANPU,11.30,-0.20,-1.74,11.40,11.50,11.10,114777951,1292537.33
9,BGRIM,39.75,-0.75,-1.85,40.75,41.00,39.75,8623711,345260.53
27,JWD,20.90,-0.50,-2.34,21.50,21.50,20.80,6056006,127030.10
54,TSTH,1.16,-0.03,-2.52,1.19,1.20,1.16,6238233,7332.28

In [9]:
file_name = "StockQuotation (3).xlsx"
input_file = dts_path + file_name
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['%Change'] != '-']
df_HD[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
26,TISCO,103.00,1.50,1.48,102.00,103.00,101.50,2923152,299707.75
28,TU,16.20,0.10,0.62,16.10,16.50,16.10,28202894,459537.00
12,KKP,68.50,0.25,0.37,68.00,68.75,67.75,3697072,252529.80
4,BCPG,10.00,0.00,0.00,10.00,10.10,9.95,1165696,11647.94
6,CHG,3.92,0.00,0.00,3.92,3.96,3.90,18490731,72527.30
...,...,...,...,...,...,...,...,...,...
29,WHA,3.92,-0.06,-1.51,3.96,4.00,3.88,81536396,319028.86
1,AP,11.80,-0.20,-1.67,12.00,12.00,11.70,19288906,226963.07
21,SAWAD,56.50,-1.25,-2.16,57.25,57.50,56.25,9233350,525638.93
10,HANA,63.25,-1.50,-2.32,63.75,64.50,62.75,9503122,601935.88
15,ORI,11.70,-0.30,-2.50,11.90,12.00,11.70,5653682,66735.87

In [10]:
file_name = "StockQuotation (4).xlsx"
input_file = dts_path + file_name
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['%Change'] != '-']
df_THSI[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
54,ITEL,4.14,0.38,10.11,3.78,4.14,3.78,42053601,168901.06
86,SAPPE,49.50,2.50,5.32,47.25,49.75,47.00,1834291,88700.08
23,BLA,30.25,1.25,4.31,29.00,30.50,29.00,7770895,233390.57
100,SYNEX,17.10,0.50,3.01,16.60,17.20,16.60,4141281,70448.50
27,CENTEL,54.00,1.25,2.37,52.75,54.25,52.75,3567775,192049.53
...,...,...,...,...,...,...,...,...,...
56,JWD,20.90,-0.50,-2.34,21.50,21.50,20.80,6056006,127030.10
32,CPN,73.00,-1.75,-2.34,74.00,74.50,73.00,8059800,591859.11
70,ORI,11.70,-0.30,-2.50,11.90,12.00,11.70,5653682,66735.87
111,TSTH,1.16,-0.03,-2.52,1.19,1.20,1.16,6238233,7332.28
95,SIRI,1.86,-0.07,-3.63,1.93,1.93,1.86,298114411,562433.12

In [11]:
file_name = "StockQuotation (5).xlsx"
input_file = dts_path + file_name
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['%Change'] != '-']
df_WB[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
23,SABUY,13.40,0.50,3.88,13.00,13.60,12.90,37566486,501764.91
29,VIBHA,2.74,0.04,1.48,2.70,2.74,2.70,1500646,4095.99
25,STA,22.60,0.30,1.35,22.30,22.80,22.30,4749739,107119.68
26,THG,71.25,0.75,1.06,70.50,72.00,70.25,3855811,274723.01
18,MEGA,51.75,0.50,0.98,51.50,52.00,51.50,1434420,74271.16
...,...,...,...,...,...,...,...,...,...
4,BJC,38.00,-0.50,-1.30,38.00,38.50,37.75,2973485,113215.35
14,HMPRO,14.70,-0.20,-1.34,14.90,14.90,14.70,10641287,157187.72
12,DOHOME,14.00,-0.20,-1.41,14.20,14.20,13.90,6214621,87188.57
21,RBF,12.80,-0.20,-1.54,13.00,13.10,12.70,1461907,18825.76
15,JWD,20.90,-0.50,-2.34,21.50,21.50,20.80,6056006,127030.10

In [12]:
file_name = "StockQuotation (6).xlsx"
input_file = dts_path + file_name
df_CONMAT = pd.read_excel(input_file, header=9)
df_CONMAT = df_CONMAT[df_CONMAT['%Change'] != '-']
df_CONMAT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
5,EPG,8.70,0.10,1.16,8.70,8.75,8.60,2244502,19509.68
14,TASCO,18.30,0.20,1.10,18.10,18.60,18.10,16869357,310078.55
19,WIIK,1.86,0.02,1.09,1.84,1.86,1.84,151100,278.89
11,SCP,5.15,0.05,0.98,5.15,5.15,5.05,132744,681.09
13,STECH,2.12,0.02,0.95,2.10,2.12,2.08,201300,422.46
...,...,...,...,...,...,...,...,...,...
17,UMI,1.55,-0.01,-0.64,1.56,1.56,1.55,146425,227.44
2,DCC,2.84,-0.02,-0.70,2.88,2.88,2.84,3754886,10735.15
3,DCON,0.43,-0.01,-2.27,0.44,0.45,0.43,4594620,2017.26
0,CCP,0.42,-0.01,-2.33,0.43,0.43,0.42,3530636,1489.55
8,Q-CON,10.50,-0.30,-2.78,10.80,10.80,10.50,314131,3330.25

In [13]:
file_name = "StockQuotation (7).xlsx"
input_file = dts_path + file_name
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['%Change'] != '-']
df_PFREIT[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
31,M-PAT,4.86,0.48,10.96,4.38,5.30,4.38,4800,22.92
0,AIMCG,5.45,0.10,1.87,5.35,5.50,5.35,1137623,6204.42
45,SHREIT,3.40,0.06,1.80,3.36,3.40,3.36,75300,255.82
14,FTREIT,11.90,0.20,1.71,11.80,12,11.80,1790344,21171.79
51,TIF1,9.20,0.15,1.66,9.15,9.20,9.15,701,6.42
...,...,...,...,...,...,...,...,...,...
2,ALLY,7.40,-0.10,-1.33,7.50,7.55,7.40,396223,2953.40
28,LPF,14,-0.20,-1.41,14.30,14.30,14,1216010,17263.54
24,KTBSTMR,8.75,-0.15,-1.69,8.85,8.85,8.75,105900,932.38
60,WHART,11.60,-0.20,-1.69,11.80,11.90,11.60,1023205,12006.11
9,CPNREIT,18.70,-0.40,-2.09,19,19,18.40,5835205,108984.06

In [14]:
file_name = "StockQuotation (8).xlsx"
input_file = dts_path + file_name
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['%Change'] != '-']
df_TRANS[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
15    MENA  1.96   0.05    2.62  1.90  1.98  1.90      9688722        18878.53
3        B  0.41   0.01    2.50  0.40  0.42  0.40     13057014         5341.12
10     III 14.90   0.20    1.36 14.80    15 14.60      2204332        32687.77
0      AAV  3.10   0.04    1.31  3.08  3.10  3.06     24126162        74490.50
6   BIOTEC  0.95   0.01    1.06  0.94  0.97  0.93     20176773        19118.66
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
7      BTS  8.30  -0.10   -1.19  8.40  8.45  8.30     19684221       164399.51
20     PSL 16.20  -0.20   -1.22 16.30 16.40 16.20      3185491        51846.39
17     NYT  3.52  -0.06   -1.68  3.60  3.60  3.52      2861646        10167.73
13    KIAT  0.49  -0.01      -2  0.51  0.51  0.49      1616001          802.62
11     JWD 20.90  -0.50   -2.34 21.50 21.50 20.80      6056006       127030.10

[24 rows x 9 columns]

In [15]:
file_name = "StockQuotation (9).xlsx"
input_file = dts_path + file_name
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['%Change'] != '-']
df_ICT[colu].sort_values(['%Change'],ascending=[False])

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
24     SDC  0.22   0.04   22.22  0.18  0.23  0.17    921401101       188004.72
14    ITEL  4.14   0.38   10.11  3.78  4.14  3.78     42053601       168901.06
26     SKY 25.25   2.25    9.78 23.80 25.50 23.70     18592433       458837.39
12   INSET  3.60   0.18    5.26  3.44  3.60  3.44     23822378        84379.48
10   ILINK  7.80   0.35    4.70  7.50  7.80  7.40      6227864        47654.92
..     ...   ...    ...     ...   ...   ...   ...          ...             ...
13  INTUCH 72.75     -1   -1.36 73.25 73.75 72.75      2075428       151501.27
2      ALT  2.24  -0.04   -1.75  2.28  2.28  2.24       801800         1809.30
9    HUMAN 12.40  -0.30   -2.36 12.60 12.60 12.30      3292081        40844.34
8    FORTH 42.50  -1.50   -3.41 43.50 44.50 42.50      4526416       196245.98
18     JTS 43.75  -3.50   -7.41    46 46.25 43.75      2830073       127300.71

[33 rows x 9 columns]

In [16]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_CONMAT, df_PFREIT, df_TRANS, df_ICT])
df.shape

(613, 16)

In [17]:
df.Symbol.nunique()

354

In [18]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(354, 16)

In [19]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [20]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[cols].sort_values('Symbol',ascending=True)

,Symbol,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,7UP,0.88,0.10,12.82,0.79,0.88,0.79,235938856,200949.93
0,AAV,3.10,0.04,1.31,3.08,3.10,3.06,24126162,74490.50
1,ACE,2.56,0.02,0.79,2.54,2.58,2.54,23240505,59621.46
2,ADVANC,197.00,-1.50,-0.76,198.50,198.50,197.00,2112826,417546.10
1,AGE,3.72,0.04,1.09,3.70,3.74,3.70,1392257,5165.50
...,...,...,...,...,...,...,...,...,...
140,WICE,12.00,0.10,0.84,11.90,12.00,11.80,1738509,20718.31
19,WIIK,1.86,0.02,1.09,1.84,1.86,1.84,151100,278.89
141,WORK,18.60,0.30,1.64,18.30,18.70,18.30,1189665,22083.55
142,XPG,1.43,-0.01,-0.69,1.44,1.45,1.43,8979406,12861.23
143,ZEN,17.60,-0.40,-2.22,18.10,18.10,17.50,458001,8069.79

In [21]:
df.insert(1, 'Date', today)

In [22]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2023-02-06,3.10,0.04,1.31,3.08,3.10,3.06,24126162,74490.50
1,ACE,2023-02-06,2.56,0.02,0.79,2.54,2.58,2.54,23240505,59621.46
2,ADVANC,2023-02-06,197.00,-1.50,-0.76,198.50,198.50,197.00,2112826,417546.10
3,AMATA,2023-02-06,20.20,-0.20,-0.98,20.50,20.50,20.20,6002476,121928.89
4,AOT,2023-02-06,73.75,0.00,0.00,74.00,74.25,73.75,9965758,736602.00
...,...,...,...,...,...,...,...,...,...,...
23,SAMTEL,2023-02-06,6.85,0,0,6.90,6.95,6.70,901802,6181.18
24,SDC,2023-02-06,0.22,0.04,22.22,0.18,0.23,0.17,921401101,188004.72
27,SVOA,2023-02-06,2.60,0,0,2.62,2.62,2.60,605772,1575.87
28,SYMC,2023-02-06,6,0,0,5.90,6,5.90,40300,239.75
33,TWZ,2023-02-06,0.07,0,0,0.07,0.08,0.07,10015377,732.14

In [23]:
file_name = "name-ttl.csv"
input_file = data_path + file_name
input_file

'../data/name-ttl.csv'

In [24]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(234, 1)

In [25]:
df_out = df[colt]
df_out.shape

(354, 10)

In [26]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(194, 10)

In [27]:
df_merge.columns

Index(['Symbol', 'Date', 'Last', 'Change', '%Change', 'Open', 'High', 'Low',
       'Total-Volume', 'Total-Value-(k)'],
      dtype='object')

In [28]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [29]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'daily_volume',
                         'change':'chg_amt','%change':'chg_pct'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'chg_amt', 'chg_pct', 'open', 'high', 'low',
       'volume', 'daily_volume'],
      dtype='object')

In [32]:
file_name = "dailies.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge.set_index("name", inplace=True)
df_merge.to_csv(output_file, header=True)
df_merge.to_csv(osd_file, header=True)

In [33]:
df_merge.reset_index(inplace=True)
df_merge

,name,date,price,chg_amt,chg_pct,open,high,low,volume,daily_volume
0,ACE,2023-02-06,2.56,0.02,0.79,2.54,2.58,2.54,23240505,59621.46
1,ADVANC,2023-02-06,197.00,-1.50,-0.76,198.50,198.50,197.00,2112826,417546.10
2,AH,2023-02-06,33.00,0.75,2.33,32.50,33.25,32.25,1062782,34888.71
3,AIE,2023-02-06,2.86,0.06,2.14,2.82,2.92,2.80,3969716,11419.99
4,AIMIRT,2023-02-06,12.40,-0.10,-0.80,12.40,12.40,12.30,100700,1242.40
...,...,...,...,...,...,...,...,...,...,...
189,WHAIR,2023-02-06,8,-0.05,-0.62,8.05,8.10,8,461968,3709.31
190,WHART,2023-02-06,11.60,-0.20,-1.69,11.80,11.90,11.60,1023205,12006.11
191,WHAUP,2023-02-06,4.12,0.00,0.00,4.14,4.14,4.10,2544057,10475.60
192,WICE,2023-02-06,12.00,0.10,0.84,11.90,12.00,11.80,1738509,20718.31
193,WORK,2023-02-06,18.60,0.30,1.64,18.30,18.70,18.30,1189665,22083.55