In [1]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/Datasets/"

# Directory to be monitored
directory = '/Users/User/Downloads'
# Dictionary of file categories and their extensions
categories = {
    'Images': ['jpeg', 'jpg', 'png'],
    'PDFs': ['pdf'],
    'Datasets': ['csv', 'xlsx', 'xls', 'json'],
    'Videos': ['mp4','m4a'],
    'Zips': ['zip'],
    'EXEs': ['exe', 'msi'],
    'Pythons': ['ipynb'],
}
pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 9), datetime.date(2023, 2, 8))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-02-09
yesterday: 2023-02-08

## Must recall whenever there is change in orders

In [3]:
sql = """
SELECT trade, name, qty, price, active, reason, market, xdate 
FROM orders
ORDER BY trade, name"""
orders = pd.read_sql(sql, conlite)
orders

   trade    name    qty  price  active reason  market       xdate
0      B   BANPU   6000  10.80       1    DTD   SET50  2023-04-08
1      B      CK   4500  22.50       1   5pct  SET100  2022-12-22
2      B     CKP  20000   4.50       1     3L  SET100  2022-12-22
3      B    COM7   3000  30.00       1    XXX   SET50  2022-12-22
4      B     CPF   4000  23.00       1    XXX   SET50  2022-12-22
..   ...     ...    ...    ...     ...    ...     ...         ...
16     S     ORI  15000  12.50       1   CP1S  SET100  2023-05-09
17     S  SINGER   1200  29.25       1    DTD  SET100  2023-04-29
18     S     STA   2500  24.50       1    CUT  SET100  2023-04-19
19     S     TMT  12000   8.70       1   C9.0     SET  2023-04-18
20     S   WHAIR  10000   8.90       1     HD     SET  2023-03-04

[21 rows x 8 columns]

In [4]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,daily_volume
0,ACE,2023-02-09,2.52,-0.02,-0.79,2.54,2.56,2.50,21359616,53832.43
1,ADVANC,2023-02-09,200.00,4.50,2.30,195.00,201.00,194.00,9499359,1875536.81
2,AH,2023-02-09,32.00,0.25,0.79,31.75,32.50,31.25,1343830,42789.46
3,AIE,2023-02-09,3.04,0.02,0.66,3.00,3.12,2.96,11831282,35995.25
4,AIMIRT,2023-02-09,12.20,-0.10,-0.81,12.30,12.30,12.20,48200,592.29
...,...,...,...,...,...,...,...,...,...,...
178,WHAIR,2023-02-09,7.90,-0.10,-1.25,7.95,7.95,7.90,256846,2033.16
179,WHART,2023-02-09,11.50,-0.20,-1.71,11.70,11.70,11.50,880226,10210.12
180,WHAUP,2023-02-09,4.10,0.02,0.49,4.08,4.10,4.06,566061,2306.40
181,WICE,2023-02-09,11.50,0.10,0.88,11.40,11.50,11.10,4108733,46286.35
182,WORK,2023-02-09,18.40,0.00,0.00,18.50,18.50,18.30,132105,2422.31

In [5]:
df_merge  = pd.merge(orders, prices, on = 'name', how='inner')
df_merge

,trade,name,qty,price_x,active,reason,market,xdate,date,price_y,change,%change,open,high,low,volume,daily_volume
0,B,BANPU,6000,10.80,1,DTD,SET50,2023-04-08,2023-02-09,11.00,0.00,0.00,11.00,11.10,10.70,81260419,882253.97
1,B,CK,4500,22.50,1,5pct,SET100,2022-12-22,2023-02-09,22.50,0.10,0.45,22.50,22.50,22.20,3387404,75799.76
2,B,CKP,20000,4.50,1,3L,SET100,2022-12-22,2023-02-09,4.66,0.00,0.00,4.70,4.70,4.60,11995586,55912.43
3,B,COM7,3000,30.00,1,XXX,SET50,2022-12-22,2023-02-09,31.25,-0.25,-0.79,31.25,31.50,30.50,11318804,349776.51
4,B,CPF,4000,23.00,1,XXX,SET50,2022-12-22,2023-02-09,23.20,-0.10,-0.43,23.30,23.40,23.10,24249406,562702.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,S,ORI,15000,12.50,1,CP1S,SET100,2023-05-09,2023-02-09,11.80,0.10,0.85,11.80,11.80,11.50,4940270,57488.41
17,S,SINGER,1200,29.25,1,DTD,SET100,2023-04-29,2023-02-09,27.50,0.50,1.85,27.25,27.50,26.25,4638934,124211.19
18,S,STA,2500,24.50,1,CUT,SET100,2023-04-19,2023-02-09,24.10,-0.40,-1.63,24.50,24.50,23.90,9154222,221065.04
19,S,TMT,12000,8.70,1,C9.0,SET,2023-04-18,2023-02-09,8.10,0.00,0.00,8.10,8.10,8.00,267821,2164.29
20,S,WHAIR,10000,8.90,1,HD,SET,2023-03-04,2023-02-09,7.90,-0.10,-1.25,7.95,7.95,7.90,256846,2033.16

In [6]:
df_merge['spd'] = 0

In [7]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'price_x', 'price_y', 'change', '%change',
        'active', 'xdate']
df_merge[colo]

,trade,name,spd,reason,market,qty,price_x,price_y,change,%change,active,xdate
0,B,BANPU,0,DTD,SET50,6000,10.80,11.00,0.00,0.00,1,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.50,22.50,0.10,0.45,1,2022-12-22
2,B,CKP,0,3L,SET100,20000,4.50,4.66,0.00,0.00,1,2022-12-22
3,B,COM7,0,XXX,SET50,3000,30.00,31.25,-0.25,-0.79,1,2022-12-22
4,B,CPF,0,XXX,SET50,4000,23.00,23.20,-0.10,-0.43,1,2022-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...
16,S,ORI,0,CP1S,SET100,15000,12.50,11.80,0.10,0.85,1,2023-05-09
17,S,SINGER,0,DTD,SET100,1200,29.25,27.50,0.50,1.85,1,2023-04-29
18,S,STA,0,CUT,SET100,2500,24.50,24.10,-0.40,-1.63,1,2023-04-19
19,S,TMT,0,C9.0,SET,12000,8.70,8.10,0.00,0.00,1,2023-04-18
20,S,WHAIR,0,HD,SET,10000,8.90,7.90,-0.10,-1.25,1,2023-03-04

In [8]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colo].to_csv(output_file, header=True, index=False)
df_merge[colo].to_csv(osd_file, header=True, index=False)

### call ruby ruby\order-log-new.rb

In [9]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [10]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [11]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
B,BANPU,-2,DTD,SET50,6000,10.8,11.0,0.0,0.0,1,2023-04-08
B,CK,0,5pct,SET100,4500,22.5,22.5,0.1,0.4464285714285714,1,2022-12-22
B,CKP,-8,3L,SET100,20000,4.5,4.66,0.0,0.0,1,2022-12-22
B,COM7,-5,XXX,SET50,3000,30.0,31.25,-0.25,-0.7936507936507936,1,2022-12-22
B,CPF,-2,XXX,SET50,4000,23.0,23.2,-0.1,-0.4291845493562232,1,2022-12-22
B,CPNREIT,-6,RD05pct,PF&REIT,10000,17.9,18.5,0.1,0.5434782608695652,1,2022-02-02
B,KCE,-6,CUT,SET100,1000,47.0,48.5,-2.0,-3.96039603960396,1,2023-03-21
B,MEGA,-16,5pct,SET100,2000,48.0,52.0,1.25,2.4630541871921183,0,2023-03-08
B,PTT,-3,XXX,SET50,3600,32.0,32.75,0.0,0.0,1,2023-03-03
B,RCL,-8,HD,SET100,3000,28.75,30.75,0.25,0.819672131147541,1,2023-03-23
B,TTB,0,52WL,SET50,90000,1.4,1.4,-0.01,-0.7092198581560284,1,2022-12-22
S,DIF,4,CUT,SET,10000,14.0,13.6,-0.1,-0.7299270072992701,1,2023-02-10
S,IVL,13,DTD,SET50,2400,44.25,41.0,0.25,0.6134969325153374,0,2023-05-06
S,JASIF,6,CP1S,SET,10000,8.5,8.2,-0.05,-0.6060606060606061,1,2023-03-03
S,JMART,24,DTD,SET50,3600,41.5,35.5,0.0,0.0,0,2023-04-19
S,JMT,31,DTD,SET50,1500,60.0,52.25,1.5,2.955665024630542,0,2023-04-19
S,ORI,7,CP1S,SET100,15000,12.5,11.8,0.1,0.8547008547008547,1,2023-05-09
S,SINGER,7,DTD,SET100,1200,29.25,27.5,0.5,1.851851851851852,1,2023-04-29
S,STA,4,CUT,SET100,2500,24.5,24.1,-0.4,-1.6326530612244898,1,2023-04-19
S,TMT,12,C9.0,SET,12000,8.7,8.1,0.0,0.0,0,2023-04-18
S,WHAIR,20,HD,SET,10000,8.9,7.9,-0.1,-1.25,0,2023-03-04

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [13]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.query('spd >= -3 and spd <= 3')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
0,B,BANPU,-2,DTD,SET50,6000,10.80,11.00,0.00,0.00,1,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.50,22.50,0.10,0.45,1,2022-12-22
4,B,CPF,-2,XXX,SET50,4000,23.00,23.20,-0.10,-0.43,1,2022-12-22
8,B,PTT,-3,XXX,SET50,3600,32.00,32.75,0.00,0.00,1,2023-03-03
10,B,TTB,0,52WL,SET50,90000,1.40,1.40,-0.01,-0.71,1,2022-12-22

In [14]:
df.query('active == 1')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
0,B,BANPU,-2,DTD,SET50,6000,10.80,11.00,0.00,0.00,1,2023-04-08
1,B,CK,0,5pct,SET100,4500,22.50,22.50,0.10,0.45,1,2022-12-22
2,B,CKP,-8,3L,SET100,20000,4.50,4.66,0.00,0.00,1,2022-12-22
3,B,COM7,-5,XXX,SET50,3000,30.00,31.25,-0.25,-0.79,1,2022-12-22
4,B,CPF,-2,XXX,SET50,4000,23.00,23.20,-0.10,-0.43,1,2022-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...
11,S,DIF,4,CUT,SET,10000,14.00,13.60,-0.10,-0.73,1,2023-02-10
13,S,JASIF,6,CP1S,SET,10000,8.50,8.20,-0.05,-0.61,1,2023-03-03
16,S,ORI,7,CP1S,SET100,15000,12.50,11.80,0.10,0.85,1,2023-05-09
17,S,SINGER,7,DTD,SET100,1200,29.25,27.50,0.50,1.85,1,2023-04-29
18,S,STA,4,CUT,SET100,2500,24.50,24.10,-0.40,-1.63,1,2023-04-19

In [15]:
df.query('active == 0')

,trade,name,spd,reason,market,qty,target,current,change,percent,active,xdate
7,B,MEGA,-16,5pct,SET100,2000,48.00,52.00,1.25,2.46,0,2023-03-08
12,S,IVL,13,DTD,SET50,2400,44.25,41.00,0.25,0.61,0,2023-05-06
14,S,JMART,24,DTD,SET50,3600,41.50,35.50,0.00,0.00,0,2023-04-19
15,S,JMT,31,DTD,SET50,1500,60.00,52.25,1.50,2.96,0,2023-04-19
19,S,TMT,12,C9.0,SET,12000,8.70,8.10,0.00,0.00,0,2023-04-18
20,S,WHAIR,20,HD,SET,10000,8.90,7.90,-0.10,-1.25,0,2023-03-04