In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 15), datetime.date(2023, 1, 14))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-15
yesterday: 2023-01-13 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 1, 13), datetime.date(2022, 1, 13))

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}',
    'max_price':'{:.2f}','min_price':'{:.2f}',
    'pct':'{:,.2f}%',  
}

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
df = pd.read_sql(sql, const)

names = df['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
#one_qtr_ago = yesterday - timedelta(days=4)
one_qtr_ago = date(2022, 12, 16)

sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_qtr_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-16' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

In [7]:
df = pd.read_sql(sql, const)
df.sample(5)

       name        date  price       qty   maxp   minp
382     STA  2022-12-20  18.50   4526699  19.10  18.40
131  GVREIT  2023-01-03   9.15    174743   9.15   9.05
119     DIF  2023-01-13  13.50   9868681  13.50  13.30
116     DIF  2023-01-10  13.30   5999052  13.30  13.20
28    BANPU  2022-12-28  13.70  58996837  13.70  13.40

In [8]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name

df.set_index("name", inplace=True)
df.to_csv(output_file, header=None)

### After call ruby ruby\chat-fin.rb

In [9]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [10]:
df['from_date'] = pd.to_datetime(df['from_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_m_d'] = df['from_date'].dt.strftime('%m-%d')
df['to_m_d'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [11]:
df.groupby("trend").nunique()

,name,from_date,to_date,days,from_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_m_d,to_m_d
trend,,,,,,,,,,,,,,,,
Downward,25,20,20,5,76,76,16,30,10,5,74,74,96,96,20,20
Upward,25,20,20,12,77,74,25,47,14,6,81,75,100,100,20,20

In [12]:
cols = 'name fm_m_d to_m_d days from_price to_price pct spd avg max_price min_price ttl_qty trend'.split()
mask = df.name == 'ASP'
df[mask][cols].style.format(format_dict)

In [13]:
cols = 'name fm_m_d to_m_d days from_price to_price pct spd avg max_price min_price ttl_qty trend'.split()
yesterday = '2023-01-13'
pct = 3.00
df.query('to_date == @yesterday and pct >= @pct')[cols].style.format(format_dict)

In [14]:
pct = -0.01
df.query('to_date == @yesterday and pct <= @pct')[cols].style.format(format_dict)

In [15]:
# It returns a DataFrameGroupBy object
df_groupby_trend = df.groupby('trend')
type(df_groupby_trend)

pandas.core.groupby.generic.DataFrameGroupBy

In [16]:
# To get the number of groups
df_groupby_trend.ngroups

2

In [17]:
# Stat of each group
df_groupby_trend.size()

trend
Downward     96
Upward      100
dtype: int64

In [18]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [19]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [20]:
df.groupby('trend').days.max()

trend
Downward     4
Upward      11
Name: days, dtype: int64

In [21]:
df[df['days'] == 11][cols].style.format(format_dict)

In [22]:
df.query('days == 4 and trend == "Downward"')[cols].style.format(format_dict)

In [28]:
df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

       name     trend      days
0       ASP  Downward  2.000000
1       ASP    Upward  5.500000
2     BANPU  Downward  0.666667
3     BANPU    Upward  0.428571
4       BCH  Downward  0.250000
5       BCH    Upward  1.600000
6   CPNREIT  Downward  1.000000
7   CPNREIT    Upward  2.500000
8       DCC  Downward  0.000000
9       DCC    Upward  3.000000
10      DIF  Downward  0.333333
11      DIF    Upward  4.666667
12   GVREIT  Downward  2.000000
13   GVREIT    Upward  2.666667
14      IVL  Downward  2.000000
15      IVL    Upward  4.000000
16    JASIF  Downward  0.500000
17    JASIF    Upward  2.750000
18      KCE  Downward  0.571429
19      KCE    Upward  0.500000
20    MAKRO  Downward  0.750000
21    MAKRO    Upward  2.500000
22      MCS  Downward  1.000000
23      MCS    Upward  2.750000
24      NER  Downward  1.000000
25      NER    Upward  1.600000
26      ORI  Downward  1.000000
27      ORI    Upward  1.200000
28    PTTGC  Downward  2.000000
29    PTTGC    Upward  1.250000
30      RCL  Downward  0.500000
31      RCL    Upward  1.750000
32      SCC  Downward  1.000000
33      SCC    Upward  3.333333
34     SCCC  Downward  0.666667
35     SCCC    Upward  6.000000
36     SENA  Downward  2.333333
37     SENA    Upward  2.333333
38      STA  Downward  2.000000
39      STA    Upward  3.000000
40    SYNEX  Downward  0.500000
41    SYNEX    Upward  0.833333
42    TFFIF  Downward  1.000000
43    TFFIF    Upward  1.250000
44      TMT  Downward  2.000000
45      TMT    Upward  2.500000
46    WHAIR  Downward  2.333333
47    WHAIR    Upward  1.750000
48    WHART  Downward  0.250000
49    WHART    Upward  2.200000

In [30]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    4     96     0.0  0.979167
Upward     11    100     1.0  2.110000