#### Restart and Run All

In [1]:
import numpy as np
import pandas as pd
import datetime as dt
from datetime import date, timedelta
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

format_dict = {
    'daily_volume':'{:,}', 'price':'{:.2f}', 'chg_amt':'{:.2f}', 'chg_pct':'{:.2f}'
}

today = date.today()
today

datetime.date(2023, 1, 24)

In [2]:
df_dailies = pd.read_csv('../data/dailies.csv',usecols=['name','price','chg_amt','chg_pct','daily_volume'])
df_dailies.query("daily_volume == '-'")

Empty DataFrame
Columns: [name, price, daily_volume, chg_amt, chg_pct]
Index: []

In [3]:
df_dailies.loc[(df_dailies.daily_volume == '-') ,'daily_volume'] = 0

df_dailies['daily_volume'] = df_dailies['daily_volume'].astype(float)
df_dailies['daily_volume'] = round(df_dailies['daily_volume'] / 1000,0)
df_dailies['daily_volume'] = df_dailies['daily_volume'].astype(int)
df_dailies.dtypes

name             object
price           float64
daily_volume      int32
chg_amt         float64
chg_pct         float64
dtype: object

In [4]:
df_dailies.query("name == 'DELTA'")

     name  price  daily_volume  chg_amt  chg_pct
57  DELTA  884.0          4283     -6.0    -0.67

In [5]:
df_dailies.sort_values(['chg_pct'],ascending=[False]).head(10)

       name  price  daily_volume  chg_amt  chg_pct
71   FSMART  16.20           500     2.00    14.08
69    FORTH  39.00           588     4.25    12.23
231    WICE  11.80           162     0.60     5.36
220     TVI  12.80            26     0.50     4.07
171     SIS  28.50            21     1.00     3.64
204     TMT   8.45            12     0.25     3.05
123      MC  11.60             8     0.30     2.65
80   GVREIT   9.75             8     0.25     2.63
126    MINT  33.25          1515     0.75     2.31
42   CENTEL  51.75           153     1.00     1.97

In [6]:
df_dailies.sort_values(['chg_pct'],ascending=[True]).head(10)

        name  price  daily_volume  chg_amt  chg_pct
145      PTG  13.80           742    -0.80    -5.48
152      RBF  13.70           147    -0.70    -4.86
93        IP  14.50            36    -0.60    -3.97
166     SCGP  53.50          1688    -1.75    -3.17
203      TKS  12.80           114    -0.40    -3.03
189      SVI  10.00            92    -0.30    -2.91
64       ECL   2.02            12    -0.06    -2.88
162       SC   4.18            67    -0.12    -2.79
9       ANAN   1.43            30    -0.04    -2.72
52   CPNREIT  19.30            54    -0.50    -2.53

In [7]:
df_dailies.sort_values(['daily_volume'],ascending=[False]).head(10)

      name   price  daily_volume  chg_amt  chg_pct
57   DELTA  884.00          4283    -6.00    -0.67
100  KBANK  143.50          2748     0.00     0.00
166   SCGP   53.50          1688    -1.75    -3.17
10     AOT   75.25          1651     0.50     0.67
81    HANA   59.00          1636     0.25     0.43
101    KCE   49.25          1582    -0.50    -1.01
48   CPALL   70.00          1555     0.75     1.08
126   MINT   33.25          1515     0.75     2.31
21     BBL  153.50          1283     0.50     0.33
30     BEM    9.75           938     0.00     0.00