In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 16), datetime.date(2023, 1, 15))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-16
yesterday: 2023-01-13 00:00:00

In [3]:
yesterday = yesterday.date()
a_year_ago = yesterday - timedelta(days=365)
yesterday, a_year_ago

(datetime.date(2023, 1, 13), datetime.date(2022, 1, 13))

In [4]:
one_month_ago = yesterday + DateOffset(days = -28)
print('New Value: ', one_month_ago, ' ', one_month_ago.day_name())

New Value:  2022-12-16 00:00:00   Friday

### Get past one quarter data

In [5]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

In [6]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-16 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date   price       qty    maxp    minp
312    RCL  2023-01-04   29.25   6755014   30.00   29.25
249    NER  2022-12-29    6.35   9368610    6.35    6.25
341   SCCC  2022-12-19  149.00     41186  149.50  148.00
25   BANPU  2022-12-23   13.40  56515404   13.60   13.40
412  SYNEX  2023-01-04   16.40   1937647   16.80   16.40

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)

### After call ruby ruby\chat-fin.rb

In [10]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [11]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [12]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,25,20,20,6,73,74,16,32,10,4,73,71,93,93,20,20
Upward,25,20,20,12,76,73,26,47,15,5,82,74,99,99,20,20

In [13]:
cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()
mask = df.name == 'ASP'
df[mask][cols].style.format(format_dict)

In [14]:
cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()
pct = 3.00
df.query('to_date == @yesterday and pct >= @pct')[cols].style.format(format_dict)

In [15]:
pct = -0.01
df.query('to_date == @yesterday and pct <= @pct')[cols].style.format(format_dict)

In [16]:
# It returns a DataFrameGroupBy object
df_groupby_trend = df.groupby('trend')
type(df_groupby_trend)

pandas.core.groupby.generic.DataFrameGroupBy

In [17]:
# To get the number of groups
df_groupby_trend.ngroups

2

In [18]:
# Stat of each group
df_groupby_trend.size()

trend
Downward    93
Upward      99
dtype: int64

In [19]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [20]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [21]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-16,2022-12-16,1,2.96,2.96,0.0,0.0,0,0,2.98,2.96,1313820,NaN,2,12-16,12-16

In [22]:
df.groupby('trend').days.max()

trend
Downward     6
Upward      12
Name: days, dtype: int64

In [23]:
df.query('days == 11')[cols].style.format(format_dict)

In [24]:
df.query('days == 4 and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
14,BANPU,01-03,01-06,4,13.40,12.30,-8.21,-11,-3,13.70,12.30,854388284,Downward
53,GVREIT,01-10,01-13,4,9.00,9.00,0.00,0,0,9.15,8.90,879365,Downward
56,IVL,01-03,01-06,4,40.25,37.75,-6.21,-10,-3,41.00,37.00,104236282,Downward
88,MCS,12-19,12-22,4,8.85,8.85,0.00,0,0,8.95,8.75,2226444,Downward
95,NER,12-20,12-23,4,5.95,5.90,-0.84,-1,-1,6.05,5.90,13434111,Downward
108,ORI,01-03,01-06,4,12.00,11.60,-3.33,-4,-1,12.30,11.40,56252405,Downward
124,RCL,12-30,01-04,4,30.75,29.25,-4.88,-6,-2,31.50,29.25,12188423,Downward
136,SCCC,12-16,12-21,4,149.00,148.50,-0.34,-1,-1,149.50,148.00,201474,Downward
148,STA,12-30,01-04,4,21.10,20.60,-2.37,-5,-2,21.60,20.40,12847722,Downward
164,TFFIF,12-16,12-21,4,7.70,7.70,0.00,0,0,7.75,7.55,6149491,Downward
182,WHAIR,01-06,01-11,4,7.50,7.45,-0.67,-1,-1,7.60,7.45,3082921,Downward

In [25]:
df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

       name     trend      days
0       ASP  Downward  3.000000
1       ASP    Upward  6.500000
2     BANPU  Downward  1.666667
3     BANPU    Upward  1.428571
4       BCH  Downward  1.250000
5       BCH    Upward  3.000000
6   CPNREIT  Downward  2.000000
7   CPNREIT    Upward  3.750000
8       DCC  Downward  1.000000
9       DCC    Upward  4.250000
10      DIF  Downward  1.333333
11      DIF    Upward  5.666667
12   GVREIT  Downward  3.000000
13   GVREIT    Upward  3.666667
14      IVL  Downward  5.000000
15      IVL    Upward  5.000000
16    JASIF  Downward  1.500000
17    JASIF    Upward  3.750000
18      KCE  Downward  1.571429
19      KCE    Upward  1.500000
20    MAKRO  Downward  1.750000
21    MAKRO    Upward  3.500000
22      MCS  Downward  2.000000
23      MCS    Upward  3.750000
24      NER  Downward  2.000000
25      NER    Upward  2.600000
26      ORI  Downward  2.000000
27      ORI    Upward  2.400000
28    PTTGC  Downward  3.000000
29    PTTGC    Upward  2.250000
30      RCL  Downward  2.000000
31      RCL    Upward  2.750000
32      SCC  Downward  2.000000
33      SCC    Upward  4.333333
34     SCCC  Downward  3.500000
35     SCCC    Upward  7.000000
36     SENA  Downward  3.333333
37     SENA    Upward  3.666667
38      STA  Downward  3.000000
39      STA    Upward  4.000000
40    SYNEX  Downward  1.500000
41    SYNEX    Upward  2.000000
42    TFFIF  Downward  2.750000
43    TFFIF    Upward  2.250000
44      TMT  Downward  3.000000
45      TMT    Upward  5.000000
46    WHAIR  Downward  3.333333
47    WHAIR    Upward  2.750000
48    WHART  Downward  1.250000
49    WHART    Upward  3.200000

In [26]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    6     93     2.0  2.118280
Upward     12     99     2.0  3.222222

### Individual stock analysis

In [27]:
name = 'IVL'
df.query('name == @name')[cols].style.format(format_dict)

In [28]:
df_tmp = price.query('name == @name')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  20.00        20.00  20.00  20.00
mean   40.14  18002611.90  40.60  39.67
std     1.00  19887756.21   0.84   1.02
min    37.75   3225857.00  39.00  37.00
25%    39.69   7552530.50  40.00  39.44
50%    40.00  11048591.50  40.50  39.50
75%    40.75  17083488.25  41.25  40.50
max    41.75  76125229.00  42.25  41.00