In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 27), datetime.date(2023, 1, 26))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-27
Today in mm-dd format: 01-27
yesterday: 2023-01-26 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-29 00:00:00   Thursday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'MC', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-29 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

       name        date  price       qty   maxp   minp
188  GVREIT  2023-01-27   9.45    281301   9.65   9.45
542   SYNEX  2023-01-24  16.70    761131  16.90  16.70
511     STA  2023-01-10  21.30   6769740  21.80  21.10
47      BCH  2023-01-06  21.90  22547400  22.00  21.30
38    BANPU  2023-01-24  12.50  35729821  12.60  12.40

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-29|2022-12-29|1|2.96|2.96|0.0|0.0|0|0|2.98|2.96||2|2,344,759
ASP|2022-12-30|2022-12-30|1|2.98|2.98|0.0|0.0|0|0|2.98|2.96|Upward|3|1,971,614
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|6|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|15|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|17|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|18|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|19|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|20|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|21|3,647,294
ASP|2023-01-27|2023-01-27|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|22|1,019,698
BANPU|2022-12-29|2022-12-30|2|13.7|13.7|0.0|0.0|0|0|13.8|13.5|Upward|24|107,358,858
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|28|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|30|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|32|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|33|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|37|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|38|193,937,283
BANPU|2023-01-23|2023-01-27|5|12.5|12.3|-0.2|-1.6|-2|-1|12.6|12.0|Downward|43|318,186,733
BCH|2022-12-29|2022-12-30|2|21.1|20.5|-0.6|-2.84|-6|-3|21.1|20.3|Downward|45|51,408,470
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|49|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|50|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|51|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|53|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|55|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|62|46,355,474
BCH|2023-01-26|2023-01-27|2|20.7|20.9|0.2|0.97|2|1|21.1|20.5|Upward|64|19,342,105
CK|2022-12-29|2022-12-30|2|24.2|24.3|0.1|0.41|1|0|24.3|23.8|Upward|66|7,843,794
CK|2023-01-03|2023-01-10|6|23.9|23.5|-0.4|-1.67|-4|-1|24.5|23.2|Downward|72|38,379,065
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|74|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|76|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|77|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|78|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|79|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|82|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|83|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|85|17,070,329
CKP|2022-12-29|2023-01-03|4|4.58|4.52|-0.06|-1.31|-3|-1|4.66|4.52|Downward|88|65,320,109
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|8|1|4.76|4.52|Upward|95|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|99|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|101|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|105|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|106|6,963,352
CPNREIT|2022-12-29|2023-01-09|8|19.4|19.5|0.1|0.52|1|0|19.7|19.4|Upward|113|5,718,944
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|114|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|121|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|124|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|126|2,216,218
CPNREIT|2023-01-27|2023-01-27|1|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Downward|127|1,410,920
DCC|2022-12-29|2023-01-04|5|2.82|2.8|-0.02|-0.71|-1|-1|2.84|2.8|Downward|131|19,489,701
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|135|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|136|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|137|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|140|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|141|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|142|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|144|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|145|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|146|6,076,325
DCC|2023-01-26|2023-01-27|2|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|148|21,773,267
DIF|2022-12-29|2023-01-03|4|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|151|13,150,833
DIF|2023-01-04|2023-01-04|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|152|3,723,467
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|154|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|163|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|166|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|167|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|168|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|169|7,462,352
GVREIT|2022-12-29|2023-01-03|4|9.1|9.15|0.05|0.55|1|0|9.15|9.05|Upward|172|1,455,698
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|175|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|176|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|182|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|187|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|188|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|189|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|190|281,301
IVL|2022-12-29|2023-01-06|7|40.75|37.75|-3.0|-7.36|-12|-2|41.25|37.0|Downward|196|128,930,106
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|204|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|205|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|206|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|210|61,818,314
IVL|2023-01-27|2023-01-27|1|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|211|12,196,468
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|4|0|8.3|8.0|Upward|221|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|222|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|224|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|225|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|229|16,790,423
JASIF|2023-01-25|2023-01-27|3|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|232|22,034,103
JMART|2022-12-29|2022-12-30|2|41.5|40.75|-0.75|-1.81|-3|-2|41.75|40.75|Downward|234|11,193,962
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|235|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|237|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|243|44,921,819
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|252|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|253|14,613,196
JMT|2022-12-29|2022-12-30|2|68.25|69.0|0.75|1.1|3|1|70.0|67.75|Upward|255|8,620,205
JMT|2023-01-03|2023-01-06|4|67.5|66.0|-1.5|-2.22|-6|-2|69.0|65.25|Downward|259|16,280,131
JMT|2023-01-09|2023-01-13|5|68.25|69.5|1.25|1.83|5|1|71.0|66.75|Upward|264|36,049,399
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|273|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|274|16,158,754
KCE|2022-12-29|2022-12-29|1|46.75|46.75|0.0|0.0|0|0|46.75|46.25|Upward|275|7,670,612
KCE|2022-12-30|2022-12-30|1|46.5|46.5|0.0|0.0|0|0|47.5|46.25|Downward|276|22,449,277
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|0|0|48.0|46.25|Upward|277|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-4|-2|47.5|44.5|Downward|279|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|282|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|283|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|284|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|290|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|291|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|292|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|293|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|294|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|295|13,719,929
MC|2022-12-29|2023-01-10|9|10.5|11.2|0.7|6.67|7|0|11.2|10.3|Upward|303|7,080,362
MC|2023-01-11|2023-01-11|1|11.0|11.0|0.0|0.0|0|0|11.1|10.7|Downward|304|1,488,870
MC|2023-01-12|2023-01-12|1|11.1|11.1|0.0|0.0|0|0|11.2|10.8|Upward|305|1,363,029
MC|2023-01-13|2023-01-13|1|11.0|11.0|0.0|0.0|0|0|11.3|11.0|Downward|306|1,259,169
MC|2023-01-16|2023-01-19|4|11.2|11.7|0.5|4.46|5|1|11.7|11.0|Upward|310|6,694,798
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-3|-2|11.8|11.3|Downward|312|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|3|1|11.9|11.3|Upward|315|4,617,106
MC|2023-01-27|2023-01-27|1|11.8|11.8|0.0|0.0|0|0|11.9|11.8|Downward|316|468,320
MCS|2022-12-29|2022-12-30|2|8.95|8.95|0.0|0.0|0|0|9.0|8.9|Downward|318|1,066,253
MCS|2023-01-03|2023-01-06|4|9.0|9.3|0.3|3.33|6|1|9.35|8.95|Upward|322|4,383,825
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|323|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|325|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|326|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|331|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|332|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|333|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|334|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|335|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|336|1,271,966
MCS|2023-01-27|2023-01-27|1|10.1|10.1|0.0|0.0|0|0|10.1|9.95|Upward|337|382,816
NER|2022-12-29|2023-01-03|4|6.35|6.35|0.0|0.0|0|0|6.45|6.25|Upward|340|25,690,059
NER|2023-01-04|2023-01-05|2|6.3|6.25|-0.05|-0.79|-1|-1|6.45|6.2|Downward|342|23,830,282
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|343|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|344|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|345|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|346|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|348|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|353|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|354|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|355|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|357|42,913,468
NER|2023-01-27|2023-01-27|1|6.6|6.6|0.0|0.0|0|0|6.7|6.6|Downward|358|10,845,319
ORI|2022-12-29|2022-12-29|1|12.0|12.0|0.0|0.0|0|0|12.0|11.7|Downward|359|11,894,329
ORI|2022-12-30|2022-12-30|1|12.1|12.1|0.0|0.0|0|0|12.1|11.8|Upward|360|9,483,707
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|364|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|365|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|367|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|370|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|372|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|375|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|378|16,286,040
ORI|2023-01-27|2023-01-27|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|379|9,726,315
PTTGC|2022-12-29|2022-12-29|1|47.5|47.5|0.0|0.0|0|0|47.75|46.75|Upward|380|14,309,832
PTTGC|2022-12-30|2023-01-03|3|47.25|46.75|-0.5|-1.06|-2|-1|47.75|46.5|Downward|382|18,960,635
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|383|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|385|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|388|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|390|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|393|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|395|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|398|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|399|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|400|13,790,565
RCL|2022-12-29|2022-12-29|1|31.0|31.0|0.0|0.0|0|0|31.25|30.5|Upward|401|2,488,533
RCL|2022-12-30|2023-01-04|4|30.75|29.25|-1.5|-4.88|-6|-2|31.5|29.25|Downward|404|12,188,423
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|408|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|409|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|410|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|412|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|414|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|416|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|419|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|420|2,352,538
RCL|2023-01-27|2023-01-27|1|31.75|31.75|0.0|0.0|0|0|32.0|31.0|Upward|421|2,699,315
SCC|2022-12-29|2022-12-29|1|344.0|344.0|0.0|0.0|0|0|344.0|339.0|Upward|422|1,374,749
SCC|2022-12-30|2023-01-03|3|342.0|342.0|0.0|0.0|0|0|344.0|340.0|Downward|424|3,705,436
SCC|2023-01-04|2023-01-11|6|345.0|359.0|14.0|4.06|14|2|360.0|340.0|Upward|430|14,796,849
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|433|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|434|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|441|16,632,975
SCC|2023-01-27|2023-01-27|1|340.0|340.0|0.0|0.0|0|0|341.0|334.0|Upward|442|2,463,264
SCCC|2022-12-29|2023-01-06|7|153.0|158.5|5.5|3.59|11|1|159.0|152.5|Upward|448|876,743
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|451|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|457|713,373
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|462|597,538
SCCC|2023-01-27|2023-01-27|1|158.5|158.5|0.0|0.0|0|0|159.0|157.0|Upward|463|148,498
SENA|2022-12-29|2023-01-03|4|3.94|3.94|0.0|0.0|0|0|3.96|3.9|Upward|466|3,145,039
SENA|2023-01-04|2023-01-05|2|3.92|3.9|-0.02|-0.51|-1|-1|3.96|3.9|Downward|468|1,498,341
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|471|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|474|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|476|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|478|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|480|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|481|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|482|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|484|2,050,656
SINGER|2022-12-29|2023-01-06|7|28.75|27.0|-1.75|-6.09|-7|-1|29.25|26.75|Downward|490|37,782,806
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|491|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|492|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|495|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|501|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|502|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|504|11,350,118
SINGER|2023-01-27|2023-01-27|1|27.5|27.5|0.0|0.0|0|0|27.75|27.0|Upward|505|3,166,067
STA|2022-12-29|2022-12-29|1|21.2|21.2|0.0|0.0|0|0|21.4|21.0|Upward|506|6,449,026
STA|2022-12-30|2023-01-04|4|21.1|20.6|-0.5|-2.37|-5|-2|21.6|20.4|Downward|509|12,847,722
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|512|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|514|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|516|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|517|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|518|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|519|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|520|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|522|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|526|45,950,994
SYNEX|2022-12-29|2023-01-03|4|15.9|16.7|0.8|5.03|8|2|17.0|15.7|Upward|529|9,292,913
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|530|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|533|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|534|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|536|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|542|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|544|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|546|4,592,919
SYNEX|2023-01-27|2023-01-27|1|16.1|16.1|0.0|0.0|0|0|16.2|16.0|Upward|547|1,266,219
TFFIF|2022-12-29|2022-12-29|1|7.7|7.7|0.0|0.0|0|0|7.7|7.6|Upward|548|2,141,981
TFFIF|2022-12-30|2022-12-30|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|549|418,765
TFFIF|2023-01-03|2023-01-03|1|7.7|7.7|0.0|0.0|0|0|7.75|7.65|Upward|550|745,322
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|551|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|554|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|555|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|565|26,912,214
TFFIF|2023-01-25|2023-01-27|3|8.15|8.15|0.0|0.0|0|0|8.25|8.1|Downward|568|6,944,090
TMT|2022-12-29|2023-01-05|6|7.9|7.65|-0.25|-3.16|-5|-1|7.95|7.6|Downward|573|1,482,117

WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|640|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|641|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|646|20,924,999
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|651|15,575,456
WHART|2023-01-27|2023-01-27|1|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|651|944,035
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'STA'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'CK'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [55]:
#df.groupby('trend').days.max()

In [23]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    9    126     2.0  2.523810
Upward     13    133     2.0  2.646617

In [24]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [25]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [26]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
91,JMART,01-16,01-26,9,41.75,35.50,-14.97,-25,-3,42.75,35.25,118032446,Downward
96,JMT,01-16,01-26,9,68.25,53.75,-21.25,-58,-7,69.75,53.75,129571700,Downward

In [27]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

### Individual stock analysis

In [28]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [29]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   21.36   5675424.38  21.61  21.04
std     0.58   4857793.29   0.50   0.42
min    20.60    879566.00  21.00  20.40
25%    21.10   2627650.00  21.30  20.80
50%    21.20   3729662.00  21.40  21.00
75%    21.30   6769740.00  21.70  21.10
max    22.90  19821209.00  22.90  22.40

In [30]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [31]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   23.66   6526958.86  23.95  23.50
std     0.32   3277469.23   0.26   0.29
min    22.70   2423298.00  23.30  22.60
25%    23.60   4544281.00  23.80  23.40
50%    23.60   5011431.00  23.90  23.50
75%    23.80   8328300.00  24.10  23.60
max    24.30  14968318.00  24.50  24.00

In [32]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [33]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)