In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 31), datetime.date(2023, 1, 30))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-31
Today in mm-dd format: 01-31
yesterday: 2023-01-30 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-02 00:00:00   Monday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-02 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

     name        date  price       qty   maxp   minp
191   IVL  2023-01-05  39.75   9696817  40.00  39.50
292   KCE  2023-01-30  50.00  10465232  50.50  49.50
448  SENA  2023-01-12   3.92    555522   3.94   3.90
9     ASP  2023-01-16   3.08   2398944   3.10   3.06
269   JMT  2023-01-26  53.75  40105767  58.75  53.75

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94||4|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|13|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|15|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|16|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|17|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|18|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|19|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|21|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|22|3,048,744
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|26|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|28|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|30|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|31|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|35|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|36|193,937,283
BANPU|2023-01-23|2023-01-31|7|12.5|11.6|-0.9|-7.2|-9|-2|12.6|11.3|Downward|43|902,129,867
BCH|2023-01-03|2023-01-04|2|21.0|21.0|0.0|0.0|0|0|21.0|20.6|Downward|45|18,509,135
BCH|2023-01-05|2023-01-06|2|21.3|21.9|0.6|2.82|6|3|22.0|20.8|Upward|47|38,406,741
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|48|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|49|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|51|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|53|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|60|46,355,474
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|64|55,795,055
CK|2023-01-03|2023-01-03|1|23.9|23.9|0.0|0.0|0|0|24.5|23.9|Upward|65|4,893,910
CK|2023-01-04|2023-01-10|5|23.8|23.5|-0.3|-1.26|-3|-1|24.1|23.2|Downward|70|33,485,155
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|72|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|74|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|75|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|76|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|77|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|80|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|81|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|83|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|84|2,492,389
CK|2023-01-31|2023-01-31|1|22.6|22.6|0.0|0.0|0|0|23.1|22.4|Downward|85|10,012,092
CKP|2023-01-03|2023-01-03|1|4.52|4.52|0.0|0.0|0|0|4.6|4.52|Downward|86|12,780,550
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|8|1|4.76|4.52|Upward|93|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|97|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|99|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|103|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|104|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|106|15,946,162
CPNREIT|2023-01-03|2023-01-10|6|19.5|18.8|-0.7|-3.59|-7|-2|19.7|18.8|Downward|112|6,832,502
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|119|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|122|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|124|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|127|3,517,218
DCC|2023-01-03|2023-01-04|2|2.82|2.8|-0.02|-0.71|-1|-1|2.84|2.8|Downward|129|7,957,530
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|133|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|134|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|135|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|138|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|139|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|140|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|142|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|143|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|144|6,076,325
DCC|2023-01-26|2023-01-27|2|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|146|21,773,267
DCC|2023-01-30|2023-01-31|2|2.84|2.86|0.02|0.7|1|0|2.9|2.82|Upward|148|37,347,656
DIF|2023-01-03|2023-01-04|2|13.2|13.3|0.1|0.76|1|0|13.3|13.2|Upward|150|8,329,716
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|152|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|161|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|164|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|165|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|166|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|167|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|169|11,737,432
GVREIT|2023-01-03|2023-01-06|4|9.15|9.0|-0.15|-1.64|-3|-1|9.15|9.0|Downward|173|755,971
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|174|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|180|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|185|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|186|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|187|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|188|281,301
GVREIT|2023-01-30|2023-01-31|2|9.55|9.6|0.05|0.52|1|0|9.65|9.45|Upward|190|336,521
IVL|2023-01-03|2023-01-03|1|40.25|40.25|0.0|0.0|0|0|41.0|40.25|Upward|191|7,697,656
IVL|2023-01-04|2023-01-06|3|39.75|37.75|-2.0|-5.03|-8|-3|40.5|37.0|Downward|194|96,538,626
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|202|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|203|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|204|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|208|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|210|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|211|13,669,626
JASIF|2023-01-03|2023-01-05|3|8.1|8.1|0.0|0.0|0|0|8.15|8.05|Downward|214|11,852,326
JASIF|2023-01-06|2023-01-12|5|8.15|8.25|0.1|1.23|2|0|8.3|8.1|Upward|219|28,092,266
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|220|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|222|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|223|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|227|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|231|28,383,533
JASIF|2023-01-31|2023-01-31|1|8.2|8.2|0.0|0.0|0|0|8.2|8.15|Upward|232|2,347,192
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|233|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|235|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|241|44,921,819
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|250|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|251|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|252|9,743,425
JMART|2023-01-31|2023-01-31|1|37.25|37.25|0.0|0.0|0|0|37.75|36.5|Upward|253|7,880,561
JMT|2023-01-03|2023-01-03|1|67.5|67.5|0.0|0.0|0|0|69.0|67.25|Upward|254|3,581,500
JMT|2023-01-04|2023-01-06|3|66.25|66.0|-0.25|-0.38|-1|-1|67.75|65.25|Downward|257|12,698,631
JMT|2023-01-09|2023-01-13|5|68.25|69.5|1.25|1.83|5|1|71.0|66.75|Upward|262|36,049,399
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|271|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|272|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|274|45,047,024
KCE|2023-01-03|2023-01-05|3|47.25|45.0|-2.25|-4.76|-9|-3|48.0|44.5|Downward|277|60,423,849
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|280|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|281|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|282|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|288|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|289|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|290|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|291|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|292|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|293|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|294|10,465,232
KCE|2023-01-31|2023-01-31|1|54.75|54.75|0.0|0.0|0|0|55.5|50.5|Upward|295|104,238,878
MCS|2023-01-03|2023-01-06|4|9.0|9.3|0.3|3.33|6|1|9.35|8.95|Upward|299|4,383,825
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|300|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|302|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|303|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|308|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|309|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|310|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|311|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|312|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|313|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|316|2,139,488
NER|2023-01-03|2023-01-03|1|6.35|6.35|0.0|0.0|0|0|6.4|6.25|Upward|317|9,308,876
NER|2023-01-04|2023-01-05|2|6.3|6.25|-0.05|-0.79|-1|-1|6.45|6.2|Downward|319|23,830,282
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|320|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|321|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|322|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|323|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|325|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|330|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|331|4,182,338

NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|332|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|334|42,913,468
NER|2023-01-27|2023-01-31|3|6.6|6.4|-0.2|-3.03|-4|-2|6.7|6.4|Downward|337|28,471,244
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|341|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|342|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|344|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|347|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|349|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|352|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|355|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|358|32,777,837
PTTGC|2023-01-03|2023-01-04|2|46.75|47.0|0.25|0.53|1|0|47.5|46.0|Upward|360|29,768,836
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|362|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|365|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|367|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|370|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|372|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|375|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|376|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|377|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|379|24,376,908
RCL|2023-01-03|2023-01-04|2|30.5|29.25|-1.25|-4.1|-5|-3|31.25|29.25|Downward|381|9,239,929
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|385|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|386|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|387|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|389|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|391|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|393|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|396|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|397|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|400|12,494,495
SCC|2023-01-03|2023-01-11|7|342.0|359.0|17.0|4.97|17|2|360.0|340.0|Upward|407|16,464,498
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|410|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|411|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|418|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|420|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|421|3,280,199
SCCC|2023-01-03|2023-01-03|1|154.5|154.5|0.0|0.0|0|0|154.5|154.0|Downward|422|94,288
SCCC|2023-01-04|2023-01-06|3|155.5|158.5|3.0|1.93|6|2|159.0|154.0|Upward|425|616,034
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|428|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|434|713,373
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|439|597,538
SCCC|2023-01-27|2023-01-31|3|158.5|159.5|1.0|0.63|2|0|162.0|157.0|Upward|442|703,928
SENA|2023-01-03|2023-01-03|1|3.94|3.94|0.0|0.0|0|0|3.96|3.92|Upward|443|703,163
SENA|2023-01-04|2023-01-05|2|3.92|3.9|-0.02|-0.51|-1|-1|3.96|3.9|Downward|445|1,498,341
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|448|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|451|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|453|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|455|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|457|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|458|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|459|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|461|2,050,656
SENA|2023-01-30|2023-01-31|2|3.94|3.94|0.0|0.0|0|0|3.96|3.9|Upward|463|6,576,407
SINGER|2023-01-03|2023-01-03|1|28.5|28.5|0.0|0.0|0|0|28.75|27.75|Upward|464|6,628,141
SINGER|2023-01-04|2023-01-06|3|27.5|27.0|-0.5|-1.82|-2|-1|28.25|26.75|Downward|467|17,020,802
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|468|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|469|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|472|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|478|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|479|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|481|11,350,118
SINGER|2023-01-27|2023-01-31|3|27.5|27.5|0.0|0.0|0|0|28.0|27.0|Upward|484|7,856,728
STA|2023-01-03|2023-01-03|1|20.8|20.8|0.0|0.0|0|0|21.1|20.7|Upward|485|2,627,650
STA|2023-01-04|2023-01-04|1|20.6|20.6|0.0|0.0|0|0|21.0|20.4|Downward|486|3,233,463
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|489|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|491|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|493|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|494|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|495|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|496|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|497|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|499|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|503|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|505|17,280,360
SYNEX|2023-01-03|2023-01-04|2|16.7|16.4|-0.3|-1.8|-3|-2|17.0|16.4|Downward|507|5,534,247
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|510|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|511|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|513|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|519|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|521|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|523|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|525|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|526|1,438,207
TFFIF|2023-01-03|2023-01-04|2|7.7|7.65|-0.05|-0.65|-1|-1|7.75|7.65|Downward|528|1,599,058
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|531|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|532|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|542|26,912,214
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|547|12,364,080
TMT|2023-01-03|2023-01-05|3|7.8|7.65|-0.15|-1.92|-3|-1|7.85|7.6|Downward|550|980,539
TMT|2023-01-06|2023-01-24|13|7.7|8.45|0.75|9.74|15|1|8.45|7.55|Upward|563|6,084,601
TMT|2023-01-25|2023-01-31|5|8.35|8.2|-0.15|-1.8|-3|-1|8.45|8.2|Downward|568|1,378,037
TTB|2023-01-03|2023-01-03|1|1.41|1.41|0.0|0.0|0|0|1.44|1.4|Downward|569|358,490,193
TTB|2023-01-04|2023-01-10|5|1.42|1.46|0.04|2.82|4|0|1.47|1.4|Upward|574|1,900,787,621
TTB|2023-01-11|2023-01-13|3|1.44|1.41|-0.03|-2.08|-3|-1|1.47|1.4|Downward|577|765,226,385
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|581|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|582|509,121,072
TTB|2023-01-23|2023-01-31|7|1.44|1.47|0.03|2.08|3|0|1.47|1.4|Upward|589|1,993,215,883
WHAIR|2023-01-03|2023-01-05|3|7.45|7.55|0.1|1.34|2|0|7.55|7.4|Upward|592|1,901,437
WHAIR|2023-01-06|2023-01-11|4|7.5|7.45|-0.05|-0.67|-1|-1|7.6|7.45|Downward|596|3,082,921
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|603|11,421,149
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|605|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|607|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|609|3,620,824
WHAIR|2023-01-31|2023-01-31|1|7.95|7.95|0.0|0.0|0|0|7.95|7.8|Upward|610|738,511
WHART|2023-01-03|2023-01-04|2|10.8|10.8|0.0|0.0|0|0|10.9|10.6|Upward|612|2,822,868
WHART|2023-01-05|2023-01-06|2|10.7|10.7|0.0|0.0|0|0|10.9|10.7|Downward|614|1,791,615
WHART|2023-01-09|2023-01-09|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|615|1,371,475
WHART|2023-01-10|2023-01-10|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|616|1,251,002
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|617|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|618|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|623|20,924,999
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|628|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|630|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|630|1,239,474
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'BCH'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')

In [21]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [22]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [23]:
#df.groupby('trend').days.max()

In [24]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    9    126     2.0  2.428571
Upward     13    125     2.0  2.568000

In [25]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [26]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [27]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
95,JMART,01-16,01-26,9,41.75,35.50,-14.97,-25,-3,42.75,35.25,118032446,Downward
102,JMT,01-16,01-26,9,68.25,53.75,-21.25,-58,-7,69.75,53.75,129571700,Downward

In [27]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

### Individual stock analysis

In [28]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [29]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   21.29  10104617.10  21.50  21.07
std     0.39   6231837.74   0.44   0.37
min    20.60   2886815.00  20.90  20.50
25%    21.00   5831572.00  21.10  20.80
50%    21.20   8886118.00  21.30  21.00
75%    21.50  11168977.00  21.90  21.30
max    21.90  28254332.00  22.20  21.70

In [30]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [33]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  21.00  2.100000e+01  21.00  21.00
mean   12.45  1.326580e+08  12.59  12.29
std     0.34  1.010692e+08   0.38   0.38
min    11.60  3.089415e+07  11.90  11.30
25%    12.30  5.796199e+07  12.40  12.20
50%    12.40  1.045682e+08  12.50  12.20
75%    12.50  1.607239e+08  12.60  12.40
max    13.40  4.159035e+08  13.70  13.40

In [34]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [35]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)