In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 14), datetime.date(2023, 2, 13))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-14
Today in mm-dd format: 02-14
yesterday: 2023-02-13 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-16 00:00:00   Monday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [11]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [12]:
in_p = in_p + ", 'MC', 'SAT', 'TCAP'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'MC', 'SAT', 'TCAP'"

In [7]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'BANPU', 'CK', 'CKP', 'COM7', 'CPF', 'CPNREIT', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MEGA', 'ORI', 'PTT', 'RCL', 'SINGER', 'STA', 'TMT', 'TTB', 'WHAIR'"

### End of Selection between Buy or Orders

In [13]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-16 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'MC', 'SAT', 'TCAP')
ORDER BY name, date

In [15]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty  maxp  minp
578  WHAIR  2023-01-26   8.00   1326742  8.00  7.90
505   TCAP  2023-01-17  43.25   2438530 43.50 43.00
217    JMT  2023-02-14  50.00  45121902 53.25 49.50
417   SENA  2023-01-17   3.94    738967  3.94  3.92
357    RCL  2023-01-25  31.75   3505471 32.00 31.25

In [16]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [17]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [18]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [19]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-16|2023-01-16|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06||2|2,398,944
ASP|2023-01-17|2023-01-18|2|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|4|1,754,573
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|6|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|7|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|8|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|9|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|10|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|12|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|13|3,048,744
ASP|2023-02-01|2023-02-02|2|3.16|3.16|0.0|0.0|0|0|3.24|3.08|Upward|15|28,871,862
ASP|2023-02-03|2023-02-03|1|3.1|3.1|0.0|0.0|0|0|3.18|3.1|Downward|16|3,867,567
ASP|2023-02-06|2023-02-06|1|3.14|3.14|0.0|0.0|0|0|3.14|3.1|Upward|17|2,481,635
ASP|2023-02-07|2023-02-14|6|3.12|3.06|-0.06|-1.92|-3|-1|3.16|3.06|Downward|23|11,864,504
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|27|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|28|193,937,283
BANPU|2023-01-23|2023-02-10|15|12.5|10.9|-1.6|-12.8|-16|-2|12.6|10.7|Downward|43|2,058,642,124
BANPU|2023-02-13|2023-02-13|1|11.1|11.1|0.0|0.0|0|0|11.2|10.9|Upward|44|90,540,091
BANPU|2023-02-14|2023-02-14|1|11.0|11.0|0.0|0.0|0|0|11.3|10.9|Downward|45|110,882,761
BCH|2023-01-16|2023-01-25|8|21.5|20.6|-0.9|-4.19|-9|-2|21.8|20.6|Downward|53|52,001,129
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|57|55,795,055
BCH|2023-02-01|2023-02-02|2|21.6|21.4|-0.2|-0.93|-2|-1|21.8|21.3|Downward|59|21,808,662
BCH|2023-02-03|2023-02-03|1|21.5|21.5|0.0|0.0|0|0|21.7|21.4|Upward|60|12,718,266
BCH|2023-02-06|2023-02-13|6|21.3|20.5|-0.8|-3.76|-8|-2|21.5|20.3|Downward|66|39,507,871
BCH|2023-02-14|2023-02-14|1|20.9|20.9|0.0|0.0|0|0|21.1|20.4|Upward|67|11,084,451
CPNREIT|2023-01-16|2023-01-19|4|19.6|20.6|1.0|5.1|10|2|20.6|19.5|Upward|71|7,660,720
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|74|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|76|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|79|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|81|1,159,029
CPNREIT|2023-02-03|2023-02-14|8|19.1|18.2|-0.9|-4.71|-9|-2|19.4|18.2|Downward|89|19,622,744
DIF|2023-01-16|2023-01-17|2|13.5|13.5|0.0|0.0|0|0|13.6|13.4|Downward|91|18,163,219
DIF|2023-01-18|2023-01-19|2|13.6|13.7|0.1|0.74|1|0|13.7|13.5|Upward|93|18,753,991
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|96|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|97|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|98|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|99|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|101|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|102|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|106|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|107|8,569,954
DIF|2023-02-10|2023-02-14|3|13.3|13.3|0.0|0.0|0|0|13.4|13.2|Downward|110|44,447,147
GVREIT|2023-01-16|2023-01-17|2|9.0|8.9|-0.1|-1.11|-2|-1|9.0|8.9|Downward|112|570,525
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|117|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|118|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|119|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|120|281,301
GVREIT|2023-01-30|2023-02-01|3|9.55|9.75|0.2|2.09|4|1|9.75|9.45|Upward|123|669,621
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|124|224,521
GVREIT|2023-02-03|2023-02-07|3|9.75|9.8|0.05|0.51|1|0|9.9|9.6|Upward|127|1,566,531
GVREIT|2023-02-08|2023-02-10|3|9.75|9.65|-0.1|-1.03|-2|-1|9.8|9.55|Downward|130|913,806
GVREIT|2023-02-13|2023-02-14|2|9.7|9.75|0.05|0.52|1|0|9.8|9.65|Upward|132|1,140,908
IVL|2023-01-16|2023-01-18|3|41.75|42.25|0.5|1.2|2|0|42.75|41.5|Upward|135|49,980,577
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|136|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|137|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|141|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|143|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|144|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|145|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|147|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|148|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|149|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|0|0|41.5|40.25|Upward|151|22,518,750
IVL|2023-02-10|2023-02-13|2|40.5|40.0|-0.5|-1.23|-2|-1|40.75|39.75|Downward|153|18,080,401
IVL|2023-02-14|2023-02-14|1|40.25|40.25|0.0|0.0|0|0|40.75|40.0|Upward|154|8,413,044
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|156|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|157|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|161|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|165|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|167|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|168|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|172|12,746,881
JASIF|2023-02-10|2023-02-14|3|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|175|12,837,375
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|184|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|185|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|186|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|189|17,299,441
JMART|2023-02-03|2023-02-14|8|37.25|31.5|-5.75|-15.44|-23|-3|37.75|31.0|Downward|197|112,608,106
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|206|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|207|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|209|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|210|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|211|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|212|12,417,267
JMT|2023-02-06|2023-02-08|3|53.75|50.75|-3.0|-5.58|-12|-4|54.75|50.75|Downward|215|33,982,605
JMT|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|0|0|53.0|50.25|Upward|216|14,352,623
JMT|2023-02-10|2023-02-13|2|50.5|49.5|-1.0|-1.98|-4|-2|52.0|48.75|Downward|218|35,100,334
JMT|2023-02-14|2023-02-14|1|50.0|50.0|0.0|0.0|0|0|53.25|49.5|Upward|219|45,121,902
KCE|2023-01-16|2023-01-16|1|51.5|51.5|0.0|0.0|0|0|52.25|51.25|Upward|220|13,811,776
KCE|2023-01-17|2023-01-20|4|50.75|49.0|-1.75|-3.45|-7|-2|52.0|48.5|Downward|224|69,519,050
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|225|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|226|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|227|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|228|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|229|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|230|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|234|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|235|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|236|17,516,788
KCE|2023-02-08|2023-02-10|3|50.5|47.25|-3.25|-6.44|-13|-5|55.25|47.25|Downward|239|202,268,953
KCE|2023-02-13|2023-02-13|1|48.0|48.0|0.0|0.0|0|0|48.25|46.75|Upward|240|16,263,448
KCE|2023-02-14|2023-02-14|1|47.0|47.0|0.0|0.0|0|0|48.75|47.0|Downward|241|16,814,980
MC|2023-01-16|2023-01-16|1|11.2|11.2|0.0|0.0|0|0|11.4|11.0|Downward|242|1,254,824
MC|2023-01-17|2023-01-19|3|11.5|11.7|0.2|1.74|2|0|11.7|11.2|Upward|245|5,439,974
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-3|-2|11.8|11.3|Downward|247|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|3|1|11.9|11.3|Upward|250|4,617,106
MC|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.9|11.7|Downward|252|900,523
MC|2023-01-31|2023-01-31|1|11.9|11.9|0.0|0.0|0|0|11.9|11.7|Upward|253|1,180,849
MC|2023-02-01|2023-02-02|2|11.8|11.4|-0.4|-3.39|-4|-2|12.0|11.4|Downward|255|3,035,796
MC|2023-02-03|2023-02-06|2|11.6|11.7|0.1|0.86|1|0|11.8|11.3|Upward|257|2,606,769
MC|2023-02-07|2023-02-08|2|11.6|11.6|0.0|0.0|0|0|11.9|11.5|Downward|259|3,253,713
MC|2023-02-09|2023-02-10|2|11.7|12.2|0.5|4.27|5|2|12.7|11.6|Upward|261|8,043,176
MC|2023-02-13|2023-02-14|2|12.1|12.0|-0.1|-0.83|-1|-1|12.5|11.7|Downward|263|5,844,588
MCS|2023-01-16|2023-01-16|1|9.7|9.7|0.0|0.0|0|0|9.7|9.6|Downward|264|647,326
MCS|2023-01-17|2023-01-19|3|9.75|9.8|0.05|0.51|1|0|9.8|9.65|Upward|267|1,902,196
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|268|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|269|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|270|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|271|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|272|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|275|2,139,488
MCS|2023-02-01|2023-02-01|1|10.0|10.0|0.0|0.0|0|0|10.1|9.9|Downward|276|869,625
MCS|2023-02-02|2023-02-03|2|9.95|9.95|0.0|0.0|0|0|10.1|9.9|Upward|278|947,644
MCS|2023-02-06|2023-02-06|1|9.9|9.9|0.0|0.0|0|0|10.0|9.9|Downward|279|652,568
MCS|2023-02-07|2023-02-07|1|9.95|9.95|0.0|0.0|0|0|10.0|9.9|Upward|280|406,865
MCS|2023-02-08|2023-02-10|3|9.9|9.85|-0.05|-0.51|-1|-1|9.95|9.8|Downward|283|1,491,749
MCS|2023-02-13|2023-02-13|1|9.9|9.9|0.0|0.0|0|0|9.95|9.85|Upward|284|411,280
MCS|2023-02-14|2023-02-14|1|9.85|9.85|0.0|0.0|0|0|9.95|9.8|Downward|285|777,995
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|290|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|291|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|292|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|294|42,913,468
NER|2023-01-27|2023-02-01|4|6.6|6.35|-0.25|-3.79|-5|-2|6.7|6.3|Downward|298|38,923,402
NER|2023-02-02|2023-02-06|3|6.4|6.5|0.1|1.56|2|0|6.5|6.3|Upward|301|24,426,533
NER|2023-02-07|2023-02-14|6|6.45|5.95|-0.5|-7.75|-10|-2|6.5|5.9|Downward|307|58,801,118
ORI|2023-01-16|2023-01-18|3|11.9|11.8|-0.1|-0.84|-1|-1|12.0|11.4|Downward|310|33,402,247
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|313|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|316|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|319|32,777,837
ORI|2023-02-01|2023-02-09|7|12.1|11.7|-0.4|-3.31|-4|-1|12.3|11.5|Downward|326|38,175,270
ORI|2023-02-10|2023-02-10|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|327|4,834,840
ORI|2023-02-13|2023-02-14|2|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Downward|329|11,032,444
PTTGC|2023-01-16|2023-01-16|1|50.25|50.25|0.0|0.0|0|0|50.75|49.75|Downward|330|14,691,840
PTTGC|2023-01-17|2023-01-18|2|51.5|51.5|0.0|0.0|0|0|51.75|50.25|Upward|332|43,068,406
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|334|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|337|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|338|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|339|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|341|24,376,908
PTTGC|2023-02-01|2023-02-01|1|50.0|50.0|0.0|0.0|0|0|50.5|49.25|Upward|342|13,026,320
PTTGC|2023-02-02|2023-02-06|3|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.0|Downward|345|20,473,206
PTTGC|2023-02-07|2023-02-14|6|49.75|50.5|0.75|1.51|3|0|52.5|49.25|Upward|351|123,970,421
RCL|2023-01-16|2023-01-18|3|31.25|31.75|0.5|1.6|2|0|32.0|31.25|Upward|354|5,497,249
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|356|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|359|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|360|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|363|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|365|21,219,944
RCL|2023-02-03|2023-02-07|3|30.75|31.0|0.25|0.81|1|0|31.25|30.5|Upward|368|6,209,457
RCL|2023-02-08|2023-02-09|2|30.5|30.5|0.0|0.0|0|0|31.25|30.25|Downward|370|4,603,482
RCL|2023-02-10|2023-02-10|1|30.75|30.75|0.0|0.0|0|0|30.75|30.25|Upward|371|1,341,212
RCL|2023-02-13|2023-02-14|2|29.5|29.25|-0.25|-0.85|-1|-1|30.75|29.25|Downward|373|7,719,237
SAT|2023-01-16|2023-01-16|1|21.1|21.1|0.0|0.0|0|0|21.2|20.9|Downward|374|701,759
SAT|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.0|Upward|375|1,653,094
SAT|2023-01-18|2023-01-18|1|21.1|21.1|0.0|0.0|0|0|21.4|21.1|Downward|376|762,178
SAT|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.1|Upward|377|1,125,554
SAT|2023-01-20|2023-01-23|2|21.1|21.1|0.0|0.0|0|0|21.5|20.8|Downward|379|2,257,736
SAT|2023-01-24|2023-01-25|2|21.4|21.5|0.1|0.47|1|0|21.7|21.1|Upward|381|3,388,826
SAT|2023-01-26|2023-01-26|1|21.1|21.1|0.0|0.0|0|0|21.5|21.1|Downward|382|1,465,304
SAT|2023-01-27|2023-01-27|1|21.6|21.6|0.0|0.0|0|0|21.6|21.3|Upward|383|1,055,229
SAT|2023-01-30|2023-01-30|1|21.2|21.2|0.0|0.0|0|0|21.6|21.1|Downward|384|1,628,098
SAT|2023-01-31|2023-02-01|2|21.4|21.5|0.1|0.47|1|0|21.6|21.1|Upward|386|1,777,880
SAT|2023-02-02|2023-02-03|2|21.4|21.3|-0.1|-0.47|-1|-1|21.6|21.2|Downward|388|1,008,901
SAT|2023-02-06|2023-02-06|1|21.6|21.6|0.0|0.0|0|0|21.8|21.2|Upward|389|1,273,172
SAT|2023-02-07|2023-02-14|6|21.5|20.9|-0.6|-2.79|-6|-1|21.7|20.7|Downward|395|5,383,557
SCC|2023-01-16|2023-01-16|1|354.0|354.0|0.0|0.0|0|0|357.0|354.0|Downward|396|1,301,432
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|397|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|404|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|406|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|407|3,280,199
SCC|2023-02-01|2023-02-01|1|342.0|342.0|0.0|0.0|0|0|343.0|337.0|Upward|408|2,080,273
SCC|2023-02-02|2023-02-06|3|338.0|336.0|-2.0|-0.59|-2|-1|343.0|336.0|Downward|411|4,970,202
SCC|2023-02-07|2023-02-10|4|338.0|338.0|0.0|0.0|0|0|340.0|335.0|Upward|415|8,476,335
SCC|2023-02-13|2023-02-13|1|335.0|335.0|0.0|0.0|0|0|339.0|335.0|Downward|416|1,796,324
SCC|2023-02-14|2023-02-14|1|341.0|341.0|0.0|0.0|0|0|341.0|336.0|Upward|417|3,326,298
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|419|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|421|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|423|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|424|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|425|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|427|2,050,656
SENA|2023-01-30|2023-02-06|6|3.94|4.04|0.1|2.54|5|0|4.06|3.9|Upward|433|13,631,211
SENA|2023-02-07|2023-02-08|2|4.0|3.94|-0.06|-1.5|-3|-2|4.04|3.94|Downward|435|2,218,445
SENA|2023-02-09|2023-02-10|2|3.96|3.96|0.0|0.0|0|0|3.98|3.92|Upward|437|1,521,299
SENA|2023-02-13|2023-02-14|2|3.94|3.94|0.0|0.0|0|0|3.96|3.92|Downward|439|1,147,705
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|445|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|446|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|448|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|453|26,173,063
SINGER|2023-02-03|2023-02-08|4|28.25|27.0|-1.25|-4.42|-5|-2|28.75|27.0|Downward|457|12,047,147
SINGER|2023-02-09|2023-02-09|1|27.5|27.5|0.0|0.0|0|0|27.5|26.25|Upward|458|5,240,034
SINGER|2023-02-10|2023-02-14|3|26.75|21.1|-5.65|-21.12|-46|-16|27.5|20.5|Downward|461|84,766,925
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|462|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|463|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|464|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|465|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|467|4,052,655

STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|471|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|473|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|475|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|476|4,951,737
STA|2023-02-06|2023-02-08|3|22.6|24.5|1.9|8.41|19|6|24.7|22.3|Upward|479|41,947,740
STA|2023-02-09|2023-02-13|3|24.1|23.6|-0.5|-2.07|-5|-2|24.5|23.5|Downward|482|22,887,544
STA|2023-02-14|2023-02-14|1|24.1|24.1|0.0|0.0|0|0|24.3|23.5|Upward|483|10,632,765
SYNEX|2023-01-16|2023-01-16|1|17.1|17.1|0.0|0.0|0|0|17.4|17.1|Upward|484|1,518,749
SYNEX|2023-01-17|2023-01-20|4|16.9|16.6|-0.3|-1.78|-3|-1|17.3|16.5|Downward|488|6,405,791
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|490|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|492|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|494|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|495|1,438,207
SYNEX|2023-02-01|2023-02-07|5|16.5|17.1|0.6|3.64|6|1|17.6|16.2|Upward|500|14,528,451
SYNEX|2023-02-08|2023-02-08|1|16.3|16.3|0.0|0.0|0|0|17.2|16.3|Downward|501|3,347,661
SYNEX|2023-02-09|2023-02-09|1|16.6|16.6|0.0|0.0|0|0|16.6|16.3|Upward|502|1,122,744
SYNEX|2023-02-10|2023-02-14|3|16.5|15.8|-0.7|-4.24|-7|-3|16.7|15.8|Downward|505|4,716,214
TCAP|2023-01-16|2023-01-18|3|43.25|42.75|-0.5|-1.16|-2|-1|43.75|42.75|Downward|508|9,045,407
TCAP|2023-01-19|2023-01-19|1|43.25|43.25|0.0|0.0|0|0|43.25|42.5|Upward|509|2,089,680
TCAP|2023-01-20|2023-01-25|4|42.75|42.5|-0.25|-0.58|-1|-1|43.25|42.5|Downward|513|8,545,310
TCAP|2023-01-26|2023-01-30|3|42.75|43.0|0.25|0.58|1|0|43.5|42.5|Upward|516|5,373,604
TCAP|2023-01-31|2023-01-31|1|42.75|42.75|0.0|0.0|0|0|43.0|42.75|Downward|517|1,512,084
TCAP|2023-02-01|2023-02-03|3|43.0|43.25|0.25|0.58|1|0|43.5|42.5|Upward|520|6,242,631
TCAP|2023-02-06|2023-02-06|1|43.0|43.0|0.0|0.0|0|0|43.25|42.75|Downward|521|2,192,738
TCAP|2023-02-07|2023-02-07|1|43.25|43.25|0.0|0.0|0|0|43.5|42.75|Upward|522|1,622,069
TCAP|2023-02-08|2023-02-14|5|42.75|42.75|0.0|0.0|0|0|43.0|42.5|Downward|527|7,123,317
TFFIF|2023-01-16|2023-01-17|2|8.0|8.0|0.0|0.0|0|0|8.05|7.95|Downward|529|5,743,545
TFFIF|2023-01-18|2023-01-24|5|8.1|8.2|0.1|1.23|2|0|8.2|8.0|Upward|534|15,915,581
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|539|12,364,080
TFFIF|2023-02-01|2023-02-01|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|540|2,482,129
TFFIF|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.25|8.15|Downward|541|1,039,802
TFFIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.3|8.15|Upward|542|3,991,431
TFFIF|2023-02-06|2023-02-14|7|8.2|8.1|-0.1|-1.22|-2|-1|8.25|8.05|Downward|549|16,748,660
TMT|2023-01-16|2023-01-17|2|8.0|8.0|0.0|0.0|0|0|8.05|7.95|Downward|551|881,510
TMT|2023-01-18|2023-01-24|5|8.05|8.45|0.4|4.97|8|1|8.45|8.0|Upward|556|3,289,220
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|563|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|564|162,400
TMT|2023-02-06|2023-02-09|4|8.15|8.05|-0.1|-1.23|-2|-1|8.25|8.0|Downward|568|760,892
TMT|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.2|8.0|Upward|569|158,167
TMT|2023-02-13|2023-02-14|2|8.05|7.95|-0.1|-1.24|-2|-1|8.1|7.95|Downward|571|558,286
WHAIR|2023-01-16|2023-01-16|1|7.5|7.5|0.0|0.0|0|0|7.55|7.4|Downward|572|1,743,636
WHAIR|2023-01-17|2023-01-20|4|7.55|7.95|0.4|5.3|8|2|8.0|7.45|Upward|576|6,455,396
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|578|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|580|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|582|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|586|3,326,380
WHAIR|2023-02-06|2023-02-10|5|8.0|7.9|-0.1|-1.25|-2|-1|8.1|7.85|Downward|591|2,057,078
WHAIR|2023-02-13|2023-02-14|2|7.95|7.95|0.0|0.0|0|0|8.0|7.8|Upward|593|482,551
WHART|2023-01-16|2023-01-19|4|11.0|12.0|1.0|9.09|10|2|12.2|10.8|Upward|597|19,902,941
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|602|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|604|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|605|1,239,474
WHART|2023-02-01|2023-02-03|3|11.7|11.8|0.1|0.85|1|0|11.8|11.5|Upward|608|3,044,650
WHART|2023-02-06|2023-02-07|2|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|610|1,507,517
WHART|2023-02-08|2023-02-08|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|611|459,646
WHART|2023-02-09|2023-02-09|1|11.6|11.6|0.0|0.0|0|0|11.7|11.5|Downward|612|927,026
WHART|2023-02-10|2023-02-10|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|613|632,010
WHART|2023-02-13|2023-02-13|1|11.5|11.5|0.0|0.0|0|0|11.7|11.5|Downward|614|1,544,552
WHART|2023-02-14|2023-02-14|1|11.6|11.6|0.0|0.0|0|0|11.6|11.5|Upward|614|2,133,923
ruby/../Data/summary.csv

In [20]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [21]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [22]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [23]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [26]:
name_up = 'PTTGC'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [27]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [28]:
name_down = 'SINGER'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [29]:
df_groupby_trend = df.groupby('trend')

In [30]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [31]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [32]:
#df.groupby('trend').days.max()

In [33]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   15    137    2.00  2.61
Upward      6    127    2.00  2.01

In [34]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [35]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [36]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
15,BANPU,01-23,02-10,15,12.50,10.90,-12.80,-16,-2,12.60,10.70,2058642124,Downward

### Individual stock analysis

In [37]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [38]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   50.34 15553077.45 50.86 49.78
std     0.66 10987087.58  0.73  0.54
min    49.25  6399065.00 49.50 49.00
25%    49.81  9178235.00 50.50 49.31
50%    50.38 12735815.50 50.88 49.75
75%    50.69 17907678.75 51.44 50.00
max    51.50 56118407.00 52.50 50.75

In [39]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [40]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   27.63  7879138.00 28.42 27.26
std     1.68 15948166.30  0.89  1.73
min    21.10  1866964.00 27.00 20.50
25%    27.50  2781818.00 27.75 27.00
50%    28.00  3671812.50 28.38 27.50
75%    28.25  6819605.50 28.75 28.00
max    30.00 78498773.00 30.75 29.75

In [41]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [42]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [43]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-14'
ORDER BY name, date

In [44]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-02-14   2.44  16016716   2.52   2.42
1    ADVANC  2023-02-14 208.00   8697801 211.00 206.00
2        AH  2023-02-14  29.75   1947585  30.25  29.50
3       AIE  2023-02-14   2.88   1510939   2.94   2.86
4    AIMIRT  2023-02-14  12.20     10200  12.30  12.20
..      ...         ...    ...       ...    ...    ...
188   WHAIR  2023-02-14   7.95    290250   8.00   7.85
189   WHART  2023-02-14  11.60   2133923  11.60  11.50
190   WHAUP  2023-02-14   4.12   3580118   4.12   4.02
191    WICE  2023-02-14  10.60   4243538  10.90  10.60
192    WORK  2023-02-14  17.70   2162925  18.30  17.70

[193 rows x 6 columns]