In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 18), datetime.date(2023, 1, 17))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-18
yesterday: 2023-01-17 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-20 00:00:00   Tuesday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CKP', 'CPF', 'CPNREIT', 'GVREIT', 'IVL', 'JMART', 'MAKRO', 'ORI', 'PTT', 'PTTGC', 'SCC', 'SINGER', 'SYNEX', 'TFFIF', 'TFG', 'TMT', 'WHAIR'"

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-20 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CKP', 'CPF', 'CPNREIT', 'GVREIT', 'IVL', 'JMART', 'MAKRO', 'ORI', 'PTT', 'PTTGC', 'SCC', 'SINGER', 'SYNEX', 'TFFIF', 'TFG', 'TMT', 'WHAIR')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty   maxp   minp
101    CPF  2023-01-13   24.2  12475309  24.30  24.00
207  MAKRO  2023-01-16   43.5  34568947  43.50  42.25
196  MAKRO  2022-12-29   39.5   1992548  39.50  39.25
397    TMT  2023-01-17    8.0    356285   8.05   8.00
356  TFFIF  2023-01-18    8.1   4848728   8.15   8.00

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [36]:
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [37]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [38]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-20|2022-12-21|2|2.94|2.94|0.0|0.0|0|0|2.98|2.92||3|4,708,127
ASP|2022-12-22|2022-12-30|7|2.96|2.98|0.02|0.68|1|0|2.98|2.92|Upward|10|11,181,503
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|13|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|22|22,455,682
BANPU|2022-12-20|2022-12-20|1|13.6|13.6|0.0|0.0|0|0|13.6|13.4|Upward|23|75,293,568
BANPU|2022-12-21|2022-12-21|1|13.5|13.5|0.0|0.0|0|0|13.7|13.4|Downward|24|39,862,227
BANPU|2022-12-22|2022-12-22|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Upward|25|62,947,205
BANPU|2022-12-23|2022-12-23|1|13.4|13.4|0.0|0.0|0|0|13.6|13.4|Downward|26|56,515,404
BANPU|2022-12-26|2022-12-26|1|13.5|13.5|0.0|0.0|0|0|13.6|13.3|Upward|27|54,412,026
BANPU|2022-12-27|2022-12-27|1|13.4|13.4|0.0|0.0|0|0|13.5|13.4|Downward|28|39,796,280
BANPU|2022-12-28|2022-12-30|3|13.7|13.7|0.0|0.0|0|0|13.8|13.4|Upward|31|166,355,695
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|35|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|37|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|39|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|40|107,438,620
BANPU|2023-01-16|2023-01-18|3|12.4|12.4|0.0|0.0|0|0|12.5|12.2|Downward|43|165,702,602
BCH|2022-12-20|2022-12-21|2|19.8|19.6|-0.2|-1.01|-2|-1|19.9|19.3|Downward|45|12,716,247
BCH|2022-12-22|2022-12-29|6|19.7|21.1|1.4|7.11|14|2|21.1|19.6|Upward|51|44,563,932
BCH|2022-12-30|2022-12-30|1|20.5|20.5|0.0|0.0|0|0|21.1|20.5|Downward|52|25,899,919
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|56|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|57|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|58|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|60|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|62|9,179,643
BCH|2023-01-17|2023-01-18|2|21.4|21.2|-0.2|-0.93|-2|-1|21.6|21.2|Downward|64|14,804,508
CKP|2022-12-20|2022-12-22|3|4.66|4.62|-0.04|-0.86|-2|-1|4.76|4.6|Downward|67|36,974,023
CKP|2022-12-23|2022-12-27|3|4.64|4.64|0.0|0.0|0|0|4.68|4.6|Upward|70|24,367,034
CKP|2022-12-28|2023-01-03|5|4.6|4.52|-0.08|-1.74|-4|-1|4.66|4.52|Downward|74|72,153,852
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|8|1|4.76|4.52|Upward|81|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|85|70,164,548
CPF|2022-12-20|2022-12-21|2|24.2|24.2|0.0|0.0|0|0|24.3|23.8|Downward|87|39,128,172
CPF|2022-12-22|2022-12-23|2|24.4|24.6|0.2|0.82|2|1|24.6|24.1|Upward|89|26,575,715
CPF|2022-12-26|2022-12-26|1|24.5|24.5|0.0|0.0|0|0|24.8|24.5|Downward|90|16,076,902
CPF|2022-12-27|2022-12-27|1|24.6|24.6|0.0|0.0|0|0|24.7|24.4|Upward|91|20,019,341
CPF|2022-12-28|2022-12-28|1|24.5|24.5|0.0|0.0|0|0|24.7|24.5|Downward|92|17,586,551
CPF|2022-12-29|2022-12-30|2|24.7|24.8|0.1|0.4|1|0|25.0|24.4|Upward|94|53,728,610
CPF|2023-01-03|2023-01-11|7|24.6|24.0|-0.6|-2.44|-6|-1|24.9|24.0|Downward|101|153,266,724
CPF|2023-01-12|2023-01-17|4|24.2|24.2|0.0|0.0|0|0|24.3|24.0|Upward|105|58,497,259
CPF|2023-01-18|2023-01-18|1|24.1|24.1|0.0|0.0|0|0|24.2|24.0|Downward|106|7,635,608
CPNREIT|2022-12-20|2022-12-21|2|19.4|19.4|0.0|0.0|0|0|19.5|19.4|Downward|108|740,604
CPNREIT|2022-12-22|2022-12-26|3|19.5|19.5|0.0|0.0|0|0|19.6|19.4|Upward|111|5,482,740
CPNREIT|2022-12-27|2022-12-29|3|19.4|19.4|0.0|0.0|0|0|19.5|19.4|Downward|114|1,746,309
CPNREIT|2022-12-30|2023-01-09|7|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Upward|120|5,177,343
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|121|2,419,471
CPNREIT|2023-01-11|2023-01-18|6|19.3|19.9|0.6|3.11|6|1|19.9|19.1|Upward|127|7,931,450
GVREIT|2022-12-20|2022-12-28|7|9.0|9.15|0.15|1.67|3|0|9.15|8.9|Upward|134|852,734
GVREIT|2022-12-29|2022-12-30|2|9.1|9.1|0.0|0.0|0|0|9.15|9.05|Downward|136|1,280,955
GVREIT|2023-01-03|2023-01-03|1|9.15|9.15|0.0|0.0|0|0|9.15|9.05|Upward|137|174,743
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|140|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|141|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|147|1,449,890
GVREIT|2023-01-18|2023-01-18|1|9.0|9.0|0.0|0.0|0|0|9.0|8.85|Upward|148|558,200
IVL|2022-12-20|2022-12-20|1|39.75|39.75|0.0|0.0|0|0|40.25|39.5|Upward|149|8,698,202
IVL|2022-12-21|2022-12-23|3|39.5|39.5|0.0|0.0|0|0|40.0|39.0|Downward|152|19,503,679
IVL|2022-12-26|2022-12-30|5|39.75|40.75|1.0|2.52|4|0|41.25|39.5|Upward|157|56,581,013
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-10|-3|41.0|37.0|Downward|161|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|169|208,263,258
JMART|2022-12-20|2022-12-22|3|40.0|40.5|0.5|1.25|2|0|41.5|39.5|Upward|172|11,412,876
JMART|2022-12-23|2022-12-23|1|39.25|39.25|0.0|0.0|0|0|40.25|39.0|Downward|173|6,170,257
JMART|2022-12-26|2022-12-29|4|39.5|41.5|2.0|5.06|8|2|41.5|39.25|Upward|177|19,466,777
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.75|40.75|Downward|178|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|179|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|181|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|187|44,921,819
JMART|2023-01-16|2023-01-18|3|41.75|41.0|-0.75|-1.8|-3|-1|42.75|40.75|Downward|190|17,727,350
MAKRO|2022-12-20|2022-12-21|2|38.0|37.5|-0.5|-1.32|-2|-1|39.0|37.25|Downward|192|15,621,337
MAKRO|2022-12-22|2022-12-27|4|39.25|39.75|0.5|1.27|2|0|40.0|37.75|Upward|196|45,705,168
MAKRO|2022-12-28|2022-12-28|1|39.25|39.25|0.0|0.0|0|0|40.0|39.0|Downward|197|10,736,659
MAKRO|2022-12-29|2023-01-09|8|39.5|43.0|3.5|8.86|14|1|43.0|39.25|Upward|204|133,585,293
MAKRO|2023-01-10|2023-01-12|3|42.5|42.0|-0.5|-1.18|-2|-1|43.25|41.5|Downward|207|59,151,829
MAKRO|2023-01-13|2023-01-16|2|42.5|43.5|1.0|2.35|4|2|43.5|41.75|Upward|209|51,570,802
MAKRO|2023-01-17|2023-01-17|1|42.75|42.75|0.0|0.0|0|0|43.5|42.5|Downward|210|13,696,528
MAKRO|2023-01-18|2023-01-18|1|43.0|43.0|0.0|0.0|0|0|43.0|42.5|Upward|211|12,485,205
ORI|2022-12-20|2022-12-21|2|10.8|10.9|0.1|0.93|1|0|11.0|10.7|Upward|213|9,771,880
ORI|2022-12-22|2022-12-22|1|10.8|10.8|0.0|0.0|0|0|11.0|10.8|Downward|214|1,681,274
ORI|2022-12-23|2022-12-30|6|11.2|12.1|0.9|8.04|9|1|12.1|10.8|Upward|220|68,755,307
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|224|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|225|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|227|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|230|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|232|28,566,002
PTT|2022-12-20|2022-12-21|2|31.25|31.0|-0.25|-0.8|-1|-1|31.5|30.75|Downward|234|124,850,760
PTT|2022-12-22|2022-12-30|7|31.5|33.25|1.75|5.56|7|1|33.5|31.0|Upward|241|394,537,137
PTT|2023-01-03|2023-01-04|2|32.75|32.0|-0.75|-2.29|-3|-2|33.5|32.0|Downward|243|101,341,906
PTT|2023-01-05|2023-01-16|8|32.25|33.75|1.5|4.65|6|0|34.0|32.0|Upward|251|401,470,936
PTT|2023-01-17|2023-01-18|2|33.5|33.5|0.0|0.0|0|0|34.0|33.25|Downward|253|115,151,722
PTTGC|2022-12-20|2022-12-23|4|45.75|44.75|-1.0|-2.19|-4|-1|46.5|44.5|Downward|257|46,988,625
PTTGC|2022-12-26|2022-12-29|4|45.5|47.5|2.0|4.4|8|2|47.75|44.5|Upward|261|76,211,587
PTTGC|2022-12-30|2023-01-03|3|47.25|46.75|-0.5|-1.06|-2|-1|47.75|46.5|Downward|263|18,960,635
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|264|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|266|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|269|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|271|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|274|57,760,246
SCC|2022-12-20|2022-12-20|1|332.0|332.0|0.0|0.0|0|0|332.0|328.0|Upward|275|2,421,904
SCC|2022-12-21|2022-12-21|1|331.0|331.0|0.0|0.0|0|0|332.0|329.0|Downward|276|920,305
SCC|2022-12-22|2022-12-29|6|332.0|344.0|12.0|3.61|12|2|344.0|329.0|Upward|282|7,097,734
SCC|2022-12-30|2023-01-03|3|342.0|342.0|0.0|0.0|0|0|344.0|340.0|Downward|284|3,705,436
SCC|2023-01-04|2023-01-11|6|345.0|359.0|14.0|4.06|14|2|360.0|340.0|Upward|290|14,796,849
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|293|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|294|1,930,796
SCC|2023-01-18|2023-01-18|1|356.0|356.0|0.0|0.0|0|0|359.0|355.0|Downward|295|1,897,911
SINGER|2022-12-20|2022-12-23|4|29.25|27.75|-1.5|-5.13|-6|-2|30.5|27.0|Downward|299|31,271,427
SINGER|2022-12-26|2022-12-30|5|28.25|28.75|0.5|1.77|2|0|29.25|27.5|Upward|304|27,255,168
SINGER|2023-01-03|2023-01-06|4|28.5|27.0|-1.5|-5.26|-6|-2|28.75|26.75|Downward|308|23,648,943
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|309|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|310|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|313|17,684,289
SINGER|2023-01-16|2023-01-18|3|30.0|28.5|-1.5|-5.0|-6|-2|30.75|28.0|Downward|316|14,548,194
SYNEX|2022-12-20|2022-12-21|2|15.6|15.6|0.0|0.0|0|0|16.0|15.5|Downward|318|3,156,425
SYNEX|2022-12-22|2022-12-22|1|15.9|15.9|0.0|0.0|0|0|15.9|15.5|Upward|319|1,424,387
SYNEX|2022-12-23|2022-12-26|2|15.7|15.7|0.0|0.0|0|0|15.9|15.5|Downward|321|1,525,672
SYNEX|2022-12-27|2022-12-27|1|16.1|16.1|0.0|0.0|0|0|16.2|15.7|Upward|322|2,236,102
SYNEX|2022-12-28|2022-12-29|2|15.9|15.9|0.0|0.0|0|0|16.1|15.7|Downward|324|2,285,847
SYNEX|2022-12-30|2023-01-03|3|16.4|16.7|0.3|1.83|3|1|17.0|16.0|Upward|326|8,531,030
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|327|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|330|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|331|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|333|7,081,640
SYNEX|2023-01-13|2023-01-18|4|17.1|16.9|-0.2|-1.17|-2|-1|17.5|16.7|Downward|337|6,763,836
TFFIF|2022-12-20|2022-12-21|2|7.7|7.7|0.0|0.0|0|0|7.75|7.6|Downward|339|3,373,780
TFFIF|2022-12-22|2022-12-23|2|7.75|7.8|0.05|0.65|1|0|7.8|7.7|Upward|341|1,712,534
TFFIF|2022-12-26|2022-12-30|5|7.75|7.65|-0.1|-1.29|-2|-1|7.8|7.6|Downward|346|7,610,655
TFFIF|2023-01-03|2023-01-03|1|7.7|7.7|0.0|0.0|0|0|7.75|7.65|Upward|347|745,322
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|348|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|351|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|352|1,298,307
TFFIF|2023-01-11|2023-01-18|6|7.85|8.1|0.25|3.18|5|0|8.15|7.8|Upward|358|15,845,361
TFG|2022-12-20|2022-12-20|1|5.1|5.1|0.0|0.0|0|0|5.25|5.1|Upward|359|5,983,621
TFG|2022-12-21|2022-12-21|1|5.0|5.0|0.0|0.0|0|0|5.15|4.98|Downward|360|9,550,066
TFG|2022-12-22|2022-12-28|5|5.1|5.2|0.1|1.96|2|0|5.3|5.0|Upward|365|22,408,329
TFG|2022-12-29|2023-01-04|5|5.15|5.1|-0.05|-0.97|-1|-1|5.25|5.05|Downward|369|19,636,351
TFG|2023-01-05|2023-01-05|1|5.15|5.15|0.0|0.0|0|0|5.15|5.05|Upward|370|8,718,141
TFG|2023-01-06|2023-01-09|2|5.05|5.05|0.0|0.0|0|0|5.2|5.05|Downward|372|10,608,653
TFG|2023-01-10|2023-01-18|7|5.25|5.45|0.2|3.81|4|0|5.6|5.05|Upward|379|74,083,679
TMT|2022-12-20|2022-12-23|4|7.25|7.65|0.4|5.52|8|2|7.7|7.1|Upward|383|2,359,935
TMT|2022-12-26|2022-12-26|1|7.55|7.55|0.0|0.0|0|0|7.65|7.55|Downward|384|298,034
TMT|2022-12-27|2022-12-29|3|7.7|7.9|0.2|2.6|4|1|7.9|7.5|Upward|387|1,017,189
TMT|2022-12-30|2023-01-05|5|7.8|7.65|-0.15|-1.92|-3|-1|7.95|7.6|Downward|391|1,180,838
TMT|2023-01-06|2023-01-18|9|7.7|8.05|0.35|4.55|7|0|8.1|7.55|Upward|400|3,253,019
WHAIR|2022-12-20|2022-12-28|7|7.3|7.65|0.35|4.79|7|1|7.65|7.3|Upward|407|1,771,628
WHAIR|2022-12-29|2023-01-04|5|7.6|7.45|-0.15|-1.97|-3|-1|7.65|7.4|Downward|411|2,468,511
WHAIR|2023-01-05|2023-01-05|1|7.55|7.55|0.0|0.0|0|0|7.55|7.5|Upward|412|674,738
WHAIR|2023-01-06|2023-01-11|4|7.5|7.45|-0.05|-0.67|-1|-1|7.6|7.45|Downward|416|3,082,921
WHAIR|2023-01-12|2023-01-18|5|7.5|7.6|0.1|1.33|2|0|7.65|7.4|Upward|420|8,034,095
ruby/../Data/summary.csv

In [39]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [40]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [41]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [17]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,20,21,20,7,60,63,18,34,9,4,63,59,72,72,21,20
Upward,20,20,21,9,60,60,29,43,13,4,63,61,72,72,20,21

In [18]:
mask_p = df['to_md'] == '01-18'
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [19]:
mask_m = df['to_md'] == '01-18'
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
mask_n = df.name == 'IVL'
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')
df_groupby_trend.ngroups

2

In [22]:
# Stat of each group
df_groupby_trend.size()

trend
Downward    72
Upward      72
dtype: int64

In [23]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [24]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [25]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-20,2022-12-21,2,2.94,2.94,0.0,0.0,0,0,2.98,2.92,4708127,NaN,3,12-20,12-21

In [26]:
df.groupby('trend').days.max()

trend
Downward    7
Upward      9
Name: days, dtype: int64

In [27]:
df.query('days == 9')[cols].style.format(format_dict)

In [28]:
df.query('days == 7 and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
36,CPF,01-03,01-11,7,24.6,24.0,-2.44,-6,-1,24.9,24.0,153266724,Downward

In [29]:
df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

       name     trend      days
0       ASP  Downward  3.000000
1       ASP    Upward  8.000000
2     BANPU  Downward  2.000000
3     BANPU    Upward  1.500000
4       BCH  Downward  1.600000
5       BCH    Upward  3.250000
6       CKP  Downward  4.000000
7       CKP    Upward  5.000000
8       CPF  Downward  2.400000
9       CPF    Upward  2.250000
10  CPNREIT  Downward  2.000000
11  CPNREIT    Upward  5.333333
12   GVREIT  Downward  3.666667
13   GVREIT    Upward  2.500000
14      IVL  Downward  3.500000
15      IVL    Upward  4.666667
16    JMART  Downward  1.750000
17    JMART    Upward  3.500000
18    MAKRO  Downward  1.750000
19    MAKRO    Upward  3.750000
20      ORI  Downward  2.250000
21      ORI    Upward  3.000000
22      PTT  Downward  2.000000
23      PTT    Upward  7.500000
24    PTTGC  Downward  2.750000
25    PTTGC    Upward  2.750000
26      SCC  Downward  2.000000
27      SCC    Upward  3.500000
28   SINGER  Downward  3.000000
29   SINGER    Upward  3.000000
30    SYNEX  Downward  2.000000
31    SYNEX    Upward  2.000000
32    TFFIF  Downward  2.250000
33    TFFIF    Upward  3.000000
34      TFG  Downward  2.666667
35      TFG    Upward  3.500000
36      TMT  Downward  3.000000
37      TMT    Upward  5.333333
38    WHAIR  Downward  4.500000
39    WHAIR    Upward  4.333333

In [30]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    7     72     2.0  2.430556
Upward      9     72     3.0  3.500000

### Individual stock analysis

In [31]:
name = 'SINGER'
df.query('name == @name')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   28.77   6406978.19  29.38  28.30
std     0.94   3248376.70   1.01   1.00
min    27.00   1984596.00  27.25  26.75
25%    28.25   4615984.00  28.75  27.50
50%    28.75   6117144.00  29.50  28.25
75%    29.50   7517233.00  30.00  29.25
max    30.25  15522537.00  31.25  30.00

In [33]:
mask_p = df['to_md'] == '01-18'
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [34]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)