In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 30), datetime.date(2023, 1, 29))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-30
Today in mm-dd format: 01-30
yesterday: 2023-01-27 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-30 00:00:00   Friday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'MC', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-30 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

       name        date  price       qty   maxp   minp
280     KCE  2023-01-11  49.25  19885273  50.75  49.25
487  SINGER  2023-01-06  27.00   6407824  27.25  26.75
85      CKP  2023-01-03   4.52  12780550   4.60   4.52
59      BCH  2023-01-25  20.60  11168977  21.00  20.60
476    SENA  2023-01-20   3.94   1140626   3.94   3.90

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-30|2022-12-30|1|2.98|2.98|0.0|0.0|0|0|2.98|2.96||2|1,971,614
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|5|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|14|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|16|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|17|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|18|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|19|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|20|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|22|1,798,533
BANPU|2022-12-30|2022-12-30|1|13.7|13.7|0.0|0.0|0|0|13.8|13.6|Upward|23|49,373,887
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|27|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|29|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|31|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|32|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|36|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|37|193,937,283
BANPU|2023-01-23|2023-01-30|6|12.5|12.0|-0.5|-4.0|-5|-1|12.6|12.0|Downward|43|486,226,331
BCH|2022-12-30|2022-12-30|1|20.5|20.5|0.0|0.0|0|0|21.1|20.5|Downward|44|25,899,919
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|48|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|49|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|50|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|52|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|54|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|61|46,355,474
BCH|2023-01-26|2023-01-30|3|20.7|21.1|0.4|1.93|4|1|21.2|20.5|Upward|64|27,540,723
CK|2022-12-30|2022-12-30|1|24.3|24.3|0.0|0.0|0|0|24.3|24.0|Upward|65|2,423,298
CK|2023-01-03|2023-01-10|6|23.9|23.5|-0.4|-1.67|-4|-1|24.5|23.2|Downward|71|38,379,065
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|73|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|75|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|76|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|77|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|78|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|81|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|82|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|84|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|85|2,492,389
CKP|2022-12-30|2022-12-30|1|4.56|4.56|0.0|0.0|0|0|4.66|4.56|Upward|86|20,163,214
CKP|2023-01-03|2023-01-03|1|4.52|4.52|0.0|0.0|0|0|4.6|4.52|Downward|87|12,780,550
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|8|1|4.76|4.52|Upward|94|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|98|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|100|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|104|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|105|6,963,352
CKP|2023-01-30|2023-01-30|1|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|106|6,324,039
CPNREIT|2022-12-30|2023-01-10|8|19.5|18.8|-0.7|-3.59|-7|-1|19.7|18.8|Downward|113|7,596,814
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|120|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|123|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|125|2,216,218
CPNREIT|2023-01-27|2023-01-30|2|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Downward|127|2,512,768
DCC|2022-12-30|2023-01-04|4|2.82|2.8|-0.02|-0.71|-1|-1|2.84|2.8|Downward|130|14,912,708
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|134|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|135|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|136|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|139|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|140|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|141|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|143|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|144|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|145|6,076,325
DCC|2023-01-26|2023-01-27|2|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|147|21,773,267
DCC|2023-01-30|2023-01-30|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|148|6,661,984
DIF|2022-12-30|2023-01-04|4|13.2|13.3|0.1|0.76|1|0|13.3|13.2|Upward|151|14,006,802
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|153|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|162|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|165|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|166|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|167|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|168|7,462,352
DIF|2023-01-30|2023-01-30|1|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|169|2,980,275
GVREIT|2022-12-30|2022-12-30|1|9.1|9.1|0.0|0.0|0|0|9.15|9.05|Downward|170|534,645
GVREIT|2023-01-03|2023-01-03|1|9.15|9.15|0.0|0.0|0|0|9.15|9.05|Upward|171|174,743
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|174|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|175|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|181|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|186|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|187|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|188|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|189|281,301
GVREIT|2023-01-30|2023-01-30|1|9.55|9.55|0.0|0.0|0|0|9.65|9.45|Upward|190|212,621
IVL|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.25|40.75|Upward|191|13,313,221
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-10|-3|41.0|37.0|Downward|195|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|203|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|204|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|205|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|209|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|211|22,582,017
JASIF|2022-12-30|2023-01-12|10|8.05|8.25|0.2|2.48|4|0|8.3|8.0|Upward|220|44,816,906
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|221|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|223|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|224|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|228|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|232|28,383,533
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.75|40.75|Downward|233|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|234|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|236|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|242|44,921,819
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|251|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|252|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|253|9,743,425
JMT|2022-12-30|2023-01-06|6|69.0|66.0|-3.0|-4.35|-12|-2|70.0|65.25|Downward|258|21,306,998
JMT|2023-01-09|2023-01-13|5|68.25|69.5|1.25|1.83|5|1|71.0|66.75|Upward|263|36,049,399
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|272|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|273|16,158,754
JMT|2023-01-30|2023-01-30|1|53.5|53.5|0.0|0.0|0|0|56.25|52.75|Downward|274|19,107,459
KCE|2022-12-30|2022-12-30|1|46.5|46.5|0.0|0.0|0|0|47.5|46.25|Downward|275|22,449,277
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|0|0|48.0|46.25|Upward|276|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-4|-2|47.5|44.5|Downward|278|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|281|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|282|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|283|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|289|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|290|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|291|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|292|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|293|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|294|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|295|10,465,232
MC|2022-12-30|2023-01-05|5|10.5|10.5|0.0|0.0|0|0|10.6|10.3|Downward|299|1,801,228
MC|2023-01-06|2023-01-10|3|10.8|11.2|0.4|3.7|4|1|11.2|10.5|Upward|302|5,029,087
MC|2023-01-11|2023-01-11|1|11.0|11.0|0.0|0.0|0|0|11.1|10.7|Downward|303|1,488,870
MC|2023-01-12|2023-01-12|1|11.1|11.1|0.0|0.0|0|0|11.2|10.8|Upward|304|1,363,029
MC|2023-01-13|2023-01-13|1|11.0|11.0|0.0|0.0|0|0|11.3|11.0|Downward|305|1,259,169
MC|2023-01-16|2023-01-19|4|11.2|11.7|0.5|4.46|5|1|11.7|11.0|Upward|309|6,694,798
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-3|-2|11.8|11.3|Downward|311|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|3|1|11.9|11.3|Upward|314|4,617,106
MC|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.9|11.7|Downward|316|900,523
MCS|2022-12-30|2022-12-30|1|8.95|8.95|0.0|0.0|0|0|9.0|8.9|Downward|317|505,700
MCS|2023-01-03|2023-01-06|4|9.0|9.3|0.3|3.33|6|1|9.35|8.95|Upward|321|4,383,825
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|322|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|324|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|325|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|330|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|331|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|332|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|333|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|334|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|335|1,271,966
MCS|2023-01-27|2023-01-30|2|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|337|1,696,878
NER|2022-12-30|2023-01-03|3|6.35|6.35|0.0|0.0|0|0|6.45|6.25|Upward|339|16,321,449
NER|2023-01-04|2023-01-05|2|6.3|6.25|-0.05|-0.79|-1|-1|6.45|6.2|Downward|341|23,830,282
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|342|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|343|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|344|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|345|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|347|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|352|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|353|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|354|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|356|42,913,468
NER|2023-01-27|2023-01-30|2|6.6|6.5|-0.1|-1.52|-2|-1|6.7|6.5|Downward|358|21,546,915
ORI|2022-12-30|2023-01-06|6|12.1|11.6|-0.5|-4.13|-5|-1|12.3|11.4|Downward|363|65,736,112
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|364|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|366|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|369|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|371|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|374|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|377|16,286,040
ORI|2023-01-27|2023-01-30|2|11.9|12.0|0.1|0.84|1|0|12.2|11.6|Upward|379|22,659,438
PTTGC|2022-12-30|2022-12-30|1|47.25|47.25|0.0|0.0|0|0|47.75|47.0|Upward|380|10,612,230
PTTGC|2023-01-03|2023-01-03|1|46.75|46.75|0.0|0.0|0|0|47.5|46.5|Downward|381|8,348,405
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|382|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|384|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|387|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|389|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|392|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|394|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|397|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|398|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|399|13,790,565
PTTGC|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.75|Downward|400|8,200,257
RCL|2022-12-30|2023-01-04|4|30.75|29.25|-1.5|-4.88|-6|-2|31.5|29.25|Downward|403|12,188,423
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|407|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|408|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|409|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|411|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|413|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|415|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|418|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|419|2,352,538
RCL|2023-01-27|2023-01-30|2|31.75|32.25|0.5|1.57|2|1|32.75|31.0|Upward|421|7,444,791
SCC|2022-12-30|2023-01-11|9|342.0|359.0|17.0|4.97|17|1|360.0|340.0|Upward|429|18,502,285
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|432|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|433|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|440|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|442|3,832,045
SCCC|2022-12-30|2023-01-06|6|153.5|158.5|5.0|3.26|10|1|159.0|153.0|Upward|447|818,633
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|450|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|456|713,373
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|461|597,538
SCCC|2023-01-27|2023-01-30|2|158.5|158.5|0.0|0.0|0|0|159.0|157.0|Upward|463|280,914
SENA|2022-12-30|2023-01-03|3|3.94|3.94|0.0|0.0|0|0|3.96|3.92|Upward|465|1,806,868
SENA|2023-01-04|2023-01-05|2|3.92|3.9|-0.02|-0.51|-1|-1|3.96|3.9|Downward|467|1,498,341
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|470|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|473|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|475|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|477|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|479|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|480|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|481|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|483|2,050,656
SENA|2023-01-30|2023-01-30|1|3.94|3.94|0.0|0.0|0|0|3.96|3.9|Upward|484|3,391,051
SINGER|2022-12-30|2022-12-30|1|28.75|28.75|0.0|0.0|0|0|29.25|28.25|Upward|485|7,336,378
SINGER|2023-01-03|2023-01-06|4|28.5|27.0|-1.5|-5.26|-6|-2|28.75|26.75|Downward|489|23,648,943
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|490|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|491|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|494|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|500|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|501|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|503|11,350,118
SINGER|2023-01-27|2023-01-30|2|27.5|27.5|0.0|0.0|0|0|28.0|27.0|Upward|505|5,201,834
STA|2022-12-30|2022-12-30|1|21.1|21.1|0.0|0.0|0|0|21.6|20.8|Upward|506|6,986,609
STA|2023-01-03|2023-01-04|2|20.8|20.6|-0.2|-0.96|-2|-1|21.1|20.4|Downward|508|5,861,113
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|511|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|513|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|515|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|516|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|517|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|518|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|519|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|521|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|525|45,950,994
STA|2023-01-30|2023-01-30|1|22.2|22.2|0.0|0.0|0|0|22.8|22.2|Downward|526|6,191,496
SYNEX|2022-12-30|2022-12-30|1|16.4|16.4|0.0|0.0|0|0|16.6|16.0|Downward|527|4,934,430
SYNEX|2023-01-03|2023-01-03|1|16.7|16.7|0.0|0.0|0|0|17.0|16.4|Upward|528|3,596,600
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|529|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|532|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|533|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|535|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|541|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|543|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|545|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|547|2,438,448
TFFIF|2022-12-30|2023-01-03|3|7.65|7.7|0.05|0.65|1|0|7.75|7.65|Upward|549|1,164,087
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|550|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|553|4,181,523

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [18]:
name_up = 'TTB'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [19]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')

In [22]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [23]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [24]:
#df.groupby('trend').days.max()

In [25]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    9    131     2.0  2.450382
Upward     13    131     2.0  2.633588

In [26]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [27]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [28]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
96,JMART,01-16,01-26,9,41.75,35.50,-14.97,-25,-3,42.75,35.25,118032446,Downward
101,JMT,01-16,01-26,9,68.25,53.75,-21.25,-58,-7,69.75,53.75,129571700,Downward

In [27]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

### Individual stock analysis

In [29]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [30]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  21.00  2.100000e+01  21.00  21.00
mean    1.43  3.156302e+08   1.44   1.42
std     0.02  1.579009e+08   0.02   0.02
min     1.41  1.320739e+08   1.41   1.38
25%     1.42  1.736250e+08   1.43   1.40
50%     1.43  2.705970e+08   1.44   1.42
75%     1.45  4.393199e+08   1.45   1.43
max     1.47  6.621394e+08   1.47   1.45

In [31]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price           qty   maxp   minp
count  21.00  2.100000e+01  21.00  21.00
mean   12.55  1.152042e+08  12.68  12.40
std     0.38  7.893362e+07   0.43   0.41
min    12.00  3.089415e+07  12.30  12.00
25%    12.30  4.943300e+07  12.40  12.20
50%    12.50  1.040914e+08  12.50  12.30
75%    12.50  1.512358e+08  12.70  12.40
max    13.70  3.054360e+08  13.80  13.60

In [33]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [34]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)