In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 16), datetime.date(2023, 1, 15))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-16
yesterday: 2023-01-13 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-16 00:00:00   Friday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [6]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-16 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

        name        date  price      qty   maxp   minp
73   CPNREIT  2022-12-30  19.50   764312  19.60  19.40
275      ORI  2022-12-20  10.80  5833217  11.00  10.70
246      MCS  2023-01-09   9.25  1049270   9.35   9.15
452    TFFIF  2023-01-03   7.70   745322   7.75   7.65
263      NER  2023-01-03   6.35  9308876   6.40   6.25

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)

### After call ruby ruby\chat-fin.rb

In [10]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [11]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [13]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,25,21,21,6,76,74,17,35,10,4,76,74,95,95,21,21
Upward,25,21,21,12,79,77,26,51,16,5,82,77,101,101,21,21

In [14]:
yesterday, today

(datetime.date(2023, 1, 13), datetime.date(2023, 1, 16))

In [33]:
df.query('to_date == @today')[cols].style.format(format_dict)

In [17]:
mask = df.name == 'IVL'
df[mask][cols].style.format(format_dict)

In [18]:
pct = 3
df.query('to_date == @today and pct >= @pct')[cols].style.format(format_dict)

In [19]:
pct = -0.01
df.query('to_date == @today and pct <= @pct')[cols].style.format(format_dict)

In [20]:
# It returns a DataFrameGroupBy object
df_groupby_trend = df.groupby('trend')
type(df_groupby_trend)

pandas.core.groupby.generic.DataFrameGroupBy

In [21]:
# To get the number of groups
df_groupby_trend.ngroups

2

In [22]:
# Stat of each group
df_groupby_trend.size()

trend
Downward     95
Upward      101
dtype: int64

In [23]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [24]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [25]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-16,2022-12-16,1,2.96,2.96,0.0,0.0,0,0,2.98,2.96,1313820,NaN,2,12-16,12-16

In [26]:
df.groupby('trend').days.max()

trend
Downward     6
Upward      12
Name: days, dtype: int64

In [27]:
df.query('days == 12')[cols].style.format(format_dict)

In [28]:
df.query('days == 6 and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
54,IVL,12-16,12-23,6,40.0,39.5,-1.25,-2,-1,40.5,39.0,40952262,Downward

In [29]:
df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

       name     trend      days
0       ASP  Downward  3.000000
1       ASP    Upward  7.000000
2     BANPU  Downward  1.571429
3     BANPU    Upward  1.428571
4       BCH  Downward  2.000000
5       BCH    Upward  3.250000
6   CPNREIT  Downward  2.000000
7   CPNREIT    Upward  4.000000
8       DCC  Downward  1.250000
9       DCC    Upward  4.250000
10      DIF  Downward  1.333333
11      DIF    Upward  6.000000
12   GVREIT  Downward  3.333333
13   GVREIT    Upward  3.666667
14      IVL  Downward  5.000000
15      IVL    Upward  5.500000
16    JASIF  Downward  1.500000
17    JASIF    Upward  3.200000
18      KCE  Downward  1.833333
19      KCE    Upward  1.666667
20    MAKRO  Downward  1.750000
21    MAKRO    Upward  3.750000
22      MCS  Downward  2.000000
23      MCS    Upward  4.000000
24      NER  Downward  1.800000
25      NER    Upward  2.600000
26      ORI  Downward  2.500000
27      ORI    Upward  2.750000
28    PTTGC  Downward  3.000000
29    PTTGC    Upward  2.000000
30      RCL  Downward  1.800000
31      RCL    Upward  2.600000
32      SCC  Downward  2.250000
33      SCC    Upward  4.333333
34     SCCC  Downward  3.500000
35     SCCC    Upward  7.500000
36     SENA  Downward  3.333333
37     SENA    Upward  3.000000
38      STA  Downward  2.250000
39      STA    Upward  3.250000
40    SYNEX  Downward  2.000000
41    SYNEX    Upward  2.000000
42    TFFIF  Downward  2.750000
43    TFFIF    Upward  2.500000
44      TMT  Downward  3.000000
45      TMT    Upward  5.333333
46    WHAIR  Downward  3.333333
47    WHAIR    Upward  3.000000
48    WHART  Downward  1.250000
49    WHART    Upward  3.400000

In [30]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    6     95     2.0  2.200000
Upward     12    101     2.0  3.287129

### Individual stock analysis

In [31]:
name = 'IVL'
df.query('name == @name')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   40.21  17680405.62  40.68  39.76
std     1.04  19440341.03   0.89   1.07
min    37.75   3225857.00  39.00  37.00
25%    39.75   7697656.00  40.00  39.50
50%    40.00  11236280.00  40.50  39.50
75%    40.75  15587590.00  41.25  40.50
max    41.75  76125229.00  42.25  41.50