In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 24), datetime.date(2023, 1, 23))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-24
Today in mm-dd format: 01-24
yesterday: 2023-01-23 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-26 00:00:00   Monday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-26 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty   maxp   minp
386   SENA  2023-01-06   3.92   1569630   3.94   3.90
188  JASIF  2023-01-24   8.25   4070494   8.25   8.20
86     DCC  2022-12-28   2.82   2555887   2.82   2.80
557  WHART  2023-01-11  10.80    606452  10.80  10.70
165    IVL  2023-01-20  42.25  15314376  42.50  41.75

In [9]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [10]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [12]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-26|2022-12-29|4|2.96|2.96|0.0|0.0|0|0|2.98|2.94||5|7,510,389
ASP|2022-12-30|2022-12-30|1|2.98|2.98|0.0|0.0|0|0|2.98|2.96|Upward|6|1,971,614
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|9|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|18|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|20|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|21|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|22|2,396,809
BANPU|2022-12-26|2022-12-27|2|13.5|13.4|-0.1|-0.74|-1|-1|13.6|13.3|Downward|24|94,208,306
BANPU|2022-12-28|2022-12-30|3|13.7|13.7|0.0|0.0|0|0|13.8|13.4|Upward|27|166,355,695
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|31|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|33|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|35|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|36|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|40|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|41|193,937,283
BANPU|2023-01-23|2023-01-24|2|12.5|12.5|0.0|0.0|0|0|12.6|12.4|Downward|43|93,691,814
BCH|2022-12-26|2022-12-26|1|20.1|20.1|0.0|0.0|0|0|20.1|19.8|Downward|44|3,348,785
BCH|2022-12-27|2022-12-29|3|20.2|21.1|0.9|4.46|9|3|21.1|20.0|Upward|47|37,781,865
BCH|2022-12-30|2022-12-30|1|20.5|20.5|0.0|0.0|0|0|21.1|20.5|Downward|48|25,899,919
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|52|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|53|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|54|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|56|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|58|9,179,643
BCH|2023-01-17|2023-01-24|6|21.4|20.9|-0.5|-2.34|-5|-1|21.6|20.8|Downward|64|35,186,497
CPNREIT|2022-12-26|2022-12-29|4|19.5|19.4|-0.1|-0.51|-1|-1|19.6|19.4|Downward|68|2,253,419
CPNREIT|2022-12-30|2023-01-09|7|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Upward|74|5,177,343
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|75|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|82|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|85|10,078,994
DCC|2022-12-26|2022-12-27|2|2.8|2.8|0.0|0.0|0|0|2.82|2.78|Downward|87|9,026,286
DCC|2022-12-28|2023-01-03|5|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Upward|91|16,824,829
DCC|2023-01-04|2023-01-04|1|2.8|2.8|0.0|0.0|0|0|2.84|2.8|Downward|92|5,220,759
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|96|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|97|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|98|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|101|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|102|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|103|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|105|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|106|3,924,289
DIF|2022-12-26|2023-01-03|7|13.2|13.2|0.0|0.0|0|0|13.3|13.1|Downward|112|34,904,457
DIF|2023-01-04|2023-01-04|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|113|3,723,467
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|115|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|124|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|127|14,698,967
GVREIT|2022-12-26|2022-12-26|1|9.1|9.1|0.0|0.0|0|0|9.15|9.05|Downward|128|54,601
GVREIT|2022-12-27|2022-12-28|2|9.15|9.15|0.0|0.0|0|0|9.15|9.1|Upward|130|142,201
GVREIT|2022-12-29|2022-12-30|2|9.1|9.1|0.0|0.0|0|0|9.15|9.05|Downward|132|1,280,955
GVREIT|2023-01-03|2023-01-03|1|9.15|9.15|0.0|0.0|0|0|9.15|9.05|Upward|133|174,743
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|136|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|137|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|143|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|148|4,993,973
IVL|2022-12-26|2022-12-30|5|39.75|40.75|1.0|2.52|4|0|41.25|39.5|Upward|153|56,581,013
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-10|-3|41.0|37.0|Downward|157|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|165|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|166|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|167|15,314,376
IVL|2023-01-23|2023-01-24|2|42.0|41.75|-0.25|-0.6|-1|-1|42.5|41.5|Downward|169|28,351,407
JASIF|2022-12-26|2022-12-26|1|8.0|8.0|0.0|0.0|0|0|8.1|8.0|Downward|170|2,342,053
JASIF|2022-12-27|2022-12-27|1|8.05|8.05|0.0|0.0|0|0|8.05|8.0|Upward|171|1,607,162
JASIF|2022-12-28|2022-12-28|1|8.0|8.0|0.0|0.0|0|0|8.05|8.0|Downward|172|3,249,547
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|4|0|8.3|8.0|Upward|182|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|183|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|185|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|186|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|190|16,790,423
JMART|2022-12-26|2022-12-29|4|39.5|41.5|2.0|5.06|8|2|41.5|39.25|Upward|194|19,466,777
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.75|40.75|Downward|195|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|196|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|198|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|204|44,921,819
JMART|2023-01-16|2023-01-24|7|41.75|38.75|-3.0|-7.19|-12|-2|42.75|38.5|Downward|211|72,156,666
KCE|2022-12-26|2022-12-26|1|46.0|46.0|0.0|0.0|0|0|46.75|45.5|Downward|212|9,548,531
KCE|2022-12-27|2022-12-27|1|47.0|47.0|0.0|0.0|0|0|47.25|45.75|Upward|213|11,240,800
KCE|2022-12-28|2022-12-30|3|46.75|46.5|-0.25|-0.53|-1|-1|47.5|46.25|Downward|216|37,571,835
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|0|0|48.0|46.25|Upward|217|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-4|-2|47.5|44.5|Downward|219|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|222|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|223|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|224|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|230|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|231|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|232|31,520,414
MCS|2022-12-26|2022-12-26|1|8.9|8.9|0.0|0.0|0|0|8.9|8.85|Downward|233|120,415
MCS|2022-12-27|2023-01-06|9|8.95|9.3|0.35|3.91|7|0|9.35|8.9|Upward|241|6,722,455
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|242|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|244|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|245|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|250|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|251|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|252|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|253|1,505,174
NER|2022-12-26|2022-12-26|1|5.95|5.95|0.0|0.0|0|0|6.0|5.9|Downward|254|3,309,674
NER|2022-12-27|2023-01-03|6|6.05|6.35|0.3|4.96|6|1|6.45|5.95|Upward|259|64,636,085
NER|2023-01-04|2023-01-05|2|6.3|6.25|-0.05|-0.79|-1|-1|6.45|6.2|Downward|261|23,830,282
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|262|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|263|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|264|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|265|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|267|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|272|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|273|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|274|2,154,024
ORI|2022-12-26|2022-12-26|1|11.5|11.5|0.0|0.0|0|0|11.5|11.2|Downward|275|13,234,814
ORI|2022-12-27|2022-12-30|4|11.7|12.1|0.4|3.42|4|1|12.1|11.4|Upward|279|44,627,649
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|283|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|284|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|286|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|289|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|291|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|294|19,054,666
ORI|2023-01-24|2023-01-24|1|11.8|11.8|0.0|0.0|0|0|12.0|11.7|Downward|295|4,560,439
PTTGC|2022-12-26|2022-12-26|1|45.5|45.5|0.0|0.0|0|0|45.5|44.5|Downward|296|15,547,424
PTTGC|2022-12-27|2022-12-29|3|47.25|47.5|0.25|0.53|1|0|47.75|45.75|Upward|299|60,664,163
PTTGC|2022-12-30|2023-01-03|3|47.25|46.75|-0.5|-1.06|-2|-1|47.75|46.5|Downward|301|18,960,635
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|302|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|304|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|307|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|309|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|312|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|314|34,342,502
PTTGC|2023-01-23|2023-01-24|2|50.75|51.0|0.25|0.49|1|0|51.5|50.0|Upward|316|20,673,590
RCL|2022-12-26|2022-12-29|4|30.0|31.0|1.0|3.33|4|1|31.25|30.0|Upward|320|8,201,785
RCL|2022-12-30|2023-01-04|4|30.75|29.25|-1.5|-4.88|-6|-2|31.5|29.25|Downward|323|12,188,423
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|327|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|328|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|329|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|331|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|333|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|335|2,950,775
RCL|2023-01-23|2023-01-24|2|31.25|31.25|0.0|0.0|0|0|31.5|31.0|Upward|337|2,463,266
SCC|2022-12-26|2022-12-29|4|335.0|344.0|9.0|2.69|9|2|344.0|333.0|Upward|341|5,359,390
SCC|2022-12-30|2023-01-03|3|342.0|342.0|0.0|0.0|0|0|344.0|340.0|Downward|343|3,705,436
SCC|2023-01-04|2023-01-11|6|345.0|359.0|14.0|4.06|14|2|360.0|340.0|Upward|349|14,796,849
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|352|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|353|1,930,796
SCC|2023-01-18|2023-01-24|5|356.0|348.0|-8.0|-2.25|-8|-2|359.0|348.0|Downward|358|7,924,935
SCCC|2022-12-26|2022-12-26|1|151.0|151.0|0.0|0.0|0|0|151.0|149.5|Downward|359|57,329
SCCC|2022-12-27|2023-01-06|9|152.0|158.5|6.5|4.28|13|1|159.0|150.5|Upward|367|1,292,361
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|370|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|376|713,373
SCCC|2023-01-20|2023-01-24|3|159.0|157.5|-1.5|-0.94|-3|-1|160.5|157.0|Downward|379|356,095
SENA|2022-12-26|2022-12-26|1|3.9|3.9|0.0|0.0|0|0|3.94|3.9|Downward|380|515,271
SENA|2022-12-27|2023-01-03|6|3.92|3.94|0.02|0.51|1|0|3.96|3.9|Upward|385|4,930,343
SENA|2023-01-04|2023-01-05|2|3.92|3.9|-0.02|-0.51|-1|-1|3.96|3.9|Downward|387|1,498,341
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|390|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|393|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|395|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|397|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|399|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|400|129,114
SINGER|2022-12-26|2022-12-27|2|28.25|28.25|0.0|0.0|0|0|29.25|27.5|Downward|402|7,546,168
SINGER|2022-12-28|2022-12-30|3|28.5|28.75|0.25|0.88|1|0|29.25|28.0|Upward|405|19,709,000
SINGER|2023-01-03|2023-01-06|4|28.5|27.0|-1.5|-5.26|-6|-2|28.75|26.75|Downward|409|23,648,943
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|410|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|411|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|414|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|420|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|421|3,780,503
STA|2022-12-26|2022-12-29|4|19.5|21.2|1.7|8.72|17|4|21.4|19.0|Upward|425|37,323,541
STA|2022-12-30|2023-01-04|4|21.1|20.6|-0.5|-2.37|-5|-2|21.6|20.4|Downward|428|12,847,722
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|431|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|433|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|435|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|436|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|437|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|438|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|439|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|441|4,052,655
STA|2023-01-24|2023-01-24|1|21.1|21.1|0.0|0.0|0|0|21.3|20.8|Upward|442|2,390,646
SYNEX|2022-12-26|2022-12-27|2|15.7|16.1|0.4|2.55|4|2|16.2|15.5|Upward|444|2,892,046
SYNEX|2022-12-28|2022-12-29|2|15.9|15.9|0.0|0.0|0|0|16.1|15.7|Downward|446|2,285,847
SYNEX|2022-12-30|2023-01-03|3|16.4|16.7|0.3|1.83|3|1|17.0|16.0|Upward|448|8,531,030
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|449|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|452|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|453|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|455|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|461|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|463|1,882,226
TFFIF|2022-12-26|2022-12-26|1|7.75|7.75|0.0|0.0|0|0|7.8|7.7|Upward|464|407,529
TFFIF|2022-12-27|2022-12-30|4|7.7|7.65|-0.05|-0.65|-1|-1|7.8|7.6|Downward|468|7,203,126

TFFIF|2023-01-03|2023-01-03|1|7.7|7.7|0.0|0.0|0|0|7.75|7.65|Upward|469|745,322
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|470|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|473|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|474|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|484|26,912,214
TMT|2022-12-26|2022-12-29|4|7.55|7.9|0.35|4.64|7|1|7.9|7.5|Upward|488|1,315,223
TMT|2022-12-30|2023-01-05|5|7.8|7.65|-0.15|-1.92|-3|-1|7.95|7.6|Downward|492|1,180,838
TMT|2023-01-06|2023-01-24|13|7.7|8.45|0.75|9.74|15|1|8.45|7.55|Upward|505|6,084,601
TTB|2022-12-26|2023-01-10|12|1.36|1.46|0.1|7.35|10|0|1.47|1.35|Upward|516|3,690,445,744
TTB|2023-01-11|2023-01-13|3|1.44|1.41|-0.03|-2.08|-3|-1|1.47|1.4|Downward|519|765,226,385
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|523|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|524|509,121,072
TTB|2023-01-23|2023-01-24|2|1.44|1.44|0.0|0.0|0|0|1.45|1.4|Upward|526|580,108,027
WHAIR|2022-12-26|2022-12-28|3|7.5|7.65|0.15|2.0|3|1|7.65|7.4|Upward|529|1,005,097
WHAIR|2022-12-29|2023-01-04|5|7.6|7.45|-0.15|-1.97|-3|-1|7.65|7.4|Downward|533|2,468,511
WHAIR|2023-01-05|2023-01-05|1|7.55|7.55|0.0|0.0|0|0|7.55|7.5|Upward|534|674,738
WHAIR|2023-01-06|2023-01-11|4|7.5|7.45|-0.05|-0.67|-1|-1|7.6|7.45|Downward|538|3,082,921
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|545|11,421,149
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|547|1,018,702
WHART|2022-12-26|2022-12-26|1|10.6|10.6|0.0|0.0|0|0|10.6|10.5|Downward|548|852,438
WHART|2022-12-27|2023-01-04|7|10.7|10.8|0.1|0.93|1|0|10.9|10.5|Upward|554|10,076,624
WHART|2023-01-05|2023-01-06|2|10.7|10.7|0.0|0.0|0|0|10.9|10.7|Downward|556|1,791,615
WHART|2023-01-09|2023-01-09|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|557|1,371,475
WHART|2023-01-10|2023-01-10|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|558|1,251,002
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|559|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|560|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|565|20,924,999
WHART|2023-01-20|2023-01-24|3|11.8|11.7|-0.1|-0.85|-1|-1|12.1|11.6|Downward|567|11,332,251
ruby/../Data/summary.csv

In [13]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [14]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [15]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [16]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,27,21,21,7,80,77,18,40,11,5,81,84,108,108,21,21
Upward,27,21,21,13,77,76,29,46,17,5,82,80,102,102,21,21

In [17]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [18]:
name_up = 'WHAIR'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [19]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
name_down = 'CPNREIT'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')
df_groupby_trend.ngroups

2

In [22]:
# Stat of each group
df_groupby_trend.size()

trend
Downward    104
Upward      109
dtype: int64

In [23]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [24]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [25]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-23,2022-12-29,5,2.96,2.96,0.0,0.0,0,0,2.98,2.92,8841786,NaN,6,12-23,12-29

In [26]:
df.groupby('trend').days.max()

trend
Downward     6
Upward      12
Name: days, dtype: int64

In [27]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [28]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [29]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
50,GVREIT,01-10,01-17,6,9.00,8.9,-1.11,-2,-1,9.15,8.90,1449890,Downward
71,JMART,01-16,01-23,6,41.75,39.0,-6.59,-11,-2,42.75,38.50,64214837,Downward
80,KCE,01-13,01-20,6,52.00,49.0,-5.77,-12,-2,53.00,48.50,123505739,Downward
158,SINGER,01-16,01-23,6,30.00,28.0,-6.67,-8,-2,30.75,27.75,29983246,Downward
178,SYNEX,01-13,01-20,6,17.10,16.6,-2.92,-5,-1,17.50,16.50,10273525,Downward

In [ ]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

In [30]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    6    104     2.0  2.230769
Upward     12    109     2.0  3.385321

### Individual stock analysis

In [31]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty   maxp   minp
count  21.00       21.00  21.00  21.00
mean    7.56   931126.10   7.61   7.49
std     0.15   578408.28   0.14   0.12
min     7.45   198502.00   7.45   7.35
25%     7.45   400421.00   7.55   7.40
50%     7.50   783934.00   7.55   7.45
75%     7.60  1570800.00   7.65   7.50
max     7.95  2022633.00   8.00   7.85

In [33]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [34]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price         qty   maxp   minp
count  21.00       21.00  21.00  21.00
mean   19.57  1476150.95  19.77  19.45
std     0.37  1111156.57   0.46   0.29
min    18.80   318708.00  19.40  18.80
25%    19.40   625201.00  19.50  19.40
50%    19.50  1144597.00  19.60  19.40
75%    19.60  1867810.00  19.70  19.50
max    20.60  4194009.00  21.30  20.30

In [35]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [36]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)