In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 26), datetime.date(2023, 1, 25))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-26
Today in mm-dd format: 01-26
yesterday: 2023-01-25 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-28 00:00:00   Wednesday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [36]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [37]:
in_p = in_p + ", 'TTB', 'MC', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [38]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-28 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'MC', 'CKP', 'CK')
ORDER BY name, date

In [39]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date   price        qty    maxp    minp
594    TTB  2023-01-06    1.45  473419365    1.45    1.42
192    IVL  2023-01-03   40.25    7697656   41.00   40.25
460   SCCC  2023-01-25  157.50      79795  158.00  157.00
611  WHAIR  2022-12-30    7.45     905123    7.55    7.40
475   SENA  2023-01-17    3.94     738967    3.94    3.92

In [40]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [41]:
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [43]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [44]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-28|2022-12-29|2|2.96|2.96|0.0|0.0|0|0|2.98|2.96||3|3,951,568
ASP|2022-12-30|2022-12-30|1|2.98|2.98|0.0|0.0|0|0|2.98|2.96|Upward|4|1,971,614
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|7|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|16|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|18|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|19|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|20|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|21|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|22|3,647,294
BANPU|2022-12-28|2023-01-06|8|13.7|12.3|-1.4|-10.22|-14|-2|13.8|12.3|Downward|29|1,020,743,979
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|31|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|33|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|34|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|38|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|39|193,937,283
BANPU|2023-01-23|2023-01-26|4|12.5|12.3|-0.2|-1.6|-2|-1|12.6|12.0|Downward|43|285,309,876
BCH|2022-12-28|2022-12-28|1|20.3|20.3|0.0|0.0|0|0|20.4|20.0|Downward|44|5,919,154
BCH|2022-12-29|2022-12-29|1|21.1|21.1|0.0|0.0|0|0|21.1|20.3|Upward|45|25,508,551
BCH|2022-12-30|2022-12-30|1|20.5|20.5|0.0|0.0|0|0|21.1|20.5|Downward|46|25,899,919
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|50|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|51|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|52|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|54|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|56|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|63|46,355,474
BCH|2023-01-26|2023-01-26|1|20.7|20.7|0.0|0.0|0|0|20.9|20.5|Upward|64|8,886,118
CK|2022-12-28|2022-12-30|3|23.8|24.3|0.5|2.1|5|1|24.3|23.7|Upward|67|11,468,663
CK|2023-01-03|2023-01-10|6|23.9|23.5|-0.4|-1.67|-4|-1|24.5|23.2|Downward|73|38,379,065
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|75|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|77|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|78|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|79|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|80|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|83|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|84|4,666,111
CK|2023-01-26|2023-01-26|1|23.3|23.3|0.0|0.0|0|0|23.7|23.3|Downward|85|5,011,431
CKP|2022-12-28|2023-01-03|5|4.6|4.52|-0.08|-1.74|-4|-1|4.66|4.52|Downward|89|72,153,852
CKP|2023-01-04|2023-01-12|7|4.58|4.74|0.16|3.49|8|1|4.76|4.52|Upward|96|72,062,088
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|100|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|102|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|106|39,628,888
CPNREIT|2022-12-28|2022-12-29|2|19.4|19.4|0.0|0.0|0|0|19.5|19.4|Downward|108|1,093,805
CPNREIT|2022-12-30|2023-01-09|7|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Upward|114|5,177,343
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|115|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|122|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|125|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|127|2,216,218
DCC|2022-12-28|2023-01-03|5|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Upward|131|16,824,829
DCC|2023-01-04|2023-01-04|1|2.8|2.8|0.0|0.0|0|0|2.84|2.8|Downward|132|5,220,759
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|136|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|137|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|138|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|141|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|142|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|143|3,490,572
DCC|2023-01-20|2023-01-23|2|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|145|11,529,636
DCC|2023-01-24|2023-01-24|1|2.82|2.82|0.0|0.0|0|0|2.86|2.82|Downward|146|3,924,289
DCC|2023-01-25|2023-01-25|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|147|6,076,325
DCC|2023-01-26|2023-01-26|1|2.82|2.82|0.0|0.0|0|0|2.84|2.8|Downward|148|7,473,746
DIF|2022-12-28|2023-01-03|5|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|152|15,453,671
DIF|2023-01-04|2023-01-04|1|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Upward|153|3,723,467
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|155|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|164|76,449,286
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|167|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|168|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|169|18,977,797
GVREIT|2022-12-28|2022-12-30|3|9.15|9.1|-0.05|-0.55|-1|-1|9.15|9.05|Downward|172|1,344,756
GVREIT|2023-01-03|2023-01-03|1|9.15|9.15|0.0|0.0|0|0|9.15|9.05|Upward|173|174,743
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|176|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|177|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|183|1,449,890
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|188|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|189|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|190|461,700
IVL|2022-12-28|2022-12-30|3|40.75|40.75|0.0|0.0|0|0|41.25|40.5|Upward|193|40,281,414
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-10|-3|41.0|37.0|Downward|197|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|205|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|206|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|207|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|211|61,818,314
JASIF|2022-12-28|2022-12-28|1|8.0|8.0|0.0|0.0|0|0|8.05|8.0|Downward|212|3,249,547
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|4|0|8.3|8.0|Upward|222|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|223|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|225|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|226|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|230|16,790,423
JASIF|2023-01-25|2023-01-26|2|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|232|16,248,484
JMART|2022-12-28|2022-12-28|1|41.0|41.0|0.0|0.0|0|0|41.5|40.25|Downward|233|6,159,673
JMART|2022-12-29|2022-12-29|1|41.5|41.5|0.0|0.0|0|0|41.5|40.75|Upward|234|5,183,726
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.75|40.75|Downward|235|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|236|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|238|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|244|44,921,819
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|253|118,032,446
JMT|2022-12-28|2022-12-28|1|67.75|67.75|0.0|0.0|0|0|68.25|66.25|Downward|254|5,815,906
JMT|2022-12-29|2022-12-30|2|68.25|69.0|0.75|1.1|3|1|70.0|67.75|Upward|256|8,620,205
JMT|2023-01-03|2023-01-06|4|67.5|66.0|-1.5|-2.22|-6|-2|69.0|65.25|Downward|260|16,280,131
JMT|2023-01-09|2023-01-13|5|68.25|69.5|1.25|1.83|5|1|71.0|66.75|Upward|265|36,049,399
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|274|129,571,700
KCE|2022-12-28|2022-12-30|3|46.75|46.5|-0.25|-0.53|-1|-1|47.5|46.25|Downward|277|37,571,835
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|0|0|48.0|46.25|Upward|278|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-4|-2|47.5|44.5|Downward|280|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|283|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|284|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|285|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|291|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|292|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|293|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|294|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|295|14,288,984
MC|2022-12-28|2023-01-05|7|10.5|10.5|0.0|0.0|0|0|10.7|10.3|Downward|301|2,508,185
MC|2023-01-06|2023-01-10|3|10.8|11.2|0.4|3.7|4|1|11.2|10.5|Upward|304|5,029,087
MC|2023-01-11|2023-01-11|1|11.0|11.0|0.0|0.0|0|0|11.1|10.7|Downward|305|1,488,870
MC|2023-01-12|2023-01-12|1|11.1|11.1|0.0|0.0|0|0|11.2|10.8|Upward|306|1,363,029
MC|2023-01-13|2023-01-13|1|11.0|11.0|0.0|0.0|0|0|11.3|11.0|Downward|307|1,259,169
MC|2023-01-16|2023-01-19|4|11.2|11.7|0.5|4.46|5|1|11.7|11.0|Upward|311|6,694,798
MC|2023-01-20|2023-01-23|2|11.6|11.3|-0.3|-2.59|-3|-2|11.8|11.3|Downward|313|2,320,749
MC|2023-01-24|2023-01-26|3|11.6|11.9|0.3|2.59|3|1|11.9|11.3|Upward|316|4,617,106
MCS|2022-12-28|2023-01-06|8|8.95|9.3|0.35|3.91|7|0|9.35|8.9|Upward|323|5,892,930
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|324|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|326|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|327|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|332|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|333|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|334|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|335|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|336|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|337|1,271,966
NER|2022-12-28|2023-01-05|7|6.35|6.25|-0.1|-1.57|-2|-1|6.45|6.05|Downward|343|72,570,751
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|344|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|345|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|346|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|347|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|349|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|354|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|355|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|356|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|358|42,913,468
ORI|2022-12-28|2022-12-30|3|11.8|12.1|0.3|2.54|3|1|12.1|11.6|Upward|361|29,810,953
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|365|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|366|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|368|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|371|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|373|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|376|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|379|16,286,040
PTTGC|2022-12-28|2023-01-03|5|47.5|46.75|-0.75|-1.58|-3|-1|47.75|46.5|Downward|383|53,847,498
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|384|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|386|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|389|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|391|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|394|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|396|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|399|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|400|24,638,391
RCL|2022-12-28|2023-01-04|6|31.0|29.25|-1.75|-5.65|-7|-2|31.5|29.25|Downward|405|16,981,796
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|409|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|410|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|411|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|413|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|415|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|417|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|420|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|421|2,352,538
SCC|2022-12-28|2022-12-28|1|341.0|341.0|0.0|0.0|0|0|342.0|338.0|Downward|422|1,700,813
SCC|2022-12-29|2022-12-29|1|344.0|344.0|0.0|0.0|0|0|344.0|339.0|Upward|423|1,374,749
SCC|2022-12-30|2023-01-03|3|342.0|342.0|0.0|0.0|0|0|344.0|340.0|Downward|425|3,705,436
SCC|2023-01-04|2023-01-11|6|345.0|359.0|14.0|4.06|14|2|360.0|340.0|Upward|431|14,796,849
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|434|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|435|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|442|16,632,975
SCCC|2022-12-28|2022-12-28|1|152.5|152.5|0.0|0.0|0|0|153.5|151.0|Downward|443|254,547
SCCC|2022-12-29|2023-01-06|7|153.0|158.5|5.5|3.59|11|1|159.0|152.5|Upward|449|876,743
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|452|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|458|713,373
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|463|597,538
SENA|2022-12-28|2023-01-05|7|3.94|3.9|-0.04|-1.02|-2|-1|3.96|3.9|Downward|469|5,825,121
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|472|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|475|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|477|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|479|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|481|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|482|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|483|2,090,555
SENA|2023-01-26|2023-01-26|1|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|484|1,904,624
SINGER|2022-12-28|2022-12-28|1|28.5|28.5|0.0|0.0|0|0|28.75|28.0|Downward|485|5,575,137
SINGER|2022-12-29|2022-12-30|2|28.75|28.75|0.0|0.0|0|0|29.25|28.25|Upward|487|14,133,863
SINGER|2023-01-03|2023-01-06|4|28.5|27.0|-1.5|-5.26|-6|-2|28.75|26.75|Downward|491|23,648,943
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|492|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|493|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|496|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|502|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|503|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|505|11,350,118
STA|2022-12-28|2022-12-28|1|21.0|21.0|0.0|0.0|0|0|21.1|20.1|Downward|506|13,323,142
STA|2022-12-29|2022-12-29|1|21.2|21.2|0.0|0.0|0|0|21.4|21.0|Upward|507|6,449,026
STA|2022-12-30|2023-01-04|4|21.1|20.6|-0.5|-2.37|-5|-2|21.6|20.4|Downward|510|12,847,722
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|513|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|515|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|517|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|518|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|519|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|520|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|521|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|523|4,052,655
STA|2023-01-24|2023-01-26|3|21.1|22.7|1.6|7.58|16|5|22.9|20.8|Upward|526|40,189,855
SYNEX|2022-12-28|2023-01-03|5|15.9|16.7|0.8|5.03|8|1|17.0|15.7|Upward|530|10,816,877
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|531|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|534|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|535|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|537|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|543|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|545|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|547|4,592,919
TFFIF|2022-12-28|2022-12-30|3|7.7|7.65|-0.05|-0.65|-1|-1|7.7|7.6|Downward|550|4,823,728
TFFIF|2023-01-03|2023-01-03|1|7.7|7.7|0.0|0.0|0|0|7.75|7.65|Upward|551|745,322
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|552|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|555|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|556|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|566|26,912,214
TFFIF|2023-01-25|2023-01-26|2|8.15|8.15|0.0|0.0|0|0|8.2|8.1|Downward|568|4,542,174
TMT|2022-12-28|2022-12-28|1|7.75|7.75|0.0|0.0|0|0|7.75|7.65|Downward|569|347,211
TMT|2022-12-29|2022-12-29|1|7.9|7.9|0.0|0.0|0|0|7.9|7.75|Upward|570|301,279
TMT|2022-12-30|2023-01-05|5|7.8|7.65|-0.15|-1.92|-3|-1|7.95|7.6|Downward|574|1,180,838
TMT|2023-01-06|2023-01-24|13|7.7|8.45|0.75|9.74|15|1|8.45|7.55|Upward|587|6,084,601
TMT|2023-01-25|2023-01-26|2|8.35|8.35|0.0|0.0|0|0|8.45|8.2|Downward|589|576,900
TTB|2022-12-28|2022-12-28|1|1.38|1.38|0.0|0.0|0|0|1.38|1.37|Downward|590|96,592,667
TTB|2022-12-29|2023-01-10|9|1.39|1.46|0.07|5.04|7|0|1.47|1.37|Upward|598|3,192,850,468
TTB|2023-01-11|2023-01-13|3|1.44|1.41|-0.03|-2.08|-3|-1|1.47|1.4|Downward|601|765,226,385
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|605|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|606|509,121,072
TTB|2023-01-23|2023-01-26|4|1.44|1.45|0.01|0.69|1|0|1.45|1.4|Upward|610|943,632,637
WHAIR|2022-12-28|2022-12-28|1|7.65|7.65|0.0|0.0|0|0|7.65|7.55|Upward|611|267,774
WHAIR|2022-12-29|2023-01-04|5|7.6|7.45|-0.15|-1.97|-3|-1|7.65|7.4|Downward|615|2,468,511

In [45]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [46]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [47]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [48]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [49]:
name_up = 'STA'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [50]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [51]:
name_down = 'JMT'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [52]:
df_groupby_trend = df.groupby('trend')

In [53]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [54]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [55]:
#df.groupby('trend').days.max()

In [56]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    9    130     2.0  2.569231
Upward     13    116     2.0  2.887931

In [57]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [58]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [59]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
93,JMART,01-16,01-26,9,41.75,35.50,-14.97,-25,-3,42.75,35.25,118032446,Downward
98,JMT,01-16,01-26,9,68.25,53.75,-21.25,-58,-7,69.75,53.75,129571700,Downward

In [60]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

### Individual stock analysis

In [61]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [62]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   21.27   6035519.76  21.52  20.93
std     0.46   5136731.98   0.42   0.35
min    20.60    879566.00  21.00  20.10
25%    21.00   2627650.00  21.30  20.80
50%    21.20   3729662.00  21.40  21.00
75%    21.30   6986609.00  21.70  21.10
max    22.70  19821209.00  22.90  21.90

In [63]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [64]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   66.14   9349397.19  67.51  65.62
std     3.78   9154610.99   2.82   3.62
min    53.75   3581500.00  58.75  53.75
25%    66.00   4365851.00  66.75  65.25
50%    67.25   5946518.00  68.25  66.25
75%    68.25   8578333.00  69.75  68.00
max    69.50  40105767.00  71.00  69.00

In [65]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [66]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)