In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 20), datetime.date(2023, 1, 19))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-01-20
Today in mm-dd format: 01-20
yesterday: 2023-01-19 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-22 00:00:00   Thursday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [ ]:
in_p = in_p + ", 'JMART'"
in_p

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

In [6]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-22 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

In [7]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty   maxp   minp
91     DCC  2023-01-03   2.82   2736771   2.84   2.80
465  SYNEX  2022-12-27  16.10   2236102  16.20  15.70
200  JMART  2023-01-09  41.50  10986578  42.00  40.25
204  JMART  2023-01-13  42.50  10655144  43.50  42.00
184  JASIF  2023-01-16   8.25   1574496   8.25   8.20

In [8]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)
price.to_csv(osd_file, header=None)

### Call ruby ruby\crt-summary.rb

In [9]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [10]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [11]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2022-12-22|2022-12-29|6|2.96|2.96|0.0|0.0|0|0|2.98|2.92||7|9,209,889
ASP|2022-12-30|2022-12-30|1|2.98|2.98|0.0|0.0|0|0|2.98|2.96|Upward|8|1,971,614
ASP|2023-01-03|2023-01-05|3|2.96|2.96|0.0|0.0|0|0|2.98|2.94|Downward|11|8,840,544
ASP|2023-01-06|2023-01-18|9|2.98|3.1|0.12|4.03|6|0|3.1|2.96|Upward|20|22,455,682
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|22|2,184,225
BANPU|2022-12-22|2022-12-23|2|13.6|13.4|-0.2|-1.47|-2|-1|13.7|13.4|Downward|24|119,462,609
BANPU|2022-12-26|2022-12-26|1|13.5|13.5|0.0|0.0|0|0|13.6|13.3|Upward|25|54,412,026
BANPU|2022-12-27|2022-12-27|1|13.4|13.4|0.0|0.0|0|0|13.5|13.4|Downward|26|39,796,280
BANPU|2022-12-28|2022-12-30|3|13.7|13.7|0.0|0.0|0|0|13.8|13.4|Upward|29|166,355,695
BANPU|2023-01-03|2023-01-06|4|13.4|12.3|-1.1|-8.21|-11|-3|13.7|12.3|Downward|33|854,388,284
BANPU|2023-01-09|2023-01-10|2|12.5|12.5|0.0|0.0|0|0|12.6|12.2|Upward|35|255,803,966
BANPU|2023-01-11|2023-01-12|2|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.1|Downward|37|229,225,521
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|38|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|42|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|43|193,937,283
BCH|2022-12-22|2022-12-29|6|19.7|21.1|1.4|7.11|14|2|21.1|19.6|Upward|49|44,563,932
BCH|2022-12-30|2022-12-30|1|20.5|20.5|0.0|0.0|0|0|21.1|20.5|Downward|50|25,899,919
BCH|2023-01-03|2023-01-06|4|21.0|21.9|0.9|4.29|9|2|22.0|20.6|Upward|54|56,915,876
BCH|2023-01-09|2023-01-09|1|21.8|21.8|0.0|0.0|0|0|22.0|21.5|Downward|55|10,334,905
BCH|2023-01-10|2023-01-10|1|21.9|21.9|0.0|0.0|0|0|22.2|21.7|Upward|56|5,831,572
BCH|2023-01-11|2023-01-12|2|21.8|21.4|-0.4|-1.83|-4|-2|22.2|21.3|Downward|58|27,784,434
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|60|9,179,643
BCH|2023-01-17|2023-01-20|4|21.4|21.1|-0.3|-1.4|-3|-1|21.6|20.9|Downward|64|23,098,634
CPNREIT|2022-12-22|2022-12-29|6|19.5|19.4|-0.1|-0.51|-1|-1|19.6|19.4|Downward|70|7,229,049
CPNREIT|2022-12-30|2023-01-09|7|19.5|19.5|0.0|0.0|0|0|19.7|19.4|Upward|76|5,177,343
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|77|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|84|11,640,345
CPNREIT|2023-01-20|2023-01-20|1|20.4|20.4|0.0|0.0|0|0|21.3|20.3|Downward|85|3,096,674
DCC|2022-12-22|2022-12-23|2|2.78|2.78|0.0|0.0|0|0|2.8|2.74|Downward|87|5,618,786
DCC|2022-12-26|2023-01-03|7|2.8|2.82|0.02|0.71|1|0|2.84|2.78|Upward|93|25,851,115
DCC|2023-01-04|2023-01-04|1|2.8|2.8|0.0|0.0|0|0|2.84|2.8|Downward|94|5,220,759
DCC|2023-01-05|2023-01-10|4|2.82|2.84|0.02|0.71|1|0|2.88|2.82|Upward|98|44,375,471
DCC|2023-01-11|2023-01-11|1|2.8|2.8|0.0|0.0|0|0|2.86|2.78|Downward|99|22,240,617
DCC|2023-01-12|2023-01-12|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|100|5,025,330
DCC|2023-01-13|2023-01-17|3|2.82|2.82|0.0|0.0|0|0|2.86|2.8|Downward|103|18,182,273
DCC|2023-01-18|2023-01-18|1|2.84|2.84|0.0|0.0|0|0|2.84|2.8|Upward|104|3,935,740
DCC|2023-01-19|2023-01-19|1|2.82|2.82|0.0|0.0|0|0|2.84|2.82|Downward|105|3,490,572
DCC|2023-01-20|2023-01-20|1|2.84|2.84|0.0|0.0|0|0|2.86|2.82|Upward|106|8,748,516
DIF|2022-12-22|2023-01-04|10|13.2|13.3|0.1|0.76|1|0|13.3|13.1|Upward|115|46,499,595
DIF|2023-01-05|2023-01-06|2|13.2|13.2|0.0|0.0|0|0|13.3|13.2|Downward|117|9,970,670
DIF|2023-01-09|2023-01-19|9|13.3|13.7|0.4|3.01|4|0|13.7|13.2|Upward|126|76,449,286
DIF|2023-01-20|2023-01-20|1|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|127|5,953,581
GVREIT|2022-12-22|2022-12-26|3|9.1|9.1|0.0|0.0|0|0|9.15|9.0|Downward|130|367,730
GVREIT|2022-12-27|2022-12-28|2|9.15|9.15|0.0|0.0|0|0|9.15|9.1|Upward|132|142,201
GVREIT|2022-12-29|2022-12-30|2|9.1|9.1|0.0|0.0|0|0|9.15|9.05|Downward|134|1,280,955
GVREIT|2023-01-03|2023-01-03|1|9.15|9.15|0.0|0.0|0|0|9.15|9.05|Upward|135|174,743
GVREIT|2023-01-04|2023-01-06|3|9.1|9.0|-0.1|-1.1|-2|-1|9.15|9.0|Downward|138|581,228
GVREIT|2023-01-09|2023-01-09|1|9.1|9.1|0.0|0.0|0|0|9.1|9.0|Upward|139|262,301
GVREIT|2023-01-10|2023-01-17|6|9.0|8.9|-0.1|-1.11|-2|-1|9.15|8.9|Downward|145|1,449,890
GVREIT|2023-01-18|2023-01-20|3|9.0|9.3|0.3|3.33|6|2|9.35|8.85|Upward|148|2,953,416
IVL|2022-12-22|2022-12-30|7|39.5|40.75|1.25|3.16|5|0|41.25|39.0|Upward|155|69,375,229
IVL|2023-01-03|2023-01-06|4|40.25|37.75|-2.5|-6.21|-10|-3|41.0|37.0|Downward|159|104,236,282
IVL|2023-01-09|2023-01-18|8|38.5|42.25|3.75|9.74|15|1|42.75|37.75|Upward|167|208,263,258
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|168|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|169|15,314,376
JASIF|2022-12-22|2022-12-27|4|8.0|8.05|0.05|0.63|1|0|8.1|7.95|Upward|173|19,576,939
JASIF|2022-12-28|2022-12-28|1|8.0|8.0|0.0|0.0|0|0|8.05|8.0|Downward|174|3,249,547
JASIF|2022-12-29|2023-01-12|11|8.05|8.25|0.2|2.48|4|0|8.3|8.0|Upward|184|47,932,471
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|185|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|187|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|188|2,744,544
JASIF|2023-01-19|2023-01-20|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|190|8,945,985
JMART|2022-12-22|2022-12-22|1|40.5|40.5|0.0|0.0|0|0|40.75|40.25|Upward|191|1,428,333
JMART|2022-12-23|2022-12-23|1|39.25|39.25|0.0|0.0|0|0|40.25|39.0|Downward|192|6,170,257
JMART|2022-12-26|2022-12-29|4|39.5|41.5|2.0|5.06|8|2|41.5|39.25|Upward|196|19,466,777
JMART|2022-12-30|2022-12-30|1|40.75|40.75|0.0|0.0|0|0|41.75|40.75|Downward|197|6,010,236
JMART|2023-01-03|2023-01-03|1|41.0|41.0|0.0|0.0|0|0|41.25|40.75|Upward|198|3,095,538
JMART|2023-01-04|2023-01-05|2|40.75|40.0|-0.75|-1.84|-3|-2|41.5|40.0|Downward|200|7,802,274
JMART|2023-01-06|2023-01-13|6|40.25|42.5|2.25|5.59|9|1|43.5|40.0|Upward|206|44,921,819
JMART|2023-01-16|2023-01-20|5|41.75|39.0|-2.75|-6.59|-11|-3|42.75|38.5|Downward|211|56,111,987
KCE|2022-12-22|2022-12-23|2|45.75|45.5|-0.25|-0.55|-1|-1|46.25|44.5|Downward|213|18,629,737
KCE|2022-12-26|2022-12-27|2|46.0|47.0|1.0|2.17|4|2|47.25|45.5|Upward|215|20,789,331
KCE|2022-12-28|2022-12-30|3|46.75|46.5|-0.25|-0.53|-1|-1|47.5|46.25|Downward|218|37,571,835
KCE|2023-01-03|2023-01-03|1|47.25|47.25|0.0|0.0|0|0|48.0|46.25|Upward|219|28,906,300
KCE|2023-01-04|2023-01-05|2|46.0|45.0|-1.0|-2.17|-4|-2|47.5|44.5|Downward|221|31,517,549
KCE|2023-01-06|2023-01-10|3|48.0|50.0|2.0|4.17|8|2|50.5|44.75|Upward|224|125,736,067
KCE|2023-01-11|2023-01-11|1|49.25|49.25|0.0|0.0|0|0|50.75|49.25|Downward|225|19,885,273
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|226|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|232|123,505,739
MAKRO|2022-12-22|2022-12-22|1|39.25|39.25|0.0|0.0|0|0|39.75|37.75|Downward|233|22,518,130
MAKRO|2022-12-23|2022-12-27|3|39.5|39.75|0.25|0.63|1|0|40.0|38.75|Upward|236|23,187,038
MAKRO|2022-12-28|2022-12-28|1|39.25|39.25|0.0|0.0|0|0|40.0|39.0|Downward|237|10,736,659
MAKRO|2022-12-29|2023-01-09|8|39.5|43.0|3.5|8.86|14|1|43.0|39.25|Upward|244|133,585,293
MAKRO|2023-01-10|2023-01-12|3|42.5|42.0|-0.5|-1.18|-2|-1|43.25|41.5|Downward|247|59,151,829
MAKRO|2023-01-13|2023-01-16|2|42.5|43.5|1.0|2.35|4|2|43.5|41.75|Upward|249|51,570,802
MAKRO|2023-01-17|2023-01-17|1|42.75|42.75|0.0|0.0|0|0|43.5|42.5|Downward|250|13,696,528
MAKRO|2023-01-18|2023-01-18|1|43.0|43.0|0.0|0.0|0|0|43.0|42.5|Upward|251|12,485,205
MAKRO|2023-01-19|2023-01-20|2|42.0|42.0|0.0|0.0|0|0|43.0|41.5|Downward|253|39,592,707
MCS|2022-12-22|2022-12-22|1|8.85|8.85|0.0|0.0|0|0|8.9|8.8|Downward|254|332,103
MCS|2022-12-23|2023-01-06|11|8.9|9.3|0.4|4.49|8|0|9.35|8.85|Upward|264|7,204,275
MCS|2023-01-09|2023-01-09|1|9.25|9.25|0.0|0.0|0|0|9.35|9.15|Downward|265|1,049,270
MCS|2023-01-10|2023-01-11|2|9.55|9.55|0.0|0.0|0|0|9.65|9.2|Upward|267|3,525,309
MCS|2023-01-12|2023-01-12|1|9.5|9.5|0.0|0.0|0|0|9.6|9.45|Downward|268|667,557
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|273|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|274|701,950
NER|2022-12-22|2022-12-23|2|5.95|5.9|-0.05|-0.84|-1|-1|5.95|5.9|Downward|276|3,421,646
NER|2022-12-26|2023-01-03|7|5.95|6.35|0.4|6.72|8|1|6.45|5.9|Upward|282|67,945,759
NER|2023-01-04|2023-01-05|2|6.3|6.25|-0.05|-0.79|-1|-1|6.45|6.2|Downward|284|23,830,282
NER|2023-01-06|2023-01-06|1|6.3|6.3|0.0|0.0|0|0|6.4|6.3|Upward|285|5,698,387
NER|2023-01-09|2023-01-09|1|6.25|6.25|0.0|0.0|0|0|6.35|6.2|Downward|286|5,356,120
NER|2023-01-10|2023-01-10|1|6.4|6.4|0.0|0.0|0|0|6.4|6.25|Upward|287|9,701,277
NER|2023-01-11|2023-01-11|1|6.3|6.3|0.0|0.0|0|0|6.45|6.3|Downward|288|8,304,764
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|290|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|295|14,996,175
ORI|2022-12-22|2022-12-22|1|10.8|10.8|0.0|0.0|0|0|11.0|10.8|Downward|296|1,681,274
ORI|2022-12-23|2022-12-30|6|11.2|12.1|0.9|8.04|9|1|12.1|10.8|Upward|302|68,755,307
ORI|2023-01-03|2023-01-06|4|12.0|11.6|-0.4|-3.33|-4|-1|12.3|11.4|Downward|306|56,252,405
ORI|2023-01-09|2023-01-09|1|11.8|11.8|0.0|0.0|0|0|12.0|11.6|Upward|307|8,382,003
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|309|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|312|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|314|28,566,002
ORI|2023-01-19|2023-01-20|2|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|316|13,582,150
PTTGC|2022-12-22|2022-12-29|6|44.75|47.5|2.75|6.15|11|1|47.75|44.5|Upward|322|104,220,218
PTTGC|2022-12-30|2023-01-03|3|47.25|46.75|-0.5|-1.06|-2|-1|47.75|46.5|Downward|324|18,960,635
PTTGC|2023-01-04|2023-01-04|1|47.0|47.0|0.0|0.0|0|0|47.0|46.0|Upward|325|21,420,431
PTTGC|2023-01-05|2023-01-06|2|46.5|46.25|-0.25|-0.54|-1|-1|47.25|46.0|Downward|327|31,764,006
PTTGC|2023-01-09|2023-01-11|3|47.5|50.5|3.0|6.32|12|4|50.5|46.5|Upward|330|118,755,741
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|332|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|335|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|337|34,342,502
RCL|2022-12-22|2022-12-26|3|30.5|30.0|-0.5|-1.64|-2|-1|31.0|30.0|Downward|340|8,507,210
RCL|2022-12-27|2022-12-29|3|30.75|31.0|0.25|0.81|1|0|31.25|30.0|Upward|343|6,939,978
RCL|2022-12-30|2023-01-04|4|30.75|29.25|-1.5|-4.88|-6|-2|31.5|29.25|Downward|346|12,188,423
RCL|2023-01-05|2023-01-10|4|29.5|31.75|2.25|7.63|9|2|31.75|29.0|Upward|350|16,950,608
RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|351|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|352|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|354|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|356|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|358|2,950,775
SCC|2022-12-22|2022-12-22|1|332.0|332.0|0.0|0.0|0|0|332.0|329.0|Downward|359|804,163
SCC|2022-12-23|2022-12-29|5|334.0|344.0|10.0|2.99|10|2|344.0|330.0|Upward|364|6,293,571
SCC|2022-12-30|2023-01-03|3|342.0|342.0|0.0|0.0|0|0|344.0|340.0|Downward|366|3,705,436
SCC|2023-01-04|2023-01-11|6|345.0|359.0|14.0|4.06|14|2|360.0|340.0|Upward|372|14,796,849
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|375|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|376|1,930,796
SCC|2023-01-18|2023-01-20|3|356.0|355.0|-1.0|-0.28|-1|-1|359.0|354.0|Downward|379|4,628,168
SCCC|2022-12-22|2022-12-23|2|149.5|149.5|0.0|0.0|0|0|150.0|148.5|Downward|381|102,219
SCCC|2022-12-26|2023-01-06|10|151.0|158.5|7.5|4.97|15|1|159.0|149.5|Upward|390|1,349,690
SCCC|2023-01-09|2023-01-11|3|158.0|158.0|0.0|0.0|0|0|159.0|157.0|Downward|393|280,206
SCCC|2023-01-12|2023-01-19|6|158.5|160.0|1.5|0.95|3|0|160.0|157.5|Upward|399|713,373
SCCC|2023-01-20|2023-01-20|1|159.0|159.0|0.0|0.0|0|0|160.5|158.5|Downward|400|152,277
SENA|2022-12-22|2022-12-26|3|3.92|3.9|-0.02|-0.51|-1|-1|3.94|3.9|Downward|403|1,239,485
SENA|2022-12-27|2023-01-03|6|3.92|3.94|0.02|0.51|1|0|3.96|3.9|Upward|408|4,930,343
SENA|2023-01-04|2023-01-05|2|3.92|3.9|-0.02|-0.51|-1|-1|3.96|3.9|Downward|410|1,498,341
SENA|2023-01-06|2023-01-10|3|3.92|3.94|0.02|0.51|1|0|3.94|3.9|Upward|413|5,681,848
SENA|2023-01-11|2023-01-13|3|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|416|4,233,706
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|418|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|420|2,393,776
SENA|2023-01-20|2023-01-20|1|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|421|1,140,626
SINGER|2022-12-22|2022-12-22|1|28.75|28.75|0.0|0.0|0|0|29.5|28.25|Upward|422|7,517,233
SINGER|2022-12-23|2022-12-23|1|27.75|27.75|0.0|0.0|0|0|28.5|27.0|Downward|423|11,146,367
SINGER|2022-12-26|2022-12-30|5|28.25|28.75|0.5|1.77|2|0|29.25|27.5|Upward|428|27,255,168
SINGER|2023-01-03|2023-01-06|4|28.5|27.0|-1.5|-5.26|-6|-2|28.75|26.75|Downward|432|23,648,943
SINGER|2023-01-09|2023-01-09|1|29.75|29.75|0.0|0.0|0|0|30.0|27.0|Upward|433|15,522,537
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|434|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|437|17,684,289
SINGER|2023-01-16|2023-01-20|5|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|442|27,406,980
STA|2022-12-22|2022-12-22|1|18.7|18.7|0.0|0.0|0|0|18.8|18.5|Downward|443|1,175,239
STA|2022-12-23|2022-12-29|5|19.0|21.2|2.2|11.58|22|4|21.4|18.6|Upward|448|40,096,969
STA|2022-12-30|2023-01-04|4|21.1|20.6|-0.5|-2.37|-5|-2|21.6|20.4|Downward|451|12,847,722
STA|2023-01-05|2023-01-09|3|21.1|21.7|0.6|2.84|6|2|21.8|20.6|Upward|454|19,227,450
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|456|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|458|7,352,075

STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|459|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|460|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|461|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|462|1,864,178
STA|2023-01-20|2023-01-20|1|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|463|3,173,089
SYNEX|2022-12-22|2022-12-26|3|15.9|15.7|-0.2|-1.26|-2|-1|15.9|15.5|Downward|466|2,950,059
SYNEX|2022-12-27|2022-12-27|1|16.1|16.1|0.0|0.0|0|0|16.2|15.7|Upward|467|2,236,102
SYNEX|2022-12-28|2022-12-29|2|15.9|15.9|0.0|0.0|0|0|16.1|15.7|Downward|469|2,285,847
SYNEX|2022-12-30|2023-01-03|3|16.4|16.7|0.3|1.83|3|1|17.0|16.0|Upward|471|8,531,030
SYNEX|2023-01-04|2023-01-04|1|16.4|16.4|0.0|0.0|0|0|16.8|16.4|Downward|472|1,937,647
SYNEX|2023-01-05|2023-01-09|3|16.5|17.2|0.7|4.24|7|2|17.5|16.4|Upward|475|7,537,422
SYNEX|2023-01-10|2023-01-10|1|17.0|17.0|0.0|0.0|0|0|17.4|16.9|Downward|476|2,355,411
SYNEX|2023-01-11|2023-01-12|2|17.1|17.2|0.1|0.58|1|0|17.6|17.0|Upward|478|7,081,640
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|484|10,273,525
TFFIF|2022-12-22|2022-12-22|1|7.75|7.75|0.0|0.0|0|0|7.8|7.7|Downward|485|961,501
TFFIF|2022-12-23|2022-12-23|1|7.8|7.8|0.0|0.0|0|0|7.8|7.75|Upward|486|751,033
TFFIF|2022-12-26|2022-12-30|5|7.75|7.65|-0.1|-1.29|-2|-1|7.8|7.6|Downward|491|7,610,655
TFFIF|2023-01-03|2023-01-03|1|7.7|7.7|0.0|0.0|0|0|7.75|7.65|Upward|492|745,322
TFFIF|2023-01-04|2023-01-04|1|7.65|7.65|0.0|0.0|0|0|7.7|7.65|Downward|493|853,736
TFFIF|2023-01-05|2023-01-09|3|7.7|7.8|0.1|1.3|2|0|7.8|7.65|Upward|496|4,181,523
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|497|1,298,307
TFFIF|2023-01-11|2023-01-20|8|7.85|8.1|0.25|3.18|5|0|8.2|7.8|Upward|505|21,536,319
TMT|2022-12-22|2022-12-23|2|7.65|7.65|0.0|0.0|0|0|7.7|7.55|Upward|507|629,823
TMT|2022-12-26|2022-12-26|1|7.55|7.55|0.0|0.0|0|0|7.65|7.55|Downward|508|298,034
TMT|2022-12-27|2022-12-29|3|7.7|7.9|0.2|2.6|4|1|7.9|7.5|Upward|511|1,017,189
TMT|2022-12-30|2023-01-05|5|7.8|7.65|-0.15|-1.92|-3|-1|7.95|7.6|Downward|515|1,180,838
TMT|2023-01-06|2023-01-20|11|7.7|8.05|0.35|4.55|7|0|8.1|7.55|Upward|526|3,800,310
WHAIR|2022-12-22|2022-12-28|5|7.35|7.65|0.3|4.08|6|1|7.65|7.35|Upward|531|1,318,904
WHAIR|2022-12-29|2023-01-04|5|7.6|7.45|-0.15|-1.97|-3|-1|7.65|7.4|Downward|535|2,468,511
WHAIR|2023-01-05|2023-01-05|1|7.55|7.55|0.0|0.0|0|0|7.55|7.5|Upward|536|674,738
WHAIR|2023-01-06|2023-01-11|4|7.5|7.45|-0.05|-0.67|-1|-1|7.6|7.45|Downward|540|3,082,921
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|547|11,421,149
WHART|2022-12-22|2023-01-04|10|10.4|10.8|0.4|3.85|4|0|10.9|10.2|Upward|556|14,745,160
WHART|2023-01-05|2023-01-06|2|10.7|10.7|0.0|0.0|0|0|10.9|10.7|Downward|558|1,791,615
WHART|2023-01-09|2023-01-09|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|559|1,371,475
WHART|2023-01-10|2023-01-10|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|560|1,251,002
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|561|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|562|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|567|20,924,999
WHART|2023-01-20|2023-01-20|1|11.8|11.8|0.0|0.0|0|0|12.1|11.7|Downward|567|6,667,944
ruby/../Data/summary.csv

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [13]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [14]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [15]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,27,21,21,6,78,79,19,40,11,4,80,84,104,104,21,21
Upward,27,21,21,11,78,70,32,50,17,4,76,77,98,98,21,21

In [16]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [17]:
name_up = 'WHAIR'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [18]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [19]:
name_down = 'SINGER'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [20]:
df_groupby_trend = df.groupby('trend')
df_groupby_trend.ngroups

2

In [21]:
# Stat of each group
df_groupby_trend.size()

trend
Downward    104
Upward       98
dtype: int64

In [22]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [23]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [24]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-22,2022-12-29,6,2.96,2.96,0.0,0.0,0,0,2.98,2.92,9209889,NaN,7,12-22,12-29

In [25]:
df.groupby('trend').days.max()

trend
Downward     6
Upward      11
Name: days, dtype: int64

In [26]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [27]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [28]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
23,CPNREIT,12-22,12-29,6,19.5,19.4,-0.51,-1,-1,19.60,19.4,7229049,Downward
48,GVREIT,01-10,01-17,6,9.0,8.9,-1.11,-2,-1,9.15,8.9,1449890,Downward
78,KCE,01-13,01-20,6,52.0,49.0,-5.77,-12,-2,53.00,48.5,123505739,Downward
176,SYNEX,01-13,01-20,6,17.1,16.6,-2.92,-5,-1,17.50,16.5,10273525,Downward

In [ ]:
#df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

In [29]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    6    104     2.0  2.221154
Upward     11     98     3.0  3.540816

### Individual stock analysis

In [30]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [31]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty   maxp   minp
count  21.00       21.00  21.00  21.00
mean    7.54   903153.48   7.58   7.47
std     0.13   603659.27   0.13   0.10
min     7.35   115305.00   7.40   7.35
25%     7.45   365362.00   7.50   7.40
50%     7.50   783934.00   7.55   7.45
75%     7.55  1570800.00   7.60   7.50
max     7.95  2022633.00   8.00   7.80

In [32]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [33]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price          qty   maxp   minp
count  21.00        21.00  21.00  21.00
mean   28.67   6418928.62  29.24  28.18
std     0.94   2957371.33   0.99   0.96
min    27.00   2451784.00  27.25  26.75
25%    28.25   4986518.00  28.50  27.50
50%    28.50   6117144.00  29.25  28.00
75%    29.50   7336378.00  30.00  29.00
max    30.25  15522537.00  31.25  30.00

In [34]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [35]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(box_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)