In [1]:
import calendar
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.set_option('display.max_row',None)

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 1, 17), datetime.date(2023, 1, 16))

In [2]:
# specify the number of business days
num_days = 1
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(num_days)
yesterday = today - num_business_days
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2023-01-17
yesterday: 2023-01-16 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2022-12-19 00:00:00   Monday

### Get past one quarter data

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2022-12-19 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DCC', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'KCE', 'MAKRO', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART')
ORDER BY name, date

In [7]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date   price        qty    maxp    minp
174  JASIF  2022-12-27    8.05    1607162    8.05    8.00
200    KCE  2023-01-04   46.00   17539946   47.50   45.50
354    SCC  2023-01-13  355.00    3920941  358.00  353.00
39   BANPU  2023-01-13   12.50  107438620   12.50   12.20
89     DCC  2022-12-26    2.80    5027559    2.82    2.78

In [8]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name

price.set_index("name", inplace=True)
price.to_csv(output_file, header=None)

### After call ruby ruby\crt-summary.rb

In [9]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [10]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [11]:
df.groupby("trend").nunique()

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,nbr,fm_md,to_md
trend,,,,,,,,,,,,,,,,
Downward,25,21,20,6,77,75,17,34,10,4,76,72,92,92,21,20
Upward,25,20,21,11,81,74,27,53,15,5,83,81,99,99,20,21

In [31]:
mask_p = df['to_md'] == '01-17'
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [13]:
mask_m = df['to_md'] == '01-17'
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [14]:
mask_n = df.name == 'IVL'
df[mask_n][cols].style.format(format_dict)

In [15]:
df_groupby_trend = df.groupby('trend')
df_groupby_trend.ngroups

2

In [16]:
# Stat of each group
df_groupby_trend.size()

trend
Downward    92
Upward      99
dtype: int64

In [17]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [18]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [32]:
df[df['trend'].isnull()]

,name,fm_date,to_date,days,fm_price,to_price,diff,pct,spd,avg,max_price,min_price,ttl_qty,trend,nbr,fm_md,to_md
0,ASP,2022-12-19,2022-12-21,3,2.94,2.94,0.0,0.0,0,0,2.98,2.92,8059471,NaN,4,12-19,12-21

In [20]:
df.groupby('trend').days.max()

trend
Downward     6
Upward      12
Name: days, dtype: int64

In [21]:
df.query('days == 12')[cols].style.format(format_dict)

In [22]:
df.query('days == 6 and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
48,GVREIT,01-10,01-17,6,9.0,8.9,-1.11,-2,-1,9.15,8.9,1449890,Downward

In [33]:
df.groupby(['name', 'trend'])[['days']].agg('mean').reset_index()

       name     trend      days
0       ASP  Downward  3.000000
1       ASP    Upward  7.500000
2     BANPU  Downward  1.833333
3     BANPU    Upward  1.666667
4       BCH  Downward  1.600000
5       BCH    Upward  3.250000
6   CPNREIT  Downward  2.333333
7   CPNREIT    Upward  5.000000
8       DCC  Downward  1.500000
9       DCC    Upward  4.000000
10      DIF  Downward  2.000000
11      DIF    Upward  9.000000
12   GVREIT  Downward  3.666667
13   GVREIT    Upward  3.333333
14      IVL  Downward  4.500000
15      IVL    Upward  6.000000
16    JASIF  Downward  1.666667
17    JASIF    Upward  4.250000
18      KCE  Downward  2.000000
19      KCE    Upward  1.500000
20    MAKRO  Downward  2.000000
21    MAKRO    Upward  4.666667
22      MCS  Downward  2.000000
23      MCS    Upward  5.333333
24      NER  Downward  2.000000
25      NER    Upward  2.400000
26      ORI  Downward  2.000000
27      ORI    Upward  2.750000
28    PTTGC  Downward  3.000000
29    PTTGC    Upward  2.500000
30      RCL  Downward  1.800000
31      RCL    Upward  2.166667
32      SCC  Downward  2.333333
33      SCC    Upward  3.750000
34     SCCC  Downward  2.000000
35     SCCC    Upward  6.000000
36     SENA  Downward  3.333333
37     SENA    Upward  3.000000
38      STA  Downward  2.000000
39      STA    Upward  2.800000
40    SYNEX  Downward  1.833333
41    SYNEX    Upward  1.833333
42    TFFIF  Downward  2.500000
43    TFFIF    Upward  2.750000
44      TMT  Downward  3.000000
45      TMT    Upward  5.333333
46    WHAIR  Downward  3.333333
47    WHAIR    Upward  3.000000
48    WHART  Downward  1.250000
49    WHART    Upward  3.400000

In [24]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median      mean
trend
Downward    6     92     2.0  2.195652
Upward     12     99     2.0  3.404040

### Individual stock analysis

In [34]:
name = 'ASP'
df.query('name == @name')[cols].style.format(format_dict)

In [35]:
df_tmp = price.query('name == @name')
df_tmp.describe().round(2)

       price         qty   maxp   minp
count  21.00       21.00  21.00  21.00
mean    2.99  2362916.52   3.01   2.98
std     0.05  1099977.19   0.05   0.05
min     2.94   368103.00   2.96   2.92
25%     2.96  1331397.00   2.98   2.94
50%     2.96  2398944.00   2.98   2.96
75%     3.02  3351344.00   3.04   3.00
max     3.10  3989415.00   3.10   3.08