In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 10), datetime.date(2023, 2, 9))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-10
Today in mm-dd format: 02-10
yesterday: 2023-02-09 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-12 00:00:00   Thursday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK'"

In [7]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'BANPU', 'CK', 'CKP', 'COM7', 'CPF', 'CPNREIT', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MEGA', 'ORI', 'PTT', 'RCL', 'SINGER', 'STA', 'TMT', 'TTB', 'WHAIR'"

### End of Selection between Buy or Orders

In [8]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-12 00:00:00' AND name IN ('BANPU', 'CK', 'CKP', 'COM7', 'CPF', 'CPNREIT', 'DIF', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MEGA', 'ORI', 'PTT', 'RCL', 'SINGER', 'STA', 'TMT', 'TTB', 'WHAIR')
ORDER BY name, date

In [9]:
price = pd.read_sql(sql, const)
price.sample(5)

        name        date  price        qty  maxp  minp
116  CPNREIT  2023-01-20  20.40    3096674 21.30 20.30
96       CPF  2023-01-24  24.00   22508281 24.10 23.80
444    WHAIR  2023-01-20   7.95    1632933  8.00  7.80
436      TTB  2023-02-09   1.40  252820767  1.41  1.39
245      KCE  2023-01-19  49.00   17141005 49.25 48.50

In [10]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [11]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [13]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
BANPU|2023-01-12|2023-01-12|1|12.3|12.3|0.0|0.0|0|0|12.4|12.1||2|83,041,084
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|3|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|7|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|8|193,937,283
BANPU|2023-01-23|2023-02-10|15|12.5|10.9|-1.6|-12.8|-16|-2|12.6|10.7|Downward|23|2,058,642,124
CK|2023-01-12|2023-01-16|3|23.7|23.6|-0.1|-0.42|-1|-1|24.0|23.4|Downward|26|13,900,418
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|27|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|28|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|29|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|32|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|33|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|35|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|36|2,492,389
CK|2023-01-31|2023-02-01|2|22.6|22.6|0.0|0.0|0|0|23.1|22.4|Downward|38|14,195,847
CK|2023-02-02|2023-02-02|1|22.8|22.8|0.0|0.0|0|0|23.2|22.7|Upward|39|6,126,236
CK|2023-02-03|2023-02-08|4|22.7|22.4|-0.3|-1.32|-3|-1|22.9|22.3|Downward|43|12,475,240
CK|2023-02-09|2023-02-09|1|22.5|22.5|0.0|0.0|0|0|22.5|22.2|Upward|44|3,740,704
CK|2023-02-10|2023-02-10|1|22.1|22.1|0.0|0.0|0|0|22.6|22.1|Downward|45|3,006,254
CKP|2023-01-12|2023-01-18|5|4.74|4.52|-0.22|-4.64|-11|-3|4.76|4.5|Downward|50|75,910,012
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|52|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|56|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|57|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|59|15,946,162
CKP|2023-02-01|2023-02-01|1|4.56|4.56|0.0|0.0|0|0|4.58|4.52|Upward|60|20,374,772
CKP|2023-02-02|2023-02-02|1|4.54|4.54|0.0|0.0|0|0|4.6|4.5|Downward|61|14,870,177
CKP|2023-02-03|2023-02-07|3|4.56|4.68|0.12|2.63|6|2|4.72|4.54|Upward|64|38,604,423
CKP|2023-02-08|2023-02-10|3|4.66|4.66|0.0|0.0|0|0|4.7|4.6|Downward|67|33,965,199
COM7|2023-01-12|2023-01-26|11|34.5|30.5|-4.0|-11.59|-16|-2|35.0|30.0|Downward|78|197,768,841
COM7|2023-01-27|2023-01-27|1|31.25|31.25|0.0|0.0|0|0|31.25|30.5|Upward|79|10,790,066
COM7|2023-01-30|2023-01-30|1|31.0|31.0|0.0|0.0|0|0|31.5|30.75|Downward|80|6,501,093
COM7|2023-01-31|2023-02-01|2|31.25|33.0|1.75|5.6|7|3|33.25|30.5|Upward|82|28,473,812
COM7|2023-02-02|2023-02-10|7|32.5|30.5|-2.0|-6.15|-8|-2|33.25|30.5|Downward|89|68,689,724
CPF|2023-01-12|2023-01-18|5|24.2|24.1|-0.1|-0.41|-1|-1|24.3|24.0|Downward|94|66,132,867
CPF|2023-01-19|2023-01-19|1|24.2|24.2|0.0|0.0|0|0|24.2|24.1|Upward|95|7,006,246
CPF|2023-01-20|2023-01-30|7|24.1|23.5|-0.6|-2.49|-6|-1|24.2|23.5|Downward|102|135,054,026
CPF|2023-01-31|2023-02-01|2|23.6|23.9|0.3|1.27|3|1|24.0|23.3|Upward|104|56,393,763
CPF|2023-02-02|2023-02-10|7|23.8|22.9|-0.9|-3.78|-9|-2|24.0|22.9|Downward|111|146,822,847
CPNREIT|2023-01-12|2023-01-12|1|19.3|19.3|0.0|0.0|0|0|19.5|19.3|Downward|112|1,144,597
CPNREIT|2023-01-13|2023-01-19|5|19.5|20.6|1.1|5.64|11|2|20.6|19.1|Upward|117|9,426,285
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|120|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|122|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|125|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|127|1,159,029
CPNREIT|2023-02-03|2023-02-10|6|19.1|18.4|-0.7|-3.66|-7|-2|19.4|18.2|Downward|133|15,593,922
DIF|2023-01-12|2023-01-12|1|13.4|13.4|0.0|0.0|0|0|13.4|13.2|Downward|134|8,708,907
DIF|2023-01-13|2023-01-19|5|13.5|13.7|0.2|1.48|2|0|13.7|13.3|Upward|139|46,785,891
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|142|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|143|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|144|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|145|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|147|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|148|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|152|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|153|8,569,954
DIF|2023-02-10|2023-02-10|1|13.3|13.3|0.0|0.0|0|0|13.4|13.2|Downward|154|13,987,920
IVL|2023-01-12|2023-01-12|1|41.5|41.5|0.0|0.0|0|0|41.5|41.0|Downward|155|12,772,481
IVL|2023-01-13|2023-01-18|4|41.75|42.25|0.5|1.2|2|0|42.75|41.0|Upward|159|75,099,634
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|160|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|161|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|165|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|167|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|168|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|169|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|171|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|172|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|173|11,842,657
IVL|2023-02-08|2023-02-09|2|40.75|40.75|0.0|0.0|0|0|41.5|40.25|Upward|175|22,518,750
IVL|2023-02-10|2023-02-10|1|40.5|40.5|0.0|0.0|0|0|40.75|40.25|Downward|176|7,953,007
JASIF|2023-01-12|2023-01-13|2|8.25|8.2|-0.05|-0.61|-1|-1|8.25|8.2|Downward|178|8,709,854
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|180|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|181|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|185|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|189|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|191|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|192|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|196|12,746,881
JASIF|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|197|3,972,561
JMART|2023-01-12|2023-01-26|11|42.5|35.5|-7.0|-16.47|-28|-3|43.5|35.25|Downward|208|133,331,026
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|209|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|210|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|213|17,299,441
JMART|2023-02-03|2023-02-10|6|37.25|34.5|-2.75|-7.38|-11|-2|37.75|33.75|Downward|219|57,203,843
JMT|2023-01-12|2023-01-26|11|69.5|53.75|-15.75|-22.66|-63|-6|71.0|53.75|Downward|230|144,443,070
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|231|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|233|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|234|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|235|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|236|12,417,267
JMT|2023-02-06|2023-02-08|3|53.75|50.75|-3.0|-5.58|-12|-4|54.75|50.75|Downward|239|33,982,605
JMT|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|0|0|53.0|50.25|Upward|240|14,352,623
JMT|2023-02-10|2023-02-10|1|50.5|50.5|0.0|0.0|0|0|52.0|50.25|Downward|241|11,528,715
KCE|2023-01-12|2023-01-20|7|52.5|49.0|-3.5|-6.67|-14|-2|53.0|48.5|Downward|248|182,060,498
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|249|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|250|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|251|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|252|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|253|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|254|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|258|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|259|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|260|17,516,788
KCE|2023-02-08|2023-02-10|3|50.5|47.25|-3.25|-6.44|-13|-5|55.25|47.25|Downward|263|202,268,953
MEGA|2023-01-12|2023-01-13|2|49.75|49.0|-0.75|-1.51|-3|-2|50.25|48.5|Downward|265|5,791,065
MEGA|2023-01-16|2023-01-18|3|49.5|49.75|0.25|0.51|1|0|50.5|49.25|Upward|268|7,396,707
MEGA|2023-01-19|2023-01-19|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Downward|269|1,548,274
MEGA|2023-01-20|2023-01-31|8|49.75|52.25|2.5|5.03|10|1|52.5|48.75|Upward|277|21,954,124
MEGA|2023-02-01|2023-02-01|1|51.75|51.75|0.0|0.0|0|0|52.25|51.0|Downward|278|1,697,726
MEGA|2023-02-02|2023-02-02|1|52.0|52.0|0.0|0.0|0|0|52.25|51.5|Upward|279|3,056,739
MEGA|2023-02-03|2023-02-03|1|51.25|51.25|0.0|0.0|0|0|52.0|51.25|Downward|280|1,374,224
MEGA|2023-02-06|2023-02-06|1|51.75|51.75|0.0|0.0|0|0|52.0|51.5|Upward|281|1,434,420
MEGA|2023-02-07|2023-02-08|2|51.5|50.75|-0.75|-1.46|-3|-2|52.0|50.5|Downward|283|3,832,397
MEGA|2023-02-09|2023-02-09|1|52.0|52.0|0.0|0.0|0|0|52.25|50.75|Upward|284|2,296,213
MEGA|2023-02-10|2023-02-10|1|51.5|51.5|0.0|0.0|0|0|52.0|51.25|Downward|285|1,598,024
ORI|2023-01-12|2023-01-12|1|11.8|11.8|0.0|0.0|0|0|11.9|11.7|Downward|286|4,747,397
ORI|2023-01-13|2023-01-16|2|11.9|11.9|0.0|0.0|0|0|12.0|11.5|Upward|288|12,469,510
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|290|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|293|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|296|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|299|32,777,837
ORI|2023-02-01|2023-02-09|7|12.1|11.7|-0.4|-3.31|-4|-1|12.3|11.5|Downward|306|38,175,270
ORI|2023-02-10|2023-02-10|1|11.9|11.9|0.0|0.0|0|0|11.9|11.6|Upward|307|4,834,840
PTT|2023-01-12|2023-01-16|3|33.75|33.75|0.0|0.0|0|0|34.0|33.25|Upward|310|179,910,510
PTT|2023-01-17|2023-01-20|4|33.5|33.25|-0.25|-0.75|-1|-1|34.0|33.0|Downward|314|204,039,863
PTT|2023-01-23|2023-01-23|1|33.75|33.75|0.0|0.0|0|0|33.75|33.25|Upward|315|15,059,359
PTT|2023-01-24|2023-02-07|11|33.5|32.5|-1.0|-2.99|-4|-1|34.0|32.5|Downward|326|331,665,517
PTT|2023-02-08|2023-02-08|1|32.75|32.75|0.0|0.0|0|0|33.0|32.5|Upward|327|42,273,305
PTT|2023-02-09|2023-02-10|2|32.5|32.5|0.0|0.0|0|0|32.75|32.25|Downward|329|71,289,061
RCL|2023-01-12|2023-01-16|3|31.75|31.25|-0.5|-1.57|-2|-1|32.0|31.25|Downward|332|7,697,498
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|334|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|336|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|339|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|340|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|343|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|345|21,219,944
RCL|2023-02-03|2023-02-07|3|30.75|31.0|0.25|0.81|1|0|31.25|30.5|Upward|348|6,209,457
RCL|2023-02-08|2023-02-09|2|30.5|30.5|0.0|0.0|0|0|31.25|30.25|Downward|350|4,603,482
RCL|2023-02-10|2023-02-10|1|30.75|30.75|0.0|0.0|0|0|30.75|30.25|Upward|351|1,341,212
SINGER|2023-01-12|2023-01-13|2|30.0|30.25|0.25|0.83|1|0|31.25|29.5|Upward|353|14,964,597
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|359|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|360|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|362|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|367|26,173,063
SINGER|2023-02-03|2023-02-08|4|28.25|27.0|-1.25|-4.42|-5|-2|28.75|27.0|Downward|371|12,047,147
SINGER|2023-02-09|2023-02-09|1|27.5|27.5|0.0|0.0|0|0|27.5|26.25|Upward|372|5,240,034
SINGER|2023-02-10|2023-02-10|1|26.75|26.75|0.0|0.0|0|0|27.5|26.75|Downward|373|2,084,092
STA|2023-01-12|2023-01-16|3|21.3|21.2|-0.1|-0.47|-1|-1|21.7|21.0|Downward|376|9,238,153
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|377|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|378|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|379|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|381|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|385|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|387|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|389|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|390|4,951,737
STA|2023-02-06|2023-02-08|3|22.6|24.5|1.9|8.41|19|6|24.7|22.3|Upward|393|41,947,740
STA|2023-02-09|2023-02-10|2|24.1|23.9|-0.2|-0.83|-2|-1|24.5|23.6|Downward|395|18,084,341
TMT|2023-01-12|2023-01-17|4|8.0|8.0|0.0|0.0|0|0|8.05|7.9|Downward|399|1,459,870
TMT|2023-01-18|2023-01-24|5|8.05|8.45|0.4|4.97|8|1|8.45|8.0|Upward|404|3,289,220
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|411|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|412|162,400
TMT|2023-02-06|2023-02-09|4|8.15|8.05|-0.1|-1.23|-2|-1|8.25|8.0|Downward|416|760,892
TMT|2023-02-10|2023-02-10|1|8.2|8.2|0.0|0.0|0|0|8.2|8.0|Upward|417|158,167
TTB|2023-01-12|2023-01-12|1|1.43|1.43|0.0|0.0|0|0|1.45|1.42|Upward|418|224,124,688
TTB|2023-01-13|2023-01-13|1|1.41|1.41|0.0|0.0|0|0|1.43|1.4|Downward|419|369,101,160
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|423|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|424|509,121,072
TTB|2023-01-23|2023-02-01|8|1.44|1.47|0.03|2.08|3|0|1.48|1.4|Upward|432|2,259,173,623
TTB|2023-02-02|2023-02-10|7|1.45|1.4|-0.05|-3.45|-5|-1|1.47|1.39|Downward|439|1,184,311,857
WHAIR|2023-01-12|2023-01-16|3|7.5|7.5|0.0|0.0|0|0|7.55|7.4|Downward|442|4,965,753
WHAIR|2023-01-17|2023-01-20|4|7.55|7.95|0.4|5.3|8|2|8.0|7.45|Upward|446|6,455,396
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|448|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|450|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|452|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|456|3,326,380
WHAIR|2023-02-06|2023-02-10|5|8.0|7.9|-0.1|-1.25|-2|-1|8.1|7.85|Downward|460|2,057,078
ruby/../Data/summary.csv

In [14]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [15]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [16]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [17]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [18]:
name_up = 'PTTGC'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [19]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')

In [22]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [23]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [24]:
#df.groupby('trend').days.max()

In [25]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   15     94    2.00  3.10
Upward      8     80    1.00  2.10

In [26]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [27]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [28]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
4,BANPU,01-23,02-10,15,12.50,10.90,-12.80,-16,-2,12.60,10.70,2058642124,Downward

### Individual stock analysis

In [29]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [30]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price  qty  maxp  minp
count   0.00 0.00  0.00  0.00
mean     NaN  NaN   NaN   NaN
std      NaN  NaN   NaN   NaN
min      NaN  NaN   NaN   NaN
25%      NaN  NaN   NaN   NaN
50%      NaN  NaN   NaN   NaN
75%      NaN  NaN   NaN   NaN
max      NaN  NaN   NaN   NaN

In [31]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [32]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price          qty  maxp  minp
count  22.00        22.00 22.00 22.00
mean   11.94 122088775.23 12.09 11.79
std     0.60 103653582.35  0.49  0.58
min    10.90  30894152.00 11.10 10.70
25%    11.52  55490737.75 11.62 11.32
50%    12.30  94456257.50 12.30 12.05
75%    12.40 154543901.00 12.50 12.20
max    12.70 415903536.00 12.70 12.40

In [33]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [34]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [35]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-10'
ORDER BY name, date

In [36]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-02-10   2.48  12908381   2.52   2.48
1    ADVANC  2023-02-10 206.00  17037520 206.00 201.00
2        AH  2023-02-10  30.75   5272428  32.00  30.50
3       AIE  2023-02-10   2.98   2006091   3.04   2.98
4    AIMIRT  2023-02-10  12.30     44600  12.30  12.20
..      ...         ...    ...       ...    ...    ...
189   WHAIR  2023-02-10   7.90    321310   7.95   7.85
190   WHART  2023-02-10  11.70    632010  11.70  11.50
191   WHAUP  2023-02-10   4.06   2800220   4.12   4.06
192    WICE  2023-02-10  11.30   1406725  11.60  11.30
193    WORK  2023-02-10  18.40    141505  18.40  18.30

[194 rows x 6 columns]