In [1]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine
#from pandas.tseries.offsets import BDay
from pandas.tseries.offsets import * 

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = 11
pd.options.display.float_format = '{:.2f}'.format

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 2, 8), datetime.date(2023, 2, 7))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
to_mmdd = today.strftime('%m-%d')
print(f'Today in mm-dd format: {to_mmdd}')
print(f'yesterday: {yesterday}')

today: 2023-02-08
Today in mm-dd format: 02-08
yesterday: 2023-02-07 00:00:00

In [3]:
yesterday = yesterday.date()
one_month_ago = yesterday + DateOffset(days = -28)
print('One month ago: ', one_month_ago, ' ', one_month_ago.day_name())

One month ago:  2023-01-10 00:00:00   Tuesday

In [4]:
format_dict = {
    'ttl_qty':'{:,}','qty':'{:,}',
    'from_price':'{:.2f}','to_price':'{:.2f}','diff':'{:.2f}','fm_price':'{:.2f}',
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',
    'maxp':'{:.2f}','minp':'{:.2f}','pct':'{:,.2f}%',  
}

cols = 'name fm_md to_md days fm_price to_price pct spd avg max_price min_price ttl_qty trend'.split()

### Get past one quarter data

In [5]:
sql = """
SELECT name
FROM buy 
ORDER BY name
"""
buy = pd.read_sql(sql, const)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART'"

In [6]:
in_p = in_p + ", 'TTB', 'CKP', 'CK'"
in_p

"'ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK'"

In [ ]:
sql = """
SELECT name
FROM orders
ORDER BY name
"""
buy = pd.read_sql(sql, conlite)

names = buy['name'].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

### End of Selection between Buy or Orders

In [7]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' AND name IN (%s) 
ORDER BY name, date"""
sql = sql % (one_month_ago, in_p)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-01-10 00:00:00' AND name IN ('ASP', 'BANPU', 'BCH', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JASIF', 'JMART', 'JMT', 'KCE', 'MCS', 'NER', 'ORI', 'PTTGC', 'RCL', 'SCC', 'SCCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TMT', 'WHAIR', 'WHART', 'TTB', 'CKP', 'CK')
ORDER BY name, date

In [8]:
price = pd.read_sql(sql, const)
price.sample(5)

      name        date  price       qty   maxp   minp
396    SCC  2023-01-10 358.00   3859474 358.00 351.00
218  JASIF  2023-02-07   8.25   3589348   8.25   8.20
288    MCS  2023-01-12   9.50    667557   9.60   9.45
45     BCH  2023-01-11  21.80  11508810  22.20  21.70
508  SYNEX  2023-01-12  17.20   1549968  17.30  17.00

In [10]:
data_path = "../data/"
file_name = "Quarterly-Price-by-Name.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

price.to_csv(output_file, header=None, index=False)
price.to_csv(osd_file, header=True, index=False)

### Call ruby ruby\crt-summary.rb

In [11]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Daily'

In [12]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

In [13]:
!ruby ruby\\crt-summary.rb

ruby/../Data/Quarterly-Price-by-Name.csv
name|fm_date|to_date|days|fm_price|to_price|diff|pct|spd|avg|max_price|min_price|trend|nbr|ttl_qty
ASP|2023-01-10|2023-01-10|1|3.02|3.02|0.0|0.0|0|0|3.04|3.0||2|3,727,565
ASP|2023-01-11|2023-01-18|6|3.06|3.1|0.04|1.31|2|0|3.1|3.02|Upward|8|12,156,697
ASP|2023-01-19|2023-01-20|2|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|10|2,184,225
ASP|2023-01-23|2023-01-23|1|3.1|3.1|0.0|0.0|0|0|3.1|3.08|Upward|11|1,069,120
ASP|2023-01-24|2023-01-24|1|3.08|3.08|0.0|0.0|0|0|3.1|3.08|Downward|12|2,396,809
ASP|2023-01-25|2023-01-25|1|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|13|3,758,047
ASP|2023-01-26|2023-01-26|1|3.08|3.08|0.0|0.0|0|0|3.12|3.08|Downward|14|3,647,294
ASP|2023-01-27|2023-01-30|2|3.1|3.1|0.0|0.0|0|0|3.12|3.08|Upward|16|1,798,533
ASP|2023-01-31|2023-01-31|1|3.08|3.08|0.0|0.0|0|0|3.1|3.06|Downward|17|3,048,744
ASP|2023-02-01|2023-02-02|2|3.16|3.16|0.0|0.0|0|0|3.24|3.08|Upward|19|28,871,862
ASP|2023-02-03|2023-02-03|1|3.1|3.1|0.0|0.0|0|0|3.18|3.1|Downward|20|3,867,567
ASP|2023-02-06|2023-02-06|1|3.14|3.14|0.0|0.0|0|0|3.14|3.1|Upward|21|2,481,635
ASP|2023-02-07|2023-02-08|2|3.12|3.12|0.0|0.0|0|0|3.16|3.12|Downward|23|3,596,310
BANPU|2023-01-10|2023-01-12|3|12.5|12.3|-0.2|-1.6|-2|-1|12.6|12.1|Downward|26|333,793,671
BANPU|2023-01-13|2023-01-13|1|12.5|12.5|0.0|0.0|0|0|12.5|12.2|Upward|27|107,438,620
BANPU|2023-01-16|2023-01-19|4|12.4|12.3|-0.1|-0.81|-1|-1|12.5|12.2|Downward|31|242,893,944
BANPU|2023-01-20|2023-01-20|1|12.7|12.7|0.0|0.0|0|0|12.7|12.3|Upward|32|193,937,283
BANPU|2023-01-23|2023-02-08|13|12.5|11.0|-1.5|-12.0|-15|-2|12.6|10.9|Downward|45|1,565,586,144
BCH|2023-01-10|2023-01-12|3|21.9|21.4|-0.5|-2.28|-5|-2|22.2|21.3|Downward|48|33,616,006
BCH|2023-01-13|2023-01-16|2|21.5|21.5|0.0|0.0|0|0|21.8|21.4|Upward|50|9,179,643
BCH|2023-01-17|2023-01-25|7|21.4|20.6|-0.8|-3.74|-8|-2|21.6|20.6|Downward|57|46,355,474
BCH|2023-01-26|2023-01-31|4|20.7|21.8|1.1|5.31|11|2|22.0|20.5|Upward|61|55,795,055
BCH|2023-02-01|2023-02-02|2|21.6|21.4|-0.2|-0.93|-2|-1|21.8|21.3|Downward|63|21,808,662
BCH|2023-02-03|2023-02-03|1|21.5|21.5|0.0|0.0|0|0|21.7|21.4|Upward|64|12,718,266
BCH|2023-02-06|2023-02-08|3|21.3|21.0|-0.3|-1.41|-3|-1|21.5|20.9|Downward|67|20,086,506
CK|2023-01-10|2023-01-10|1|23.5|23.5|0.0|0.0|0|0|23.8|23.2|Downward|68|8,765,137
CK|2023-01-11|2023-01-12|2|23.6|23.7|0.1|0.42|1|0|24.0|23.4|Upward|70|8,423,299
CK|2023-01-13|2023-01-16|2|23.6|23.6|0.0|0.0|0|0|23.9|23.4|Downward|72|8,917,541
CK|2023-01-17|2023-01-17|1|23.8|23.8|0.0|0.0|0|0|24.2|23.8|Upward|73|14,968,318
CK|2023-01-18|2023-01-18|1|23.6|23.6|0.0|0.0|0|0|24.0|23.4|Downward|74|12,435,903
CK|2023-01-19|2023-01-19|1|23.9|23.9|0.0|0.0|0|0|24.1|23.6|Upward|75|6,837,042
CK|2023-01-20|2023-01-24|3|23.7|23.5|-0.2|-0.84|-2|-1|24.1|23.4|Downward|78|17,524,734
CK|2023-01-25|2023-01-25|1|23.6|23.6|0.0|0.0|0|0|23.8|23.5|Upward|79|4,666,111
CK|2023-01-26|2023-01-27|2|23.3|22.7|-0.6|-2.58|-6|-3|23.7|22.6|Downward|81|17,070,329
CK|2023-01-30|2023-01-30|1|22.8|22.8|0.0|0.0|0|0|23.0|22.6|Upward|82|2,492,389
CK|2023-01-31|2023-02-01|2|22.6|22.6|0.0|0.0|0|0|23.1|22.4|Downward|84|14,195,847
CK|2023-02-02|2023-02-02|1|22.8|22.8|0.0|0.0|0|0|23.2|22.7|Upward|85|6,126,236
CK|2023-02-03|2023-02-08|4|22.7|22.4|-0.3|-1.32|-3|-1|22.9|22.3|Downward|89|12,475,240
CKP|2023-01-10|2023-01-10|1|4.7|4.7|0.0|0.0|0|0|4.74|4.64|Downward|90|26,751,010
CKP|2023-01-11|2023-01-12|2|4.74|4.74|0.0|0.0|0|0|4.76|4.7|Upward|92|14,743,900
CKP|2023-01-13|2023-01-18|4|4.7|4.52|-0.18|-3.83|-9|-3|4.76|4.5|Downward|96|70,164,548
CKP|2023-01-19|2023-01-20|2|4.56|4.64|0.08|1.75|4|2|4.66|4.52|Upward|98|29,205,388
CKP|2023-01-23|2023-01-26|4|4.6|4.5|-0.1|-2.17|-5|-2|4.64|4.48|Downward|102|39,628,888
CKP|2023-01-27|2023-01-27|1|4.54|4.54|0.0|0.0|0|0|4.56|4.52|Upward|103|6,963,352
CKP|2023-01-30|2023-01-31|2|4.52|4.52|0.0|0.0|0|0|4.58|4.5|Downward|105|15,946,162
CKP|2023-02-01|2023-02-01|1|4.56|4.56|0.0|0.0|0|0|4.58|4.52|Upward|106|20,374,772
CKP|2023-02-02|2023-02-02|1|4.54|4.54|0.0|0.0|0|0|4.6|4.5|Downward|107|14,870,177
CKP|2023-02-03|2023-02-07|3|4.56|4.68|0.12|2.63|6|2|4.72|4.54|Upward|110|38,604,423
CKP|2023-02-08|2023-02-08|1|4.66|4.66|0.0|0.0|0|0|4.7|4.62|Downward|111|12,625,762
CPNREIT|2023-01-10|2023-01-10|1|18.8|18.8|0.0|0.0|0|0|19.6|18.8|Downward|112|2,419,471
CPNREIT|2023-01-11|2023-01-19|7|19.3|20.6|1.3|6.74|13|1|20.6|19.1|Upward|119|11,640,345
CPNREIT|2023-01-20|2023-01-24|3|20.4|19.3|-1.1|-5.39|-11|-4|21.3|19.3|Downward|122|10,078,994
CPNREIT|2023-01-25|2023-01-26|2|19.4|19.6|0.2|1.03|2|1|19.7|19.4|Upward|124|2,216,218
CPNREIT|2023-01-27|2023-01-31|3|19.5|19.3|-0.2|-1.03|-2|-1|19.7|19.2|Downward|127|3,517,218
CPNREIT|2023-02-01|2023-02-02|2|19.4|19.4|0.0|0.0|0|0|19.5|19.2|Upward|129|1,159,029
CPNREIT|2023-02-03|2023-02-08|4|19.1|18.4|-0.7|-3.66|-7|-2|19.4|18.2|Downward|133|13,218,559
DIF|2023-01-10|2023-01-11|2|13.3|13.3|0.0|0.0|0|0|13.3|13.2|Downward|135|14,384,062
DIF|2023-01-12|2023-01-19|6|13.4|13.7|0.3|2.24|3|0|13.7|13.2|Upward|141|55,494,798
DIF|2023-01-20|2023-01-24|3|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|144|14,698,967
DIF|2023-01-25|2023-01-25|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|145|8,103,408
DIF|2023-01-26|2023-01-26|1|13.6|13.6|0.0|0.0|0|0|13.7|13.5|Downward|146|18,977,797
DIF|2023-01-27|2023-01-27|1|13.7|13.7|0.0|0.0|0|0|13.7|13.5|Upward|147|7,462,352
DIF|2023-01-30|2023-01-31|2|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|149|11,737,432
DIF|2023-02-01|2023-02-01|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|150|8,966,593
DIF|2023-02-02|2023-02-07|4|13.6|13.6|0.0|0.0|0|0|13.7|13.6|Downward|154|31,473,792
DIF|2023-02-08|2023-02-08|1|13.7|13.7|0.0|0.0|0|0|13.7|13.6|Upward|155|8,569,954
GVREIT|2023-01-10|2023-01-16|5|9.0|9.0|0.0|0.0|0|0|9.15|8.9|Upward|160|1,133,566
GVREIT|2023-01-17|2023-01-17|1|8.9|8.9|0.0|0.0|0|0|9.0|8.9|Downward|161|316,324
GVREIT|2023-01-18|2023-01-24|5|9.0|9.75|0.75|8.33|15|3|9.75|8.85|Upward|166|4,993,973
GVREIT|2023-01-25|2023-01-25|1|9.6|9.6|0.0|0.0|0|0|9.75|9.6|Downward|167|642,010
GVREIT|2023-01-26|2023-01-26|1|9.65|9.65|0.0|0.0|0|0|9.7|9.6|Upward|168|461,700
GVREIT|2023-01-27|2023-01-27|1|9.45|9.45|0.0|0.0|0|0|9.65|9.45|Downward|169|281,301
GVREIT|2023-01-30|2023-02-01|3|9.55|9.75|0.2|2.09|4|1|9.75|9.45|Upward|172|669,621
GVREIT|2023-02-02|2023-02-02|1|9.7|9.7|0.0|0.0|0|0|9.75|9.65|Downward|173|224,521
GVREIT|2023-02-03|2023-02-07|3|9.75|9.8|0.05|0.51|1|0|9.9|9.6|Upward|176|1,566,531
GVREIT|2023-02-08|2023-02-08|1|9.75|9.75|0.0|0.0|0|0|9.8|9.55|Downward|177|375,806
IVL|2023-01-10|2023-01-10|1|41.25|41.25|0.0|0.0|0|0|41.5|39.0|Downward|178|69,011,455
IVL|2023-01-11|2023-01-18|6|41.5|42.25|0.75|1.81|3|0|42.75|40.75|Upward|184|109,443,298
IVL|2023-01-19|2023-01-19|1|41.75|41.75|0.0|0.0|0|0|42.25|41.5|Downward|185|12,436,138
IVL|2023-01-20|2023-01-20|1|42.25|42.25|0.0|0.0|0|0|42.5|41.75|Upward|186|15,314,376
IVL|2023-01-23|2023-01-26|4|42.0|40.25|-1.75|-4.17|-7|-2|42.5|40.0|Downward|190|61,818,314
IVL|2023-01-27|2023-01-30|2|41.25|41.25|0.0|0.0|0|0|41.5|40.25|Upward|192|22,582,017
IVL|2023-01-31|2023-01-31|1|40.5|40.5|0.0|0.0|0|0|41.25|40.5|Downward|193|13,669,626
IVL|2023-02-01|2023-02-01|1|41.25|41.25|0.0|0.0|0|0|41.25|40.5|Upward|194|11,652,339
IVL|2023-02-02|2023-02-03|2|40.75|40.5|-0.25|-0.61|-1|-1|41.25|40.25|Downward|196|15,971,520
IVL|2023-02-06|2023-02-06|1|41.0|41.0|0.0|0.0|0|0|41.25|39.75|Upward|197|16,598,179
IVL|2023-02-07|2023-02-07|1|40.5|40.5|0.0|0.0|0|0|41.0|40.25|Downward|198|11,842,657
IVL|2023-02-08|2023-02-08|1|40.75|40.75|0.0|0.0|0|0|41.5|40.5|Upward|199|13,513,473
JASIF|2023-01-10|2023-01-12|3|8.25|8.25|0.0|0.0|0|0|8.3|8.2|Upward|202|13,676,877
JASIF|2023-01-13|2023-01-13|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|203|6,798,932
JASIF|2023-01-16|2023-01-17|2|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|205|3,632,171
JASIF|2023-01-18|2023-01-18|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|206|2,744,544
JASIF|2023-01-19|2023-01-24|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|210|16,790,423
JASIF|2023-01-25|2023-01-30|4|8.2|8.15|-0.05|-0.61|-1|-1|8.25|8.15|Downward|214|28,383,533
JASIF|2023-01-31|2023-02-01|2|8.2|8.25|0.05|0.61|1|0|8.25|8.15|Upward|216|8,227,605
JASIF|2023-02-02|2023-02-02|1|8.2|8.2|0.0|0.0|0|0|8.25|8.2|Downward|217|3,117,519
JASIF|2023-02-03|2023-02-08|4|8.25|8.25|0.0|0.0|0|0|8.25|8.2|Upward|221|12,746,881
JMART|2023-01-10|2023-01-13|4|42.0|42.5|0.5|1.19|2|0|43.5|41.5|Upward|225|30,820,286
JMART|2023-01-16|2023-01-26|9|41.75|35.5|-6.25|-14.97|-25|-3|42.75|35.25|Downward|234|118,032,446
JMART|2023-01-27|2023-01-27|1|37.25|37.25|0.0|0.0|0|0|37.5|36.0|Upward|235|14,613,196
JMART|2023-01-30|2023-01-30|1|37.0|37.0|0.0|0.0|0|0|38.0|36.5|Downward|236|9,743,425
JMART|2023-01-31|2023-02-02|3|37.25|37.5|0.25|0.67|1|0|38.25|36.5|Upward|239|17,299,441
JMART|2023-02-03|2023-02-08|4|37.25|35.5|-1.75|-4.7|-7|-2|37.75|35.5|Downward|243|25,443,886
JMT|2023-01-10|2023-01-10|1|68.75|68.75|0.0|0.0|0|0|69.75|68.75|Downward|244|7,008,353
JMT|2023-01-11|2023-01-13|3|69.5|69.5|0.0|0.0|0|0|71.0|68.75|Upward|247|22,160,818
JMT|2023-01-16|2023-01-26|9|68.25|53.75|-14.5|-21.25|-58|-7|69.75|53.75|Downward|256|129,571,700
JMT|2023-01-27|2023-01-27|1|55.5|55.5|0.0|0.0|0|0|56.0|53.5|Upward|257|16,158,754
JMT|2023-01-30|2023-01-31|2|53.5|53.5|0.0|0.0|0|0|56.25|51.5|Downward|259|45,047,024
JMT|2023-02-01|2023-02-01|1|54.25|54.25|0.0|0.0|0|0|54.5|53.0|Upward|260|11,053,059
JMT|2023-02-02|2023-02-02|1|53.75|53.75|0.0|0.0|0|0|55.0|53.25|Downward|261|12,540,923
JMT|2023-02-03|2023-02-03|1|54.75|54.75|0.0|0.0|0|0|55.25|53.75|Upward|262|12,417,267
JMT|2023-02-06|2023-02-08|3|53.75|50.75|-3.0|-5.58|-12|-4|54.75|50.75|Downward|265|33,982,605
KCE|2023-01-10|2023-01-11|2|50.0|49.25|-0.75|-1.5|-3|-2|50.75|49.0|Downward|267|50,328,018
KCE|2023-01-12|2023-01-12|1|52.5|52.5|0.0|0.0|0|0|53.0|49.5|Upward|268|58,554,759
KCE|2023-01-13|2023-01-20|6|52.0|49.0|-3.0|-5.77|-12|-2|53.0|48.5|Downward|274|123,505,739
KCE|2023-01-23|2023-01-23|1|49.75|49.75|0.0|0.0|0|0|50.25|48.75|Upward|275|17,524,215
KCE|2023-01-24|2023-01-24|1|49.25|49.25|0.0|0.0|0|0|51.25|49.25|Downward|276|31,520,414
KCE|2023-01-25|2023-01-25|1|49.5|49.5|0.0|0.0|0|0|50.0|49.25|Upward|277|10,143,028
KCE|2023-01-26|2023-01-26|1|49.0|49.0|0.0|0.0|0|0|50.25|48.75|Downward|278|14,288,984
KCE|2023-01-27|2023-01-27|1|50.25|50.25|0.0|0.0|0|0|50.5|49.0|Upward|279|13,719,929
KCE|2023-01-30|2023-01-30|1|50.0|50.0|0.0|0.0|0|0|50.5|49.5|Downward|280|10,465,232
KCE|2023-01-31|2023-02-03|4|54.75|58.0|3.25|5.94|13|3|58.5|50.5|Upward|284|214,389,940
KCE|2023-02-06|2023-02-06|1|56.5|56.5|0.0|0.0|0|0|57.75|56.25|Downward|285|25,252,398
KCE|2023-02-07|2023-02-07|1|57.0|57.0|0.0|0.0|0|0|57.75|56.0|Upward|286|17,516,788
KCE|2023-02-08|2023-02-08|1|50.5|50.5|0.0|0.0|0|0|55.25|50.5|Downward|287|96,517,615
MCS|2023-01-10|2023-01-12|3|9.55|9.5|-0.05|-0.52|-1|-1|9.65|9.2|Downward|290|4,192,866
MCS|2023-01-13|2023-01-19|5|9.6|9.8|0.2|2.08|4|0|9.8|9.5|Upward|295|3,829,788
MCS|2023-01-20|2023-01-20|1|9.75|9.75|0.0|0.0|0|0|9.8|9.65|Downward|296|701,950
MCS|2023-01-23|2023-01-23|1|9.95|9.95|0.0|0.0|0|0|9.95|9.7|Upward|297|1,005,676
MCS|2023-01-24|2023-01-24|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|298|1,505,174
MCS|2023-01-25|2023-01-25|1|10.2|10.2|0.0|0.0|0|0|10.3|10.1|Upward|299|837,103
MCS|2023-01-26|2023-01-26|1|10.0|10.0|0.0|0.0|0|0|10.2|9.85|Downward|300|1,271,966
MCS|2023-01-27|2023-01-31|3|10.1|9.95|-0.15|-1.49|-2|-1|10.2|9.9|Upward|303|2,139,488
MCS|2023-02-01|2023-02-01|1|10.0|10.0|0.0|0.0|0|0|10.1|9.9|Downward|304|869,625
MCS|2023-02-02|2023-02-03|2|9.95|9.95|0.0|0.0|0|0|10.1|9.9|Upward|306|947,644
MCS|2023-02-06|2023-02-06|1|9.9|9.9|0.0|0.0|0|0|10.0|9.9|Downward|307|652,568
MCS|2023-02-07|2023-02-07|1|9.95|9.95|0.0|0.0|0|0|10.0|9.9|Upward|308|406,865
MCS|2023-02-08|2023-02-08|1|9.9|9.9|0.0|0.0|0|0|9.95|9.9|Downward|309|527,195
NER|2023-01-10|2023-01-11|2|6.4|6.3|-0.1|-1.56|-2|-1|6.45|6.25|Downward|311|18,006,041
NER|2023-01-12|2023-01-13|2|6.4|6.45|0.05|0.78|1|0|6.45|6.3|Upward|313|11,482,949
NER|2023-01-16|2023-01-20|5|6.4|6.35|-0.05|-0.78|-1|-1|6.45|6.35|Downward|318|14,996,175
NER|2023-01-23|2023-01-23|1|6.45|6.45|0.0|0.0|0|0|6.45|6.4|Upward|319|4,182,338
NER|2023-01-24|2023-01-24|1|6.4|6.4|0.0|0.0|0|0|6.45|6.4|Downward|320|2,154,024
NER|2023-01-25|2023-01-26|2|6.55|6.65|0.1|1.53|2|1|6.7|6.4|Upward|322|42,913,468
NER|2023-01-27|2023-02-01|4|6.6|6.35|-0.25|-3.79|-5|-2|6.7|6.3|Downward|326|38,923,402
NER|2023-02-02|2023-02-06|3|6.4|6.5|0.1|1.56|2|0|6.5|6.3|Upward|329|24,426,533
NER|2023-02-07|2023-02-08|2|6.45|6.35|-0.1|-1.55|-2|-1|6.5|6.3|Downward|331|18,169,994
ORI|2023-01-10|2023-01-11|2|11.7|11.7|0.0|0.0|0|0|12.1|11.6|Downward|333|18,046,746
ORI|2023-01-12|2023-01-16|3|11.8|11.9|0.1|0.85|1|0|12.0|11.5|Upward|336|17,216,907
ORI|2023-01-17|2023-01-18|2|11.8|11.8|0.0|0.0|0|0|11.9|11.4|Downward|338|28,566,002
ORI|2023-01-19|2023-01-23|3|11.9|11.9|0.0|0.0|0|0|12.0|11.6|Upward|341|19,054,666
ORI|2023-01-24|2023-01-26|3|11.8|11.6|-0.2|-1.69|-2|-1|12.0|11.5|Downward|344|16,286,040
ORI|2023-01-27|2023-01-31|3|11.9|12.2|0.3|2.52|3|1|12.2|11.6|Upward|347|32,777,837
ORI|2023-02-01|2023-02-08|6|12.1|11.7|-0.4|-3.31|-4|-1|12.3|11.5|Downward|353|32,257,200
PTTGC|2023-01-10|2023-01-10|1|50.25|50.25|0.0|0.0|0|0|50.5|47.5|Downward|354|70,792,460
PTTGC|2023-01-11|2023-01-11|1|50.5|50.5|0.0|0.0|0|0|50.5|49.25|Upward|355|28,106,901
PTTGC|2023-01-12|2023-01-13|2|50.25|50.0|-0.25|-0.5|-1|-1|50.75|49.25|Downward|357|38,521,704
PTTGC|2023-01-16|2023-01-18|3|50.25|51.5|1.25|2.49|5|1|51.75|49.75|Upward|360|57,760,246
PTTGC|2023-01-19|2023-01-20|2|51.25|50.0|-1.25|-2.44|-5|-3|51.5|49.75|Downward|362|34,342,502
PTTGC|2023-01-23|2023-01-25|3|50.75|51.25|0.5|0.99|2|0|51.5|50.0|Upward|365|29,789,145
PTTGC|2023-01-26|2023-01-26|1|49.75|49.75|0.0|0.0|0|0|51.0|49.25|Downward|366|24,638,391
PTTGC|2023-01-27|2023-01-27|1|50.5|50.5|0.0|0.0|0|0|50.5|49.5|Upward|367|13,790,565
PTTGC|2023-01-30|2023-01-31|2|50.0|49.25|-0.75|-1.5|-3|-2|50.5|49.25|Downward|369|24,376,908
PTTGC|2023-02-01|2023-02-01|1|50.0|50.0|0.0|0.0|0|0|50.5|49.25|Upward|370|13,026,320
PTTGC|2023-02-02|2023-02-06|3|49.75|49.5|-0.25|-0.5|-1|-1|50.25|49.0|Downward|373|20,473,206
PTTGC|2023-02-07|2023-02-08|2|49.75|50.0|0.25|0.5|1|0|51.25|49.25|Upward|375|27,850,963
RCL|2023-01-10|2023-01-10|1|31.75|31.75|0.0|0.0|0|0|31.75|31.25|Upward|376|2,992,413

RCL|2023-01-11|2023-01-11|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|377|3,769,557
RCL|2023-01-12|2023-01-12|1|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|378|1,948,286
RCL|2023-01-13|2023-01-16|2|31.5|31.25|-0.25|-0.79|-1|-1|32.0|31.25|Downward|380|5,749,212
RCL|2023-01-17|2023-01-18|2|31.75|31.75|0.0|0.0|0|0|32.0|31.25|Upward|382|3,214,446
RCL|2023-01-19|2023-01-20|2|31.5|31.0|-0.5|-1.59|-2|-1|31.75|31.0|Downward|384|2,950,775
RCL|2023-01-23|2023-01-25|3|31.25|31.75|0.5|1.6|2|0|32.0|31.0|Upward|387|5,968,737
RCL|2023-01-26|2023-01-26|1|31.25|31.25|0.0|0.0|0|0|31.75|31.0|Downward|388|2,352,538
RCL|2023-01-27|2023-01-31|3|31.75|32.75|1.0|3.15|4|1|32.75|31.0|Upward|391|12,494,495
RCL|2023-02-01|2023-02-02|2|30.75|30.25|-0.5|-1.63|-2|-1|32.25|30.0|Downward|393|21,219,944
RCL|2023-02-03|2023-02-07|3|30.75|31.0|0.25|0.81|1|0|31.25|30.5|Upward|396|6,209,457
RCL|2023-02-08|2023-02-08|1|30.5|30.5|0.0|0.0|0|0|31.25|30.5|Downward|397|2,338,011
SCC|2023-01-10|2023-01-10|1|358.0|358.0|0.0|0.0|0|0|358.0|351.0|Downward|398|3,859,474
SCC|2023-01-11|2023-01-11|1|359.0|359.0|0.0|0.0|0|0|360.0|355.0|Upward|399|3,514,153
SCC|2023-01-12|2023-01-16|3|356.0|354.0|-2.0|-0.56|-2|-1|358.0|353.0|Downward|402|7,482,267
SCC|2023-01-17|2023-01-17|1|359.0|359.0|0.0|0.0|0|0|359.0|354.0|Upward|403|1,930,796
SCC|2023-01-18|2023-01-26|7|356.0|334.0|-22.0|-6.18|-22|-4|359.0|332.0|Downward|410|16,632,975
SCC|2023-01-27|2023-01-30|2|340.0|344.0|4.0|1.18|4|2|344.0|334.0|Upward|412|3,832,045
SCC|2023-01-31|2023-01-31|1|336.0|336.0|0.0|0.0|0|0|343.0|336.0|Downward|413|3,280,199
SCC|2023-02-01|2023-02-01|1|342.0|342.0|0.0|0.0|0|0|343.0|337.0|Upward|414|2,080,273
SCC|2023-02-02|2023-02-06|3|338.0|336.0|-2.0|-0.59|-2|-1|343.0|336.0|Downward|417|4,970,202
SCC|2023-02-07|2023-02-08|2|338.0|338.0|0.0|0.0|0|0|340.0|336.0|Upward|419|4,419,654
SCCC|2023-01-10|2023-01-19|8|158.0|160.0|2.0|1.27|4|0|160.0|157.0|Upward|427|894,613
SCCC|2023-01-20|2023-01-26|5|159.0|156.5|-2.5|-1.57|-5|-1|160.5|155.5|Downward|432|597,538
SCCC|2023-01-27|2023-02-01|4|158.5|160.5|2.0|1.26|4|1|162.0|157.0|Upward|436|750,023
SCCC|2023-02-02|2023-02-08|5|159.5|156.5|-3.0|-1.88|-6|-2|161.0|156.0|Downward|441|1,318,390
SENA|2023-01-10|2023-01-13|4|3.94|3.92|-0.02|-0.51|-1|-1|3.94|3.9|Downward|445|6,389,266
SENA|2023-01-16|2023-01-17|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|447|2,355,770
SENA|2023-01-18|2023-01-19|2|3.92|3.92|0.0|0.0|0|0|3.94|3.9|Downward|449|2,393,776
SENA|2023-01-20|2023-01-23|2|3.94|3.94|0.0|0.0|0|0|3.94|3.9|Upward|451|1,636,810
SENA|2023-01-24|2023-01-24|1|3.92|3.92|0.0|0.0|0|0|3.94|3.92|Downward|452|129,114
SENA|2023-01-25|2023-01-25|1|3.96|3.96|0.0|0.0|0|0|3.96|3.92|Upward|453|2,090,555
SENA|2023-01-26|2023-01-27|2|3.92|3.92|0.0|0.0|0|0|3.96|3.9|Downward|455|2,050,656
SENA|2023-01-30|2023-02-06|6|3.94|4.04|0.1|2.54|5|0|4.06|3.9|Upward|461|13,631,211
SENA|2023-02-07|2023-02-08|2|4.0|3.94|-0.06|-1.5|-3|-2|4.04|3.94|Downward|463|2,218,445
SINGER|2023-01-10|2023-01-10|1|29.25|29.25|0.0|0.0|0|0|30.0|29.0|Downward|464|4,615,984
SINGER|2023-01-11|2023-01-13|3|29.5|30.25|0.75|2.54|3|1|31.25|29.25|Upward|467|17,684,289
SINGER|2023-01-16|2023-01-23|6|30.0|28.0|-2.0|-6.67|-8|-2|30.75|27.75|Downward|473|29,983,246
SINGER|2023-01-24|2023-01-24|1|28.25|28.25|0.0|0.0|0|0|28.5|27.5|Upward|474|3,780,503
SINGER|2023-01-25|2023-01-26|2|27.75|26.75|-1.0|-3.6|-4|-2|28.25|26.5|Downward|476|11,350,118
SINGER|2023-01-27|2023-02-02|5|27.5|28.5|1.0|3.64|4|0|29.25|27.0|Upward|481|26,173,063
SINGER|2023-02-03|2023-02-08|4|28.25|27.0|-1.25|-4.42|-5|-2|28.75|27.0|Downward|485|12,047,147
STA|2023-01-10|2023-01-11|2|21.3|21.2|-0.1|-0.47|-1|-1|21.8|20.9|Downward|487|11,115,875
STA|2023-01-12|2023-01-13|2|21.3|21.3|0.0|0.0|0|0|21.7|21.0|Upward|489|7,352,075
STA|2023-01-16|2023-01-16|1|21.2|21.2|0.0|0.0|0|0|21.4|21.1|Downward|490|1,886,078
STA|2023-01-17|2023-01-17|1|21.3|21.3|0.0|0.0|0|0|21.5|21.2|Upward|491|2,576,072
STA|2023-01-18|2023-01-18|1|21.0|21.0|0.0|0.0|0|0|21.7|20.9|Downward|492|5,861,787
STA|2023-01-19|2023-01-19|1|21.4|21.4|0.0|0.0|0|0|21.4|21.0|Upward|493|1,864,178
STA|2023-01-20|2023-01-23|2|21.0|21.0|0.0|0.0|0|0|21.4|20.8|Downward|495|4,052,655
STA|2023-01-24|2023-01-27|4|21.1|22.9|1.8|8.53|18|4|22.9|20.8|Upward|499|45,950,994
STA|2023-01-30|2023-01-31|2|22.2|21.9|-0.3|-1.35|-3|-2|22.8|21.5|Downward|501|17,280,360
STA|2023-02-01|2023-02-02|2|22.0|22.7|0.7|3.18|7|3|22.7|21.7|Upward|503|12,309,899
STA|2023-02-03|2023-02-03|1|22.3|22.3|0.0|0.0|0|0|22.7|22.2|Downward|504|4,951,737
STA|2023-02-06|2023-02-08|3|22.6|24.5|1.9|8.41|19|6|24.7|22.3|Upward|507|41,947,740
SYNEX|2023-01-10|2023-01-12|3|17.0|17.2|0.2|1.18|2|0|17.6|16.9|Upward|510|9,437,051
SYNEX|2023-01-13|2023-01-20|6|17.1|16.6|-0.5|-2.92|-5|-1|17.5|16.5|Downward|516|10,273,525
SYNEX|2023-01-23|2023-01-24|2|16.7|16.7|0.0|0.0|0|0|16.9|16.6|Upward|518|1,882,226
SYNEX|2023-01-25|2023-01-26|2|16.3|15.9|-0.4|-2.45|-4|-2|16.7|15.8|Downward|520|4,592,919
SYNEX|2023-01-27|2023-01-30|2|16.1|16.2|0.1|0.62|1|0|16.4|16.0|Upward|522|2,438,448
SYNEX|2023-01-31|2023-01-31|1|16.1|16.1|0.0|0.0|0|0|16.3|16.0|Downward|523|1,438,207
SYNEX|2023-02-01|2023-02-07|5|16.5|17.1|0.6|3.64|6|1|17.6|16.2|Upward|528|14,528,451
SYNEX|2023-02-08|2023-02-08|1|16.3|16.3|0.0|0.0|0|0|17.2|16.3|Downward|529|3,347,661
TFFIF|2023-01-10|2023-01-10|1|7.75|7.75|0.0|0.0|0|0|7.8|7.75|Downward|530|1,298,307
TFFIF|2023-01-11|2023-01-24|10|7.85|8.2|0.35|4.46|7|0|8.2|7.8|Upward|540|26,912,214
TFFIF|2023-01-25|2023-01-31|5|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.1|Downward|545|12,364,080
TFFIF|2023-02-01|2023-02-01|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|546|2,482,129
TFFIF|2023-02-02|2023-02-02|1|8.15|8.15|0.0|0.0|0|0|8.25|8.15|Downward|547|1,039,802
TFFIF|2023-02-03|2023-02-03|1|8.25|8.25|0.0|0.0|0|0|8.3|8.15|Upward|548|3,991,431
TFFIF|2023-02-06|2023-02-08|3|8.2|8.2|0.0|0.0|0|0|8.25|8.15|Downward|551|5,224,640
TMT|2023-01-10|2023-01-10|1|7.95|7.95|0.0|0.0|0|0|7.95|7.8|Downward|552|325,634
TMT|2023-01-11|2023-01-24|10|8.0|8.45|0.45|5.62|9|0|8.45|7.9|Upward|562|5,248,394
TMT|2023-01-25|2023-02-02|7|8.35|8.15|-0.2|-2.4|-4|-1|8.45|8.15|Downward|569|1,939,587
TMT|2023-02-03|2023-02-03|1|8.2|8.2|0.0|0.0|0|0|8.2|8.1|Upward|570|162,400
TMT|2023-02-06|2023-02-08|3|8.15|8.1|-0.05|-0.61|-1|-1|8.25|8.05|Downward|573|481,845
TTB|2023-01-10|2023-01-13|4|1.46|1.41|-0.05|-3.42|-5|-2|1.47|1.4|Downward|577|994,076,129
TTB|2023-01-16|2023-01-19|4|1.42|1.42|0.0|0.0|0|0|1.43|1.41|Upward|581|687,814,110
TTB|2023-01-20|2023-01-20|1|1.41|1.41|0.0|0.0|0|0|1.41|1.38|Downward|582|509,121,072
TTB|2023-01-23|2023-02-01|8|1.44|1.47|0.03|2.08|3|0|1.48|1.4|Upward|590|2,259,173,623
TTB|2023-02-02|2023-02-08|5|1.45|1.41|-0.04|-2.76|-4|-1|1.47|1.4|Downward|595|680,589,081
WHAIR|2023-01-10|2023-01-11|2|7.45|7.45|0.0|0.0|0|0|7.5|7.45|Downward|597|1,921,936
WHAIR|2023-01-12|2023-01-20|7|7.5|7.95|0.45|6.0|9|1|8.0|7.4|Upward|604|11,421,149
WHAIR|2023-01-23|2023-01-24|2|7.9|7.9|0.0|0.0|0|0|7.95|7.85|Downward|606|1,018,702
WHAIR|2023-01-25|2023-01-26|2|7.95|8.0|0.05|0.63|1|0|8.0|7.9|Upward|608|2,073,101
WHAIR|2023-01-27|2023-01-30|2|7.8|7.8|0.0|0.0|0|0|8.0|7.6|Downward|610|3,620,824
WHAIR|2023-01-31|2023-02-03|4|7.95|8.05|0.1|1.26|2|0|8.05|7.8|Upward|614|3,326,380
WHAIR|2023-02-06|2023-02-08|3|8.0|8.0|0.0|0.0|0|0|8.1|8.0|Downward|617|1,473,021
WHART|2023-01-10|2023-01-10|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|618|1,251,002
WHART|2023-01-11|2023-01-11|1|10.8|10.8|0.0|0.0|0|0|10.8|10.7|Upward|619|606,452
WHART|2023-01-12|2023-01-12|1|10.7|10.7|0.0|0.0|0|0|10.8|10.7|Downward|620|1,551,924
WHART|2023-01-13|2023-01-19|5|10.9|12.0|1.1|10.09|11|2|12.2|10.7|Upward|625|20,924,999
WHART|2023-01-20|2023-01-26|5|11.8|11.6|-0.2|-1.69|-2|-1|12.1|11.4|Downward|630|15,575,456
WHART|2023-01-27|2023-01-30|2|11.8|11.8|0.0|0.0|0|0|11.8|11.5|Upward|632|1,943,970
WHART|2023-01-31|2023-01-31|1|11.6|11.6|0.0|0.0|0|0|11.8|11.5|Downward|633|1,239,474
WHART|2023-02-01|2023-02-03|3|11.7|11.8|0.1|0.85|1|0|11.8|11.5|Upward|636|3,044,650
WHART|2023-02-06|2023-02-07|2|11.6|11.6|0.0|0.0|0|0|11.9|11.6|Downward|638|1,507,517
WHART|2023-02-08|2023-02-08|1|11.7|11.7|0.0|0.0|0|0|11.7|11.5|Upward|638|459,646
ruby/../Data/summary.csv

In [14]:
os.chdir("C:\\users\\user\\onedrive\\a7\\daily")
%pwd

'C:\\users\\user\\onedrive\\a7\\daily'

In [15]:
file_name   = 'summary.csv'
input_file = data_path + file_name
df = pd.read_csv(input_file, sep=',', index_col=None)
df.sample(5).style.format(format_dict)

In [16]:
df.rename(columns={'from_date':'fm_date','from_price':'fm_price'},inplace=True)
df['fm_date'] = pd.to_datetime(df['fm_date'])
df['to_date'] = pd.to_datetime(df['to_date'])
df['fm_md'] = df['fm_date'].dt.strftime('%m-%d')
df['to_md'] = df['to_date'].dt.strftime('%m-%d')

### Group analysis

In [17]:
mask_p = df['to_md'] == to_mmdd
df[mask_p][cols].sort_values('pct',ascending=False).head().style.format(format_dict)

In [18]:
name_up = 'STA'
mask_n = df.name == name_up
df[mask_n][cols].style.format(format_dict)

In [19]:
mask_m = df['to_md'] == to_mmdd
df[mask_m][cols].sort_values('pct',ascending=True).head().style.format(format_dict)

In [20]:
name_down = 'BANPU'
mask_n = df.name == name_down
df[mask_n][cols].style.format(format_dict)

In [21]:
df_groupby_trend = df.groupby('trend')

In [22]:
# To retrieve one of the created groups
df_up = df_groupby_trend.get_group('Upward')
df_up[cols].sample(5).style.format(format_dict)

In [23]:
# To retrieve one of the created groups
df_dw = df_groupby_trend.get_group('Downward')
df_dw[cols].sample(5).style.format(format_dict)

In [ ]:
#df.groupby('trend').days.max()

In [24]:
# there is a function called .agg() and it allows us to specify multiple aggregation functions at once
df.groupby('trend').days.agg(['max', 'count', 'median', 'mean'])

          max  count  median  mean
trend
Downward   13    138    2.00  2.41
Upward     10    123    2.00  2.47

In [25]:
downward_max = df.groupby('trend').days.max().loc['Downward']
upward_max = df.groupby('trend').days.max().loc['Upward']

In [26]:
df.query('days == @upward_max')[cols].style.format(format_dict)

In [27]:
df.query('days == @downward_max and trend == "Downward"')[cols]

,name,fm_md,to_md,days,fm_price,to_price,pct,spd,avg,max_price,min_price,ttl_qty,trend
17,BANPU,01-23,02-08,13,12.50,11.00,-12.00,-15,-2,12.60,10.90,1565586144,Downward

### Individual stock analysis

In [28]:
df.query('name == @name_up')[cols].style.format(format_dict)

In [29]:
df_tmp = price.query('name == @name_up')
df_tmp.describe().round(2)

       price         qty  maxp  minp
count  22.00       22.00 22.00 22.00
mean   21.93  7143156.82 22.19 21.54
std     0.92  6045240.19  0.88  0.69
min    21.00   879566.00 21.20 20.80
25%    21.22  3285420.00 21.42 21.00
50%    21.65  4850738.00 22.00 21.20
75%    22.52  7719686.25 22.78 22.12
max    24.50 19821209.00 24.70 23.20

In [30]:
df.query('name == @name_down')[cols].style.format(format_dict)

In [31]:
df_tmp = price.query('name == @name_down')
df_tmp.describe().round(2)

       price          qty  maxp  minp
count  22.00        22.00 22.00 22.00
mean   12.08 111074984.64 12.20 11.92
std     0.51  83409996.09  0.43  0.48
min    11.00  30894152.00 11.40 10.90
25%    11.60  55490737.75 11.75 11.50
50%    12.30  98245661.00 12.40 12.20
75%    12.48 143639296.25 12.50 12.28
max    12.70 415903536.00 12.70 12.40

In [32]:
mask_p = df['to_md'] == to_mmdd
summary = df[mask_p][cols].sort_values(['pct','trend'],ascending=[False,False])

In [35]:
file_name = 'summary-240.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

summary[cols].to_csv(output_file, header=True, index=False)
summary[cols].to_csv(data_file, header=True, index=False)
summary[cols].to_csv(one_file, header=True, index=False)
summary[cols].to_csv(osd_file, header=True, index=False)

In [36]:
sql = """
SELECT name, date, price, qty, maxp, minp
FROM price 
WHERE date >= '%s' 
ORDER BY name, date"""
sql = sql % (today)
print(sql)

SELECT name, date, price, qty, maxp, minp
FROM price
WHERE date >= '2023-02-08'
ORDER BY name, date

In [37]:
df = pd.read_sql(sql, const)
df

       name        date  price       qty   maxp   minp
0       ACE  2023-02-08   2.54  16004646   2.56   2.54
1    ADVANC  2023-02-08 195.50   3770659 196.50 195.00
2        AH  2023-02-08  31.75   1449205  33.00  31.50
3       AIE  2023-02-08   3.02  18022789   3.10   2.94
4    AIMIRT  2023-02-08  12.30    291801  12.30  12.30
..      ...         ...    ...       ...    ...    ...
189   WHAIR  2023-02-08   8.00    164603   8.05   8.00
190   WHART  2023-02-08  11.70    459646  11.70  11.50
191   WHAUP  2023-02-08   4.08   2547336   4.12   4.06
192    WICE  2023-02-08  11.40   5889162  11.80  11.30
193    WORK  2023-02-08  18.40    329012  18.70  18.40

[194 rows x 6 columns]